### PR TITLE
return additional information about the instance

### PR DESCRIPTION
**Pull request by windowsrefund**
##### Issue Type:

Please pick one and delete the rest:
- Feature Pull Request
##### Plugin Name:

ec2_remote_facts
##### Ansible Version:

latest development
##### Summary:

This is useful information
##### Example output:

N/A

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @windowsrefund. @michaeljs1990 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @windowsrefund for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@windowsrefund A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@windowsrefund Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by michaeljs1990** [comment]
it looks like the branch that this was created from was deleted. Possibly this can just be closed now?

**Comment by gregdek** [comment]
Yep. Closing.

**Pull request closed without merging**
