### PR TITLE
Update win_updates.py

### PR DESCRIPTION
**Pull request by adematte**
just added logPath parameter to the documentation.

### CODE REVIEW

**Comment by petemounce** [comment]
lgtm.

**Comment by gregdek** [comment]
@adematte can't auto-merge -- can you rebase? @petemounce has already given a tentative +1, so when you rebase, I'll ask him for a definitive +1, and then we can merge.

**Comment by gregdek** [comment]
@petemounce looks like @adematte isn't available to rebase, and this one has been sitting for awhile. 

Without any response from the original submitter to rebase, I have no choice but to mark it for closure -- but it looks pretty low risk, so if you think it's a valuable addition, maybe you could submit a new PR with the properly based changes?

**Comment by petemounce** [comment]
@gregdek done in #745.

Does ansible use [gitter.im](https://gitter.im/)? I [didn't find an official channel with a search...?](https://gitter.im/explore/tags/ansible)

**Comment by cchurch** [comment]
These changes have been applied via #745.

**Pull request closed without merging**
