### PR TITLE
Add ipa_group module

### PR DESCRIPTION
**Pull request by ToBeReplaced**
There was some talk a while back on ansible-devel about coming up with FreeIPA modules to work with ansible.

This is a step towards that. It is a module to provide idempotent management of ipa groups.

### CODE REVIEW

**Comment by ToBeReplaced** [comment]
This commit needs minor changes for FreeIPA 4, which has now been adopted in RHEL 7.1 and has been in Fedora for two releases.

If this PR is of interest to the project, I will contribute these changes.

**Comment by gregdek** [comment]
Thanks for submitting your module to Ansible Extras. Our policy is that each new module needs to be reviewed and approved by at least two official module reviewers, the list of whom can be found here: https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

If you know someone on that list, please poke them and encourage them to review your module. :)

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by mscherer** [comment]
So, I fail to understand how the auth is supposed to work, I need to use kerberos for that, no login/password to connect ?

**Comment by ToBeReplaced** [comment]
@mscherer - That is correct. If the user already has credentials locally and you want to forward them to the host running the role, you could add `GSSAPIDelegateCredentials=yes` to your `ssh_args` in `ansible.cfg`. If you need to fetch credentials, `kinit` or `kinit username` is required.

That said, I'm not sure if this role is a good idea or not...  For us, user administration changed hands, so this role is no longer in use. IPA already has a great administration interface, so maybe just use that directly?

**Comment by mscherer** [comment]
I think there is some use for the module, but if you do not use it yourself and do not maintain, then I would indeed not push it.

**Pull request closed without merging**
