### PR TITLE
Feature udm dns zone

### PR DESCRIPTION
**Pull request by keachi**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

udm_dns_zone
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

This module allows to manage dns zones on a [univention corporate server](https://www.univention.de/produkte/ucs/).
Example task:

```
- udm_dns_zone: zone=example.com type=forward_zone nameserver=['ucs.example.com'] interfaces=['192.168.1.1']
```

To use this module, the target system must be an UCS. The module use the python API of an univention corporate server, called univention directory manager, to create, edit and delete dns zones.

This module needs the [PR #16172](https://github.com/ansible/ansible/pull/16172).

### CODE REVIEW

**Comment by keachi** [comment]
I excluded common code (for other univention specific modules) to a library ([PR #16172](https://github.com/ansible/ansible/pull/16172)).

**Comment by gregdek** [comment]
Thanks @2-B for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @2-B for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@2-B A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by keachi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @2-B for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @2-B for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by keachi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @2-B for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @2-B for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by keachi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @2-B for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @2-B for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Thanks!

**Pull request merged**
