### PR TITLE
ovirt_vms: Add support to specify template version

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

This patch add support to specify if the template should use always latest template when running stateless VM. This patch also add support to specify template version when createing new VM.

### CODE REVIEW

**Comment by machacekondra** [comment]
@ganniterix @mwperina @ryansb

**Comment by machacekondra** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @machacekondra for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Review by mwperina — APPROVED** [review]
Looks good to me! :+1:

**Comment by machacekondra** [comment]
ready_for_review shipit

**Review by mwperina — APPROVED** [review]
:+1:

**Pull request merged**
