### PR TITLE
pacman: change -Syy to -Sy for "update-cache"

### PR DESCRIPTION
**Pull request by RubenKelevra**
-Syy do always update, which is not needed, since the caches might already be up to date.

### CODE REVIEW

**Comment by bcoca** [comment]
this leaves us with no way to force the sync, which is rarely needed but it does happen

**Comment by RubenKelevra** [comment]
I thought about using the force=yes on update_cache=yes as well.

**Comment by bcoca** [comment]
that overloads force a bit too much, i might want to force install or cache update but not both?

**Comment by RubenKelevra** [comment]
Sure ... but doing "-Syy" everytime is insane, especially when you want to install more than one package.

**Comment by RubenKelevra** [comment]
Sure ... but doing "-Syy" everytime is insane, especially when you want to install more than one package.

The name "cache update" sounds completly wrong to me. The man-page of pacman names this option "refresh":

SYNC OPTIONS
-y, --refresh
    Download a fresh copy of the master package list from the server(s) defined in pacman.conf(5). This should typically be used each time you use --sysupgrade or -u. Passing two --refresh or -y flags will force a refresh of all package lists, even if they appear to be up- to-date.

I know other package-mangers syntaxes are different, but since there are also possible options with the package cache this option sounds completly wrong to me at the moment.

A cache-update would be equivalent to "pacman -Syuw --noconfirm" which refreshes and update all packages to the cache.

So the option should be named as "refresh" and "force-refresh" or "complete-refresh".

**Pull request merged**
