### PR TITLE
Support verbose output from npm

### PR DESCRIPTION
**Pull request by r1b**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

npm
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

When verbose=yes is provided, npm will give verbose output.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @r1b for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by r1b** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @r1b. To the current maintainers, @chrishoffman please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by xen0l** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @r1b for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@r1b A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by r1b** [comment]
I don't see any output from the build.

**Comment by r1b** [comment]
ready_for_review

**Pull request closed without merging**
