### PR TITLE
Add support for filtering flavors on ephemeral storage

### PR DESCRIPTION
**Pull request by trumant**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

os_flavor_facts
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### SUMMARY

The module already supports filtering on vCPU and RAM. I have a use case to filter on ephemeral storage as well.

```
New feature, no change in output, only a change in usage.
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @trumant. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by omgjlk** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @trumant for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Shrews** [comment]
You need to define 'ephemeral' in the argument_spec. A simple playbook test using this would have identified this error.

needs_revision

**Comment by trumant** [comment]
@Shrews - Thanks for catching that! Fixed.

**Pull request merged**
