### PR TITLE
add append-only mode to ec2_vpc_route_table.py

### PR DESCRIPTION
**Pull request by lpowers**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

ec2_vpc_route_table
##### Summary:

this adds append-only functionality to ec2_vpc_route_table, in order to not have to rewrite all routing table entries on every run. this PR essentially duplicates work I found here: https://github.com/preo/ansible-modules-core/pull/2
##### Example:

```
- name: add default route to a routing table
  ec2_vpc_route_table:
    vpc_id: vpc-1245678
    region: us-west-1
    tags:
      Name: Public
    subnets:
      - "{{ jumpbox_subnet.subnet.id }}"
      - "{{ frontend_subnet.subnet.id }}"
      - "{{ vpn_subnet.subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: igw
    append_routes: true
```

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @lpowers. To the current maintainers, @erydo, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by lpowers** [comment]
@erydo or @wimnat will you take a look here?

**Comment by gregdek** [comment]
Thanks @lpowers for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lpowers** [comment]
merge conflicts with the underlying branches... I don't have time to sort this.
will continue to use our (locally) changed module. closing.

**Pull request closed without merging**
