### PR TITLE
Add a new module to handle schema with postgres

### PR DESCRIPTION
**Pull request by Dorn-**
##### Issue Type:
- New Module Pull Request
##### Plugin Name:

postgresql_schema
##### Summary:

Add a new module to handle the schema into postgresql. You can add / modify or delete a schema for a specific user. This module is really close from the actual postgresql modules.
##### Example:

```
- name: Creates schema
  become: true
  become_user: postgres
  postgresql_schema:
    name: fizzbuz
    owner: foo
    database: dbb_fizzbuzz
    state: present

TASK: [role-postgres-9 | Creates schema] ************************************** 
<localhost> REMOTE_MODULE postgresql_schema database=bdd_fizzbuz name=fizzbuz state=present owner=foo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1458314355.23-271430311562708 && chmod a+rx /tmp/ansible-tmp-1458314355.23-271430311562708 && echo /tmp/ansible-tmp-1458314355.23-271430311562708']
<localhost> PUT /tmp/tmpGYz_OL TO /tmp/ansible-tmp-1458314355.23-271430311562708/postgresql_schema
<localhost> EXEC ['/bin/sh', '-c', u'chmod a+r /tmp/ansible-tmp-1458314355.23-271430311562708/postgresql_schema']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=flpafgoqjdbdeduipltqepjsinbzwgfy] password: " -u postgres /bin/sh -c '"'"'echo BECOME-SUCCESS-flpafgoqjdbdeduipltqepjsinbzwgfy; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1458314355.23-271430311562708/postgresql_schema'"'"''
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /tmp/ansible-tmp-1458314355.23-271430311562708/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "schema": "fizzbuz"}
```

```
- name: Drops public schema
  become: true
  become_user: postgres
  postgresql_schema:
    name: public
    state: absent

TASK: [role-postgres-9 | Drops public schema] ********************************* 
<localhost> REMOTE_MODULE postgresql_schema name=public state=absent
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1458314355.45-215891500091072 && chmod a+rx /tmp/ansible-tmp-1458314355.45-215891500091072 && echo /tmp/ansible-tmp-1458314355.45-215891500091072']
<localhost> PUT /tmp/tmpou6MDY TO /tmp/ansible-tmp-1458314355.45-215891500091072/postgresql_schema
<localhost> EXEC ['/bin/sh', '-c', u'chmod a+r /tmp/ansible-tmp-1458314355.45-215891500091072/postgresql_schema']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=hkzyzjlrrklrcltnkrqerdaqvlumxmby] password: " -u postgres /bin/sh -c '"'"'echo BECOME-SUCCESS-hkzyzjlrrklrcltnkrqerdaqvlumxmby; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1458314355.45-215891500091072/postgresql_schema'"'"''
<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /tmp/ansible-tmp-1458314355.45-215891500091072/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "schema": "public"}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Dorn- for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by Dorn-** [comment]
@gregdek Any news ?

**Comment by gregdek** [comment]
Sorry @Dorn- for the lack of progress yet -- testing new modules can be a challenge for community members, and there are 165+ new modules out there to be tested. If you know anyone who might want to use this module, please feel free to send them here.

**Comment by gregdek** [comment]
Thanks @Dorn- for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Dorn- A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Dorn-** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Dorn- for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rbygrave** [comment]
shipit

**Comment by leucos** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @Dorn- for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Dorn-** [comment]
So,
Since you take 8 month to accept or not a PR, I'll not update it everytime your tests are changing.
Tell me when you are ready @gregdek to ship it, I'll do all the update which are needed.
But, till this moment, I won't change anything.

Kind regards

**Comment by gundalow** [comment]
@Dorn- I've just merged this and will see if there are any changes needed.
This only went to `shipit` just as we were doing the code freeze of Ansible 2.2 which is one of the reasons it didn't get looked at since 6th September.

We have a huge backlog of PRs to work though and `ansible-modules-extras` is often at the tail end of that

https://app.shippable.com/runs/58372c8d7ae6830f00c4369f/summary is the shippable run of the merge which I'll check in on

**Comment by gundalow** [comment]
Fixes done and merged in https://github.com/ansible/ansible-modules-extras/pull/3542

**Pull request merged**
