### PR TITLE
Check to make sure the firewalld client is connected before proceeding

### PR DESCRIPTION
**Pull request by lightblu**
Fixes #6911

Original patches referenced in https://github.com/ansible/ansible/issues/6911 (https://github.com/ansible/ansible/commit/b2c10df2c821caf4c157f5091e394fd1fe18f77e and https://github.com/ansible/ansible/commit/8cb8c49b23d01b378323a1dd4feb2db53cd7d0e8) got lost?

### CODE REVIEW

**Comment by robynbergeron** [comment]
@lightblu -- thanks for this PR.

@maxamillion -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@maxamillion This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@maxamillion still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by maxamillion** [comment]
:+1: shipit

**Comment by robynbergeron** [comment]
Thanks again to @lightblu for this PR, and thanks @maxamillion for reviewing. Marking for inclusion.

**Pull request merged**
