### PR TITLE
Add 'link' action to jira module

### PR DESCRIPTION
**Pull request by Slezhuk**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

jira
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

Add 'link' action to jira module, allowing to link issues

```
- name: Create link from HSP-1 to MKY-1
  jira: uri={{server}} username={{user}} password={{pass}} operation=link
        linktype=Relate inwardissue=HSP-1 outwardissue=MKY-1
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Slezhuk. To the current maintainers, @tarka please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Slezhuk for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dresc** [comment]
Hi i'm very intrested of this linking feature! Keep up good work :)

**Comment by gregdek** [comment]
@Slezhuk A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Slezhuk** [comment]
Hello! Sorry for keep you waiting. I finaly managed how to work properly with PR and accordingly with ansible repository recommendations i rebased my changes, also squashed them in 1 commit.
ready_for_review

**Comment by gregdek** [comment]
Thanks @Slezhuk. To the current maintainers, @tarka please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Merged to devel.  Thanks @Slezhuk for implementing this feature.

**Comment by Slezhuk** [comment]
Thanks!

**Pull request merged**
