### PR TITLE
Minor bug fixes and enhancements

### PR DESCRIPTION
**Pull request by popurisiva**
##### ISSUE TYPE

- Feature Pull Request
- Bugfix Pull Request
##### COMPONENT NAME

cloud/centurylink/clc_modify_server.py
cloud/centurylink/clc_publicip.py
cloud/centurylink/clc_server.py
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.0.1.0
  config file =
  configured module search path =
```
##### SUMMARY

1) Added the capability to add additional network to an existing server with clc_modify_server module
2) Added the capability to add source restrictions with clc_publicup module
3) Fixed some minor validation bugs with clc_server module
4) added the capability to specify minimum and maximum server counts via min_count and max_count arguments with clc_server module.

```
<!--- Paste verbatim command output here, e.g. before and after your change -->
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @popurisiva. To the current maintainers, @clc-runner please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jufkes** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @popurisiva for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@popurisiva A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@popurisiva Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by popurisiva** [comment]
ready_for_review

**Pull request closed without merging**
