### PR TITLE
Create, Delete, and Modify a Kinesis Stream.

### PR DESCRIPTION
**Pull request by linuxdynasty**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

kinesis_stream
##### ANSIBLE VERSION

```
ansible 2.1.0
```
##### SUMMARY

I originally was going to do a PR against #819 , except this module does quite a bit more than just create a Kinesis Stream.

Create, Delete, and Modify a Kinesis Stream.
- Create a Kinesis Stream.
- Tag a Kinesis Stream.
- Update the Retention Period of a Kinesis Stream.
- Delete a Kinesis Stream.
- Wait for a Kinesis Stream to be in an ACTIVE State.

```
{
    "changed": true,
    "msg": "Kinesis Stream test-stream updated successfully",
    "retention_period_hours": 24,
    "stream_arn": "arn:aws:kinesis:east-side:123456789:stream/test-stream",
    "stream_name": test-stream",
    "stream_status": "ACTIVE",
    "success": true,
    "tags": {
        "env": "development"
    }
}
```

Examples...

```
# Basic creation example:
- name: Set up Kinesis Stream with 10 shards and wait for the stream to become ACTIVE
  kinesis_stream:
    name: test-stream
    shards: 10
    wait: yes
    wait_timeout: 600
  register: test_stream

# Basic creation example with tags:
- name: Set up Kinesis Stream with 10 shards, tag the environment, and wait for the stream to become ACTIVE
  kinesis_stream:
    name: test-stream
    shards: 10
    tags:
      Env: development
    wait: yes
    wait_timeout: 600
  register: test_stream

# Basic creation example with tags and increase the retention period from the default 24 hours to 48 hours:
- name: Set up Kinesis Stream with 10 shards, tag the environment, increase the retention period and wait for the stream to become ACTIVE
  kinesis_stream:
    name: test-stream
    retention_period: 48
    shards: 10
    tags:
      Env: development
    wait: yes
    wait_timeout: 600
  register: test_stream

# Basic delete example:
- name: Delete Kinesis Stream test-stream and wait for it to finish deleting.
  kinesis_stream:
    name: test-stream
    state: absent
    wait: yes
    wait_timeout: 600
  register: test_stream
```

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-extras/1901)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by linuxdynasty** [comment]
@gregdek the tests fail because it requires the same type of documentation as a module??
@bcoca or @gregdek, may I ask what is the correct way to submit tests for Ansible modules?

**Comment by sivel** [comment]
Generally speaking we don't do unit tests for modules.  Instead we do integration tests that are stored in the main Ansible repo.

However there is 1 module that has integration tests which are stored off in another directory.  See https://github.com/ansible/ansible-modules-core/tree/devel/test/unit/cloud/openstack however this is not typical but has the potential to become more common place.  Also do note that the tests included in the modules repos are not automatically run.  However integration tests are more widely used.

**Comment by linuxdynasty** [comment]
@sivel does this mean I should not include the test into this PR? Or are you saying that I should submit the tests into test/unit/cloud/amazon directory which doesn't exist today? The test I submitted do full integration testing using the Ansible v2 API as well as unit testing for each function. Please let me know how to proceed. I would like to include a test for each PR that I have, which currently is a total of 5.

**Comment by sivel** [comment]
Integration testing via the API should _not_ be done.  Integration tests should be written as roles and play books and submitted to the main Ansible repo.

At this time there is not a precedent of including unit tests for modules, but should you desire including unit tests, you can do so following the pathing used in -core.  However be aware that there because unit tests for modules are uncommon there is no wide spread knowledge of their existence nor anything that runs them at this time.

**Comment by linuxdynasty** [comment]
Thank you @sivel for the quick response. I removed the the tests from this PR. I will maintain a separate repository containing the Ansible modules I have written with their coinciding unit tests. Are there plans in the future, to include tests with their associated modules and have them run during a PR? I have seen a couple of modules already that have bugs that would have been caught easily through some well placed unit tests.

**Comment by linuxdynasty** [comment]
If anyone on this thread is curious, I will be maintaining all of my modules [ld-ansible-modules](https://github.com/linuxdynasty/ld-ansible-modules) with their coinciding tests. I added it to travis.ci and I will be adding coveralls shortly as well.

**Comment by linuxdynasty** [comment]
@sivel and @bcoca I included my test in test/unit/cloud/amazon/test_kinesis_stream.py. I understand that currently tests are not ran automatically, but from what I gather from this [conversation](https://groups.google.com/forum/#!topic/ansible-devel/ejY4CjKeC34), the running of tests in this repo may happen soon. In the mean time, users of this module can see the status of coveralls.io and travic.ci on https://github.com/linuxdynasty/ld-ansible-modules

**Comment by sivel** [comment]
I am still a -1 on including integration tests through use of the Ansible API.  Our standard is to utilize ansible itself via roles and playbooks to perform integration tests, which are included in the main ansible repo.

We have not yet made any statements of the python API being stable or a first class citizen, as such, changes we make that may not impact the CLIs could impact these tests.  This adds tech debt that I am not sure we are prepared to own yet.

**Comment by linuxdynasty** [comment]
@sivel: I removed the Ansible API based tests from this PR and just left in the Unit Tests for each function. Is the Ansible v2 API in the process of being stable?

**Comment by bcoca** [comment]
@linuxdynasty its never intended to be 'stable' or an externally consumable thing, that is what the command line tools are, the API can change at any point arbitrarily in support of the command line tools.

**Comment by linuxdynasty** [comment]
@bcoca, thank you for clearing that up for me.

**Comment by linuxdynasty** [comment]
@sivel if you still feel it needs revision, please let me know in which aspect. As per above I removed the API testing.

**Comment by gregdek** [comment]
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@gregdek I updated as per @sivel requests, and I was waiting for him to get back to me.

ready_for_review

**Comment by ap-dji** [comment]
@linuxdynasty I tried using this and ran into the following error: NameError: global name 'boto' is not defined .

To fix it I just added an import for boto:
try:
    import boto
    HAS_BOTO = True
except ImportError:
    HAS_BOTO = False

Looks to be the same issue as another aws module in development that uses boto3: https://github.com/pjodouin/ansible-lambda/issues/2 .

**Comment by linuxdynasty** [comment]
I keep forgetting that ec2.py in ansible repo requires boto. I'll update in a bit. Thank you @ap-dji

**Comment by linuxdynasty** [comment]
@ap-dji, I just updated the module to include boto.

**Comment by ap-dji** [comment]
@linuxdynasty Looks good.

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@ap-dji, please let me know if you feel this needs anything else or any other feedback.

**Comment by ap-dji** [comment]
shipit

**Comment by gregdek** [comment]
@sivel any comment here?

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@gregdek would it be safe to say, that all of my PR's that are older than one month, need to be rebased?

**Comment by gregdek** [comment]
@linuxdynasty well, it kinda depends. :/

With changes to existing modules, if we can't get it merged quickly, it's much more likely to need more frequent rebases, since code can legitimately change underneath. 

With new modules like this, though, we could probably benefit from fixing our process; we often throw spurious Travis errors that could not possibly apply to a new module.

**Comment by gregdek** [comment]
Putting this one back into community_review, thanks!

**Comment by linuxdynasty** [comment]
@gregdek if you can get this in the community Agenda as it has been in a PR state for 4 months. I would appreciate it and it has 1 shipit so far.

**Comment by gregdek** [comment]
Added. Next meeting is in 3 weeks.

**Comment by ryansb** [comment]
There seems to be an oddity with the way the number of shards is handled. If I change the shard number, the playbook succeeds and the task is marked "changed"

```
changed: [localhost] => {"changed": true, "enhanced_monitoring": [{"shard_level_metrics": []}], "has_more_shards": true, "msg": "Kinesis Stream test-stream updated successfully.", "retention_period_hours": 72, "stream_arn": "arn:aws:kinesis:us-west-2:REDACTED:stream/test-stream", "stream_name": "test-stream", "stream_status": "ACTIVE", "success": true, "tags": {"owner": "ryansb"}}
```

If the user changes the shard number (which is unsupported) the task should fail with a message that they can't change that after creation.

Also, if I don't make any changes and re-run the task, it always returns `changed` which it really shouldn't.

Other than those two things, looks good, thanks for adding tests!

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@ryansb, thank you for catching the number of shards issue. Even though it was not changing, it should have failed, because it is not allowed. I fix that in my last commit as well, I re-ran this in my lab environment and the changed flag is set to False after consecutive runs with no changes and set to True when retention period changes.

**Comment by linuxdynasty** [comment]
ready_for_review

**Comment by ryansb** [comment]
LGTM: ship_it

@sivel or @ap-dji - can you take a second look at this PR please?

**Comment by gregdek** [comment]
Thanks again to @linuxdynasty for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
