### PR TITLE
Check for zypper version before using options

### LINKED ISSUE #2548: zypper_repository fails with Unknown option '--gpgcheck' on SLES 11.1
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

- zypper_repository
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

From

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

Managing

```
# cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 1
```
##### SUMMARY

Trying to add a new repository using the `zypper_repository` module results in the following error.

```
Unknown option '--gpgcheck'
```
##### STEPS TO REPRODUCE

Get a clean install SLES 11.1, and try to add a repository.

```
  zypper_repository: name=NAME
                     repo=REPO_URL
                     state=present
```

##### EXPECTED RESULTS

No error.
##### ACTUAL RESULTS

Error.

```
fatal: [endpoint]: FAILED! => {"changed": false, "failed": true, "msg": "Unknown option '--gpgcheck'\n"}
```
##### ADDITIONAL INFORMATION

This works fine with SLES 11.4. The zypper versions and help output are as follows.

SLES11.1

```
# /usr/bin/zypper --version
zypper 1.3.7
# zypper ar --help
addrepo (ar) [options] <URI> <alias>
addrepo (ar) [options] <file.repo>

Add a repository to the sytem. The repository can be specified by its URI or can be read from specified .repo file (even remote).

  Command options:
-r, --repo <file.repo>  Just another means to specify a .repo file to read.
-t, --type <type>       Type of repository (yast2, rpm-md, plaindir).
-d, --disable           Add the repository as disabled.
-c, --check             Probe URI.
-C, --no-check          Don't probe URI, probe later during refresh.
-n, --name <name>       Specify descriptive name for the repository.
-k, --keep-packages     Enable RPM files caching.
-K, --no-keep-packages  Disable RPM files caching.
-f, --refresh           Enable autorefresh of the repository.
```

SLES 11.4

```
# zypper --version
zypper 1.6.326
# zypper ar --help
addrepo (ar) [options] <URI> <alias>
addrepo (ar) [options] <file.repo>

Add a repository to the system. The repository can be specified by its URI or can be read from specified .repo file (even remote).

  Command options:
-r, --repo <file.repo>  Just another means to specify a .repo file to read.
-t, --type <type>       Type of repository (yast2, rpm-md, plaindir).
-d, --disable           Add the repository as disabled.
-c, --check             Probe URI.
-C, --no-check          Don't probe URI, probe later during refresh.
-n, --name <name>       Specify descriptive name for the repository.
-k, --keep-packages     Enable RPM files caching.
-K, --no-keep-packages  Disable RPM files caching.
-g, --gpgcheck          Enable GPG check for this repository.
-G, --no-gpgcheck       Disable GPG check for this repository.
-f, --refresh           Enable autorefresh of the repository.
```

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

packaging/os/zypper_repository.py
##### ANSIBLE VERSION

devel, stable-2.1
##### SUMMARY

Check for the zypper version before using options. Some features (gpgcheck, priority) only work for newer versions and adding them by default therefore breaks older zypper versions.
- fixes #2548
- priority needs zypper version >= 1.12.25
- gpgcheck needs zypper version >= 1.6.2
- output warnings if version not sufficient for option

This should be backported to stable-2.1, since the zypper rewrite was introduced there and now breaks the use of the module on older suse versions.

### CODE REVIEW

**Comment by paavoap** [comment]
Minor thing: I get the warning for `gpgcheck` even when I don't explicitly set the property in my playbook. Works fine, but it may make it seem like the user did something wrong, when it's just preemptively warning about the version.

**Comment by robinro** [comment]
The thing is, that when you don't set it, so far we don't know the output, since according to the zypper changelog the behaviour changed in the past. So I thought it might be a good idea to always output the warning so people explicitly check whether the result for gpgcheck is what they want.

**Comment by robinro** [comment]
We can also change that behavior. My opinion about warnings is that there should rather be more than less, but I'm happy to change that warning if it's annoying.

**Comment by paavoap** [comment]
I trust your judgement.

**Comment by gregdek** [comment]
Thanks @robinro. To the current maintainers, @matze please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alxgu** [comment]
shipit

**Comment by robinro** [comment]
Thanks @alxgu 

I guess we have to wait for @matze though.

**Comment by matze** [comment]
Not anymore: shipit

**Comment by gregdek** [comment]
Thanks again to @robinro for this PR, and thanks @matze for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
