### PR TITLE
documentation error fixed vpc_peering_connection to vpc_peering_conne…

### PR DESCRIPTION
**Pull request by raben2**
…ction_id

Sorry to be a pedantic idiot but it took me 5 Minutes to notice.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @raben2 -- thanks for submitting this PR.

@erydo @wimnat -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by raben2** [comment]
shipit

**Comment by wimnat** [comment]
Looks like commit 57101d2 has been made in error. There's a lot more changes here than just the doc fix. 

needs_revision

**Comment by robynbergeron** [comment]
@wimnat indeed, thanks for calling that out :)

@raben2 -- putting this back in needs_revision to trim out the commit @wimnat referenced above. Thanks!

**Pull request closed without merging**
