### PR TITLE
Refactored maven_artifact

### PR DESCRIPTION
**Pull request by grilo**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY

Reduced code base in approximately 30%, removed some dead code, simplified some logic, used ansible's own error checking to catch the glaring ones (such as absence of required parameters).
Added ignore_checksum option, enabling artifact download without forcing remote checksum validation.
Added aliases to repository, username and password parameters for better consistency.
Fixed (unreported) issue where http credentials weren't being propagated correctly.
Module initialization parameters are mandatory according to the documentation but not in the code.
##### TESTING

I've been using this in production on my company for a couple of days now (a few thousand downloads so far, very heterogeneous parameters), no issues found.
- hosts: 127.0.0.1
  tasks:
  - maven_artifact: group_id=junit artifact_id=junit dest=/tmp/junit-latest.jar 
  - maven_artifact: group_id=junit artifact_id=junit version=4.11 dest=/tmp/junit-4.11.jar 
  - maven_artifact: group_id=com.jfrog.artifactory.client artifact_id=api dest=/tmp repository=https://repo.jfrog.org/artifactory/libs-snapshots-local 
  - maven_artifact: group_id=com.jfrog.artifactory.client artifact_id=services dest=/tmp repository=https://repo.jfrog.org/artifactory/libs-snapshots-local 
  - maven_artifact: group_id=junit artifact_id=junit dest=/tmp/junit-latest.jar state=absent
  - maven_artifact: group_id=junit artifact_id=junit version=4.11 dest=/tmp/junit-4.11.jar state=absent
  - maven_artifact: group_id=com.jfrog.artifactory.client artifact_id=api dest=/tmp repository=https://repo.jfrog.org/artifactory/libs-snapshots-local 
  - maven_artifact: group_id=com.jfrog.artifactory.client artifact_id=services dest=/tmp repository=https://repo.jfrog.org/artifactory/libs-snapshots-local 
  - maven_artifact: group_id=org.jfrog.maven.plugins artifact_id=jfrog-jnlp-plugin dest=/tmp repository=https://repo.jfrog.org/artifactory/plugins-snapshots-local version=0.3-SNAPSHOT
  - maven_artifact: group_id=org.jfrog.maven.plugins artifact_id=jfrog-jnlp-plugin dest=/tmp repository=https://repo.jfrog.org/artifactory/plugins-snapshots-local version=latest

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @grilo. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @grilo for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chrisisbeef** [comment]
@grilo - Wow! Quite a refactor! I'll have to spend a little time running through this one. I believe there will be some conflicts with #2369 and #2255 - can we come back to this after those PRs are merged in, update the source to resolve any conflicts and then run through some testing scenarios?

**Comment by grilo** [comment]
Feel free to merge both of them first, ping me when you're done. I'll put some additional details on the next MR to make some of my decisions a little more obvious.

**Comment by gregdek** [comment]
@grilo A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by grilo** [comment]
Please, ignore this pull request. Somehow messed up and travis is being picky. Consider #2422 instead.

**Pull request closed without merging**
