### PR TITLE
Add more modes to the mysql_replication module

### LINKED ISSUE #979: Add more modes to the mysql_replication module
For instance `RESET SLAVE` and `RESET SLAVE ALL`.

### PR DESCRIPTION
**Pull request by tersmitten**
Fixes #979

### CODE REVIEW

**Comment by gregdek** [comment]
@banyek Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by banyek** [comment]
needs_revision the new operation modes are not documented, otherwise lgtm

**Comment by tersmitten** [comment]
Sorry I forgot that, I will fix it soon

**Comment by tersmitten** [comment]
@banyek: New operation modes are documented

**Comment by banyek** [comment]
then shipit !

**Comment by gregdek** [comment]
Thanks @tersmitten for the PR and thanks @banyek for the review.

Marking for inclusion. cc: @ansible/core team.

**Comment by tersmitten** [comment]
Great!

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
