### PR TITLE
Add thin pool / volume managment to lvol (follow up #2216)

### PR DESCRIPTION
**Pull request by ganto**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

lvol
##### ANSIBLE VERSION

```
ansible 2.3.0
```
##### SUMMARY

I have taken the stale PR #2216, by @mvdbeek (and originally @KlabKatsumi #1422) and rebased the two patches onto current `devel` HEAD. Unfortunately the logic got a bit shaken up by the recent check-mode update, which I tried to fix with my commits. I also rewrote the logical volume check logic.

If it matters, I could also try to rebase a bit "nicer" so that 0573674 wouldn't be necessary. Please let me know.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ganto. To the current maintainers, @jhoekx, @abulimov please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by haad** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @ganto for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by giovannicandido** [comment]
How to create the thinpool metadata?

For example, how to replicate this:

```
- name: vgcreate
  lvg:
    vg:  "{{vg_name}}"
    pvs: "{{physical_partitions}}"
- name: lvcreate thinpool
  lvol:
    vg: "{{vg_name}}"
    size: 95%VG
    lv: thinpool
- name: lvcreate thinpool meta
  lvol:
    vg: "{{vg_name}}"
    size: 1%VG
    lv: thinpoolmeta
- name: prepare pool
  command: "{{ item }}"
  with_items:
    - lvconvert -y --zero n -c 512K --thinpool {{vg_name}}/thinpool --poolmetadata {{vg_name}}/thinpoolmeta
    - mkdir -p /etc/lvm/profile
- name: configure {{vg_name}}-thinpool.profile
  template:
    src: templates/thinpool.profile
    dest: /etc/lvm/profile/{{vg_name}}-thinpool.profile
- name: enable thinpool profile
  shell: lvchange --metadataprofile {{vg_name}}-thinpool {{vg_name}}/thinpool 
- name: verify thinpool
  shell: lvs -o+seg_monitor
```

The playbook above create a thinpool and a thinpool meta data to use as docker device-mapper storage

But the problem is that is get executed every time it runs, failing. I would like to use _present_ function to declare and check and do nothing in the second run

**Comment by ganto** [comment]
@giovannicandido The proposed change doesn't break your playbook. You can continue using that. This PR should just make it simpler to define a "default" thin LV.

**Comment by ganto** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ganto. To the current maintainers, @jhoekx, @abulimov please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcdonadio** [comment]
I confirm this PR work as expected. Already using on production.

**Pull request closed without merging**
