### PR TITLE
Correction for spelling of 'azure_rm_deployment' in example

### PR DESCRIPTION
**Pull request by pipern**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

azure_rm_deployment
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

Documentation fix to allow example to work

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by devigned** [comment]
`azure_rm_deployment` looks right to me. I think that was changed upon it being pulled into the repo. Originally, I think it was `azure_rm_deploy`.

**Comment by gregdek** [comment]
Thanks @pipern. To the current maintainers, @devigned, @lmazuel please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by devigned** [comment]
shipit

**Pull request merged**
