### PR TITLE
Homebrew: Allow repository_path to be defined

### PR DESCRIPTION
**Pull request by ashmckenzie**
This is useful when both Boxen and Ansible exist on the same node.  Also PR is to help facilitate https://github.com/ashmckenzie/ansible-modules-extras/pull/1.

### CODE REVIEW

**Comment by gregdek** [comment]
@danieljaouen please review this PR; if you +1, we will merge

**Comment by gregdek** [comment]
@danieljaouen Please let us know if you're available to review pull requests for this module. 

If we don't hear from you within the next two weeks, we will assume that you're no longer interested in helping us maintain this module, and we will look for another maintainer. Thanks!

**Comment by gregdek** [comment]
We have a new reviewer -- thanks @indrajitr! 

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by indrajitr** [comment]
I wan't to test this PR once in a local OSX. Give me a day please.

**Comment by indrajitr** [comment]
I have an alternative take on this.

Currently `path` is already an available argument although this isn't documented (since it is missing from the `DOCUMENTATION` block -- can be fixed easily). This `path` allows us to provide an alternative `brew` location of our choice. Per [Homebew documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#multiple-installations), a formula is installed based on whichever `brew` command is called. And this is the _endorsed_ way of maintaining multiple homebrew installations.

So how about actually making good use of `path` (and surfacing it properly in documentation) instead of adding yet another variable?

@ashmckenzie, anything you found in current arrangement that was inadequate?

**Comment by ashmckenzie** [comment]
Sure :)  I'm not fussed as long as the path to where the brew shim exists
can be defined then I'm :+1:

**Comment by indrajitr** [comment]
Okay, #1053 is awaiting your endorsement :)

**Comment by robynbergeron** [comment]
Just to update anyone who happens to look in this PR to figure out current state:

@indrajitr has a (currently open) PR in #1053 which includes the capabilities implemented in this PR -- he and @ashmckenzie (AIUI) have agreed to go with #1053 -- so once that one is merged, we'll close this one too. (I just don't want this to get lost altogether if #1053 runs into any speedbumps!)

I'm going to mark this as pending_action -- not by anything / anyone on this PR, just pending the merge of #1053. :) Not the conventional use of this label but if @gregdek wants to disagree with me on it he knows where to find me :D :smirk_cat: 

Thanks to @indrajitr and @ashmckenzie for your collaboration and pleasant communication on these two PRs! :) (And to @ashmckenzie for your patience on getting this functionality in, too!)

**Comment by gregdek** [comment]
#1053 is now marked shipit, so closing this one. Thanks to everyone for helping to push this functionality through.

**Pull request closed without merging**
