### PR TITLE
Module/trigger

### PR DESCRIPTION
**Pull request by chepazzo**
module to use Trigger framework to interact with network devices.

### CODE REVIEW

**Comment by gregdek** [comment]
@privateip can you take a look at this one?

**Comment by privateip** [comment]
needs_revision

The docstring for version added needs to be a string not a float value and it should reflect the version added.  Also the README.md should not be there and the examples should be pushed into the docstrings.

**Comment by chepazzo** [comment]
Updated docs. I wasn't sure what version to put for `version_added`, so I used 1.9, since that's what I'm using.

**Comment by privateip** [comment]
add version: "2.0" to your documentation string

**Comment by gregdek** [comment]
Thanks @chepazzo for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chepazzo** [comment]
What is the revision needed?

**Comment by gregdek** [comment]
@chepazzo A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@chepazzo Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chepazzo** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @chepazzo for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
