### PR TITLE
Fix win_iis_webapppool and documentation

### LINKED ISSUE #2072: win_iis_webapppool failing with 'Specified cast is not valid'
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_iis_webapppool
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The win_iis_webappool documentation states that you can separate attributes by a pipe and name values by colon like  "foo:1|bar:2"  However, doing this in the task results in a 'Specified cast is not valid error.'
##### STEPS TO REPRODUCE

Create a basic playbook with attributes that are separated by a pipe:

```
- name: Setting up IIS application pool 
    win_iis_webapppool: 
      name: PoolParty
      state: started 
      attributes: "managedRuntimeVersion:v4.0|managedPipelineMode:0|queueLength:30000"
```

##### EXPECTED RESULTS

App pool would get created successfully.
##### ACTUAL RESULTS

```
TASK [Setting up IIS application pool] *****************************************
fatal: [52.39.68.141]: FAILED! => {"changed": false, "failed": true, "msg": "Specified cast is not valid."}
```

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

win_iis_webapppool
##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0 (devel 4549604cc7) last updated 2016/10/20 07:47:34 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 7a7ff3ebca) last updated 2016/10/20 07:48:27 (GMT +100)
  lib/ansible/modules/extras: (win_fix_webapppool e2b1647764) last updated 2016/10/20 20:22:26 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

This change allows application pool properties which are based on controlled values in the iis configuration xml schema to be set and retrieved correctly, without turning off strict mode.

In order to retrieve the controlled values, the module now imports the 
C:\Windows\system32\inetsrv\Microsoft.Web.Administration.dll
Further logic is required to retrieve the correct value for these controlled settings.
Also the enumeration names have to match the schema exactly, meaning the first letter of the property name has to be upper cased.

I also included the controlled (enumeration) values in the result object, allowing users to see which options are available.
The result object now returns the controlled name, rather than its array index position.  For example instead of
            "managedPipelineMode": 0,
the module now returns
            "managedPipelineMode": "Classic",

Fixes https://github.com/ansible/ansible-modules-extras/issues/2072
supercedes https://github.com/ansible/ansible-modules-extras/pull/2578

```
BEFORE:
ansible slweb -i DEPLOYTEST -l malpdwfftsla001 -m win_iis_webapppool -a "name='DefaultAppPool'"
Thursday 20 October 2016  16:11:18 -0400 (0:00:00.056)       0:00:00.056 ******
malpdwfftsla001 | SUCCESS => {
    "attributes": {},
    "changed": false,
    "info": {
        "attributes": {
            "CLRConfigFile": "",
            "applicationPoolSid": "S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415",
            "autoStart": true,
            "enable32BitAppOnWin64": true,
            "enableConfigurationOverride": true,
            "managedPipelineMode": 0,
            "managedRuntimeLoader": "webengine4.dll",
            "managedRuntimeVersion": "v2.0",
            "name": "DefaultAppPool",
            "passAnonymousToken": true,
            "queueLength": 1000,
            "startMode": 0,
            "state": 1
        },
        "name": "DefaultAppPool",
        "state": "Started"
    }
}
AFTER:

ansible slweb -i DEPLOYTEST -l malpdwfftsla001 -m win_iis_webapppool -a "name='DefaultAppPool'" 

malpdwfftsla001 | SUCCESS => {
    "attributes": {},
    "changed": false,
    "info": {
        "attributes": {
            "CLRConfigFile": "",
            "applicationPoolSid": "S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415",
            "autoStart": true,
            "enable32BitAppOnWin64": true,
            "enableConfigurationOverride": true,
            "managedPipelineMode": "Integrated",
            "managedRuntimeLoader": "webengine4.dll",
            "managedRuntimeVersion": "v2.0",
            "name": "DefaultAppPool",
            "passAnonymousToken": true,
            "queueLength": 1000,
            "startMode": "OnDemand",
            "state": "Started"
        },
        "enumerations": {
            "managedPipelineMode": [
                "Integrated",
                "Classic"
            ],
            "startMode": [
                "OnDemand",
                "AlwaysRunning"
            ],
            "state": [
                "Starting",
                "Started",
                "Stopping",
                "Stopped",
                "Unknown"
            ]
        },
        "name": "DefaultAppPool",
        "state": "Started"
    }
}
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Still no tests... but this is actually fairly easy to test.  First use win_feature to install IIS, then you can issue adhoc ansible commands against the IIS box.

Mentioning a few people here in the hope that some others can test this out.

@michelleperz - who reported #2072 
@deekayen - who opened #2578 
@rriggs - who reports https://github.com/ansible/ansible/issues/12494 (long since closed)

@nitzmahone - if there are any more RCs for 2.2 could this bugfix be cherry-picked?

**Comment by gregdek** [comment]
Thanks @jhawkesworth. To the current maintainers, @whenrik please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by deekayen** [comment]
Finally tested this today with 2.2.0.0. It doesn't resolve the issue I reported in #2578.

```
At C:\Users\svc_development\AppData\Local\Temp\ansible-tmp-1478704369.34-263216690497628\win_iis_webapppool.ps1:366 char:22
+   $pool.Attributes | ForEach {
+                      ~~~~~~~~~
fatal: [10.129.128.181]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "win_iis_webapppool"
    }, 
    "msg": "Property 'PropertyType' cannot be found on this object. Make sure that it exists."
}
```

**Comment by jhawkesworth** [comment]
@deekayen This fix is still unmerged, so is not in 2.2.0.0. 
To test it you would need to pull the code and put it in your /etc/ansible/library (or wherever you have library defined in your ansible.cfg) or use the updated files in this PR to replace the versions you have installed.

**Comment by jhawkesworth** [comment]
replacement PR https://github.com/ansible/ansible/pull/20680

**Pull request closed without merging**
