### PR TITLE
Added support for chain and direct rule manipulation

### PR DESCRIPTION
**Pull request by fzoske**
##### ISSUE TYPE
 - Feature Pull Request
##### COMPONENT NAME
system/firewalld.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

Added support for chain and direct rule manipulation.

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @fzoske. To the current maintainers, @maxamillion please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @fzoske for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fzoske** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @fzoske. To the current maintainers, @maxamillion please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
