### PR TITLE
Adds autofetch ability to known_hosts using ssh-keyscan

### PR DESCRIPTION
**Pull request by dokipen**
If key is unspecified and state=present, the known hosts entries will be autogenerated using ssh-keyscan. This is useful when provisioning new machines. It might make sense to have a flag to turn this on/off and require the user to explicitly turn it on to prevent carelessness. Let me know.

### CODE REVIEW

**Comment by gregdek** [comment]
@mcv21 Please review this PR; we will merge with a +1 from you.

**Comment by mcv21** [comment]
I think this is probably a bad idea. The point of managing known_hosts files is that you can be reasonably certain that the entries you add are correct; ssh-keyscan does away with that need. If what you wanted was to run ssh-keyscan on the target machine, you could just do that.

If we must put this in, I think it needs to be documented very clearly as subverting the security benefits of managing known_host; in that case an explicit option to enable would be much better than using ssh-keyscan if the user forgets to supply a host key.

**Comment by gregdek** [comment]
@dokipen can you refactor to address @mcv21's concerns?

**Comment by dokipen** [comment]
Sure, give me a week.

**Comment by gregdek** [comment]
@dokipen ping again :)

**Comment by gregdek** [comment]
To be specific: please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by robynbergeron** [comment]
@dokipen: A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing due to contributor inactivity. @dokipen please feel free to reopen this PR or open a new PR if/when you're ready to make the requested changes.

**Pull request closed without merging**
