### PR TITLE
Modules for gathering facts about ZFS datasets and pools

### PR DESCRIPTION
**Pull request by xen0l**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

zfs_facts.py
zpool_facts.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

These modules return facts about ZFS datasets and pools. They can be used for much better ZFS management with Ansible. They return ZFS dataset/pools properties as facts and based on those one can take decisions, e.g. delete snapshots older than X, report space usage, report property values, check ZFS pool health status etc.  These modules should run on all ZFS platforms and should work for both OpenZFS and ZFS implementations.

I also created a new category "zfs" under storage and move zfs.py there, so modules are kept together.

### CODE REVIEW

**Comment by xen0l** [comment]
@johanwiren this might be of interest to you.

**Comment by gregdek** [comment]
Thanks @xen0l for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @xen0l for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by xen0l** [comment]
ready_for_review

**Comment by xen0l** [comment]
ready_for_review

**Comment by ghost** [comment]
+1

**Pull request closed without merging**
