### PR TITLE
New module to retrieve AWS ECR (Container Registry) credentials

### PR DESCRIPTION
**Pull request by Etherdaemon**
New module to retrieve AWS ECR credentials to utilise with docker_login in later. This module grabs the details and returns an output which means users don't need to base64 decode tokens etc.

### CODE REVIEW

**Comment by Etherdaemon** [comment]
Hmm - I'm not sure what those checks are failing on - I'm not sure the failure messages are related to my module either.

**Comment by sivel** [comment]
> Hmm - I'm not sure what those checks are failing on - I'm not sure the failure messages are related to my module either.

You are correct.  They are failing on another module.  Once the submodule sha is advanced in the main ansible repo, that "error" should disappear, but shouldn't affect this PR.

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Etherdaemon A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robbiet480** [comment]
Could we try to get this integrated again now that some time has passed which should have fixed the submodule sha issue?

**Pull request closed without merging**
