### PR TITLE
openbsd_pkg: Add support for "pkgname%branch" syntax. Fixes #97

### LINKED ISSUE #97: Use -z when invoking pkg_add to allow installation of alternatives
##### Issue Type:

Bug Report/Feature Request
(WAS https://github.com/ansible/ansible/issues/8990)
##### Ansible Version:

1.6.1, but same in master
##### Environment:

OpenBSD
##### Summary:

openbsd_pkg 's module doesnt allow to install a package when it has alternatives - ie for example php-fpm, which could be 5.3 or 5.4 - or python, where 2.6, 2.7 and 3.3 are available
##### Steps To Reproduce:

playbook snippet:

```
- name: install php-fpm
  openbsd_pkg: name=php-fpm-5.4 state=installed
```
##### Expected Results:

php-fpm 5.4 should have installed
##### Actual Results:

```
failed: [twilight.rhaalovely.net] => {"failed": true, "item": ""}
msg: Error from http://ftp.fr.openbsd.org/pub/OpenBSD/5.5/packages/amd64/php-fpm-5.4.tgz
ftp: Error retrieving file: 404 Not Found
```

pkg_add has this feature that if you use -z, it will try fuzzy-matching the package name/version, if you provided it enough details

Various usescases for -z ..

```
$ sudo pkg_add -I php-fpm-5.4*  
Error from http://ftp.fr.openbsd.org/pub/OpenBSD/5.5/packages/amd64/php-fpm-5.4*.tgz
ftp: Error retrieving file: 404 Not Found
$ sudo pkg_add -Iz php-fpm      
Ambiguous: php-fpm could be php-fpm-5.3.28p3 php-fpm-5.4.24
$ sudo pkg_add -Iz php-fpm-5.4*
php-fpm-5.4.24: ok
```

If openbsd_pkg would add -z in pkg_add invocation in https://github.com/ansible/ansible/blob/devel/library/packaging/openbsd_pkg#L127, then i would be able to install the correct version of the package within the alternatives, specifying php-fpm-5.4\* in the name arg.

### PR DESCRIPTION
**Pull request by eest**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

openbsd_pkg
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 7ba71fc2d2) last updated 2016/06/27 18:58:32 (GMT +200)
  lib/ansible/modules/core: (devel 3c6f2c2db1) last updated 2016/06/27 18:59:31 (GMT +200)
  lib/ansible/modules/extras: (openbsd_pkg_branch d55f22a2c6) last updated 2016/06/30 18:56:13 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add support for the new "pkgname%branch" syntax coming to pkg_add in OpenBSD 6.0.

Fixes #97. While not implementing what was initially requested there (use of pkg_add -z) this does provide a way to install packages using less specific names in playbooks while still being able to remove the packages using those same names etc.

This change required me to modify the use if pkg_info as well, which improved the code overall because I could remove some custom parsing etc.

While working on this I did some cosmetic cleanup along the way.

### CODE REVIEW

**Comment by eest** [comment]
@bonds helped me verify a bugfix for the the build=true code which was encountered while working on this.

**Comment by gregdek** [comment]
Thanks again to @eest. This module is going into community review.

We notice that you are one of the maintainers (@eest) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by eest** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @eest. Since you are one of the maintainers (@eest) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
