### PR TITLE
User password change using ssh with ssh_key as authentication

### PR DESCRIPTION
**Pull request by ivanbojer**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

panos_admpwd
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

New panos module that allows for user password changes given ssh with ssh_key as authentication method. This is used in cloud environments where box comes up w/o password and with ssh_key only.

### CODE REVIEW

**Comment by ivanbojer** [comment]
ready_for_review

I am not sure why do checks fail at:
2016-10-20 22:29:04 Compiling ./network/panos/panos_admpwd.py ...
2016-10-20 22:29:04   File "./network/panos/panos_admpwd.py", line 195
2016-10-20 22:29:04     except Exception as x:
2016-10-20 22:29:04                       ^
2016-10-20 22:29:04 SyntaxError: invalid syntax

I cannot see anything wrong with that, please advise.

**Comment by gregdek** [comment]
Thanks @ivanbojer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by romain-dartigues** [comment]
Hi @ivanbojer,

I learned (in one of my PR) that modules should comply with http://docs.ansible.com/ansible/developing_modules.html#module-checklist.

Your case fall in the:

> Modules must be written to support **Python 2.4**. If this is not possible, required minimum python version and rationale should be explained in the requirements section in DOCUMENTATION. This minimum requirement will be advanced to Python-2.6 in Ansible-2.4.

The syntax `except X as Y` appeared in Python 2.6; you might correct it with:

``` python
except:
  x = sys.exc_info()[1]
```

Hope this could help.

**Comment by ivanbojer** [comment]
ready_for_review

**Pull request closed without merging**
