### PR TITLE
Initial commit for codedeploy_facts module.

### PR DESCRIPTION
**Pull request by czeeb**

### CODE REVIEW

**Comment by czeeb** [comment]
After a lot of digging, I see that ansible-validate-modules is complaining that there is no RETURN documentation block.  This wasn't immediately obvious to a new module author. Especially when almost all the existing modules are missing it.

``` bash
$ ../ansible/hacking/test-module -m cloud/amazon/codedeploy_facts.py -a "query=list_applications"
* including generated source, if any, saving to: /home/czeeb/.ansible_module_generated
* this may offset any line numbers in tracebacks/debuggers!
***********************************
RAW OUTPUT
{"applications": ["TestApplication"], "changed": false, "ResponseMetadata": {"HTTPStatusCode": 200, "RequestId": "03717d2c-b0d5-11e5-b101-e1a0e3fb23ac"}}


***********************************
PARSED OUTPUT
{
    "ResponseMetadata": {
        "HTTPStatusCode": 200, 
        "RequestId": "03717d2c-b0d5-11e5-b101-e1a0e3fb23ac"
    }, 
    "applications": [
        "TestApplication"
    ], 
    "changed": false
}

$ ../ansible/hacking/test-module -m cloud/amazon/codedeploy_facts.py -a "query=list_deployments application_name=TestApplication deployment_group_name=Production"
* including generated source, if any, saving to: /home/czeeb/.ansible_module_generated
* this may offset any line numbers in tracebacks/debuggers!
***********************************
RAW OUTPUT
{"changed": false, "ResponseMetadata": {"HTTPStatusCode": 200, "RequestId": "72531c13-b0d5-11e5-89e2-873c8c0b03be"}, "deployments": ["d-74Y1HLWZC", "d-L0MIOT00D", "d-UB2OEGXZC", "d-1BEUEMXZC", "d-UW5VQU00D", "d-CVWS8K10D", "d-UAO4EI60D", "d-Q6HMEI30D", "d-XWDF2AZZC", "d-C98D50XZC", "d-IY542U70D", "d-XC4GOZ20D"]}


***********************************
PARSED OUTPUT
{
    "ResponseMetadata": {
        "HTTPStatusCode": 200, 
        "RequestId": "72531c13-b0d5-11e5-89e2-873c8c0b03be"
    }, 
    "changed": false, 
    "deployments": [
        "d-74Y1HLWZC", 
        "d-L0MIOT00D", 
        "d-UB2OEGXZC", 
        "d-1BEUEMXZC", 
        "d-UW5VQU00D", 
        "d-CVWS8K10D", 
        "d-UAO4EI60D", 
        "d-Q6HMEI30D", 
        "d-XWDF2AZZC", 
        "d-C98D50XZC", 
        "d-IY542U70D", 
        "d-XC4GOZ20D"
    ]
}
```

Given the above example output for two of the query types for the codedeploy_facts module is the following a correct RETURN block?  Each query type returns different output, which is the part I'm not too sure on how to put in the documentation. There aren't any other _facts modules that have a RETURN block that I can use as an example to work from.

``` yaml
applications:
  description: List of applications
  returned: success
  type: list
  sample:
    [
      "TestApplication",
      "AnotherTestApplication"
    ]

deployments:
  description: List of deployments
  returned: success
  type: list
  sample:
    [
      "d-74Y1HLWZC", 
      "d-XC4GOZ20D"
    ]
```

**Comment by robynbergeron** [comment]
Thanks @czeeb for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by czeeb** [comment]
@robynbergeron is there something I need to do to get eyes on this?  I sent an email to the ansible mailing list with my question and I didn't get any response.

**Comment by gregdek** [comment]
@czeeb A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by czeeb** [comment]
@gregdek I fully intend to update the PR as soon as my question is answered about what format and information should go in the RETURN block.  I do not want to simply through something random in there that is not helpful.

I've tried asking in this PR and on the Ansible mailing list to get an answer.  At the time I posed the question, I couldn't find the answer in any of the existing modules I checked or in the Ansible documentation. The experience has been a bit frustrating, to say the least.

**Comment by gregdek** [comment]
@czeeb Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by czeeb** [comment]
@robynbergeron Could I get a little help here? I've been waiting for months to get an answer to what should be a simple question that I can't find an answer to anywhere in the documentation.

**Comment by gregdek** [comment]
Sorry @czeeb -- we're still working on our bot game. 

RETURN was added fairly recently as a requirement. Let me do some quick research and get back to you.

**Comment by gregdek** [comment]
OK, I double-checked, and it is in the new module documentation:

http://docs.ansible.com/ansible/developing_modules.html

Scroll down to where it says "The RETURN section documents what the module returns" and there's an example there. This is a documentation requirement. 

For other good examples, feel free to look at the modules in ./cloud/cloudstack/.

**Comment by gregdek** [comment]
@czeeb A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@czeeb Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@czeeb A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@czeeb Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@czeeb A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the Travis issues, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

needs_revision

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
