### PR TITLE
support host parameter to datadog_event module closes #2837

### LINKED ISSUE #2837: datadog_event module does not correctly set host for event
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

datadog_event
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

The `datadog_event` module does not allow correctly setting the host to be associated with events. The hostname should be passed to Datadog using the 'host' parameter in their API.

The documentation for this module shows setting a tag called 'host', which does not achieve the same thing.
##### STEPS TO REPRODUCE

Use the `datadog_event` module to submit an event to Datadog indicating that an Ansible run has completed, for example. As indicated in the documentation, set a host tag, e.g. `tags="host:example.com"`

In Datadog, verify that the event appears in the event stream. And shows the host tag that was set. Now search for `host:example.com`. The event just submitted does not appear, because it doesn't match the search (!).

This is certainly an confusing quirk in the Datadog interface, but their support team insist that the correct way to submit a host tag is using the 'host' parameter in their API, which this Ansible module does not currently support.
##### EXPECTED RESULTS

I would expect the submitted Datadog event to be correctly associated with the host. 

The problem is a combination of two things - primarily this module's lack of support for setting the 'host' parameter in the call to Datadog's API. The second is the misleading documentation, which shows setting a 'host' tag using the 'tags' parameter.

And this probably came about because the Datadog documentation for this API method does not demonstrate use of the 'host' parameter in the example code.

### PR DESCRIPTION
**Pull request by n0ts**
ISSUE TYPE
- Fix Pull Request for #2837

COMPONENT NAME
- monitoring/datadog_event.py

ANSIBLE VERSION
- 2.1.1.0

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @n0ts for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by n0ts** [comment]
ready_for_review

**Comment by n0ts** [comment]
'ready_for_review'  @greenbrian @ansibot

**Comment by n0ts** [comment]
'ready_for_review'

**Comment by n0ts** [comment]
shipit

**Comment by n0ts** [comment]
@gregdek Could you shiptit?

**Comment by n0ts** [comment]
@gregdek @ansibot shipt

**Comment by n0ts** [comment]
@gregdek @ansibot shipit

**Comment by n0ts** [comment]
ready_for_review

**Comment by n0ts** [comment]
@gregdek @ansibot ping...

**Pull request closed without merging**
