### PR TITLE
win_share: add module to manage smb shares

### PR DESCRIPTION
**Pull request by h0nIg**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes, which can be contributed by anyone other than the author of the new module:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

More information about the review process can be seen here: 
https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

Thanks again for submitting your Ansible module!

cc: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by trondhindenes** [comment]
Maybe we should consider moving the UserSearch function into powershell.ps1 since it is used by multiple modules? @gregdek: Any thoughts on how we should plan for "common functionality" in PowerShell-based modules?

**Comment by bcoca** [comment]
it is common enough a pattern, yes, if it is something only a subset of modules use, we might want a nother shared .ps1 file ('users.ps1'?)

**Comment by trondhindenes** [comment]
Yep, we should start looking at breaking powershell.ps1 down into smaller chunks. I can start a thread in Groups regarding this.

**Comment by h0nIg** [comment]
regarding the common functions: the split can be made later, right?

Pinging the windows guys for review: @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by koloros** [comment]
i would appreciate the inclusion.

works_for_me

ping: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by jhawkesworth** [comment]
I notice the module only supports Win 8.1 / S 2012 and later.  
Currently modules are supposed to support powershell 3.0 and later - is there an alternative to Get-SMBShare etc that could be used for older windows versions?

**Comment by h0nIg** [comment]
Since powershell is "new" compared to linux/bash there are some missing configuration options for older OS'es like Windows 7 / 2008. The SMBShare commands target a new WMI namespace (ROOT/Microsoft/Windows/SMB) that does not exist on earlier versions of the OS.

However it is possible to do some dirty hacks with the win_share wmi  (https://msdn.microsoft.com/en-us/library/windows/desktop/aa389393%28v=vs.85%29.aspx). BUT i did not implemented it using these methods, because they are very complex and more C like.

**Comment by tsintwin** [comment]
according to http://docs.ansible.com/ansible/developing_modules.html it looks good
+1
passes_guidelines

**Comment by jlevis** [comment]
works_for_me

Ansible 2.0.0.2 (Ubuntu 14.04)
Windows Server 2012 R2
:+1:

**Comment by h0nIg** [comment]
would be nice if some of the core guys will comment on this @abadger @sivel @gregdek @bcoca

**Comment by Jmainguy** [comment]
@h0nIg If you can squash the git commits into one commit, it will make it easier when this gets merged for people to see what was actually added. I am not very familiar with Windows now a days, so this is about the only value I can add to this review.

**Comment by h0nIg** [comment]
@Jmainguy checkout the "Files changed" tab at the top. there you can see the full changeset

**Comment by nitzmahone** [comment]
@h0nIg Sorry it's taken so long to get to this- looks great! I have a few little tweaks I might make (around exception handling/diagnostic stuff) down the line. Also, it'd be great if you wanted to add support for check mode (now that Windows modules support it in 2.0), but I'm merging as-is. Thanks!

**Comment by h0nIg** [comment]
FYI: stict mode is already supported, development was done based on 2.0. Are there some points i missed?

**Pull request merged**
