### PR TITLE
return a proper result set for getmaster/getslave

### PR DESCRIPTION
**Pull request by srgvg**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

database/mysql/mysql_replication.py
##### ANSIBLE VERSION

2.1.0.0
##### SUMMARY

When doing a getslave on a master or getmaster on a slave, the module fails, and doesn't return a clean error message.

```
tns1270 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Server is not configured as mysql slave. ERROR: exit_json() argument after ** must be a mapping, not NoneType"
}
```

This patch makes the module return a proper result set, which can more cleanly be handled in a playbook.

```
tns1270 | SUCCESS => {
    "changed": false, 
    "msg": "Server is not configured as mysql slave", 
    "slave": false
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @srvg. To the current maintainers, @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Change looks sensible

shipit

**Comment by gregdek** [comment]
Thanks again to @srvg for this PR, and thanks @banyek for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by srgvg** [comment]
I added a small patch to this to make sure `getslave` and `getmaster` always return at least a boolean `Is_Slave` and `Is_Master` key in their result, for a more uniform result set, and typically to be used in further conditionals.

**Comment by gundalow** [comment]
my shipit still stands

**Comment by abadger** [comment]
Thanks @srvg !  merged to devel.

**Pull request merged**
