### PR TITLE
change zabbix host.delete() parameter for newer API

### PR DESCRIPTION
**Pull request by tomgoto**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

zabbix_host
##### Summary:

As of Zabbix API 2.4, host.delete() will not takes parameter with
`hostid` property but only the array of it.
https://www.zabbix.com/documentation/2.2/manual/api/reference/host/delete

If you use Zabbix API newer than that, deleting host fails with SQL error.
Please refer to #1800

Also, I added `module.exit_json(changed=False)` to idempotently exit module when 
you try to delete the already deleted host.

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @tomgoto. To the current maintainers, @eikef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by eikef** [comment]
Looks good, thank you :-)

**Comment by eikef** [comment]
shipit

**Comment by resmo** [comment]
Thanks again to @tomgoto for this PR, and thanks @eikef for reviewing. Marking for inclusion.

**Pull request merged**
