### PR TITLE
Add more idempotency for zabbix_hostmacro.py

### PR DESCRIPTION
**Pull request by knakayama**
`zabbix_hostmacro.py` does not check macro value, so always updates hostmacro even if macro value is the same.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks, @knakayama. 

@cove -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@cove This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@cove still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
@cove This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@ansible still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
This module is now managed by the @ansible/core team. Thanks for your patience @knakayama.

**Comment by gregdek** [comment]
Thanks @knakayama. @eikef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by eikef** [comment]
Thank you @knakayama; (un)fortunately your PR fixes the exact same issue as PR #706 which is due to be committed soon (and had been languishing for a while, same as your PR). As such I'd like to close this PR and apologize for the duplicated work (zabbix-related PRs should now be handled quite a bit quicker though :-)

**Comment by knakayama** [comment]
Thanks for all replies!

I wasn’t aware that PR #706. Sorry. I think this PR should close.

**Pull request closed without merging**
