### PR TITLE
zypper_repository: don't silently ignore repo changes

### PR DESCRIPTION
**Pull request by agx**
So far when a repo URL changes this got silently ignored (leading to
incorrect package installations) due to this code:

```
elif 'already exists. Please use another alias' in stderr:
    changed = False
```

Removing this reveals that we correctly detect that a repo definition
has changes (via repo_subset) but don't indicate this as change but as a
nonexistent repo. This makes us currenlty bail out silently in the above
statement.

To fix this distinguish between non existent and modified repos and
remove the repo first in case of modifications (since there is no force
option in zypper to overwrite it and 'zypper mr' uses different
arguments). Recreate it as usual. Only do this if we have an alias name
since with a different name a new repo is o.k.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @agx. @matze please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by matze** [comment]
shipit :+1:

**Comment by agx** [comment]
@matze thanks a lot for review! 

I needed to do some major changes since the detection of changes in the repo did not work as intended with multiple repos (marking repos as changed although they weren't). 

Since I have no means to test zypper 0.x I removed support for that ancient version (SLES11 already has 1.x and all currently supported OpenSUSE versions as well).

I'm happy to provide integration tests in ansible proper but would like to avoid the situation with

https://github.com/ansible/ansible/commit/0821d251c8878990326ffee567ab2a5baafd089a

where we have the tests merged in ansible but the fixes still  pending in ansible-modules-extras.

**Comment by robinro** [comment]
this might also fix #939

**Comment by gregdek** [comment]
Thanks again to @agx for this PR, and thanks @matze for reviewing. Marking for inclusion.

**Comment by agx** [comment]
I fixed an issue when deleting repositores (state=absent) with a separat patch on top of the current one. I'm happy to squash the patches but wanted to ease review.

This makes the just submitted integration tests

```
https://github.com/ansible/ansible/pull/15004
```

pass so hopefully we won't regress in the future.

**Comment by agx** [comment]
This one has a four months old. Can it be merged?

**Comment by gregdek** [comment]
@ansible/core team, looks like this has been in shipit for a while... help?

**Comment by robinro** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1990#issuecomment-209676569 raises an issue also for this PR. We drop support for old zypper versions. I added some requirements statement over there but maybe @agx knows more about which SLES version we need to have the new zypper?

https://github.com/ansible/ansible-modules-extras/pull/1990 is based on this PR and extends it. Maybe they can be considered together?

**Comment by robinro** [comment]
@agx
I hope you agree with the merge and close. Please let me know if not. I only now realized you didn't comment on them.
I kept your commits, so your contributions are visible. Thanks for your work!

**Comment by agx** [comment]
Hi,
On Mon, Apr 18, 2016 at 09:12:07AM -0700, Robin Roth wrote:

> @agx
> I hope you agree with the merge and close. Please let me know if not. I only now realized you didn't comment on them.
> I kept your commits, so your contributions are visible. Thanks for your work!

I'm fine with anything that gets ansible usable on SLES. That one of
these. Thanks a log!
 -- Guido

**Pull request closed without merging**
