### PR TITLE
Fix #1107: win_regedit parameter parsing and New-Item prompt error

### LINKED ISSUE #1107: win_regedit: Failure in parameter validation and in creating registry key
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/13 06:57:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/13 06:57:49 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/13 06:58:00 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = /vagrant/ansible/library
```
##### Ansible Configuration:

I haven't changed anything that affects this module.
##### Environment:

Running from Ubuntu 14, managing Windows Server 2012 R2.
##### Summary:

Two issues: 
1. win_regedit fails with property error when parsing parameters
2. win_regedit fails to create a new registry key with a NonInteractiveMode error
##### Steps To Reproduce:
- Use win_regedit to create a new registry value in a new key
##### Expected Results:

It successfully creates the key
##### Actual Results:

It fails with strict mode errors when parsing parameters.  After moving the parameter parsing to use Get-Attr, it started failing saying you can't prompt in NonInteractiveMode.  Digging in, I saw that it was prompting for the Type parameter in the New-Item call to create the key.  I fixed this by prepending a "Registry::" before the path so Powershell knows it's a registry path.  Pull request coming shortly.

### PR DESCRIPTION
**Pull request by bgeihsgt**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @bgeihsgt -- thanks for submitting this PR.

@smadam813 & @joshludwig -- note that this is a PR to fix #1107.

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also pinging other windows folks for good measure: @trondhindenes @petemounce @elventear @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by smadam813** [comment]
I will review this afternoon!  Thanks @bgeihsgt and @robynbergeron

**Comment by smadam813** [comment]
Tested:  Formatting is fine and it works as expected.  Thanks again @bgeihsgt 

@robynbergeron shipit

**Comment by gregdek** [comment]
@bgeihsgt thanks for the PR, and @smadam813 thanks for the review. Marking for inclusion.

**Comment by jhawkesworth** [comment]
I know this is marked for inclusion already, but for what its worth, once this is merged I can contribute my integration tests for win_regmerge (the tests use win_regedit).

**Pull request merged**
