### PR TITLE
Module to move different subtrees to btrfs submodules.

### PR DESCRIPTION
**Pull request by theunixman**
This module will create a btrfs subvolume, then copy the data from the source path to the destination path. It determines the destination by appending the subvolume name to the root btrfs path.

### CODE REVIEW

**Comment by bcoca** [comment]
I would add state=present|absent and add the ability to remove the subvolume

**Comment by gregdek** [comment]
@misandrist can you make the requested changes?

**Comment by gregdek** [comment]
@misandrist A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to inaction.

**Comment by theunixman** [comment]
Sorry, what were the requested changes?

**Pull request closed without merging**
