### PR TITLE
Feature LXC module  support -P {new_directory}. 

### LINKED ISSUE #3114: LXC_CONTAINER clone should support -P {new_directory} and -p {original_directory} for cloning into a new directory in lxc v1.0.x
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

lxc_container
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel aa1ec8af17)
```
##### OS / ENVIRONMENT

ansible running on Ubuntu 12.04 LTS
lxc running on CentOS release 6.7 (Final)
##### SUMMARY

Presently there is not a way to clone (without snapshot) a directory based container to a new filesystem path. However this is supported by the underlying lxc-clone command: 

lxc-clone -p /original/container/path/ -P /mnt/lxc_new_container_path -o original_container_name -n new_container_name

Usage: lxc-clone [-s] [-B backingstore] [-L size[unit]] [-K] [-M] [-H]
          [-p lxcpath] [-P newlxcpath] orig new

  -s: snapshot rather than copy
  -B: use specified new backingstore.  Default is the same as
      the original.  Options include aufs, btrfs, lvm, overlayfs,
      dir and loop
  -L: for blockdev-backed backingstore, use specified size \* specified
      unit. Default size is the size of the source blockdev, default
      unit is MB
  -K: Keep name - do not change the container name
  -M: Keep macaddr - do not choose a random new mac address
  -p: use container orig from custom lxcpath
  -P: create container new in custom lxcpath
##### EXPECTED RESULTS

Wanted the ability to clone a directory based container to a new filesystem location
##### ACTUAL RESULTS

Was not possible without modifying lxc_container.py src

### PR DESCRIPTION
**Pull request by cocoy**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

Moudle lxc/lxc_container
##### ANSIBLE VERSION

```
ansible 2.3.0

```
##### SUMMARY

LXC_CONTAINER clone should support -P {new_directory}
Added option to specify new path for  for lxc clone "Fixes #3114" 

```
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "archive": false, 
            "archive_compression": "gzip", 
            "archive_path": null, 
            "backing_store": "dir", 
            "clone_name": "test-clone2x", 
            "clone_snapshot": false, 
            "config": null, 
            "container_command": null, 
            "container_config": null, 
            "container_log": false, 
            "container_log_level": "INFO", 
            "directory": null, 
            "fs_size": "5G", 
            "fs_type": "ext4", 
            "lv_name": "ubuntu02", 
            "lxc_path": null, 
            "name": "ubuntu02", 
            "new_path": "/var/lib/lxc2x", 
            "state": "stopped", 
            "template": "ubuntu", 
            "template_options": null, 
            "thinpool": null, 
            "vg_name": "lxc", 
            "zfs_root": null
        }, 
        "module_name": "lxc_container"
    }, 
    "lxc_container": {
        "cloned": true, 
        "init_pid": -1, 
        "interfaces": [], 
        "ips": [], 
        "name": "ubuntu02", 
        "state": "stopped"
    }
}

TASK [debug info on container "test-container"] ********************************
ok: [localhost] => {
    "clone_container_info": {
        "changed": true, 
        "lxc_container": {
            "cloned": true, 
            "init_pid": -1, 
            "interfaces": [], 
            "ips": [], 
            "name": "ubuntu02", 
            "state": "stopped"
        }
    }
}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @cocoy. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cloudnull** [comment]
Thanks @cocoy. changes LGTM.

**Comment by cloudnull** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @cocoy for this PR, and thanks @cloudnull for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cocoy A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cocoy** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @cocoy. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
