### PR TITLE
Pass the lxc_path when checking if container exists

### LINKED ISSUE #887: lxc-create fails when using lxc_path parameter
Hi,

There is an issue when I use the lxc_path parameter where ansible will mark the task as fail, although the actual container itself is correctly created in the target host. It seems like the module tries to recreate the container twice.

Note that before every run, I ensure that the container has been deleted by running lxc-destroy -n <container-name>  -P /mnt/lxc2 on the target host

Here's my task to create the lxc container in my Ansible Role file

-name: Create LXC container
  lxc_container:
   name: test
   container_log: true
   lxc_path: /mnt/lxc2/
   template: centos
   state: stopped

Ansible Playbook run output
TASK: [lxc | Create LXC container] *******************************************\* 
failed: [x.x.x.x] => {"command": "/usr/bin/lxc-create --name test --quiet --config /etc/lxc/default.conf --template centos --lxcpath /mnt/lxc2 --bdev dir --logfile /var/log/lxc/lxc-test.log --logpriority INFO", "err": "Container already exists\n", "failed": true, "rc": 1}
msg: Failed executing lxc-create.

### PR DESCRIPTION
**Pull request by skoster**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

lxc_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Passes the lxc_path to the list_containers call which is called when checking if the container exists. Without it, the list_containers call will look at the default location which is not correct when overridden. If no lxc_path is provided, the code will fall back to the default functionality. 

Before:

```
TASK [lxc : Create the LXC container] ******************************************
fatal: [vagrant]: FAILED! => {"changed": false, "command": "/bin/lxc-create --name sktest --quiet --template fedora --lxcpath /virt/lxc --bdev dir --logfile /var/log/lxc/lxc-sktest.log --logpriority INFO -- --release=23 --arch=x86_64", "err": "Container already exists\n", "failed": true, "msg": "Failed executing lxc-create.", "rc": 1}
```

After:

```
TASK [lxc : Create the LXC container] ******************************************
changed: [vagrant]
```

fixes #887

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @skoster. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cloudnull** [comment]
LGTM thanks for the fix @skoster

**Comment by cloudnull** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @skoster for this PR, and thanks @cloudnull for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
