### PR TITLE
Adding support for service rules

### PR DESCRIPTION
**Pull request by trumant**
The existing code neglected to include support for the full ACL format, which includes not just policies on keys in the Consul KV store, but also service paths. Sample ACL format is:

```
# Default all keys to read-only
key "" {
  policy = "read"
}
key "foo/" {
  policy = "write"
}
key "foo/private/" {
  # Deny access to the dir "foo/private"
  policy = "deny"
}

# Default all services to allow registration
service "" {
    policy = "write"
}

# Deny registration access to services prefixed "secure-"
service "secure-" {
    policy = "read"
}
```

### CODE REVIEW

**Comment by trumant** [comment]
@sgargan - Thanks for your original contribution of this module. Would appreciate it if you could give these changes a quick review.

**Comment by sgargan** [comment]
The original submission was developed against the 0.4 release of Consul, the service rules were added in the recent 0.5 release. I took a look through the submission and it all looks reasonable to me, the Rules class could do with adding the service entries to the _eq_ method as without this rule updates may not be applied and the 'changed' status may not report correctly. 

There was a complimentary commit to the core project in the original sumbmission that contained a suite of integration tests, Its easy to overlook them the way the projects are split. @trumant I suggest adding tests for your service rules and run these against your 0.5 cluster to verify.

**Comment by trumant** [comment]
Thanks for the additional context. Will follow up with some integration
tests and review the equals implementation

**Comment by trumant** [comment]
@sgargan - Followed your tip and dove into the integration tests. They revealed that the consul Python lib upon which this module relies does not yet support passing an auth token when it registers a service. I'm hopeful I'll get a chance to address that issue soon. Relevant change will end up being a PR here: https://github.com/cablehead/python-consul/ that will then get consumed by this module.

**Comment by sgargan** [comment]
Good stuff! he's pretty good about fixing bugs and merging PRs so if its an
easy fix your turnaround will be quick.

**Comment by gregdek** [comment]
Hi @trumant. Looks like you're still waiting for an upstream change here? I'm presuming so and will leave it open -- just ping and let me know.

If you do get a chance to update this PR, please let us know by adding "ready_for_review" to a comment and we'll get it back into the review process. Thanks!

**Comment by robynbergeron** [comment]
@trumant -- A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by robynbergeron** [comment]
@trumant @sgargan -- put in some boilerplate above just to keep this moving along -- if either of you have any insight into whether or not the upstream changes have made it in and if this can make some progress, let us know and we can put it back into the process stream.

**Comment by trumant** [comment]
It does look like the upstream changes have been made: https://github.com/cablehead/python-consul/commit/1a039801d676e2dea65925e79bc35edb75eee02e

Not sure I'll have the time to integrate/test the new upstream state though.

**Comment by gregdek** [comment]
Thanks @trumant -- just let us know.

This now also needs rebasing as well.  If you're interested in continuing work on this, just ping with your intention to do so and we'll continue to hold it open for you.

When you have made any necessary changes, please add a comment with the text "ready_for_review" and we will continue with the review process.  

If no response within the next week or so, we'll assume you don't have the time and we'll close the PR.

Thanks for sticking with it thus far.

**Comment by gregdek** [comment]
@trumant since we haven't heard back from you, I'm going to close this PR. Please feel free to open a new PR with any changes you might feel necessary.

**Pull request closed without merging**
