### PR TITLE
To reload Windows DNS zone after edited any changes, including insert, modify and delete.

### PR DESCRIPTION
**Pull request by teochenglim**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

Module: win_dns_reload_zone
##### ANSIBLE VERSION

```
devel
```
##### SUMMARY

```
To reload windows DNS zone after edited any changes, including insert, modify and delete.
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by teochenglim** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @teochenglim for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by teochenglim** [comment]
ready_for_review

**Comment by teochenglim** [comment]
ready_for_review

**Pull request closed without merging**
