### PR TITLE
Windows module to unzip zip files

### PR DESCRIPTION
**Pull request by perzizzle**
Windows module to unzip zip files. Discussed in google group at https://groups.google.com/forum/#!starred/ansible-devel/3wSl03GLGGY

### CODE REVIEW

**Comment by perzizzle** [comment]
I created a test playbook but wasn't sure where to put it. It's dependent on a zip file being staged on the remote machine (I don't have win_copy working on my test machine). The zip file is called file.zip and contains parentFolder/childFolder/file.txt. The gist below has the test playbook.

https://gist.github.com/perzizzle/c25daebfb66dcb16be42

**Comment by elventear** [comment]
Tried the module; works for me. It would be nice to have a feature where we could specify the destination is a directory and it should be created if it doesn't exist already.

**Comment by perzizzle** [comment]
Makes sense, I can add the ability to create the destination path as an option.

**Comment by perzizzle** [comment]
Commit 164c541 checks to see if the destination path exists and creates it if it doesn't. Didn't seem worth creating another parameter for this. I believe it follows the unarchive paradigm. @elventear

**Comment by elventear** [comment]
:+1:

**Pull request closed without merging**
