### PR TITLE
Update mongodb_user.py

### PR DESCRIPTION
**Pull request by senz**
Auth source support for mongodb_user.
Probably need pymongo version check.

### CODE REVIEW

**Comment by gregdek** [comment]
@senz This PR needs revisions. 

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by senz** [comment]
@gregdek already added in 781043f
ready_for_review

**Comment by elliotttf** [comment]
:+1:

**Comment by gregdek** [comment]
Thanks @senz for the PR, and thanks @elliotttf for the review, and thanks @resmo for poking @elliotttf. :) 

Marking for inclusion. cc: @ansible/core team.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
