### PR TITLE
Update mongodb_user.py

### PR DESCRIPTION
**Pull request by lsb**
Typo

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @lsb. @elliotttf please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Lujeni** [comment]
@lsb @gregdek imho, this comment must be a docstring (and the second comment also), it's more pythonic in this case. Otherwise we can `shipit`.

**Comment by robynbergeron** [comment]
@elliotttf This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Lujeni** [comment]
Hello,

@robynbergeron 
In this PR #1122 

> Can I transfer maintainership of this to someone else? I haven't kept on top of this as I'm no longer actively involved in server configuration and deployment. Elliott Foster @elliotttf

**Comment by resmo** [comment]
trivial fix, typo in comment 
shipit

**Comment by gregdek** [comment]
Thanks @resmo, and thanks @lsb for the PR.

**Pull request merged**
