### PR TITLE
Fix some SSL errors in mail.py causing SMTP Syntax Errors 

### PR DESCRIPTION
**Pull request by dayton967**
The current module just tries to connect via SSL on any and all ports.  By default the only SMTP port that this should occur on is port 465.  All other ports use ehlo and will start SSL after SMTP synchronization has occurred.

This change allows the end user to choose to enable ssl on any port, but by default will only attempt to use SSL on the defined SSMTP port 465 only.

### CODE REVIEW

**Comment by gregdek** [comment]
@dagwieers Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by dayton967** [comment]
I have been running this change without a problem, so I would say shipit

**Comment by gregdek** [comment]
@dayton967 Sure, but you're the submitter. I'd expect you to say that. :)

Let's give @dagwieers some time to review.

**Comment by dayton967** [comment]
feel free.. it's been running for 2 months.  The change was relatively simple so I'll add this needs_revision just so someone can look through then.

**Comment by dagwieers** [comment]
Ok, I haven't tested the code. But just looking at the code I was wondering the whole time: "What if int() fails".

So what I would do is move the if/else statement within the try/except block, and as a result the int(port) will cause a proper json error that is traceable. It also simplifies the code (as you can replace two identical try/except blocks into a single block.

Another point of contention is that if either use_ssl _or_ port=465 is set, SSMTP is tested, but on failure it falls back to normal SMTP. Now, I can understand that if you see port 465 you could assume SSL is needed, or when use_ssl is set (but port is e.g. 25) you'd want SSL too. But why fall back to non-SSL if there is an SSL error. I think that is a security problem (silently ignoring the wishes of the user).

So my preference is to not make assumptions, or at least make (port 465 means use_ssl) explicit in your documentation and very obvious in your code at the start (not in the evaluation). And not to fall back to insecure connections when we determined SSL is expected by the user. So if start_tls is supposed to be used, that should be enforced, and it is missing in the second block.

Does this make sense ?

**Comment by dayton967** [comment]
Yes it does I'll look at refactoring when I get a chance.  It's crazy right
now at work, rebuilding a network for 10k users

**Comment by dagwieers** [comment]
And then there's also this issue: https://twitter.com/jpmens/status/630651460070572032
@jpmens :-)

**Comment by gregdek** [comment]
Thanks @dagwieers for the review. 

@dayton967 Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by dayton967** [comment]
Sorry I haven't gotten around to the code cleaning as I've been very sick
followed by unbearably overworked with a rebuild of a network, that covers
sites across the country.

**Comment by gregdek** [comment]
Thanks @dayton967 -- will leave this open and check back in with you in a couple of weeks.

**Comment by robynbergeron** [comment]
@dayton967 -- A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by dayton967** [comment]
Yes but i have been super busy which has killed any time i have had.  I
think I can get it out for the next release of you need to push quickly.

**Comment by gregdek** [comment]
Going to assume this is ready for re-review. Back to @dagwieers.

**Comment by dagwieers** [comment]
I have the following feedback up for debate:
- Maybe name the option 'secured' rather than 'use_ssl', it feels more forward-compatible ? What do other modules do in this respect ?
- I would leave out the whole service-name to port logic and only allow port numbers (ironically this is what the help mentions anyway).
- I have an issue with the fact that if 'use_ssl' is explicitly set to 'no', SSL may still be attempted. So I would propose to keep it simple. If it is unset, you could try to be smart (e.g. use the port number to assume SSL is required), but if it is explicitly set to 'no', SSL must not be used. This change will make the code much more straightforward to read (and maintain onward), but also maps more closely what the user would expect IMO.
- And then there is the STARTTLS question. One could have use_ssl=no, and STARTTLS would still be attempted. So maybe there needs to be a relation to this option as well. Or it should be documented that when username/password is used STARTTLS is attempted, but not guaranteed. (which should scare every sane user) If we'd be very security conscious, we should not allow the combination username/password without 'use_ssl' or 'STARTTLS'.

PS This pull request also touches the hall.py module permissions. Probably that should be removed from the pull request, and added to its own pull request. (I know its harmless, but also unrelated...)

**Comment by bcoca** [comment]
+1 for 'secured' or 'encrypted' option

Also we might want to attempt to starttls by default and just fail gracefully, no matter what the port.
Unless the user explicitly sets the option, then behave accordingly.

**Comment by gregdek** [comment]
Kicking this one.

**Comment by gregdek** [comment]
Thanks @dayton967. To the current maintainers, @dagwieers please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dayton967 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
It is a shame that this PR has not been merged yet, and if I played any part in it not being merged I am really sorry. If you resolve the conflicts and rebase it, I will review it and sign it off ASAP.

**Comment by gregdek** [comment]
@dayton967 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dayton967** [comment]
ready_for_review Sorry for the delays I've been killer busy at work so I am just getting back to it.

**Comment by gregdek** [comment]
Thanks @dayton967. To the current maintainers, @lpenz, @tarka, @ivanbojer, @indrajitr, @bcoca, @dagwieers, @yaegashi, @L2G, @szinck, @troy2914 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by troy2914** [comment]
needs_revision

documentation in notification/mail.py is inconsistent
choices: [ "Always", "Never", "Try", "StartTLS"]
yet the lines above that showed the choices as all lowercase

then again under
mail:
-    secure=True
  what? True is not a valid choice for secure.

And why was the newline removed from the last line of that file?

**Comment by troy2914** [comment]
Looks better.

shipit

**Comment by dayton967** [comment]
Thanks.  for Dag, the Copyright should be updated, as it's still at 2012, but I didn't think it was my place to update that part for him.

**Comment by gregdek** [comment]
Thanks again to @dayton967 for this PR, and thanks @lpenz, @tarka, @ivanbojer, @indrajitr, @bcoca, @dagwieers, @yaegashi, @L2G, @szinck, @troy2914 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dayton967 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dayton967** [comment]
'ready_for_review'

**Comment by troy2914** [comment]
Hmm, not sure if the comment works with quotes

ready_for_review

**Comment by gregdek** [comment]
Thanks @dayton967. To the current maintainers, @lpenz, @tarka, @ivanbojer, @indrajitr, @bcoca, @dagwieers, @yaegashi, @L2G, @szinck, @troy2914 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by troy2914** [comment]
shipit

**Comment by abadger** [comment]
Took a quick look here.  Couple, almost administrative things I saw:

* There's several merge commits embedded here.  If you can rebase to get rid of the merge commits and just build on top of the current HEAD of the devel branch, that would be awesome.
* There's a recent change that makes the examples use yaml instead of key=value.  (Since the examples here are multiline, using yaml makes a lot of sense).  That should just be a matter of replacing "=" with ": " in the examples that you're adding and modifying at the top.

@bcoca other than those things, does this now look good to merge?

**Comment by gregdek** [comment]
Thanks again to @dayton967 for this PR, and thanks @lpenz, @tarka, @ivanbojer, @indrajitr, @bcoca, @dagwieers, @yaegashi, @L2G, @szinck, @troy2914 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dayton967 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bcoca** [comment]
commit history is still a mess

**Comment by troy2914** [comment]
It might be helpful to provide @dayton967 with the git commands necessary to cleanup the history.
Ex, when first telling him to pull the current devel
`git pull --rebase`
would have left it mostly clean
followed up with a 
`git rebase -i $HASH`
to `fixup` all his intermediate commits 
and make a `reword` to cleanup the final message to reflect what he was adding.

But we are beyond that point now.  So something like:
git checkout -b pull_708
git checkout devel
git rebase -i some_hash_before_he_started_doing_stuff
   remove all his commits and the merge commits
git pull
git merge --squash pull_708

**Comment by troy2914** [comment]
please remove that space you added, and fix the problem:
line 174
```
++<<<<<<< HEAD
 +    to: 'John Smith <john.smith@example.com>'
 +    subject: 'Ansible-report'
++=======
+     to: John Smith <john.smith@example.com>
+     subject: Ansible-report
++>>>>>>> origin/devel
```
your branch has
    to: 'John Smith <john.smith@example.com>'
    subject: 'Ansible-report'

devel
has them unquoted

remove the quotes, and then `git rebase -i` to `fixup` all the intermediate commits, and `reword` the final commit.

**Comment by troy2914** [comment]
and discard `ca11118`  (ugly spacing)

**Comment by dayton967** [comment]
Hopefully everything is cleaned up, my git experience is way limited.

**Comment by dayton967** [comment]
I give up every time I fix it, a change breaks it.  And it's not worth continually pushing changes.

**Comment by abadger** [comment]
@dayton967 yeah, git can be painful....

I can fix this and merge it but can't figure out how to keep your commits if I do so.   If that's okay with you, I'll open a new PR with that.

**Comment by dagwieers** [comment]
@dayton967 I can understand your sentiment :-/
For me this is ready to be shipped, as I stated before !

**Comment by abadger** [comment]
I've pushed the cleaned up PR here: https://github.com/ansible/ansible/pull/19253  Had some questions that probably should be answered, though.  Please reply in the other PR.  If I don't respond, feel free to ping me on #ansible-devel (dag does that often so I think he can keep me informed of any answers to the questions :-)

**Comment by dayton967** [comment]
Do what you need

**Pull request closed without merging**
