### PR TITLE
re-add datadog_dowmtime module after completely resetting the fork

### PR DESCRIPTION
**Pull request by stefanweller**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

datadog_downtime
##### ANSIBLE VERSION

```
2.0.1.0
```

### CODE REVIEW

**Comment by stefanweller** [comment]
@gregdek Hi Greg, sorry but I don't get it.
What do I have to do to make this work?
https://travis-ci.org/ansible/ansible-modules-extras/builds/124215450

**Comment by gregdek** [comment]
OK, let's look at the errors:

> > > ERROR: DOCUMENTATION.notes: not a valid value

Looks like "notes" on line 32 isn't a valid field. You might just want to put this in the description.

> > > ERROR: No RETURN documentation provided

New guidelines say that you must document return codes in the RETURN section. See http://docs.ansible.com/ansible/developing_modules.html for more details.

> > > ERROR: requests import found, should use ansible.module_utils.urls instead

We prefer to do URL handling using ansible.module_utils.urls here, although it doesn't appear that this requirement is documented. We'll fix this on our end.

**Comment by gregdek** [comment]
Thanks @stefanweller for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanweller** [comment]
ready_for_review
works_for_me
passes_guidelines

**Comment by gregdek** [comment]
Thanks @stefanweller for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by skornehl** [comment]
Hi @stefanweller,
I would like to see an idempotency PR in the future :)

shipit

**Comment by gregdek** [comment]
Thanks @stefanweller for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@stefanweller A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@stefanweller Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@stefanweller A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanweller** [comment]
closed for PR #2381

**Pull request closed without merging**
