### PR TITLE
Bugfix influxdb/retention_policy: infinite retention is returned as 0

### PR DESCRIPTION
**Pull request by nmorsman**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

influxdb/retention_policy
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

A retention policy with infinite duration is created with duration `INF` but is displayed with duration `0`.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by nmorsman** [comment]
ping @kamsz

**Comment by kamsz** [comment]
@nmorsman Verified, this PR resolves the issue. If you could add required=True and remove the default value for database_name in line 128 I'd be grateful (otherwise it'll fail if you don't specify db name).

**Comment by nmorsman** [comment]
Done!

**Comment by kamsz** [comment]
shipit

**Comment by nmorsman** [comment]
This one is good to go, ping @gregdek @resmo @robynbergeron.

**Comment by resmo** [comment]
fix has been backported to 2.1, thanks!

**Pull request merged**
