### PR TITLE
Add check mode support to ec2_elb_facts

### LINKED ISSUE #3521: ec2_elb_facts should support check mode
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_elb_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
*N/A*

##### OS / ENVIRONMENT
*N/A*

##### SUMMARY
Since the `ec2_elb_facts` is strictly a read-only operation, it should support running with `--check`

##### STEPS TO REPRODUCE

```sh
ansible-playbook \
    -i hosts \
    -l my-elb-host \
    ec2_elb_facts_check.yml \
    -vv \
    --check
```

```yaml
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Collect ELB facts
      ec2_elb_facts:
        names: "my-elb"
        region: "us-east-1"
      register: elbfacts
      tags: always
```

##### EXPECTED RESULTS
It would be expected that `ec2_elb_facts` would still fetch the instance information. This being omitted, prevents the ability to enumerate ELB instance hosts, dynamically add them to the inventory, and then conduct `--check` mode against what would *actually* be getting done.

##### ACTUAL RESULTS

```
TASK [Collect ELB facts] ***********************************************
task path: /Projects/ec2_elb_facts_check.yml:6
skipping: [my-elb-host] => {
    "changed": false, 
    "skipped": true
}

MSG:

remote module (ec2_elb_facts) does not support check mode
```

### PR DESCRIPTION
**Pull request by tomislacker**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
ec2_elb_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Enables `ec2_elb_facts` to run in check mode. This then allows the ability to use the module to collect instance information, dynamically add those instances to the inventory, and do real checks with other tasks against the ELB instances.

Fixes #3521

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @tomislacker. To the current maintainers, @mjschultz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tomislacker** [comment]
@mjschultz would you possibly have time to review this change?

**Comment by mjschultz** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @tomislacker for this PR, and thanks @mjschultz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
