### PR TITLE
Adding request timeout to datadog_monitor

### PR DESCRIPTION
**Pull request by tkensiski**
##### ISSUE TYPE
- Feature Pull Request
- Bugfix Pull Request
##### COMPONENT NAME

monitoring/datadog_monitor
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file =
  configured module search path = Default w/o overrides
```

NOTE: running devel right now
##### SUMMARY

So due to the sheer amount of monitors that we have setup we were consistently timing out against datadog's api. This allows you to set a timeout to a larger value. While I don't like where this is stored for me it works since I am doing programatic execution and can inject this into my records and not have to store it in my yaml files.

However short of forking the datadogpy lib there is no easy way to override this value that I can think of other than this.

Before:

```
DEBUG [2016-09-01 13:15:14,294] Found monitor: VPN - clients connected - /20 network
INFO [2016-09-01 13:15:14,294] Finished loaded 1 monitor
DEBUG [2016-09-01 13:15:14,296] Host list generated: /var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/tmprqgJbV
INFO [2016-09-01 13:15:14,297] Adding monitor to task list: VPN - clients connected - /20 network
DEBUG [2016-09-01 13:15:14,298] Playbook generated: /var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/tmpjc7tW3

PLAY [Datadog Monitor Sync] ****************************************************

TASK [datadog_monitor] *********************************************************
fatal: [datadog]: FAILED! => {"changed": false, "failed": true, "module_stderr": "No handlers could be found for logger \"dd.datadogpy\"\nTraceback (most recent call last):\n  File \"/var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/ansible_u1OvPv/ansible_module_datadog_monitor.py\", line 318, in <module>\n    main()\n  File \"/var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/ansible_u1OvPv/ansible_module_datadog_monitor.py\", line 191, in main\n    install_monitor(module)\n  File \"/var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/ansible_u1OvPv/ansible_module_datadog_monitor.py\", line 266, in install_monitor\n    monitor = _get_monitor(module)\n  File \"/var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/ansible_u1OvPv/ansible_module_datadog_monitor.py\", line 205, in _get_monitor\n    if monitor['name'] == module.params['name']:\nTypeError: string indices must be integers, not str\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/tmpjc7tW3.retry

PLAY RECAP *********************************************************************
datadog                    : ok=0    changed=0    unreachable=0    failed=1
```

After:

```
DEBUG [2016-09-01 13:15:42,036] Found monitor: VPN - clients connected - /20 network
INFO [2016-09-01 13:15:42,036] Finished loaded 1 monitor
DEBUG [2016-09-01 13:15:42,038] Host list generated: /var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/tmpO_TUoO
INFO [2016-09-01 13:15:42,041] Adding monitor to task list: VPN - clients connected - /20 network
DEBUG [2016-09-01 13:15:42,041] Playbook generated: /var/folders/g3/j7pmb2xs2cs8_0jdg29sf141wf4ytj/T/tmpy3n0Xp

PLAY [Datadog Monitor Sync] ****************************************************

TASK [datadog_monitor] *********************************************************
changed: [datadog]

PLAY RECAP *********************************************************************
datadog                    : ok=1    changed=1    unreachable=0    failed=0
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @tkensiski. To the current maintainers, @skornehl please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Jackyjjc** [comment]
When can we merge this PR?

**Comment by skornehl** [comment]
Whoa sorry @Jackyjjc I totally forgot about this one. I believe setting a timeout here is absolutely Ok, so shipit

Thanks for the PR!

**Comment by Jackyjjc** [comment]
Thanks a lot :) We uses this module to configure our datadog monitors. However, since we are a heavy datadog user, most of our requests to datadog take more than the default timeout duration to complete which renders this module completely unusable without this patch. We have been carrying this patch around in our code base which is not ideal.

**Comment by gregdek** [comment]
Thanks @tkensiski for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@tkensiski A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tkensiski** [comment]
Should be fixed now!

**Pull request closed without merging**
