### PR TITLE
Make os_user_role respect domain when querying for projects

### PR DESCRIPTION
**Pull request by alvaroaleman**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

os_user_role
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When a domain is submitted, the module should respect that domain when querying for projects.

CC @Shrews

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alvaroaleman for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alvaroaleman** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @alvaroaleman. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Shrews** [comment]
lgtm

**Comment by rcarrillocruz** [comment]
shipit

**Comment by Shrews** [comment]
Cherry-picked to stable-2.1

**Pull request merged**
