### PR TITLE
Adding missing required field in doc example

### PR DESCRIPTION
**Pull request by marcus-ahle**
##### ISSUE TYPE

- Docs Pull Request
##### COMPONENT NAME

 pagerduty
##### ANSIBLE VERSION

```
ansible 1.9.2
  configured module search path = None
```
##### SUMMARY

requester_id is required when token is used. It is not shown in the example in the documentation.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @marcus-ahle for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by marcus-ahle** [comment]
ready_for_review

**Comment by marcus-ahle** [comment]
```
2016-10-06 14:11:30 + ANSIBLE_DEPRECATION_WARNINGS=false
2016-10-06 14:11:30 + ansible-validate-modules --exclude '/utilities/|/shippable(/|$)' .
2016-10-06 14:11:38 ============================================================================
2016-10-06 14:11:38 ./network/asa/asa_config.py
2016-10-06 14:11:38 ============================================================================
2016-10-06 14:11:38 ERROR: version_added for new option (passwords) should be 2.3. Currently 0.0
2016-10-06 14:11:38 ERROR: version_added for new option (defaults) should be 2.3. Currently 0.0
2016-10-06 14:11:38 
```

I'm unsure why version is getting set as 0.0

**Comment by thaumos** [comment]
shipit

**Comment by thaumos** [comment]
@marcus-ahle, actually... could  you do a rebase to get the job to fire off?  If we can do this before tomorrow; that'd be great!

**Pull request closed without merging**
