### PR TITLE
Create ansible_tower_organization module

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
ansible_tower_organization

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 8552ad6bf1) last updated 2016/11/09 21:44:37 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 2584fca0ae) last updated 2016/11/09 21:44:59 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD a1dcbf9ce5) last updated 2016/11/09 21:45:17 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Add ansible_tower_organization module

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Fale for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by krzysztof-magosa** [comment]
Instead of using `requests` library you must use ansible utils for that:

```
2016-11-10 00:39:01 ERROR: requests import found, should use ansible.module_utils.urls instead
```

**Comment by Fale** [comment]
@krzysztof-magosa thanks. I did found the problem, but I used a little bit of time to familiarize with the scarse documentation of ansible.module_utils.urls ;)

ready_for_review

**Comment by gregdek** [comment]
Thanks @Fale for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by krzysztof-magosa** [comment]
Most of modules use `login_` prefix for parameters related to authorisation of module in target system. IMHO it would be good to follow that style also here.

e.g.:
- http://docs.ansible.com/ansible/rabbitmq_queue_module.html
- http://docs.ansible.com/ansible/mysql_user_module.html

**Comment by wenottingham** [comment]
Hi, dropping in as the Ansible Tower product person - 

I don't want to discourage contribution, but any Tower modules that end up in Ansible, we'd be forced to essentially take them over by business realities with our customers.

We're actually working on a full set of these for release in the Ansible 2.3 timeframe. More info soon.

**Comment by wenottingham** [comment]
Following up on an offline conversation - elaborating on the 'take them over" phrasing. We're absolutely happy to work with people on modules for Tower.

However, especially In the context of the 2.3 module rework (https://github.com/ansible/proposals/issues/30) - an 'unsupported by Ansible' Tower module in isn't a tenable situation.
We'd be required to make it at least 'core_curated', if not 'core' maintained. The goal is to make sure that anyone submitting modules for Tower is aware of that _going in_, I don't want to have modules come in and then surprise people later.

**Comment by Fale** [comment]
@wenottingham thanks for the followup message :). I would be glad to have the Ansible core team as co-maintainer or eventually to hand over completely the maintainership if this will make easier to merge incoming pull-requests and improvements

**Comment by Fale** [comment]
Thanks @krzysztof-magosa I've integrated your suggestion :)

**Pull request closed without merging**
