### PR TITLE
Update bigpanda.py

### PR DESCRIPTION
**Pull request by hyperized**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
monitoring/bigpada.py

##### ANSIBLE VERSION
n/a

##### SUMMARY
Update Examples to use YAML syntax

### CODE REVIEW

**Comment by gundalow** [comment]
@hyperized Thanks for this. I'm not sure if we should be recommending `local_action` or `delegate_to:` in examples. I'll find out and let you know

**Comment by mscherer** [comment]
I suspect we prefer delegate_to, as local action do not appear with ansible-doc so this might confuse people more

**Comment by bcoca** [comment]
`local_action` and `delegate_to: localhost` are interchangeable, there is not an official preference.

@mscherer  both do show in ansible-doc if they exist in the examples.

**Comment by gregdek** [comment]
Thanks @hyperized for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
needs_revision - merge conflict

**Comment by mscherer** [comment]
What I mean is that I got questions from people in the office about why ansible-doc local_action didn't return anything. So I think "delegate_to: localhost" is likely easier to understand by users, since it is not a exception to the usual rule regarding modules and doc.

**Comment by hyperized** [comment]
Seems to have been solved. Closing.

**Pull request closed without merging**
