### PR TITLE
add 'behavior' attribute to consul_session

### PR DESCRIPTION
**Pull request by irlevesque**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

consul_session
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Implements https://github.com/ansible/ansible-modules-extras/issues/2154

python-consul provides the [behavior parameter](http://python-consul.readthedocs.io/en/latest/#consul.base.Consul.Session)  when creating a session:

`behavior` can be set to either ‘release’ or ‘delete’. This controls the behavior when a session is invalidated. By default, this is ‘release’, causing any locks that are held to be released. Changing this to ‘delete’ causes any locks that are held to be deleted. ‘delete’ is useful for creating ephemeral key/value entries

``` yaml
    - name: Register new session
      consul_session:
        name: "{{ consul_session_name }}"
        behavior: delete
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @irlevesque for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by irlevesque** [comment]
@gregdek I added the `version_added` parameter to satisfy the Travis check. Can this be reviewed again?

**Comment by gregdek** [comment]
@irlevesque A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by irlevesque** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @irlevesque. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
looks good, thanks for adding this. shipit!

**Comment by gregdek** [comment]
Thanks again to @irlevesque for this PR, and thanks @sgargan for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
