### PR TITLE
Feature/profitbricks modules

### PR DESCRIPTION
**Pull request by baldwinSPC**
This is a new cloud provider module for ProfitBricks. It allows users to manage instances, datacenters, nics, snapshots, and volumes.

### CODE REVIEW

**Comment by gregdek** [comment]
Lots of modules! Could take a while to review. Thanks for the submission! Boilerplate follows.

---

Thanks for submitting this new module.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, and receives no -1 votes, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by bcoca** [comment]
one thing, instead of putting them all in a single PR, it will be easier to make several of them as we can then review them one by one and spend much less time until we approve the first.

**Comment by gregdek** [comment]
I second @bcoca here. Up to you @baldwinSPC but I would recommend closing this PR and making separate new PRs for each module.

**Comment by baldwinSPC** [comment]
@gregdek Sounds good. I will close this PR and break it into multiple PRs per @bcoca 's recommendation.

**Pull request closed without merging**
