### PR TITLE
Fix zfs properties handling

### PR DESCRIPTION
**Pull request by johanwiren**
Removes all "options" for zfs properties and uses the check_invalid_args=False to skip verification of "bad" options.

All extra options are passed on to the zfs command that sets properties just as before.

The reason for this big change is that the zfs properties and their possible values are difficult to maintain since they differ on OS'es and zpool versions. If we wanted the options correct we would have to make the module much more complex to try to figure out valid options for different scenarios.

In essence, not much changed in expected behaviour, except fixing some bugs.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @johanwiren. Since you are a maintainer of this module, we are marking this PR for inclusion.

**Comment by bcoca** [comment]
Knowing the mess that cross ZFS property handling is I understand the change, but this does seem to break backwards compatibility.  Can we keep the old options and just add a 'extra_options' that handles as this new code does?

**Comment by johanwiren** [comment]
In what way does it break backwards compatibility?

**Comment by bcoca** [comment]
you are removing the existing options?

**Comment by johanwiren** [comment]
They are just removed from the argument specification and documentation.

Any option passed to the module that is not part of the argument specification is assumed to be a zfs property and handled accordingly. 

This behaviour is backwards compatible and no playbooks should break because of this.

**Comment by bcoca** [comment]
ah, we just loose the verification and documentation .... or 'defer' the verification to execution

**Comment by gregdek** [comment]
Thanks @johanwiren. Since you are a maintainer of this module, we are marking this PR for inclusion.

**Comment by abadger** [comment]
Merged to devel.  Thanks!

**Pull request merged**
