### PR TITLE
New module: zanata

### PR DESCRIPTION
**Pull request by sdp5**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

web_infrastructure/zanata.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel cf4d436e07) last updated 2016/09/23 19:23:39 (GMT +550)
  lib/ansible/modules/core: (detached HEAD 0f505378c3) last updated 2016/09/23 19:26:55 (GMT +550)
  lib/ansible/modules/extras: (detached HEAD 1ade801f65) last updated 2016/09/23 19:31:47 (GMT +550)
  config file = /home/suanand/Projects/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This module enables interactions with [zanata](http://zanata.org) to manage translation projects.  

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @sundeep-co-in for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@sundeep-co-in please don't add your own module to the new modules agenda. That meeting is only for final review of new modules that have already received some degree of community review.

**Comment by sdp5** [comment]
sure

**Comment by gregdek** [comment]
Thanks @sundeep-co-in for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sdp5** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @sundeep-co-in for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
