### PR TITLE
adding Cumulus Linux Quagga related modules

### PR DESCRIPTION
**Pull request by LeslieCarr**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @LeslieCarr -- thanks for submitting this new module.

I noticed that the author line has an email address but not a github ID associated with it -- 
can you update that, so it adheres to the guidelines? (http://docs.ansible.com/developing_modules.html#module-checklist)

When you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.

Thanks!

**Comment by LeslieCarr** [comment]
ready_for_review

**Comment by gregdek** [comment]
@LeslieCarr do these modules all need to be in the same PR for some reason? Are they dependent on one another, or...?  Ordinarily we ask that modules be separated to one module per PR -- just want to know if there's a reason not to do that here.

**Comment by LeslieCarr** [comment]
for this specific one they do not, but they are all closely related to each other.  Would you prefer I closed and submitted one request per?

**Comment by robynbergeron** [comment]
Hi @LeslieCarr -- Adding new process. We will be evaluating all new module PRs according to this process, effective immediately. 

(Also, @gregdek is coming with an answer to your question :D)

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by gregdek** [comment]
@LeslieCarr we can leave it like this; it just may affect people's ability to review it -- i.e. if they have to review them all at once it may take longer. Up to you.

**Comment by privateip** [comment]
works_for_me

**Comment by privateip** [comment]
needs_revision
- please add version_added: "2.1" to the DOCUMENTATION string
- please add RETURN (see http://docs.ansible.com/ansible/developing_modules.html#documenting-your-module)

**Comment by gregdek** [comment]
Thanks @LeslieCarr for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by privateip** [comment]
Closed per discussions with author

**Pull request closed without merging**
