### PR TITLE
win_firewall_rule: strictmode fixes

### PR DESCRIPTION
**Pull request by ilpianista**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

win_firewall_rule
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Enabled StrictMode (moved from Get-Attr to Get-AnsibleParam).

I set the default values to `netsh advfirewall firewall add rule` defaults.

### CODE REVIEW

**Comment by ilpianista** [comment]
This patch also contains #2431 changes to fix #2424

**Comment by gregdek** [comment]
Thanks @ilpianista. To the current maintainers, @TimothyVandenbrande please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by t-v** [comment]
tested and approved, thank you @ilpianista for the update.

shipit

**Comment by gregdek** [comment]
Thanks again to @ilpianista for this PR, and thanks @TimothyVandenbrande for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Shipping it.

**Comment by dreamcat4** [comment]
Hi @ilpianista I try your latest but its still broken as before despite such changes / fixing. Try something like this for example, and see what happens:

``` yaml
- name: Kodi - Allow on Private Network - TCP
  win_firewall_rule:
    name: Kodi
    program: "C:\\program files (x86)\\kodi\\kodi.exe"
    profile: Private
    protocol: "{{ item }}"
    direction: in
    action: allow
    enable: yes
    state: present
    force: yes
  with_items:
    - tcp
    - udp
```

**Comment by dreamcat4** [comment]
The result for me was: `win_firewall_rule: the property 'Program' cannot be found on this object`

**Comment by ilpianista** [comment]
@dreamcat4 oh I'm sorry, I'll file a new issue with a patch ASAP.

**Comment by dreamcat4** [comment]
Thanks man! It would really be appreciated, whenever you get the time to come back to it.

**Comment by ilpianista** [comment]
@dreamcat4 please try https://github.com/ansible/ansible-modules-extras/pull/2654

**Comment by dreamcat4** [comment]
Yeah it seems a general error affecting many of the properties. I can confirm that it now it passes the specific example I gave earlier on. Many thanks for this.

Before fix:

``` json
TASK [4_pkgs : Kodi - Allow on Private Network - TCP] **************************
task path: /home/id/ansible/windows/roles/4_pkgs/tasks/kodi.yml:522
failed: [brix-3205] (item=tcp) => {"changed": false, "error": "The property 'Program' cannot be found on this object. Verify that the property exists.", "failed": true, "item": "tcp", "msg": ["The rule 'Kodi' exists."]}
```

after fix:

``` json
TASK [4_pkgs : Kodi - Allow on Private Network - TCP] **************************
task path: /home/id/ansible/windows/roles/4_pkgs/tasks/kodi.yml:3
changed: [brix-3205] => (item=tcp) => {"changed": true, "difference": ["null"], "failed": false, "fwsettings": {"Action": "allow", "Direction": "in", "Enabled": "yes", "LocalIP": "any", "LocalPort": "any", "Profiles": "Private", "Program": "C:\\program files (x86)\\kodi\\kodi.exe", "Protocol": "tcp", "RemoteIP": "any", "RemotePort": "null", "Rule Name": "Kodi"}, "item": "tcp", "msg": ["The rule 'Kodi' exists.", "The rule exists but has different values", "Removed the rule", "Created firewall rule Kodi"]}
changed: [brix-3205] => (item=udp) => {"changed": true, "difference": [], "failed": false, "fwsettings": {"Action": "allow", "Direction": "in", "Enabled": "yes", "LocalIP": "any", "LocalPort": "any", "Profiles": "Private", "Program": "C:\\program files (x86)\\kodi\\kodi.exe", "Protocol": "udp", "RemoteIP": "any", "RemotePort": "null", "Rule Name": "Kodi"}, "item": "udp", "msg": ["No rule could be found", "Created firewall rule Kodi"]}
```

**Pull request merged**
