### PR TITLE
added hall.com notification module

### PR DESCRIPTION
**Pull request by bkimble**

### CODE REVIEW

**Comment by ddbenson** [comment]
Any updates on this?

**Comment by theshapguy** [comment]
+1

**Comment by bcoca** [comment]
we have not had a chance to review yet, but we will get to it

**Comment by gregdek** [comment]
@bkimble, thanks for submitting this module to Ansible Extras. Apologies that it’s taken a while to get your module reviewed.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Pull request merged**
