### PR TITLE
New module for creating gitlab groups

### PR DESCRIPTION
**Pull request by dj-wasabi**
Hi,

New module for creating and deleting groups in Gitlab.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this new module.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, and receives no -1 votes, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by resmo** [comment]
LGTM +1

**Comment by gregdek** [comment]
@resmo since we changed policy, could you clarify that you tested and checked for guidelines? If so, we'll take your +1 as both of those and we'll get it in. Thanks!

**Comment by resmo** [comment]
Thanks for the patience, started to test it for 2.1

**Comment by gregdek** [comment]
Thanks @dj-wasabi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@dj-wasabi A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dj-wasabi** [comment]
Hi,

The error is:

```
pip 6.0.7 from /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages (python 2.7)
Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.
0.20s$ python2.4 -m compileall -fq -x 'cloud/|monitoring/zabbix.*\.py|/dnf\.py|/layman\.py|/maven_artifact\.py|clustering/consul.*\.py|notification/pushbullet\.py' .
Compiling ./clustering/znode.py ...
  File "./clustering/znode.py", line 123
    command_type = 'op' if 'op' in module.params and module.params['op'] is not None else 'state'
                         ^
SyntaxError: invalid syntax
```

Don't see why this has to do with my PR?

ready_for_review

**Comment by sivel** [comment]
The problem seems to be that this PR was submitted from an old state of devel and needs to be rebased to the current state of devel.

**Comment by dj-wasabi** [comment]
Take 2: ready_for_review

**Comment by gregdek** [comment]
Thanks @dj-wasabi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
shipit

**Comment by resmo** [comment]
@dj-wasabi could you please rebase and squash the commits?

**Pull request merged**
