### PR TITLE
Moved the atomic modules to cloud/atomic.

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

system/atomic*
##### ANSIBLE VERSION

```
devel
```
##### SUMMARY

as noted by @bcoca in today's new module meeting, these should be categorized like docker and lxd.  This PR just moves the modules into that category.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @abadger for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tima** [comment]
shipit

;)

**Comment by gregdek** [comment]
Thanks again to @abadger for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansb** [comment]
:ship:ed

**Pull request merged**
