### PR TITLE
Add module for retrieving SmartOS image facts

### PR DESCRIPTION
**Pull request by xen0l**
This module implements support for retrieving facts about SmartOS images.

### CODE REVIEW

**Comment by lenw** [comment]
+1

**Comment by xen0l** [comment]
Anyone else?

**Comment by mscherer** [comment]
+1

**Comment by mariuspana** [comment]
+1

**Comment by gregdek** [comment]
Thanks again to @xen0l for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
