### PR TITLE
mysql_replication: feature - Support Multi-Source Replication

### PR DESCRIPTION
**Pull request by paihu**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

[module: database/mysql/mysql_replication.py]
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY
#2180

MySQL support Multi-Source Replication ( https://dev.mysql.com/doc/refman/5.7/en/replication-multi-source.html )

Add option named channel
MySQL 5.7 like channel base Multi-Source Replication

exmaple

```
# Change master to master server 192.168.1.1 for channel "master-1"
- mysql_replication: mode=changemaster master_host=192.168.1.1 channel=master-1

#stop slave for channel "master-1"
- mysql_replication: mode=stopslave channel=master-1

#start slave for channel "master-1"
- mysql_replication: mode=startslave channel=master-1

#reset slave for channel "master-1"
- mysql_replication: mode=resetslave channel=master-1

#get slave status for channel "master-1"
- mysql_replication: mode=getslave channel=master-1

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @paihu. To the current maintainers, @banyek please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by banyek** [comment]
I have no experiences in multi source replication, I can't test it.

**Comment by paihu** [comment]
mysql channel base multi source replication uses mysqld option follow

```
--master-info-repository=TABLE --relay-log-info-repository=TABLE
```

or my.conf

```
[mysqld]
master-info-repository=TABLE
relay-log-info-repository=TABLE
```

mysql channel base multi source replication syntax
add last "for channel 'channel' "
example

```
> show slave for channel 'channel';
> stop slave for channel 'channel';
> start slave for channel 'channel';
> reset slave for channel 'channel';
> change master to master_host="host", ......master_log_pos=9999 for channel 'channel';
```

**Comment by gregdek** [comment]
Thanks @paihu for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@paihu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@paihu Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@paihu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@paihu Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@paihu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
