### PR TITLE
WIP nuage networks network virtualization  

### PR DESCRIPTION
**Pull request by christx2**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```
##### SUMMARY

```
<!--- Paste verbatim command output here, e.g. before and after your change -->
```

### CODE REVIEW

**Comment by christx2** [comment]
Placeholder for Network Virtualization - creation of netvirt

**Comment by gregdek** [comment]
Thanks @christx2 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by christx2** [comment]
ready for review created **init**.py placeholder, this is the repo directory we want to publish under

**Comment by privateip** [comment]
the folder structure seems fine but there is nothing to review yet.  once you have added your module code we can review for inclusion into extras

**Comment by gundalow** [comment]
As agreed in Networking meeting 2016-05-25 the first module should add the **init**.py and README.md

One PR per module to make reviewing easier please.

So I believe that means this this PR can be killed.

**Comment by gregdek** [comment]
@christx2 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by christx2** [comment]
Please keep open, impending GPLv3 license coming for me to get this completed. No review yet however required.

**Comment by gregdek** [comment]
@christx2 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by christx2** [comment]
Note, work in progress on documentation. If you want to close it and re-open it when completed, so less hassle in ready_for_review state, that is fine.

**Comment by gundalow** [comment]
@christx2 I believe if you edit the the title for this PR in github to start "WIP" (work in progress) the bot will ignore it, also that should make it clearer to reviews that their isn't any point looking at this PR yet.

Otherwise feel free to ignore Ansibull-bot, or just close and reopen it later.

**Comment by christx2** [comment]
done, moved to WIP

**Comment by gregdek** [comment]
This PR is a work-in-progress. @christx2, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by gundalow** [comment]
Closing as nothing has been done here for months

**Pull request closed without merging**
