### PR TITLE
Conditional main - packaging

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
packaging/*

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Use conditional main as for the 16th point of the module checklist at http://docs.ansible.com/ansible/dev_guide/developing_modules.html#module-checklist that reads:

Call your main() from a conditional so that it would be possible to import them into unittests in the future example:

    if __name__ == '__main__':
        main()

@gundalow

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Fale. To the current maintainers, @wltjr, @matze, @robinro, @mavit, @brian-brazil, @eest, @berenddeboer, @shane-walker, @dermute, @gentledevil, @brontitall, @KimNorgaard, @skinp, @melodous, @jcftang, @pmakowski, @franckcuny please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
LGTM, shipit

**Comment by pmakowski** [comment]
ok , shipit

**Comment by Fale** [comment]
@pmakowski this repo is not used any more, the ansible/ansible one is the one to use (and this patch has already been merged there)

**Pull request merged**
