### PR TITLE
ecs_service_facts fixes

### LINKED ISSUE #1483: Return values in ecs_service.py and ecs_service_facts.py are not valid
When I merged the ecs_service and ecs_service_facts modules we started seeing errors in travis: https://travis-ci.org/ansible/ansible-modules-extras/builds/101685996  Tracked it down to the RETURN values in the ecs_service and ecs_service_facts modules being invalid and thus causing tracebacks when reading the docs from those modules.

RETURN follows a definite structure just like the parameters do.  Here's an example: https://github.com/ansible/ansible-modules-core/blob/devel/files/copy.py

Not knowing what the code in the module does, I can't fix the documentation so I'm filing a bug in hopes you can fix it instead.  Thanks!

\cc @Java1Guy

### PR DESCRIPTION
**Pull request by kaczynskid**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

cloud/amazon/ecs_service_facts
##### Ansible Version:

```
ansible 2.1.0 (devel 2db3f290ba) last updated 2016/02/24 10:06:09 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 7162623e86) last updated 2016/02/24 10:09:54 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ecs_servic) last updated 2016/02/24 12:04:25 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### Summary:

Module will now return previously cut out deployments and events lists with datetime fields converted to strings as a workaround to #1348.

Improved documentation to fix #1483.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @kaczynskid. @Java1Guy please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by Java1Guy** [comment]
Good job - thx for doing this.
shipit

**Comment by kaczynskid** [comment]
@Java1Guy thx and you're welcome - I just needed it for my deployment :)

**Comment by gregdek** [comment]
Thanks again to @kaczynskid for this PR, and thanks @Java1Guy for reviewing. Marking for inclusion.

**Pull request merged**
