### PR TITLE
New OpenStack module os_port_facts

### PR DESCRIPTION
**Pull request by Shrews**
##### ISSUE TYPE
- New Module Pull Request
- Docs Pull Request
##### COMPONENT NAME

cloud/openstack/os_port_facts.py
##### ANSIBLE VERSION

2.1
##### SUMMARY

Adds a new OpenStack module for getting port facts.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @Shrews. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rcarrillocruz** [comment]
shipit

**Comment by rcarrillocruz** [comment]
lgtm, thanks @Shrews :+1:

**Comment by gregdek** [comment]
Thanks again to @Shrews for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@Shrews don't forget to add this new module to the CHANGELOG

**Comment by Shrews** [comment]
@resmo Will do. Thx.

**Pull request merged**
