### PR TITLE
Fix #1101: win_webpicmd strict mode fixes

### LINKED ISSUE #1101: win_webpicmd fails with strict mode errors
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/13 06:57:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD d659c79db7) last updated 2015/10/13 06:57:49 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/13 06:58:00 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = /vagrant/ansible/library
```
##### Ansible Configuration:

I haven't changed anything that affects this module.
##### Environment:

Running from Ubuntu 14, managing Windows Server 2012 R2.
##### Summary:

win_iis_webpicmd fails with property error when doing any operation
##### Steps To Reproduce:
- Use webpicmd to install any package
##### Expected Results:

It successfully installs the package.
##### Actual Results:

It does not install the package and fails with an error that 'length' does not exist on the object.  Pull request fixing this incoming.

### PR DESCRIPTION
**Pull request by bgeihsgt**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @bgeihsgt -- thanks for submitting this PR, which fixes #1101 :)

@petemounce -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Also pinging other windows folks for their feedback as well. @trondhindenes @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by jhawkesworth** [comment]
not tested but looks good to me.

**Comment by petemounce** [comment]
passes_guidelines. Will test in the next couple days. Thanks for the contribution!

**Comment by jamemackson** [comment]
:+1: to merge this from me, I manually updated my file (clone of devel from yesterday) with this PR version and it fixed this error for me.

**Comment by petemounce** [comment]
shipit - thanks!

**Comment by jamemackson** [comment]
:+1: thanks for quick response!

**Pull request merged**
