### PR TITLE
New module: rds_snapshot_facts

### PR DESCRIPTION
**Pull request by manicminer**
##### Issue Type:
- New Module Pull Request
##### Plugin Name:

rds_snapshot_facts
##### Ansible Version:

```
ansible 2.1.0
  config file = /path/to/my/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

The module allows searching for RDS snapshots by various criteria, to obtain the snapshot ID/name. This is useful when launching a new RDS instance from a snapshot using the `rds` module.

This PR replaces https://github.com/ansible/ansible-modules-extras/pull/1281
##### Example output:

```
TASK [Find latest snapshot] ****************************************************
ok: [localhost] => {"changed": false, "results": [{"allocated_storage": 400, "availability_zone": "us-west-2b", "engine_version": "9.3.6", "id": "rds:my-instance-2016-02-21-09-25", "instance_create_time": "2015-11-17T13:01:31.951Z", "instance_id": "my-instance", "iops": 4000, "master_username": "deploy", "option_group_name": "default:postgres-9-3", "port": 5432, "snapshot_create_time": "2016-02-21T09:25:52.339Z", "snapshot_type": "automated", "source_region": null, "status": "available", "vpc_id": "vpc-5fa623e8"}]}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "snapshot_details": {
        "changed": false,
        "results": [
            {
                "allocated_storage": 400,
                "availability_zone": "us-west-2b",
                "engine_version": "9.3.6",
                "id": "rds:my-instance-2016-02-21-09-25",
                "instance_create_time": "2015-11-17T13:01:31.951Z",
                "instance_id": "my-instance",
                "iops": 4000,
                "master_username": "deploy",
                "option_group_name": "default:postgres-9-3",
                "port": 5432,
                "snapshot_create_time": "2016-02-21T09:25:52.339Z",
                "snapshot_type": "automated",
                "source_region": null,
                "status": "available",
                "vpc_id": "vpc-5fa623e8"
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @tombamford for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by manicminer** [comment]
Pinging @ansible/aws for eyeballs :-)

**Comment by gregdek** [comment]
Thanks @tombamford for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
