### PR TITLE
ec2_eni_facts module: Get EIP association information for ENI if EIP is associated

### PR DESCRIPTION
**Pull request by stefanhorning**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_eni_facts.py
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allows retrieving the ElasticIP associated with the ENI. The AWS API returns that as part of the `ec2 describe-eni` command. Boto has a less supportive way of including this information, but I think it's still handy to return that information as it allows obtaining the public IP of a network interface.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @stefanhorning. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanhorning** [comment]
Any comments on this?

**Comment by wimnat** [comment]
shipit

**Comment by wimnat** [comment]
@stefanhorning i've also added this via boto3 support here - https://github.com/ansible/ansible-modules-extras/pull/2425

**Comment by gregdek** [comment]
Thanks again to @stefanhorning for this PR, and thanks @wimnat for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Merged into devel.

**Pull request merged**
