### PR TITLE
Ignore .ropeproject

### PR DESCRIPTION
**Pull request by ogenstad**
##### ISSUE TYPE
- Development Pull Request
##### SUMMARY

.ropeproject files should be ignored

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
@bcoca @abadger ...ropeproject? Any idea how to treat this PR?

**Comment by gregdek** [comment]
Putting into core_review because ¯_(ツ)_/¯

**Comment by ogenstad** [comment]
So the .ropeproject files are created by my vi setup, it's related to editing Python files with vi/vim. I think it's this one https://github.com/klen/python-mode.

Mostly I use Atom, but I did some edits to the ASA modules using vi and the .ropeproject folder kept appearing.

**Pull request closed without merging**
