### PR TITLE
Added module win_package

### PR DESCRIPTION
**Pull request by trondhindenes**
win_package is an "advanced" version of the win_msi module, based on the same codebase as the "package" DSC resource. It can perform all kinds of installs (not just msi), auto-download from url or unc path, etc. See the py file for options. This was PRed just before the ansible repo was broken into submodules and was therefore auto-closed by Michael D.

### CODE REVIEW

**Comment by trondhindenes** [comment]
btw, I have no idea why the CI build fails :-(

**Comment by gregdek** [comment]
I think Travis is having issues today... other PRs are failing for completely innocuous reasons...

...oh, or not. Travis is ok, failed in the other case because ternary expressions aren't allowed in Python 2.4. Lemme look.

**Comment by gregdek** [comment]
Closed and reopened to kick Travis. Problem was with another module this morning.

**Comment by gregdek** [comment]
OK, passes now. It gets an automatic +1 from you; get one of the other folks from the Windows crew to review, and if it passes, we'll be happy to merge.

**Comment by trondhindenes** [comment]
ping @cchurch  - did you do any work on integration tests for this? I just submitted the PR as is, but would be great to get some tests on it aswell.

**Comment by gregdek** [comment]
I think @cchurch is traveling right now, fwiw, so it may take him some time to respond.

**Comment by jhawkesworth** [comment]
Would it be possible to rename 'ensure' to 'state' to make it more consistent with other modules?

**Comment by jhawkesworth** [comment]
Or perhaps have it so that state is an alias for ensure.  Some of the other windows modules do this - I think win_stat lets you use src or path to mean the same thing.

**Comment by trondhindenes** [comment]
agreed. I'll ad that as the main option, and ensure as an alias.

**Comment by trondhindenes** [comment]
Darnit, screwed up my rebase. Closing this and re-opening.

**Pull request closed without merging**
