### PR TITLE
Win say

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

win_say
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel a9d5bf717c) last updated 2016/08/28 10:50:36 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 6eab2b3d40) last updated 2016/08/28 10:52:27 (GMT +100)
  lib/ansible/modules/extras: (win_say 6867267122) last updated 2016/09/06 17:30:37 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

Adds win_say module which uses .net features to convert text to speech and play sounds on suitable hardware

Doesn't fix anything, but hopefully will make playbook runs noisier.

```
before, not applicable, examples to follow.

```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
A couple of examples

```
ansible win10machines -m win_say -a "msg='Hello, Ansible World' start_sound_path='C:\\windows\\media\\ding.wav' speech_speed=2"

WIN10TEST | SUCCESS => {
    "changed": false, 
    "message_text": "Hello, Ansible World", 
    "voice": "Microsoft Hazel Desktop"
}
```

playbook example

```
$ cat speech_demo.yml
---
- hosts: 10
  gather_facts: no
  tasks:
  - name: announce upgrade
    win_say:
       start_sound_path: 'C:\Windows\Media\Windows Balloon.wav'
       msg: Warning, upgrade in progress
       end_sound_path: 'C:\Windows\Media\chimes.wav'
       speech_speed: 3
# upgrade steps here
  - name: announce upgrade complete
    win_say:
       start_sound_path: 'C:\Windows\Media\Windows Balloon.wav'
       msg: Upgrade completed.
       end_sound_path: 'C:\Windows\Media\chimes.wav'
       speech_speed: 3

ansible-playbook win10hosts speech_demo.yml -v

Using /etc/ansible/ansible.cfg as config file

PLAY [10] **********************************************************************

TASK [announce upgrade] ********************************************************
ok: [TENSY] => {"changed": false, "message_text": "Warning, upgrade in progress", "voice": "Microsoft Hazel Desktop"}

TASK [announce upgrade complete] ***********************************************
ok: [TENSY] => {"changed": false, "message_text": "Upgrade completed.", "voice": "Microsoft Hazel Desktop"}

PLAY RECAP *********************************************************************
TENSY                      : ok=2    changed=0    unreachable=0    failed=0   

```

**Comment by gregdek** [comment]
Thanks @jhawkesworth for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nitzmahone** [comment]
Hahahaha, this is ripe for misuse by cruel admins. I love it.

**Comment by trondhindenes** [comment]
LGTM!!!

**Comment by gregdek** [comment]
Thanks again to @jhawkesworth for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible/core could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Yay! thanks for the merge.

**Comment by bcoca** [comment]
I expect your next presentation to hijack all windows machines present in audience and have them play "midsummer night's dream"

**Pull request merged**
