### PR TITLE
Set LANG env in zypper_repository as we parse stdout there

### PR DESCRIPTION
**Pull request by pief**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

packaging/os/zypper_repository
##### ANSIBLE VERSION

```
2.2.0 devel
```
##### SUMMARY

Fixes running the zypper_repository module in localized environments by initializing all locale-related env vars through module.run_command_environ_update.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @pief. To the current maintainers, @matze please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@pief Where exactly is localization an issue in this module?
The XML output should be localization agnostic (at least package names, state and version) and the same should be true for the zypper version parsing.

Depending on the issue it should also be fixed in the zypper module.

**Comment by pief** [comment]
zypper_repository, not zypper. zypper_repository doesn't return XML output, we parse its messages on stdout.

**Comment by pief** [comment]
Doh! Damnid, sorry, my error.

**Pull request closed without merging**
