### PR TITLE
Adds provision info to bigip facts

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

network/f5/bigip_facts.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

This patch adds provision information to the bigip_facts module
through a "provision" include.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
@mhite for review

**Comment by caphrim007** [comment]
@gundalow this too

**Comment by caphrim007** [comment]
shipit

**Comment by mhite** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @caphrim007 for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
probably a note in the docs that provision facts were added in 2.2 would be nice.

**Comment by caphrim007** [comment]
@resmo addressed your comment. please review

**Pull request merged**
