### PR TITLE
New BIG-IP module to manage users

### PR DESCRIPTION
**Pull request by mhite**
A new BIG-IP module supporting the management of users. Needs testers!

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mhite for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by mhite** [comment]
Thanks, Greg. I've put the word out on the mailing lists to solicit potential testers.

-M

**Comment by caphrim007** [comment]
Hey @mhite I know we mentioned this on list, but I was curious if you'd be open to combining efforts on this module. I took the code that you have here and folded it in to the one that is part of the f5networks repo (temporarily).

My code originally had only used the REST interface, so with your efforts here the module will support both the REST and SOAP interfaces; a big win for versions less than whenever REST went GA.

I'd like to open a PR and reference this one in it. I've also added your contributor details to the PR as you've done top-notch work on this and other modules. I can ping you here when I have run the tests on my end and am comfortable with the results.

Would you be cool with that? Lemme know. Thanks!

**Comment by mhite** [comment]
Hey @caphrim007 -- mind if I take a gander before you submit it? Let me know! Thanks.

**Comment by caphrim007** [comment]
@mhite sure thing. I will stage it in the f5networks repo and point you to it when I'm finished with the test playbook. We can clean it up there and submit it here for further discussion and changes. Thanks!

**Comment by mhite** [comment]
@caphrim007 -- Sounds good to me.

**Comment by caphrim007** [comment]
@mhite can you tell me which version of BIG-IP you tested code with so I can pull it down on my end and test? Thanks!

**Comment by mhite** [comment]
Lately I've been using 11.5.2 HF1 I think...

**Comment by caphrim007** [comment]
I've been silent on this for the last couple days because I've been waiting for a response from my colleagues as to whether specifying a partition via the REST interface to create a user is possible (since it's possible in the SOAP API).

Turns out it's not...so that has required my REST work to be adjusted to use your SOAP work @mhite if a user specifies a partition.

I'll update this PR again when I push changes to the f5networks repo so you can try on your end. Thanks for your patience!

**Comment by mhite** [comment]
Yes, there are some gaps in the REST API and I've just stuck to the SOAP API which is very mature for all the work I've done. 

I presume you create the user in /Common by default if the REST API is created?

**Comment by caphrim007** [comment]
Yeah the REST API appears to only support Common. Bug filed though, so I guess it's a step in the right direction as talk around the office is "rest rest rest rest..." yada yada yada. But if it's not at least at feature parity, then we've got a problem. ¯_(ツ)_/¯

**Comment by caphrim007** [comment]
@mhite here's a bigip_user module with your changes folded in and REST support added.

https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_user.py

I also added some other parameters making the module similar to the existing ansible user module. Here are some tests that use it if you want to use that as a base to test.

https://github.com/F5Networks/f5-ansible/blob/master/tests/bigip_user.yaml

If you and I want to clean it up or make any changes, I'd be happy to do that and can open a PR here that supersedes this one. Lemme know.

**Comment by mhite** [comment]
Hey, @caphrim007 -- I will hopefully kick the tires on this over the week! But I am excited, thanks for this.

I was also pleased to see you published:

https://devcentral.f5.com/articles/getting-started-with-ansible

Don't forget to plug the existing modules @srvg and I created that already ship with Ansible! ;) We've been big supporters of automating the F5's since pretty much the very beginning of Ansible.

**Comment by caphrim007** [comment]
Will do! I'm shooting to make a whole series that plugs the existing modules you all have worked on and expose more of the community to the tool. Thanks for all your hard work!

**Comment by caphrim007** [comment]
@mhite I've added checks for password changes so that the changed status is False if the new password is the same as the old password (using a re-login as we had discussed). Updated code is here if you want to have a go at it

https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_user.py

thanks!

**Comment by mhite** [comment]
Nice! Thanks for your work here.

I finally had a chance to test the bigip_user.py in the F5 repo. Comments follow:

In the module documentation, it mentions 'smart' as the default connection method:

```
  connection:
    description:
      - The connection used to interface with the BIG-IP
    required: false
    default: smart
    choices: ['rest', 'soap']
```

When I inspected the API factory object to better understand what 'smart' is, I noticed a few things.
- You are using a Python reserved keyword 'type' as a variable. You should probably change that.
- You won't ever catch the scenario where someone has selected 'rest' for connection and also is attempting to create a user in non-'Common' partition. Or am I misunderstand the logic here? I think in a previous comment you said REST only supports user creation in Common. My understanding is that you want to force SOAP in that case. I don't understand why you check partition_access there, etiher.  

I'm also a little confused by the need for a default partition_access value:

```
partition_access=dict(required=False, default='all:no-access'),
```

I think it's fine to have a default partition access for a create action, ie. user does not exist, but updates should not use this default. Ideally you don't want to know the user's list of partition access items just to perform a credential update for said user... and you certainly don't want to wipe out an existing list of permissions if someone happens to omit it in a playbook call. Do you agree?

Unfortunately I don't have a BIG-IP device running 11.6 yet and it appears you have an API call that depends on it. I'm still on 11.5.2 HF1 in my lab and probably will be going to 11.5.3 HF2 next.
This appears to be the 11.6 dependent API call:

Management::UserManagement::delete_user_permission

... which is what raised my question about why it was trying to blow away my user permissions when all I was doing was updating credentials. Here is my playbook:

```
---
- name: BIG-IP bulk password update
  hosts: "{{ env | default('none') }}"
  gather_facts: no
  connection: local
  vars_files:
    - vars/login.yml

  tasks:
  - name: Update admin user credentials
    register: results
    local_action: >
      bigip_user
      server={{ inventory_hostname }}
      user={{ api_auth.user }}
      password={{ api_auth.password }}
      state=present
      username_credential=admin
      password_credential={{ admin_password }}

  - name: Display results
    local_action: debug var=results

  - name: Update root user credentials
    register: results
    local_action: >
      bigip_user
      server={{ inventory_hostname }}
      user={{ api_auth.user }}
      password={{ api_auth.password }}
      state=present
      username_credential=root
      password_credential={{ root_password }}

  - name: Display results
    local_action: debug var=results
```

**Comment by caphrim007** [comment]
@mhite When you have the chance, can you check to see if the set_user_permission on your 11.5.2 image overrides the existing permission? On the 12.0.0+ images that I am using it appends to the existing permissions instead of stomping on the existing ones. I'll see if I can boot your version also to verify. Thanks!

**Comment by caphrim007** [comment]
@mhite ok, so I booted 11.5.2 and saw what I presume you're seeing. 11.5.2 (and I'll have to check on the other versions to see where this changed) has a user = role = partition = 1 layout; you can't have multiple roles per partition per user. So when you call set_user_permission, it stomps on the old permissions and applies the new one.

In later versions, it supports multiple roles (still one per partition) per user. When calling set_user_permission on these later versions though, it doesn't stomp on the existing permissions but instead appends to them.

So this module and my module would behave unexpectedly across different versions.

Having said that, that's probably why the delete permission code was introduced in 11.6.0; because 11.6.0 (I'm guessing) is where this multiple roles code came into existence.

What I'm going to do is verify the version where this was introduced and then check in the module to see if I should use that delete code or not based on the version that is reported. Lemme know how that sounds to you, or if you have other ideas.

**Comment by caphrim007** [comment]
@mhite i've been sitting on my updates for a while, sorry about the delay. If you want to try https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_user.py again

**Comment by gregdek** [comment]
Thanks @mhite. Since you are one of the maintainers (@mhite) of this module, we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Thanks again to @mhite. This module is going into community review.
We notice that you are one of the maintainers (@mhite) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
@resmo - We're going to close and abandon this PR in favor of upstreaming https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_user.py into ansible-modules-extras. @caphrim007 has a more full-featured (supports idempotency for password changes unlike mine) module that should fill the user management gap rather than this one.

**Pull request closed without merging**
