### PR TITLE
Fix deploy

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

deploy_helper

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @ramondelafuente please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ramondelafuente** [comment]
@gregdek I'm afraid I'm going to need a little help on this one. Is it policy to use `path` instead of `str` for module parameters? I'm not familiar with it, so I'm not sure about the implications of this change.

**Comment by mscherer** [comment]
'path' is just 'str' with proper path expansion, see https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L1394

The change is here so we can be sure to have a consistent behavior for path arguments. 

And maybe in the future, if we need to do some conversion of path or anything, we would be able to do it in one single place (even if that's just a theorical possibility, I do see how it would be needed)

**Comment by abadger** [comment]
Took a look.  I was a little hesitant about expanding shared_path and current_path as those can be relative and the path type was created with absolute paths in mind but looking at the code I can't think of any way that this will break.

Should releases_path also be made into type path?

**Pull request closed without merging**
