### PR TITLE
Created digital_ocean_floating_ip module

### PR DESCRIPTION
**Pull request by harneksidhu**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

digital_ocean_floating_ip
##### ANSIBLE VERSION

2.1
##### SUMMARY

This creates a digital_ocean_floating_ip module which allows developers to manage Floating IPs on digital ocean.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @harneksidhu for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @harneksidhu for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@harneksidhu A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@harneksidhu Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by harneksidhu** [comment]
@gregdek Please close this. I had to fork the repository again. A new PR is submitted on #2378

**Comment by harneksidhu** [comment]
Closing.

**Pull request closed without merging**
