### PR TITLE
Adding ansible module for datadog tags

### PR DESCRIPTION
**Pull request by gshivani**
Adding ansible module for datadog tags

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this module to Ansible Extras.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by robynbergeron** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately. 

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by apenney** [comment]
@stefanweller I hope (and tested as best I can) that your feedback above is addressed now!  Any chance you can take a relook and let me know if we can get this tagged with the "works_for_me" tags at this point.

**Comment by sivel** [comment]
```
============================================================================
./monitoring/datadog_downtime.py
============================================================================
ERROR: version_added should be 2.1. Currently 2.0
ERROR: No RETURN documentation provided
ERROR: GPLv3 license header not found

============================================================================
./monitoring/datadog_tag.py
============================================================================
TRACE:
    mapping values are not allowed here
      in "datadog_tag.DOCUMENTATION", line 34, column 17:
                required: true
                        ^
ERROR: DOCUMENTATION is not valid YAML. Line 34 column 17
ERROR: No RETURN documentation provided
ERROR: GPLv3 license header not found 
```

**Comment by gregdek** [comment]
@gshivani A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@gshivani Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
@gshivani A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gshivani Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gshivani** [comment]
@gregdek I apologize for the delayed response. I am working on the issues with this PR. Please keep it open.

**Comment by gregdek** [comment]
Thanks @gshivani for letting us know. Keeping it open.

**Comment by gshivani** [comment]
Hey @gregdek. Thanks so much for keeping it open! It's ready_for_review

**Comment by gregdek** [comment]
Thanks @gshivani for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by apenney** [comment]
shipit! I'm using this module daily.

**Pull request closed without merging**
