### PR TITLE
Pass through service_id if specified on a check

### LINKED ISSUE #3249: Consul module does not allow for more than one check per service
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

 ansible-modules-extras/clustering/consul.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Consul supports healthchecks at the node (host) level, and also explicitly against specific services on the host.
When creating these healthchecks using Consul's HTTP API, you have a few options, including:
1. Register a service, and specify a healthcheck as part of that registration.
2. Explicitly register a check at the node level.
3. Explicitly register a check against an existing service on a node.

Using point 3 above, it is possible to have multiple healthchecks registered for a service.

The Ansible consul module currently does not support this. If a `service_id` is specified when registering a check, it is ignored, and the check becomes like point 2 above (registered at the Node level).

This is an inconsistency between the Ansible consul module and the Consul HTTP API. It is also inconsistent with Consul libraries in other languages (Node.js and Golang both definitely support this).
##### STEPS TO REPRODUCE

Tested with local standalone consul instance. Run playbook below 3 times, to cover the 3 `TEST` tasks - commenting out the other two as needed each time.

Consul being run via Docker:
`docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap -ui-dir /ui`
Status then viewed in the Consul ui: http://localhost:8500/ui/#/dc1/services

Playbook:

```

---
- hosts: localhost
  vars:
    testhost: "localhost"
    testservice: "jhart_test"
    testport: "9999"
    testsuffix1: "status1"
    testsuffix2: "status2"
  tasks:
  - name: clean up any old registration
    consul:
      host: "{{ testhost }}"
      service_name: "{{ testservice }}"
      state: absent
  - name: clean up spurious host level check created by TEST1
    consul:
      host: "{{ testhost }}"
      check_name: "{{ testservice }}-health2"
      state: absent

  - name: register in consul with first http check
    consul:
      host: "{{ testhost }}"
      service_name: "{{ testservice }}"
      service_id: "{{ testservice }}"
      service_address: "{{ testhost }}"
      service_port: "{{ testport }}"
      # As an aside - check_name and check_id are ignored here. The check ends up being called "Service '{{ testservice }}' check"
      check_name: "{{ testservice }}-health1"
      check_id: "{{ testservice }}-health1"
      interval: "10s"
      http: "http://{{ testhost }}:{{ testport }}/{{ testsuffix1 }}"

# TEST1
  - name: register a second check against this service_name
    consul:
      host: "{{ testhost }}"
      # service_id is ignored, and the check is registered at the node level
      service_id: "{{ testservice }}"
      check_name: "{{ testservice }}-health2"
      check_id: "{{ testservice }}-health2"
      interval: "10s"
      http: "http://{{ testhost }}:{{ testport }}/{{ testsuffix2 }}"

# TEST2
  # - name: register a second check against this service_name, take 2
  #   consul:
  #     host: "{{ testhost }}"
  #     # This one fails with:
  #     # fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "service_name supplied but no service_port, a port is required to configure a service. Did you configure the 'port' argument meaning 'service_port'?"}
  #     service_id: "{{ testservice }}"
  #     service_name: "{{ testservice }}"
  #     check_name: "{{ testservice }}-health2"
  #     check_id: "{{ testservice }}-health2"
  #     interval: "10s"
  #     http: "http://{{ testhost }}:{{ testport }}/{{ testsuffix2 }}"

# TEST3
  # - name: working second check using curl
  #   uri:
  #     url: "http://{{ testhost }}:8500/v1/agent/check/register"
  #     method: PUT
  #     body: "{\"Name\":\"{{ testservice }}-health2\", 
  #     \"ID\":\"{{ testservice }}-health2\", 
  #     \"HTTP\":\"http://{{ testhost }}:{{ testport }}/{{ testsuffix2 }}\", 
  #     \"interval\": \"10s\", 
  #     \"ServiceID\":\"{{ testservice }}\"}"
  #     body_format: json

```
##### EXPECTED RESULTS

TEST1 should be equivalent to TEST3, and should result in the second check being created against the service 'jhart_test'
TEST2 is probably ok failing as it does now. Really included in the playbook for completeness.
##### ACTUAL RESULTS

Playbook output is irrelevant here. TEST1 and TEST3 both run just fine from an Ansible perspective.
BUT - TEST1 results in the check `jhart_test-health2` being created at the node level, rather than against the service.

I would expect TEST1 and TEST3 to produce identical results.

### PR DESCRIPTION
**Pull request by jhart1685**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ansible-modules-extras/clustering/consul.py
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Simple bug fix -:
The python-consul library already supports passing a service_id on a check registration, so it is just a simple case of enablement.
This does not break the current logic in the `add` function of parsing as a check, then parsing as a service if that fails… because service_name is mandatory on a service registration and is invalid on a check registration. The two cases are still mutually exclusive.
Also modified the examples in comments at the top of the file, to correct a pre-existing example and to add a new example to cover this case.

Fixes #3249

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jhart1685. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
Looks good @jhart1685, thanks for taking the time to make the change. shipit.

**Comment by jhart1685** [comment]
@sgargan many thanks! do you know what the process is to get from this point to merger and then into a release? (cc @gregdek )

**Comment by jhart1685** [comment]
Sorry - accidentally closed and re-opened this. Hope that doesn't break anything.

**Comment by sgargan** [comment]
the shipit comment should get it merged, I'll let @gregdek speak to it getting into a release.

**Comment by gregdek** [comment]
Thanks again to @jhart1685 for this PR, and thanks @sgargan for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
