### PR TITLE
Pager Duty Alert module null response handling.

### PR DESCRIPTION
**Pull request by ghost**
Previously the check method had assumed json results from the pager duty api so if the api returned null the module would kill a playbook with an incorrectly formatted data exception.

This code shortens the check method and adds a condition to handle null data.

### CODE REVIEW

**Comment by bcoca** [comment]
6 commits and 103 files changed ... looks wrong

**Comment by ghost** [comment]
Sorry about that, I had made the updates in 1.9.4 originally and installed 2.0.0.2 on top of that before I made the pull request. I've since removed the old commits and replaced them with the suggested update.

**Comment by gregdek** [comment]
Thanks @malgaudreault. @aps-sids please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ghost** [comment]
The PagerDuty API is behaving oddly in my case, but I still think there are updates that need to be made here. I haven't gotten any response from their API that includes an HTTP status code, just success to indicate a new ticket or nothing when an incident key is not provided.

I've added a conditional at the top of the check method that returns a message indicating a new incident and skips the rest of the method. This looks to have solved the root cause of my issue. I won't be able to use this module without the updates I've made or something like them being included in the next release.

In the meantime I'll be using my fork of this repo on all of my ansible deployments.

**Comment by gregdek** [comment]
Thanks @malgaudreault for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@malgaudreault A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
@gregdek I will get this sorted by Monday.

**Comment by ghost** [comment]
It's building clean now, but it looks like there have been updates to the module remove the need for this PR. It's safe to close. Thanks!

**Comment by gregdek** [comment]
@malgaudreault Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @malgaudreault. To the current maintainers, @aps-sids please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Kicking.

**Comment by gregdek** [comment]
Thanks @malgaudreault. To the current maintainers, @aps-sids please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
