### PR TITLE
openbsd_pkg: Use correct part of name in match.

### PR DESCRIPTION
**Pull request by eest**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

openbsd_pkg
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 6be09ee866) last updated 2016/10/12 19:40:10 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/12 19:43:47 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 6c31d91fa5) last updated 2016/10/12 19:43:47 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Makes module behave properly when using branch syntax (pkgname%branch) when there are messages on stderr but the requested package still managed to be installed.

Before

```
$ doas ansible localhost -m openbsd_pkg -a 'name=autoconf%2.13 state=present' 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Error from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.57p4.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.58p5.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.69p2.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.52p6.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.61p5.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.13p4.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.59p5.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.68p1.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.60p5.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.54p5.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.63p1.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.67p1.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.62p2.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.65p1.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.56p4.tgz\nsignify: write to stdout: Broken pipe\nError from http://ftp.eu.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/autoconf-2.64p1.tgz\nsignify: write to stdout: Broken pipe\n"
}
```

After:

```
$ doas ansible localhost -m openbsd_pkg -a 'name=autoconf%2.13 state=present'                                                        
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

localhost | SUCCESS => {
    "build": false, 
    "changed": true, 
    "name": "autoconf%2.13", 
    "state": "present"
}
```

Previously this part of the code could assume that the name was a stem
with nothing else attached (like "autoconf"). With the introduction of the
branch syntax ("autoconf%2.13") this is no longer true.

Check if the package name was identified as using a "branch" style name,
and base the match on the leading part of the name if that is the case.

While here remove unnecessary "pass" and tidy up debug log message.

Problem reported by @jasperla.

### CODE REVIEW

**Comment by jasperla** [comment]
The issue was actually reported to me by @cschutijser. And I can confirm your patch resolves the problem we were seeing. Thanks!

**Comment by gregdek** [comment]
Thanks again to @eest. This module is going into community review.

We notice that you are one of the maintainers (@eest) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by eest** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @eest. Since you are one of the maintainers (@eest) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
