### PR TITLE
Allow NPM to update packages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gregdek** [comment]
@chrishoffman please review this PR; if you give +1, we will merge

**Comment by gregdek** [comment]
@chrishoffman a friendly ping; this PR has been waiting for review for at least a month. Please review it if you can, or ping to let us know that you intend to review it at some point. If we don't hear from you within the next week, we will look for a new maintainer for this module.

**Comment by chrishoffman** [comment]
Sorry I haven't had a chance to look at this.  I haven't been doing too much node stuff recently so it may be a little difficult to fully test this PR.

**Comment by gregdek** [comment]
@chrishoffman no worries. Anyone you can recommend we might hand off to? 

Gonna put this in core_review for now, but if (a) you can nominate someone who might be able to help review this patch, or (b) you can test it yourself, please let us know. Thanks!

**Comment by gregdek** [comment]
Bump. Looking for someone who uses npm and can validate this 1-line change.

**Comment by gregdek** [comment]
Bump again. If anyone cares about the NPM module, feel free to step up as a reviewer. :)

**Comment by mattwwarren** [comment]
hi @gregdek - I filed bug #1184 for this exact fix and can confirm this pull request solves the issue. We use npm and ansible heavily and would love to see this merged.

**Comment by offero** [comment]
Works. Please merge.

**Pull request merged**
