### PR TITLE
added s3 support to maven artifact module

### PR DESCRIPTION
**Pull request by gedl**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added S3 support for maven_artifact 
Re-used all http fetch logic. The S3 supported was added through means of generating a temporary HTTP download, that is passed to the pre-existing HTTP get flow
No changes in the command output or existing behaviour. The new S3 download behaviour is exactly the same as the pre-existing one.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @gedl. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gedl** [comment]
ready_for_review

**Comment by chrisisbeef** [comment]
@gregdek - Can someone clarify whether the failed travis build is due to this change or a bug in the build process itself? It's unclear from the build-log. 

@gedl - This is awesome! I don't have simple access (or unfortunately time) to fully test this against s3 presently. Can you provide an example configuration _and_ results log for implementing this with s3 as an alternative?

**Comment by gregdek** [comment]
So the Travis error is this:

Auto-merging packaging/language/maven_artifact.py
CONFLICT (content): Merge conflict in packaging/language/maven_artifact.py
Failed to merge in the changes.

To me that says that there's a merge conflict that needs to be resolved, and it looks like it happened at 1c46bb7. I'd say rebase.

**Pull request closed without merging**
