### PR TITLE
Correctly report "changed: false" when trying to install a package not i...

### LINKED ISSUE #230: The pkgutil provider reports state: present when a package is not in the catalog
When I try to install a non-existing package with something like

```
# ansible unstable9s -m pkgutil -a "name=CSWlibpsl-dev state=present"
```

The result is success and the state "present" is reported:

```
unstable9s | success >> {
    "changed": true, 
    "name": "CSWlibpsl-dev", 
    "state": "present", 
    "stderr": "Package CSWlibpsl-dev not in catalog. Exiting.\n", 
    "stdout": "Solving needed dependencies ...\n"
}
```

The package was not installed on the machine and is not installed afterwards:

```
unstable9s% pkginfo -x CSWlibpsl-dev
ERROR: information for "CSWlibpsl-dev" was not found
```

### PR DESCRIPTION
**Pull request by dago**
...n the catalog. This fixes #230

### CODE REVIEW

**Comment by abadger** [comment]
I don't have a solaris box with pkgutil to check this but some of this looks a little strange.
- Is rc ever going to be None?
- Is rc a dependable indicator for failure?  ie: is trying to install an already installed package going to return rc=0?  Will attempting to upgrade a package that's already at the latest version return rc=0?  Will uninstalling a package that's not present on the system return rc=0?
- How do we differentiate between failure and no action?  It seems like return code might not be enough to do that?

**Comment by dago** [comment]
Regarding your questions:
- If the package is already installed `package_install` is not called and rc stays with the preinitialized value `None`
- A package is not tried to be installed if it is already present as the existence is checked previously with `pkginfo -q`. From pkginfo the returned is dependable. If the operation was successful 0 is returned, otherwise a different returncode. Otherwise it is considered a bug in pkgutil. I am also in contact with Peter Bonivart, the author of pkgutil, to fix issues as they occur.
- If pkgutil was invoked for action and rc == 0 then something was changed, otherwise an error occurred or rc was still None and pkgutil was not invoked. The operation is failed if pkgutil was invoked which means rc != None where rc == 0 means success.

I do acknowledge that the twist with rc == None if pkgutil was not invoked is not clearly visible in the code, if you think this is useful I can refactor it.

**Comment by abadger** [comment]
Ah, okay.  So maybe something like this:

``` python
if rc is None:
    # Did not run commands as no change needed
    result['changed'] = False
elif rc == 0
    result['changed'] = True
else:
    result['changed'] = False
    result['failed'] = True
```

It's a little quirky but by and large we don't set failed=False when everything succeeds.  Just set failed=True when there is a failure.

**Comment by dago** [comment]
Yes, this is exactly the definitions I had in mind.

**Comment by abadger** [comment]
@dago if you'd like to update the PR I'll merge this.

**Comment by dago** [comment]
Pull request updated.

**Comment by abadger** [comment]
Thanks!

# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
