### PR TITLE
Adding support for service ACLs in consul_acl module

### PR DESCRIPTION
**Pull request by chrishoffman**
This pull request adds support to the consul_acl module for ACLs on services.

Consul 0.5.0 added support for service discovery ACLs.  The current version of the module only supports ACLs on the kv part of Consul.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @sgargan

**Comment by sgargan** [comment]
Service changes look good thanks for adding them. I have a minor concern about the token obfuscation, the reasoning behind returning it is so that it could be registered in a variable and subsequently used in further operations e.g. stored via a template onto client machines that will use the token, obfuscating it will break this. What is your concern here? If you're worried about it being passed back you could add an optional flag to omit or obfuscate it. There are probably other ways it can be excluded from the logs too.

**Comment by chrishoffman** [comment]
You are absolutely correct about registering variables.  My concern was the -v output but it completely makes sense and was a use case I wasn't considering.  I personally generate tokens and set them explicitly for new acl policies so I was more concerned about tokens leaking into the logs.  I will remove the token obfuscation.

**Comment by bcoca** [comment]
add no_log to the token spec if it should be kept 'confidential'

**Comment by gregdek** [comment]
+1 to no_log being needed.

@chrishoffman Please make the suggested revisions, and when you're done -- or if we're incorrect and no revision to no_log needs to be made -- please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by chrishoffman** [comment]
The revisions were made to no longer obfuscate the token.  I have updated the pull request text accordingly.

ready_for_review

**Comment by gregdek** [comment]
Thanks @chrishoffman.

@sgargan can you give a quick re-review? If you think it's good, please add a comment with "shipit" in the text, and we will flag it for inclusion. If not, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by sgargan** [comment]
Obfuscation is gone, looks good. Ship it (or shipit as the case may be).

**Comment by robynbergeron** [comment]
Thanks @chrishoffman for the PR, and to @sgargan for the reviews. 

Marking for inclusion, cc: @ansible/core team.

**Comment by abadger** [comment]
If there is concern about logging the token parameters we need to update the argument spec to mark those as no_log.  It won't affect returning a value wth token in it but it will affect logging of the parameter that is given to the module.  So Line 322 and possibly Line 316 need to be updated to have no_log.  Since token and mgmt_token are already parameters of this module, I'll go ahead and merge this now but I'd appreciate either a pull request or information about whether both Line 322 and Line 316 should be marked no_log.

If you're taking the PR route, this is what the argument spec would look like:

``` patch
- token=dict(required=False),
+ token=dict(required=False, no_log=True),
```

**Comment by abadger** [comment]
# Merged

Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Pull request merged**
