### PR TITLE
system/firewalld module refactor; added source, interface, masquerade, forward and icmp_block support

### PR DESCRIPTION
**Pull request by jkramarz**
Few more features are still missing, but it's quite usable in common scenarios :-)

### CODE REVIEW

**Comment by jkramarz** [comment]
Any chance to merge it someday?

**Comment by bcoca** [comment]
yes, but  please have patience, we have a huge backlog and have not had a chance to review this yet.

**Comment by gregdek** [comment]
Looks like this has merge conflicts. @jkramarz if you can rebase, please ping @maxamillion when you're done. If he gives a +1, we will merge.

**Comment by maxamillion** [comment]
These are going to conflict also https://github.com/ansible/ansible-modules-extras/pull/116

**Comment by jkramarz** [comment]
@maxamillion it does not, as it already includes changes from #116 in 02dfd3a. I've rebased this pull request on current devel.

**Comment by maxamillion** [comment]
Ah ok, my mistake. Reviewing.

**Comment by maxamillion** [comment]
This is great, definitely a more clean way to handle adding new options later and a much better handling of conflicting operations.

Thanks! 

LGTM :+1:

**Comment by gregdek** [comment]
@jkramarz This is a pretty big refactor, so just double-checking: can I presume you're using this module currently in its present form?

**Comment by resmo** [comment]
Hi, just my 2 cents, there are some missing `version_added: "2.0"` for the new params.

**Comment by jkramarz** [comment]
@gregdek yes, we've most of the servers configured using this version of module, but the tasks performed are very similar. It is not impossible that it will fail in some cases I've not tried out.

**Comment by jkramarz** [comment]
@resmo thank you, I've added some more

**Comment by gregdek** [comment]
@jkramarz Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible.

**Comment by jkramarz** [comment]
@gregdek ok, I've rebased this PR again.

**Comment by gregdek** [comment]
Setting to core_review out of an abundance of caution because of the scope of the changes. @ansible/core please have a look?

**Comment by gregdek** [comment]
Ping again to the @ansible/core team. (I know you guys are busy, just doing some bookkeeping.)

**Comment by rbu** [comment]
@ansible/core, any chance you could review this? The original submitter rebased this twice and this PR makes firewalld support much more usable in setups that are not just basic "open http port" scenarios.

**Comment by jkramarz** [comment]
Talking about rebase... done.

**Comment by maxamillion** [comment]
FWIW, this still looks good to me. :+1:

**Comment by robynbergeron** [comment]
Thanks @jkramarz for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Thanks @jkramarz. @maxamillion please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @jkramarz for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@maxamillion This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Once again this is now showing merge conflicts. 

Looking at its history, I think one of the reasons it's failing is because it's just too large a commit. Which means it takes longer to review, and because it waits, something changes beneath it, and it waits again.

It's now also failing Travis, because we've got a more detailed syntax checker now, and it found this:

sys.exit() call found. Should be exit_json/fail_json

So. @jkramarz, I know you've refactored this several times now, and I appreciate the effort. Might I propose that you break this up into smaller features that are easier to merge one at a time? That way I hope we'll have better luck with the long review cycle.

**Comment by gregdek** [comment]
@jkramarz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by rbu** [comment]
Couldn't you continue with a review based on the current state of the commit, then ask for a rebase that includes fixes for the issues you'd raise and hopefully merge it afterwards?

I'm not the original submitter, but I find it demotivating that you ask them for another rebase after it was rebased four times already, every single time followed by a lack of response until it would not merge again.

**Comment by maxamillion** [comment]
shipit

**Comment by jkramarz** [comment]
Hi all, I don't have time to rebase it in this particular moment.
Also, I'm not able to split this commit (I've squashed it during one of previous merges) without some lose of features (so the build will fail) - this pull requests throws away handcrafted code from this plugin and replaces it with a bit more generic.

**Comment by gregdek** [comment]
Thanks @jkramarz for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jkramarz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jkramarz Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jkramarz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jkramarz Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@jkramarz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jkramarz** [comment]
@gregdek, I'm no longer interested in.

**Pull request closed without merging**
