### PR TITLE
added code which returns instance & platform type aswell.

### PR DESCRIPTION
**Pull request by aaratn**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

-  ansible-modules-extras/cloud/amazon/ec2_remote_facts
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

- Current ec2_remote_facts does not return instance_type & Platform. This change will return the instance_type & platform which can be useful to the user for performing action when instance_type or platform is required from ec2_remote_facts.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @aaratn. To the current maintainers, @michaeljs1990 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @aaratn for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by aaratn** [comment]
ready_for_review

**Comment by bcoca** [comment]
bad merge, please rebase

**Comment by gregdek** [comment]
Thanks @aaratn for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Thanks for this PR. It appears you've got a lot of other changes listed here. When creating/updating a PR (Pull Request) it's often useful to review the "Files Changed" tab.

Have a look at the following page for details on how to clean up this branch

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

If you still have issues please join `#ansible-devel` on Freenode

**Comment by gundalow** [comment]
needs_revision - As there are unrelated changes in this PR

**Comment by michaeljs1990** [comment]
Current state is un reviewable possibly because of a bad rebase or merge.

**Comment by gregdek** [comment]
Thanks @aaratn for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@aaratn A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@aaratn Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@aaratn A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@aaratn Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
This PR hasn't been touched in 2 months+ and has merge conflicts.

If you need assistance please swing by `#ansible-devel` on Freenode IRC

**Pull request closed without merging**
