### PR TITLE
add fleet_facts module which gathers information about CoreOS clusters

### PR DESCRIPTION
**Pull request by coderfi**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

fleet_facts
##### ANSIBLE VERSION

ansible 2.2.0 (devel d81b9ca29e) last updated 2016/05/30 11:32:27 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 90e8a36d4c) last updated 2016/05/30 11:32:37 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 0e4a023a7e) last updated 2016/05/30 11:32:47 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
##### SUMMARY

Gather facts about Fleet machines and units of a CoreOS cluster

### CODE REVIEW

**Comment by coderfi** [comment]
My previous pull request #928 was auto-deleted when I tried to bring my branch up to date.
Here is a new pull request. Sorry for the confusion.

This is related to pull #2344

**Comment by gregdek** [comment]
Thanks @coderfi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@coderfi A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@coderfi Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@coderfi A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@coderfi Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by coderfi** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @coderfi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
