### PR TITLE
New facts module for AWS EC2 VPC Endpoints

### PR DESCRIPTION
**Pull request by Etherdaemon**
Retrieves AWS VPC endpoints details using AWS methods. Requires Boto3.
Filter options can be found http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpoints.html

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @Etherdaemon for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Etherdaemon A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Etherdaemon Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Etherdaemon** [comment]
@gregdek ready_for_review - the travis build failed due to something to do with yum and doesn't appear to be related to this PR itself

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgnn7** [comment]
needs_revision

@Etherdaemon This patch doesn't work as-is since it's not importing ec2 referenced [here](https://github.com/ansible/ansible-modules-extras/pull/1428/files#diff-572dacbff83687e7d9513885f84b6342R187) from anywhere

**Comment by sgnn7** [comment]
Opened a PR (https://github.com/Etherdaemon/ansible-modules-extras/pull/3) to fix this

**Pull request closed without merging**
