### PR TITLE
download artifacts from s3

### PR DESCRIPTION
**Pull request by gedl**
##### ISSUE TYPE

- Feature Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added S3 support for maven_artifact 
Re-used all http fetch logic. The S3 supported was added through means of generating a temporary HTTP download, that is passed to the pre-existing HTTP get flow
No changes in the command output or existing behaviour. The new S3 download behaviour is exactly the same as the pre-existing one.

New version of #2118 

@chrisisbeef I will post examples once CI completes successfully.

### CODE REVIEW

**Comment by gedl** [comment]
@chrisisbeef Examples as requested. 
- Example configuration:

```
- hosts: localhost
  tasks:
    - name: download artifact if absent
      maven_artifact:
        group_id: com.something.somethingelse
        artifact_id: myartifact
        version: "latest"
        dest: "/tmp"
        repository_url: "s3://<redacted>.s3.amazonaws.com/dev"
        aws_secret_key: <redacted>
        aws_secret_access_key: <redacted>
        extension: war
      register: artifact
    - debug: var=artifact
```
- Result (artifact already existed locally)

```
ok: [localhost] => {
    "artifact": {
        "changed": false, 
        "dest": "/tmp/myartifact-latest.war", 
        "gid": 0, 
        "group": "wheel", 
        "mode": "0600", 
        "owner": "gluiz", 
        "size": 98637847, 
        "state": "file", 
        "uid": 502
    }
}
```
- Result (artifact did not exist locally)

```
ok: [localhost] => {
    "artifact": {
        "artifact_id": "myartifact", 
        "changed": true, 
        "classifier": null, 
        "dest": "/tmp/myartifact-latest.war", 
        "extension": "war", 
        "gid": 0, 
        "group": "wheel", 
        "group_id":  com.something.somethingelse", 
        "mode": "0600", 
        "owner": "gluiz", 
        "repository_url":  "s3://<redacted>.s3.amazonaws.com/dev", 
        "size": 98637847, 
        "state": "file", 
        "uid": 502, 
        "version": "latest"
    }
}
```

**Comment by gregdek** [comment]
Thanks @gedl. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
As all new Amazon modules must use boto3 now i guess it makes sense to enforce that here too.  @gedl  can you switch to boto3?

**Comment by gedl** [comment]
@wimnat done

**Comment by gedl** [comment]
@wimnat looks like I spoke to early, but it is done now.

**Comment by gedl** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @gedl for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gedl** [comment]
Not sure what the process is when devel is not passing CI.

**Comment by gedl** [comment]
ready_for_review

**Comment by chrisisbeef** [comment]
Apologies for the delay folks - I was out of pocket for a couple weeks. The closed status is confusing to me - where are we at with this presently?

I am good w/ including this functionality in the plugin. I think it will need to be updated once the other PR for Py3 compatibility is merged in however.

**Comment by gedl** [comment]
hi @chrisisbeef . I've messed with this PR at some point and created PR #2317 instead. Same changes, but already with Py3

**Pull request closed without merging**
