### PR TITLE
Add ability to create event and query acl rules for a given acl token

### PR DESCRIPTION
**Pull request by Etherdaemon**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

consul_acl
##### ANSIBLE VERSION

```
ansible 2.0.1.0 (detached HEAD 870a4b8dc1) last updated 2016/03/21 14:29:55 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD b4a4f74724) last updated 2016/03/21 14:30:01 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD b9f5838c78) last updated 2016/03/21 14:30:01 (GMT +1000)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Update existing module to allow for creation of query and event rules to a given acl token.
##### Before change: event and query policies were not allowed even though consul supports it.

```
fatal: [127.0.0.1]: FAILED! => {
        "changed": false,
        "failed": true,
        "msg": "a rule requires a key/service and a policy."
    }
```
##### After change:  updated to support event and query policies/rules:

```
ok: [127.0.0.1] => {
        "changed": false,
        "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "rules": [
            {
                "key": "",
                "policy": "read"
            },
            {
                "key": "apple/",
                "policy": "write"
            },
            {
                "policy": "write",
                "service": ""
            },
            {
                "event": "apple-",
                "policy": "write"
            },
            {
                "event": "",
                "policy": "read"
            },
            {
                "policy": "read",
                "query": ""
            }
        ],
        "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "type": "client"
    }
```

### CODE REVIEW

**Comment by Etherdaemon** [comment]
@sgargan - following up on this - consul acl rules also support keyring but unfortunately keyring is not in the same format as the rest of the rules - and does not have a policy. I'm not 100% sure how you want to implement it as a result given your functions require policies to be provided.

**Comment by gregdek** [comment]
Thanks @Etherdaemon. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Etherdaemon** [comment]
@gregdek I'm not sure @sgargan exists anymore? When typing it doesn't resolve that alias?

**Comment by gregdek** [comment]
He exists: https://github.com/sgargan

(Also, his username links in the body of the comment.)

Let's give him time to respond.

**Comment by Etherdaemon** [comment]
No worries. It wasnt coming up in another PR I was doing yesterday  so thought I better check.  Cheers

**Comment by sgargan** [comment]
Without getting too philosophical, I'm reasonably sure I exist, If I fell in the woods I'd probably swear.

I'm happy for these to be added, we could probably clean up the rules addition to make it a little drier but its a small comment. It would be useful to add some examples for these to the documentation. (There are tests for all of this in the core project too if you're feeling like being really thorough)

The keyring acl is new, not sure why they chose to diverge from the existing rules format but should be straightforward enough to add a rule type to cover these kinds rules in case there are more of this style in the future. Adding support will require patching the python-consul library as it doesn't seem to support this yet, shouldn't be a big deal to add and the maintainer is pretty good at accepting patches. If you're going to tackle this I'd suggest cutting a new PR just for it.

**Comment by Etherdaemon** [comment]
Glad to hear you haven't fallen into the woods @sgargan :)

Thanks heaps - I'll take a look at the python-consul lib later and see if I can tackle that one at some point.

**Comment by klynch** [comment]
Can this be merged? It's extremely useful for us.

**Comment by sgargan** [comment]
in case this is waiting on me :shipit: shipit

**Comment by gregdek** [comment]
Thanks again to @Etherdaemon for this PR, and thanks @sgargan for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
