### PR TITLE
switched to use module loggigng

### PR DESCRIPTION
**Pull request by bcoca**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @bcoca Thanks :)

Travis is failing -- it looks like on maybe 2.4 with znode.py, which @abadger just moved in/renamed last night. I could be wrong though. Still learning the ropes of Travis. :) So I think something needs revision? :)

**Comment by robynbergeron** [comment]
https://github.com/ansible/ansible-modules-extras/commit/962afeed5434e944e39e37b835b514f9bb9ce9ab for reference

**Comment by bcoca** [comment]
yep, that is not caused by this PR

**Comment by gregdek** [comment]
Entrusting this one to the core team. :) 

Since (a) it was opened by a core team member and (b) it touches multiple files.

**Pull request merged**
