### PR TITLE
Add auth basic support on Zabbix modules (Fixes #1647)

### LINKED ISSUE #1647: Add force_basic_auth in modules zabbix_*
Hello,

For Example, in module "uri" it's possible auth basic on option "force_basic_auth".

My zabbix server is setup with authentification basic (nginx).
The module "zabbix_host" don't authentication successfully (401 :/).

The module zabbix-api (https://github.com/gescheit/scripts/tree/master/zabbix) support auth basic.

Is it possible to integrate option "force_basic_auth" in all zabbix modules ?

Regards,

### PR DESCRIPTION
**Pull request by thelan**
##### Issue Type:

Feature Pull Request
##### Plugin Name:

Updated: monitoring/zabbix_*
##### Summary:

Add parameter http_login_user and http_login_password for zabbix modules to provide support to Auth Basic

Previous PR: #1665

### CODE REVIEW

**Comment by eikef** [comment]
Thank you, that looks excellent -- the only thing missing is the version_added on timeout :-)

**Comment by thelan** [comment]
Fixed

**Comment by eikef** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @thelan for this PR, and thanks @eikef for reviewing. Marking for inclusion.

**Comment by resmo** [comment]
Thanks @thelan for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by thelan** [comment]
ready_for_review

**Comment by eikef** [comment]
shipit

**Comment by resmo** [comment]
Thanks again to @thelan for this PR, and thanks @eikef for reviewing. Marking for inclusion.

**Pull request merged**
