### PR TITLE
Validate return code and fail properly

### LINKED ISSUE #2333: win_regmerge does not verify command success, fails when reporting success
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_regmerge
##### ANSIBLE VERSION

v2.1
##### SUMMARY

The win_regmerge module does not report back if a command worked or failed, and does not return the command output. Not understanding why my Curses.reg was not working, I found out that the module could not find the file and actually returned:

```
ERROR: Error opening the file. There may be a disk or file system error.
```

It simply didn't look in `files/` as I was expecting. Despite this important error, the module reports:

```
changed: [windows1] => {"changed": true, "compared": false, "invocation": {"module_name": "win_regmerge"}}
```

That's rather important. If we want the Windows support in Ansible to shine, things like this basically kills the user experience.

PS I have similar problems with other modules, if things are not exactly as the module expects it silently fails with no clue to the user.

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

win_regmerge
##### ANSIBLE VERSION

v2.1
##### SUMMARY

This fixes #2333

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by jhawkesworth** [comment]
I am the maintainer for this module.

I will test it and comment again after testing.

**Comment by resmo** [comment]
@jhawkesworth great. Marked you as the maintainer.

**Comment by gregdek** [comment]
Thanks @dagwieers. To the current maintainers, @jhawkesworth please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Thanks for this.  passes tests against s2008r2 s2012r2 and s2016tp5 so I'm giving it a

shipit

**Comment by gregdek** [comment]
Thanks again to @dagwieers for this PR, and thanks @jhawkesworth for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
