### PR TITLE
win_secedit module: adds ability to mod local security policies

### PR DESCRIPTION
**Pull request by juliedavila**
##### ISSUE TYPE

Feature Pull Request
##### COMPONENT NAME

win_secedit
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allows users to modify local security policies via the secedit utility for example:

``` yml
    - name: Set local password age policy to 14 days
      win_secedit:
        category: System Access
        key: MaximumPasswordAge
        value: 14
```

### CODE REVIEW

**Comment by jmighion** [comment]
This works for me on the 2k8r2, 2k12ms, and 2k12dc servers on AWS.

**Comment by gregdek** [comment]
Thanks @defionscode for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jmighion** [comment]
shipit

**Comment by bpleines** [comment]
shipit

**Comment by jhawkesworth** [comment]
Would it be possible to re-submit this or move this PR now that the ansible repos have been merged?

**Comment by jhawkesworth** [comment]
Hi there is a feature freeze for ansible 2.3 very shortly, so if you are able to resubmit or move this PR in the next few days it might still be possible to get it included in ansible 2.3.

**Comment by jhawkesworth** [comment]
@defionscode I just realised you might not have seen my messages above regarding this pull request as I hadn't mentioned your github handle. Would be great to try and get this in before the 2.3 code freeze next week if you can spare the time to move your PR.

**Pull request closed without merging**
