### PR TITLE
Error in examples in key

### PR DESCRIPTION
**Pull request by daveres**
There is a extra ":" that makes the script fails

KO: HKCU:\Software\MyCompany
OK: HKCU\Software\MyCompany

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @daveres. @joshludwig @smadam813 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@joshludwig @smadam813 This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by nitzmahone** [comment]
The examples work fine for me under devel/2.1 as is- can you attach a sample that's failing for you?

**Comment by gregdek** [comment]
@daveres Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
