### PR TITLE
[Bug] exchange name contains chars that needs to be quoted

### PR DESCRIPTION
**Pull request by caduri**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @caduri -- thanks for this PR.

@manuel-sousa -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by manuel-sousa** [comment]
shipit

@caduri what exchange were you trying to create for this to become an issue? 
I've made a quick test with allowed characters (https://www.rabbitmq.com/specification.html) and didn't give me any issue in my environment.

> The exchange name consists of a non-empty sequence of these characters: letters, digits, hyphen, underscore, period, or colon.
> Notes: The lexicon is not enforced by the server.

The submited patch shouldn't produce side effects on working configurations and might allow some names since the lexicon isn't enforced by RabbitMQ. As such i think we should allow it.

**Comment by caduri** [comment]
Try exchange name with / like "ansible/input"

**Comment by manuel-sousa** [comment]
According to specification / isn't in the allowed characters for the exchanges. However RabbitMQ doesn't enforce it and as such i think the plugin shouldn't either which is why I recomended to shipit.

Those names might cause issues elsewhere so use with caution.

**Comment by caduri** [comment]
I weren't aware of that, thanks.

**Comment by gregdek** [comment]
Thanks @caduri for the PR, and thanks @manuel-sousa for the detailed review. Marking for inclusion.

**Pull request merged**
