### PR TITLE
module to enable/disable apache2 sites

### PR DESCRIPTION
**Pull request by paulczar**
This is mostly a copy&paste from the already existing apache_module module with a few bits changed to support the `a2ensite` and `a2dissite` commands provided by apache2 on ubuntu.

### CODE REVIEW

**Comment by bcoca** [comment]
I think it might be better to patch the current module do be able to do both

**Comment by ghost** [comment]
should ansible modules in this repository be distro specific?

**Comment by bcoca** [comment]
we try to avoid that, only things like packaging should be distro specific

**Comment by ghost** [comment]
@bcoca : so should this PR be closed then? The a2*site commands are only available by default on debian derivatives

**Comment by bcoca** [comment]
no, I'm just suggesting it be expanded to work in more scenarios

**Comment by ghost** [comment]
I mistakenly submitted a [similar PR](https://github.com/ansible/ansible-modules-core/pull/1242) to the core modules repo. My PR is a cut and paste job too, but does add the option to specify an apache instance in the same way as the PR for [apache2_module](https://github.com/ansible/ansible-modules-core/pull/1194)

**Comment by gregdek** [comment]
@bcoca when you say this should be expanded to work in more scenarios, did you have any details?

**Comment by bcoca** [comment]
@gregdek what the description states, being able to manage sites and modules from a single plugin

**Comment by gregdek** [comment]
So is the right approach, then, to add this functionality to the existing apache module, or no?

**Comment by michaeljs1990** [comment]
It looks the maintainer is no longer interested in carrying this one though or has not checked github in a long time. I would be willing to take this one over and submit a PR with functionality for RHEL and Debian.

**Comment by gregdek** [comment]
@michaeljs1990 I agree. I'll close this one. Looking forward to your new PR.

**Pull request closed without merging**
