### PR TITLE
adds module ec2_vpc_dhcp_options_set

### PR DESCRIPTION
**Pull request by klj613**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @klj613 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by klj613** [comment]
Thanks :)

Only now I found/saw http://docs.ansible.com/ansible/developing_modules.html#module-checklist - I will update my PR accordingly today or tomorrow.

**Comment by klj613** [comment]
Updated PR

**Comment by jsmartin** [comment]
This seems to mimic functionality provided in #1330, but it appears #1330 some additional options around preserving and deleting options.

**Comment by gregdek** [comment]
Thanks for this PR @klj613 but #1330 was merged. If the current version of the module does not do what you need, please feel free to submit PRs against the new module.

**Pull request closed without merging**
