### PR TITLE
Adds module to manage SNAT pools on a BIG-IP

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

network/f5/bigip_snat_pool.py
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This module adds the ability to manage the lifecycle of SNAT pools on a BIG-IP.

Tests for this module can be found here

https://github.com/F5Networks/f5-ansible/blob/master/roles/bigip_snat_pool/tasks/main.yaml

Platforms this was tested on are

12.1.0 HF1

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
lgtm

shipit

**Comment by gregdek** [comment]
Thanks again to @caphrim007 for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
@gundalow

**Comment by gundalow** [comment]
Merged to `devel` aka `2.3`

Thanks :)

**Pull request merged**
