### PR TITLE
adding username/password support along with ssl/starttls to mail

### PR DESCRIPTION
**Pull request by bowensong**
original pull request from here: https://github.com/ansible/ansible-modules-extras/pull/42
added exception handling for non-SSL smtp

### CODE REVIEW

**Comment by bhcopeland** [comment]
Expected output: 

```
msg: Failed to send mail to server 127.0.0.1 on port 25: [Errno 111] Connection refused
FATAL: all hosts have already failed -- aborting
```

Actual output:

```
Traceback (most recent call last):
  File "/home/ben/.ansible/tmp/ansible-tmp-1424875865.81-20693470031868/mail", line 1843, in <module>
    main()
  File "/home/ben/.ansible/tmp/ansible-tmp-1424875865.81-20693470031868/mail", line 192, in main
    smtp = smtplib.SMTP_SSL(host, port=int(port))
  File "/usr/lib/python2.7/smtplib.py", line 792, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 797, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

FATAL: all hosts have already failed -- aborting 

```

Not catching the error properly.

**Comment by bowensong** [comment]
@bhcopeland sorry, my mistake, has solved.

**Comment by bcoca** [comment]
overlaps with #42 and #271

**Comment by bcoca** [comment]
closing this as duplicate of the merged #42

**Pull request closed without merging**
