### PR TITLE
Add optional 'public' option to ec2_ami_copy

### PR DESCRIPTION
**Pull request by cjh1**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

ec2_ami_copy
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allow a AMI copy to be marked as public.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @cjh1. To the current maintainers, @amir343 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amir343** [comment]
I believe this change (making an image public) does not belong to `ec2_ami_copy` but rather to its own ansible module, something like `ec2_ami_attribute` that will be responsible for modifying attributes of an EC2 Image.

**Comment by amir343** [comment]
close_me

**Comment by cjh1** [comment]
@amir343 Fair enough, was torn, but I saw that 'tags' was an option ...

**Comment by amir343** [comment]
@cjh1 That's true. When you have your `ec2_ami_attribute` or whatever it's called, then we need to move tags to that one as well :)

**Pull request closed without merging**
