### PR TITLE
make: Expose std{out,err} of successful make commands

### PR DESCRIPTION
**Pull request by stevekuznetsov**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

`make`
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When using the `make:` extras module, often the action taken
by the Make target is large. It is useful, therefore, to see
the output that `make` had to std{out,err} during execution
even when the target did not fail.
##### BEFORE

```
TASK [make : execute make target(s) "install" in the origin-web-console repository] ***
task path: /home/skuznets/Documents/go/src/github.com/openshift/origin-ci-tool/oct/ansible/oct/roles/make/tasks/main.yml:12
changed: [openshiftdevel] => (item=install) => {
    "changed": true, 
    "chdir": "/data/src/github.com/openshift/origin-web-console", 
    "failed": false, 
    "invocation": {
        "module_args": {
            "chdir": "/data/src/github.com/openshift/origin-web-console", 
            "params": null, 
            "target": "install"
        }, 
        "module_name": "make"
    }, 
    "item": "install", 
    "params": null, 
    "target": "install"
}
```
##### AFTER

```
TASK [make : execute make target(s) "install" in the origin-web-console repository] ***
task path: /home/skuznets/Documents/go/src/github.com/openshift/origin-ci-tool/oct/ansible/oct/roles/make/tasks/main.yml:12
changed: [openshiftdevel] => (item=install) => {
    "changed": true, 
    "chdir": "/data/src/github.com/openshift/origin-web-console", 
    "failed": false, 
    "invocation": {
        "module_args": {
            "chdir": "/data/src/github.com/openshift/origin-web-console", 
            "params": null, 
            "target": "install"
        }, 
        "module_name": "make"
    }, 
    "item": "install", 
    "params": null, 
    "stderr": "", 
    "stdout": "hack/install-deps.sh\n[install-assets] npm install --unsafe-perm\n[install-assets] bower cache clean --allow-root\n[install-assets] bower update --allow-root\n[install-assets] rm -rf openshift-jvm\n[install-assets] mkdir -p openshift-jvm\nhack/install-deps.sh took 23 seconds", 
    "stdout_lines": [
        "hack/install-deps.sh", 
        "[install-assets] npm install --unsafe-perm", 
        "[install-assets] bower cache clean --allow-root", 
        "[install-assets] bower update --allow-root", 
        "[install-assets] rm -rf openshift-jvm", 
        "[install-assets] mkdir -p openshift-jvm", 
        "hack/install-deps.sh took 23 seconds"
    ], 
    "target": "install"
}
```

Signed-off-by: Steve Kuznetsov skuznets@redhat.com

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Also, this _potentially_ fixes a bug, as the previous implementation did not pass the parameters (from the user-provided `params:` argument to the module) into the command that checked to see if the `make` target was up to date. Without deep thought, it seems possible that the presence or absence of parameters could change that check.

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by stevekuznetsov** [comment]
Any thoughts @gregdek @resmo @robynbergeron ?

**Comment by gregdek** [comment]
Added @LinusU as maintainer of this module, kicking

**Comment by gregdek** [comment]
Thanks @stevekuznetsov. To the current maintainers, @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by LinusU** [comment]
Awesome work 🙌 

'shipit'

**Comment by gregdek** [comment]
Thanks again to @stevekuznetsov for this PR, and thanks @LinusU for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
