### PR TITLE
Allow parameters to be passed for uninstall (required by some packages)

### PR DESCRIPTION
**Pull request by tim-seoss**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

win_chocolatey module
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel d197407306) last updated 2016/05/18 16:10:09 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 92bf802cb8) last updated 2016/05/18 16:10:16 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD e710dc47fe) last updated 2016/05/18 16:10:22 (GMT +000)
```
##### SUMMARY

Some chocolatey packages require the passing of parameters during uninstall

Without the patch, running this playbook:

``` yaml

---
- hosts: logosportsdesktops
  tasks:
  - name: Install win32-openssh
    win_chocolatey:
        name: win32-openssh
        params: /SSHServerFeature /KeyBasedAuthenticationFeature
        state: present
        version: 2016.05.15
        upgrade: True
...
```

followed by:

``` yaml

---
- hosts: logosportsdesktops
  tasks:
  - name: Install win32-openssh
    win_chocolatey:
        name: win32-openssh
        params: /SSHServerFeature
        state: absent
        version: 2016.05.15
        upgrade: True
...
```

... will fail, since the chocolatey package in question requires you to pass the  /SSHServerFeature on uninstall, if the ssh binary is setup to run as a service.

before:

```
tim@ansible:~/ansible-work$ ansible-playbook OpenSshWin32Choco.yml

PLAY [logosportsdesktops] ******************************************************

TASK [setup] *******************************************************************
ok: [logosports20]

TASK [Install win32-openssh] ***************************************************
fatal: [logosports20]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe uninstall -dv -y win32-openssh -version 2016.05.15", "choco_error_log": "Chocolatey is running on Windows v 10.0.10240.0 Attempting to delete file \"C:/ProgramData/chocolatey/choco.exe.old\". Attempting to delete file \"C:\\ProgramData\\chocolatey\\choco.exe.old\". Command line: \"C:\\ProgramData\\chocolatey\\choco.exe\" uninstall -dv -y win32-openssh -version 2016.05.15 Received arguments: uninstall -dv -y win32-openssh -version 2016.05.15  NOTE: Hiding sensitive configuration data! Please double and triple   check to be sure no sensitive data is shown, especially if copying   output to a gist for review. Configuration: CommandName='uninstall'| CacheLocation='C:\\Users\\LOGOSP~1\\AppData\\Local\\Temp'| ContainsLegacyPackageInstalls='True'| CommandExecutionTimeoutSeconds='2700'| Sources='https://chocolatey.org/api/v2/'|Debug='True'|Verbose='True'| Force='False'|Noop='False'|HelpRequested='False'|RegularOutput='True'| QuietOutput='False'|PromptForConfirmation='False'|AcceptLicense='True'| AllowUnofficialBuild='False'|Input='win32-openssh'| Version='2016.05.15'| AllVersions='False'|SkipPackageInstallProvider='False'| PackageNames='win32-openssh'|Prerelease='False'|ForceX86='False'| OverrideArguments='False'|NotSilent='False'|IgnoreDependencies='False'| AllowMultipleVersions='False'|AllowDowngrade='False'| ForceDependencies='False'|Information.PlatformType='Windows'| Information.PlatformVersion='10.0.10240.0'| Information.PlatformName='Windows'| Information.ChocolateyVersion='0.9.9.12'| Information.ChocolateyProductVersion='0.9.9.12'| Information.FullName='choco, Version=0.9.9.12, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|  Information.Is64Bit='True'|Information.IsInteractive='False'| Information.IsUserAdministrator='True'| Information.IsProcessElevated='True'|Features.AutoUninstaller='False'| Features.CheckSumFiles='True'|Features.FailOnAutoUninstaller='False'| ListCommand.LocalOnly='False'| ListCommand.IncludeRegistryPrograms='False'| UpgradeCommand.FailOnUnfound='False'| UpgradeCommand.FailOnNotInstalled='False'| UpgradeCommand.NotifyOnlyAvailableUpgrades='False'| NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'| SourceCommand.Priority='0'|FeatureCommand.Command='unknown'| ConfigCommand.Command='unknown'|PushCommand.TimeoutInSeconds='0'| PinCommand.Command='unknown'| _ Chocolatey:ChocolateyUninstallCommand - Normal Run Mode _ Uninstalling the following packages: win32-openssh Backing up existing win32-openssh prior to upgrade. Moving 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh'  to 'C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh' Attempting to create directory \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\win32-openssh.nupkg\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\win32-openssh.nupkg\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\win32-opensshInstall.zip.txt\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\win32-opensshInstall.zip.txt\". Attempting to create directory \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\tools\\chocolateyinstall.ps1\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyinstall.ps1\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\tools\\chocolateyuninstall.ps1\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\tools\\ntrights.ps1\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\ntrights.ps1\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\tools\\PsExec.exe\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\PsExec.exe\". Attempting to copy \"C:\\ProgramData\\chocolatey\\lib-bkp\\win32-openssh\\tools\\PsExec.exe.ignore\"  to \"C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\PsExec.exe.ignore\". Capturing package files in 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\win32-openssh.nupkg'   with checksum '51AB8B8F970FD459FF524F7AD4640692'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\win32-opensshInstall.zip.txt'   with checksum '825EAB86067650A2314D01E78A985276'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyinstall.ps1'   with checksum '169203398892AD6FB435237EAAE5E569'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1'   with checksum '1C9F4AC0D1589DC8121AE6B56AEE6C0E'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\ntrights.ps1'   with checksum '55C5F2A320EEBBFCE1F25410A214F5E3'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\PsExec.exe'   with checksum 'A7F7A0F74C8B48F1699858B3B6C11EDA'  Found 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\PsExec.exe.ignore'   with checksum 'D41D8CD98F00B204E9800998ECF8427E' [NuGet] Uninstalling 'win32-openssh 2016.05.15'.  win32-openssh v2016.05.15 Contents of 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1':  $ErrorActionPreference = 'Stop'; # stop on all errors  $packageName= 'win32-openssh' $toolsDir   = \"$(Split-Path -parent $MyInvocation.MyCommand.Definition)\"  $OSBits = Get-ProcessorBits  #On 64-bit, always favor 64-bit Program Files no matter what our execution is now (works back past XP / Server 2003) If ($env:ProgramFiles.contains('x86')) {   $PF = $env:ProgramFiles.replace(' (x86)','') } Else {   $PF = $env:ProgramFiles }  $filename = \"$toolsdir\\OpenSSH-Win$($OSBits).zip\" $TargetFolder = \"$PF\\OpenSSH-Win$($OSBits)\"  # Default the values $SSHServerFeature = $false $KeyBasedAuthenticationFeature = $false  $arguments = @{}; $packageParameters = $env:chocolateyPackageParameters;  # Now parse the packageParameters using good old regular expression if ($packageParameters) {     $match_pattern = \"\\/(?<option>([a-zA-Z]+)):(?<value>([`\"'])?([a-zA-Z0-9- _\\\\:\\.]+)([`\"'])?)|\\/(?<option>([a-zA-Z]+))\"     #\"     $option_name = 'option'     $value_name = 'value'      if ($packageParameters -match $match_pattern ){         $results = $packageParameters | Select-String $match_pattern -AllMatches         $results.matches | % {           $arguments.Add(               $_.Groups[$option_name].Value.Trim(),               $_.Groups[$value_name].Value.Trim())       }     }     else     {       throw \"Package Parameters were found but were invalid (REGEX Failure)\"     }      if ($arguments.ContainsKey(\"SSHServerFeature\")) {         Write-Host \"/SSHServerFeature - Uninstalling SSH Server Feature if Present.\"         $SSHServerFeature = $true     }      if ($arguments.ContainsKey(\"DeleteConfigAndServerKeys\")) {         Write-Host \"/DeleteConfigAndServerKeys - Removing SSH Config and Server Keys.\"         $DeleteConfigAndServerKeys = $true     }  } else {     Write-Debug \"No Package Parameters Passed in\"; }  $SSHServiceInstanceExistsAndIsOurs = ([bool]((Get-WmiObject win32_service | ?{$_.Name -ilike 'sshd'} | select -expand PathName) -ilike \"*$TargetFolder*\"))  If ($SSHServerFeature -AND (!$SSHServiceInstanceExistsAndIsOurs) -AND (Get-Service sshd -ErrorAction SilentlyContinue)) {   $ExistingSSHDInstancePath = (Get-WmiObject win32_service | ?{$_.Name -ilike 'sshd'} | select -expand PathName)   Throw \"You have requested that the SSHD service be uninstalled, but this system appears to have an instance of an SSHD service configured for another folder ($ExistingSSHDInstancePath).  Ignoring /SSHServerFeature\"   $SSHServerFeature = $False }  If ((!$SSHServerFeature) -AND $SSHServiceInstanceExistsAndIsOurs) {   Throw \"There is a configured instance of the SSHD service, please specify the /SSHServerFeature to confirm it is OK to UNINSTALL the SSHD service at this time.\" }   If ([bool](get-process ssh -erroraction silentlycontinue | where {$_.Path -ilike \"*$TargetPath*\"})) {   Throw \"It appears you have instances of ssh.exe (client) running from the folder this package installs to, please terminate them and try again.\" }  If ($SSHServiceInstanceExistsAndIsOurs -AND ([bool](Get-Service SSHD -ErrorAction SilentlyContinue | where {$_.Status -ieq 'Running'}))) { #Shutdown and unregister service for upgrade     Stop-Service SSHD -Force     Start-Sleep -seconds 3     If (([bool](Get-Service SSHD | where {$_.Status -ieq 'Running'})))     {       Throw \"Could not stop the SSHD service, please stop manually and retry this package.\"     }     Stop-Service ssh-agent -Force     Start-Sleep -seconds 3     If (([bool](Get-Service ssh-agent | where {$_.Status -ieq 'Running'})))     {       Throw \"Could not stop the ssh-agent service, please stop manually and retry this package.\"     } }  If ((get-item 'Registry::HKLM\\System\\CurrentControlSet\\Control\\Lsa').getvalue(\"authentication packages\") -contains 'msv1_0\\0ssh-lsa.dll') {   $KeyBasedAuthenticationFeatureINSTALLED = $True }  If ($SSHServiceInstanceExistsAndIsOurs -AND ([bool](Get-Service SSHD | where {$_.Status -ieq 'Running'}))) { #Shutdown and unregister service for upgrade     Stop-Service sshd -Force     If (([bool](Get-Service SSHD | where {$_.Status -ieq 'Running'})))     {       Throw \"Could not stop the SSHD service, please stop manually and retry this package.\"     }     Stop-Service ssh-agent -Force     Start-Sleep -seconds 3     If (([bool](Get-Service ssh-agent | where {$_.Status -ieq 'Running'})))     {       Throw \"Could not stop the ssh-agent service, please stop manually and retry this package.\"     } }  If ($SSHServiceInstanceExistsAndIsOurs -AND ($SSHServerFeature)) {   Stop-Service sshd   sc.exe delete sshd 1> null   Stop-Service ssh-agent   sc.exe delete ssh-agent 1> null }  If ($KeyBasedAuthenticationFeatureINSTALLED) {   If (Test-Path \"$env:windir\\sysnative\")   { #We are running in a 32-bit process under 64-bit Windows     $sys32dir = \"$env:windir\\sysnative\"   }   Else   { #We are on a 32-bit OS, or 64-bit proc on 64-bit OS     $sys32dir = \"$env:windir\\system32\"   }    $AuthpkgToRemove = 'msv1_0\\0ssh-lsa.dll'   foreach ($authpackage in (get-item 'Registry::HKLM\\System\\CurrentControlSet\\Control\\Lsa').getvalue(\"authentication packages\"))   {     If ($authpackage)     {       If ($authpackage -ine \"$AuthpkgToRemove\")       {         [string[]]$Newauthpackages += \"$authpackage\"       }     }   }   Set-ItemProperty \"HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\\" \"Authentication Packages\" $Newauthpackages   del \"$sys32dir\\ssh-lsa.dll\" -force }  #Don't remove config in case they reinstall. If ($DeleteConfigAndServerKeys) {     Write-Warning \"Removing all config and server keys as requested by /DeleteConfigAndServerKeys\"     Remove-Item \"$TargetFolder\\*\" -Recurse -Force } Else {   Remove-Item \"$TargetFolder\\*.*\" -include *.exe,*.dll,*.cmd -Recurse -Force   Write-Warning \"NOT REMOVED: Config files and any keys in `\"$TargetFolder`\" were NOT REMOVED - you must remove them manually or use the package uninstall parameter /DeleteConfigAndServerKeys.\" } netsh advfirewall firewall delete rule name='SSHD Port win32-openssh'  $PathToRemove = \"$TargetFolder\" foreach ($path in [Environment]::GetEnvironmentVariable(\"PATH\",\"Machine\").split(';')) {   If ($Path)   {     If (($path -ine \"$PathToRemove\") -AND ($path -ine \"$PathToRemove\\\"))     {       [string[]]$Newpath += \"$path\"     }   } } $AssembledNewPath = ($newpath -join(';')).trimend(';')  [Environment]::SetEnvironmentVariable(\"PATH\",$AssembledNewPath,\"Machine\")  Calling command ['\"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command \"[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyInstaller.psm1'; & 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyScriptRunner.ps1' -packageScript 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1' -installArguments '' -packageParameters ''\"']  DEBUG: Posh version is 5.0.10240.16384  DEBUG: Loading community extensions  VERBOSE: Exporting function 'Get-BinRoot'.  VERBOSE: Exporting function 'Get-ChecksumValid'.  VERBOSE: Exporting function 'Get-ChocolateyUnzip'.  VERBOSE: Exporting function 'Get-ChocolateyWebFile'.  VERBOSE: Exporting function 'Get-EnvironmentVariable'.  VERBOSE: Exporting function 'Get-EnvironmentVariableNames'.  VERBOSE: Exporting function 'Get-FtpFile'.  VERBOSE: Exporting function 'Get-ProcessorBits'.  VERBOSE: Exporting function 'Get-UACEnabled'.  VERBOSE: Exporting function 'Get-VirusCheckValid'.  VERBOSE: Exporting function 'Get-WebFile'.  VERBOSE: Exporting function 'Get-WebHeaders'.  VERBOSE: Exporting function 'Install-BinFile'.  VERBOSE: Exporting function 'Install-ChocolateyDesktopLink'.  VERBOSE: Exporting function 'Install-ChocolateyEnvironmentVariable'.  VERBOSE: Exporting function 'Install-ChocolateyExplorerMenuItem'.  VERBOSE: Exporting function 'Install-ChocolateyFileAssociation'.  VERBOSE: Exporting function 'Install-ChocolateyInstallPackage'.  VERBOSE: Exporting function 'Install-ChocolateyPackage'.  VERBOSE: Exporting function 'Install-ChocolateyPath'.  VERBOSE: Exporting function 'Install-ChocolateyPinnedTaskBarItem'.  VERBOSE: Exporting function 'Install-ChocolateyPowershellCommand'.  VERBOSE: Exporting function 'Install-ChocolateyShortcut'.  VERBOSE: Exporting function 'Install-ChocolateyVsixPackage'.  VERBOSE: Exporting function 'Install-Vsix'.  VERBOSE: Exporting function 'Install-ChocolateyZipPackage'.  VERBOSE: Exporting function 'Set-EnvironmentVariable'.  VERBOSE: Exporting function 'Start-ChocolateyProcessAsAdmin'.  VERBOSE: Exporting function 'Test-ProcessAdminRights'.  VERBOSE: Exporting function 'Uninstall-BinFile'.  VERBOSE: Exporting function 'Uninstall-ChocolateyPackage'.  VERBOSE: Exporting function 'UnInstall-ChocolateyZipPackage'.  VERBOSE: Exporting function 'Update-SessionEnvironment'.  VERBOSE: Exporting function 'Write-ChocolateyFailure'.  VERBOSE: Exporting function 'Write-ChocolateySuccess'.  VERBOSE: Exporting function 'Write-FileUpdateLog'.  VERBOSE: Exporting alias 'Generate-BinFile'.  VERBOSE: Exporting alias 'Add-BinFile'.  VERBOSE: Exporting alias 'Remove-BinFile'.  DEBUG: Running 'Get-ProcessorBits'  There is a configured instance of the SSHD service, please specify the /SSHServerFeature to confirm it is OK to   UNINSTALL the SSHD service at this time.  At C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1:74 char:3  +   Throw \"There is a configured instance of the SSHD service, please s ...  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : OperationStopped: (There is a conf...e at this time.:String) [], RuntimeException      + FullyQualifiedErrorId : There is a configured instance of the SSHD service, please specify the /SSHServerFeature       to confirm it is OK to UNINSTALL the SSHD service at this time. Command ['\"C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command \"[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyInstaller.psm1'; & 'C:\\ProgramData\\chocolatey\\helpers\\chocolateyScriptRunner.ps1' -packageScript 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1' -installArguments '' -packageParameters ''\"'] exited with '1' Calling command ['\"shutdown\" /a'] Command ['\"shutdown\" /a'] exited with '1116' win32-openssh uninstall not successful. Error while running 'C:\\ProgramData\\chocolatey\\lib\\win32-openssh\\tools\\chocolateyuninstall.ps1'.  See log for details. win32-openssh not uninstalled. An error occurred during uninstall:  win32-openssh uninstall not successful.  Chocolatey uninstalled 0/1 packages. 1 packages failed.  See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log). Failures  - win32-openssh Exiting with 1", "failed": true, "msg": "Error uninstalling win32-openssh"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @OpenSshWin32Choco.retry

PLAY RECAP *********************************************************************
logosports20               : ok=1    changed=0    unreachable=0    failed=1   

```

after:

```
tim@ansible:~/ansible-work$ ansible-playbook OpenSshWin32Choco.yml

PLAY [logosportsdesktops] ******************************************************

TASK [setup] *******************************************************************
ok: [logosports20]

TASK [Install win32-openssh] ***************************************************
changed: [logosports20]

PLAY RECAP *********************************************************************
logosports20               : ok=2    changed=1    unreachable=0    failed=0   

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @tim-seoss. To the current maintainers, @smadam813 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by smadam813** [comment]
Change works and this is a valuable feature!  Thanks @tim-seoss

shipit

**Comment by gregdek** [comment]
Thanks again to @tim-seoss for this PR, and thanks @smadam813 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Got a shipit. Shipping it.

**Pull request merged**
