### PR TITLE
Do not use a default value for -n parameter, fix #1400

### LINKED ISSUE #1400: rabbitmq_user module inserts "node" parameter even when it was not given
rabbitmq_user tries to run 

```
/usr/sbin/rabbitmqctl -q -n rabbit list_users
```

even, when there was no node parameter defined.

The correct behavior would be:

```
/usr/sbin/rabbitmqctl -q list_users
```

The difference is that the later works on rabbit@local but the previos does not. So if there's a parameter, and it does not have a value, the correct method would be not to give that parameter to the underlying process with a default but let it handle the missing (optional!) parameter the way it was intended.

effect:

failed: [local] => (item=rabbitmq_user_remove) => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit list_users", "failed": true, "item": "rabbitmq_user_remove", "rc": 2}
stderr: Error: unable to connect to node rabbit@local: nodedown
# DIAGNOSTICS

attempted to contact: [rabbit@local]

rabbit@local:
- connected to epmd (port 4369) on local
- epmd reports node 'rabbit' running on port 25672
- TCP connection succeeded but Erlang distribution failed
- suggestion: hostname mismatch?
- suggestion: is the cookie set correctly?
- suggestion: is the Erlang distribution using TLS?

rabbitmq_user runs the following command, when I'm trying to remove the guest:

but the simpler command works fine:

```
$ sudo /usr/sbin/rabbitmqctl -q list_users
guest   [administrator]
```

Of course I could work around this with setting the node parameter, but that depends on the hostname, in this case:

```
$ sudo /usr/sbin/rabbitmqctl -q -n rabbit@develbox list_users
guest   [administrator]
```

So if you don't have information, don't give a bad default to a not necessary (optional) parameter, or if its very-very neccessary this case you should use rabbit@hostname with the current hosts name.

### PR DESCRIPTION
**Pull request by mscherer**
fixes #1400

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @mscherer. @chrishoffman please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@chrishoffman This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by chrishoffman** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @chrishoffman for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
so the docs mention that the default node is 'rabbit' which was also the case in the spec, any reason for this change? the original bug seems only related to passing an empty node.

**Comment by gregdek** [comment]
@mscherer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by ClementGautier** [comment]
Hi, actually I am facing this issue too and would like this changes to be merged.

@bcoca I just did a simple install using apt package for rabbitmq-server. When I try to use rabbitmq_user just after it I face this issue.

**Comment by gregdek** [comment]
@mscherer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by mscherer** [comment]
I am not a rabbitmq specialist, I just made the patch to fix the bug according to the request of the reporter. It seems that -n rabbit is not working in some case (ie, it should be rabbit@thehostname, so I skip it, but that's also why I would like to get a test from the reporter.

**Comment by gregdek** [comment]
@mscherer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@mscherer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mscherer** [comment]
I am not sure what action I should do, nor what info I should provides.

**Comment by gregdek** [comment]
So we got a "shipit" from the maintainer originally, was then kicked back to needs_revision by a member of the core team, and then subsequently @ClementGautier said "this module doesn't work without this change, please merge it".

I know we would like a test from original reporter @Petrox but in the absence of that, given the comment from @ClementGautier, I'm putting this one back into shipit.

**Comment by Petrox** [comment]
Sorry, I'm not available currently to test this fix, but thank you for the effort. :)

:tada:

**Pull request merged**
