### PR TITLE
Windows Server DNS A Record (Add and Remove)

### PR DESCRIPTION
**Pull request by teochenglim**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

Windows Server DNS A Record (Add and Remove)
##### ANSIBLE VERSION

```
devel
```
##### SUMMARY

To add/remove Windows DNS A Record

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @teochenglim for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cggruszka** [comment]
1) If ptr is specified as `ptr: true`, an error occurs:

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +
> 
> ```
> fatal: [labserver]: FAILED! => {"changed": false, "failed": true, "msg": "Method invocation failed because [System.Boolean] does not contain a method named 'ToLower'."}
> ```

Changing my playbook to `ptr: "true"` worked around the issue.

2) windows/win_dns_arecord.py contains references to `win_dns_a`.  Should they be changed to `win_dns_arecord`?

**Comment by teochenglim** [comment]
Hi Cggruszka,

Thanks for the comment. I think it is because I used "true" as string in the beginning and later realize that it is a Boolean. Will update that and please wait for my next update.

Cheers,
Cheng Lim

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by teochenglim** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @teochenglim for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by angystardust** [comment]
@teochenglim Thank you for this module: it's very useful.
@gregdek why this PR wasn't moved to the main ansible/ansible repo?

**Comment by jhawkesworth** [comment]
@angrystardust  - PRs have to be moved by the person who submitted the PR unfortunately.  I believe this is just because of the way github works.  There is an automated tool for moving PRs though.  There is more information here: https://docs.ansible.com/ansible/dev_guide/repomerge.html

One of the most useful things that can help get a module merged is knowing that other people (not just the submitter of the PR) have tested it, so please comment on any modules you have tested as it helps the maintainers get confident that changes and additions should get merged.

**Pull request closed without merging**
