### PR TITLE
Adds bigip_gtm_facts module

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

network/f5/bigip_gtm_facts.py
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This patch adds support for querying the GTM(DNS) facts from a
BIG-IP. This completes a previous PR that was requested but not
finished.

Tests for this module can be found here

https://github.com/F5Networks/f5-ansible/blob/master/roles/bigip_gtm_facts/tasks/main.yaml

Platforms this was tested on are

11.6.0
12.1.0 HF1

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
lgtm

shipit

**Comment by caphrim007** [comment]
@gundalow

**Comment by gregdek** [comment]
Thanks again to @caphrim007 for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Merged to `devel` aka `2.3`

Thanks :)

**Comment by perzizzle** [comment]
@caphrim007 Is there an effort to re-write all the F5 modules to no longer use bigsuds?

**Comment by caphrim007** [comment]
@perzizzle yes

**Pull request merged**
