### PR TITLE
Adds support for setting an F5 virtual server's "source address translation" policy to a specific SNAT pool

### PR DESCRIPTION
**Pull request by Rylon**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME
- bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

Currently the `bigip_virtual_server` module supports only two options for Source Address Translation - `None` or `Automap`. This pull request adds support for enabling SNAT with a specific SNAT Pool.

You would use it like so:

```
- name: Add virtual server
  bigip_virtual_server:
      server: lb.mydomain.net
      user: admin
      password: secret
      state: present
      partition: MyPartition
      name: myvirtualserver
      destination: "{{ ansible_default_ipv4['address'] }}"
      port: 443
      pool: "{{ mypool }}"
      snat: /Common/snat_pool_1
      description: Test Virtual Server
      all_profiles:
          - http
          - clientssl
      enabled_vlans:
          - /Common/vlan2
  delegate_to: localhost
```

If `None` or `Automap` is specified instead, it continues to work as it did before.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Rylon. To the current maintainers, @mhite, @caphrim007, @Etienne-Carriere please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by caphrim007 — COMMENTED** [review]
Under review

**Comment by caphrim007** [comment]
@Rylon can you note the repo below for future reference.

https://github.com/F5Networks/f5-ansible

Its where I collect functional tests and do out-of-band code changes before merging upstream.

**Comment by Rylon** [comment]
@caphrim007 hi! Yeah I spotted that repo when I was looking at opening the initial PR, but it looked like that repo was downstream of this one, so I decided to open the PR here. I can re-submit it there if that's beneficial?

**Comment by caphrim007** [comment]
@Rylon it's ok. that one or this one is fine with me. I sync them when an upstream merge happens. We can work this PR here

**Comment by Rylon** [comment]
Ah cool, sounds good @caphrim007 🙂

**Comment by caphrim007** [comment]
lgtm. verified with tests here

https://github.com/F5Networks/f5-ansible/blob/master/roles/bigip_virtual_server/tasks/pr-3158.yaml

shipit

**Comment by gregdek** [comment]
Thanks again to @Rylon for this PR, and thanks @mhite, @caphrim007, @Etienne-Carriere for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Rylon** [comment]
That's great, thanks everyone! 👍

**Comment by caphrim007** [comment]
@gundalow

**Comment by gundalow** [comment]
Merged

**Pull request merged**
