### PR TITLE
pkg5 failed if package is installed #932

### PR DESCRIPTION
**Pull request by Steffeng5**
Working solution for issue #932

### CODE REVIEW

**Comment by bcoca** [comment]
why not just remove the previous failing check and use pkginfo for all?

**Comment by bcoca** [comment]
cc @mavit

**Comment by Steffeng5** [comment]
Is pkginfo working for all types of packages or is it as buggy as pkg list?

**Comment by bcoca** [comment]
good question, as someone that has avoided Solaris for the past 10 yrs, I'm not the best to answer this

**Comment by Steffeng5** [comment]
Okay. I've tried sth. to get sure the code is with the double check: 

root@solaris:~# pkginfo motif
ERROR: information for "motif" was not found
root@solaris:~# pkg list -- motif
NAME (PUBLISHER)                                  VERSION                    IFO
library/motif                                     0.5.11-0.175.0.0.0.0.0     i--

Therefore we should retain both checks :sweat:

**Comment by bcoca** [comment]
So this made no sense to me and I looked at it deeper.

It seems we are mixing package managers here, pkginfo is part of SVR4 packaging and pkg is IPS packaging (which has it's own `pkg info` command).

The reason that it fails with one and succeeds with the other is because they are different package management systems with different package tracking, so a package appears in the one you installed it with. As such this PR is incorrect, pkg5 should not be tracking v4 packaging and viceversa.

**Comment by Steffeng5** [comment]
hm okay, mixing the packagemanagers is not so good. 

Another idea: 

pkg install returns rc = 4 if the package is installed but no update is required. 

root@solaris:~# pkg install SUNWfont-xorg-core
No updates necessary for this image.
root@solaris:~# echo $?
4

Maybe we should change the code to accept also rc 4 as "ok"?

**Comment by bcoca** [comment]
since we already check before trying to install, it is not needed (unless someone installs in the milliseconds between check and attempt to install.

**Comment by Steffeng5** [comment]
As you can see above or in my bugreport the check is not working for all packages starting with "SUNW" ;)

And interpret rc 4 No updates necessary as FAILED is in my opinion wrong.

**Comment by bcoca** [comment]
is that package installed using the SRV4 system?

**Comment by Steffeng5** [comment]
No, using pkg5 -> pkg install SUNWfont-xorg-core

**Comment by bcoca** [comment]
so this looks like a pkg bug, but i would accept a special case for rc == 4 that sets a  custom message and changed=False

**Comment by mavit** [comment]
The reason that `pkg list` doesn't show `SUNWfont-xorg-core` is because it technically isn't installed.  Because it has its `renamed` attribute set to `true`, `pkg install` will chase down and install its dependencies but skip the package itself.  See the manifest at http://pkg.oracle.com/solaris/release/manifest/0/SUNWfont-xorg-core%400.5.11%2C5.11-0.133%3A20101027T183825Z

So, I don't think running `pkginfo` to check for installed packages would hurt, but it wouldn't help in the case of package renames unrelated to SVR4 packages.

Agreed, treating rc 4 as not changed seems like the way to go.  @Steffeng5: will you prepare a pull request?  I think we need to do some testing to make sure this does the right thing when `state=installed` rather than `state=latest`, though.

That said, my advice is that if one wants the functionality provided by `SUNWfont-xorg-core`, it would be probably be best to run `pkg info -r SUNWfont-xorg-core`, observe that that functionality is now provided by `system/font/xorg/xorg-core`, and use `system/font/xorg/xorg-core` in your playbook instead.

**Comment by bcoca** [comment]
would passing `-r` to `pkg list` also work out this renaming? should we switch the test to `pkg info -r`? it seems that fixing the detection error is better than handling the outcome of it's failure.

**Comment by mavit** [comment]
I'm afraid not.  Here `-r` means, "display information about packages in the repositories", which doesn't help when checking for installed packages.

Presumably it would be possible to resolve these chains by calling the pkg Python API, but it looks pretty fiddly and low-level and I don't think it's supposed to be user-facing.

**Comment by bcoca** [comment]
_grumble_solaris_grumble_, ok, so it seems rc == 4 detection it is, at this point i would even take out the existing check as it is ineffective.

**Pull request closed without merging**
