### PR TITLE
Add os_group.py OpenStack module

### PR DESCRIPTION
**Pull request by Shrews**
Allows an admin (or privileged user) to manage Keystone v3
groups.

### CODE REVIEW

**Comment by Shrews** [comment]
Ping @emonty @j2sol

**Comment by gregdek** [comment]
Thanks @Shrews for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by omgjlk** [comment]
Tested here, CRUD. 

shipit

**Comment by emonty** [comment]
shipit

**Pull request merged**
