### PR TITLE
svc: Ensure python 2.5 compatibility

### PR DESCRIPTION
**Pull request by SkaveRat**
- eg. debian lenny

Ansible has python 2.5 as minimum version

### CODE REVIEW

**Comment by bcoca** [comment]
actually its 2.4, but this works for that also.

**Comment by jirutka** [comment]
> eg. debian lenny

@SkaveRat Security updates for Lenny have been discontinued as of February 6th, 2012. We have the year 2015 now, so why the hell are you arguing with Debian Lenny?

**Comment by SkaveRat** [comment]
not arguing that it's a good thing, just that there is some old python out there

**Comment by jirutka** [comment]
I’m sure that there’s also some Python 1.1 out there… So what?

**Comment by SkaveRat** [comment]
but ansible doesn't run on 1.1 - it runs on 2.4+

so this script should also be 2.4+

not even a big change, so I don't see your problem

**Pull request merged**
