### PR TITLE
New module to create amazon Virtual Private Gateways

### PR DESCRIPTION
**Pull request by MichaelBaydoun**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ecs_virtual_private_gateway
##### ANSIBLE VERSION

```
➜  amazon git:(ec2_aws_vpg) ansible --version
ansible 2.1.0 (devel 1ee6d489ab) last updated 2016/03/17 14:23:55 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 345d9cbca8) last updated 2016/03/17 14:24:02 (GMT -400)
  lib/ansible/modules/extras: (ec2_aws_vpg b90c798b52) last updated 2016/03/24 15:11:22 (GMT -400)
  config file = /home/iabaydma/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

New module to create amazon Virtual Private Gateways

A module to create Virtual Private Gateway's did not exists, so I wrote one

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-extras/1907)

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @MichaelBaydoun for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Thanks @MichaelBaydoun for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@MichaelBaydoun A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelBaydoun** [comment]
yes, I'm working on it.

**Comment by gregdek** [comment]
@MichaelBaydoun Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelBaydoun** [comment]
Closing this.  When I get a chance to clean up this module I'll open a new pull request.

**Pull request closed without merging**
