### PR TITLE
Adds coding conventions for the bigip-virtual-server module

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- bigip_virtual_server.py
##### ANSIBLE VERSION

```
2.1.0.0
```
##### SUMMARY

A number of coding conventions have been adopted for new F5 modules
that are in development. To ensure common usage across the modules,
this module needed to be updated to reflect those conventions.

No functional code changes were made.

### CODE REVIEW

**Comment by caphrim007** [comment]
build failed because of python 2.4 syntax error. F5 doesn't support python versions that old.

**Comment by gregdek** [comment]
Thanks @caphrim007 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
@gregdek what to do if F5's specific modules dont want to support python 2.4?

**Comment by caphrim007** [comment]
answering my own question. I see what to do. going to send another PR that updates the travis yml

**Comment by caphrim007** [comment]
@gregdek this should have an owner_pr label

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007, @Etienne-Carriere) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
shipit

**Comment by caphrim007** [comment]
passing tests available here

https://github.com/F5Networks/f5-ansible/blob/master/roles/__bigip_virtual_server/tasks/main.yaml

tested on 11.6.0 and 12.0.0

**Comment by gregdek** [comment]
Thanks @caphrim007. Since you are one of the maintainers (@mhite, @caphrim007, @Etienne-Carriere) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
LGTM, shipit

**Comment by caphrim007** [comment]
@resmo if you're feeling like an easy merge

**Pull request merged**
