### PR TITLE
add application to Package Types

### PR DESCRIPTION
**Pull request by jasonmader**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

packaging/os/zypper
##### Ansible Version:

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Summary:

Add support for the Zypper Package Type: "application"
Added to Zypper in OpenSUSE 13.2
##### Example:

```
- zypper: type=application
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jasonmader. @dirtyharrycallahan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jasonmader** [comment]
@alxgu, @andytom please consider reviewing this commit

**Comment by alxgu** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @jasonmader for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @jasonmader. To the current maintainers, @robinro please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@andytom 
This PR got included in #2108. Please check the change there works for you and then I would close this PR.

**Comment by jasonmader** [comment]
@robinro I just had a chance to test this with `type=patch` and had an issue when a repo signature verification failed:
```
"failed": true, "msg": "Zypper run command failed with return code 4.", "rc": 4
```
full text:
```
fatal: [grandizer.local]: FAILED! => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "search", "--type", "patch", "--match-exact", "--verbose", "--installed-only", "openSUSE-2016-38", "openSUSE-2016-106"], "failed": true, "msg": "Zypper run command failed with return code 4.", "rc": 4, "stderr": "", "stdout": "<?xml version='1.0'?>\n<stream>\n<prompt id=\"15\">\n<text>Signature verification failed for file &apos;repomd.xml&apos; from repository &apos;google-chrome&apos;.\nWarning: This might be caused by a malicious change in the file!\nContinuing might be risky. Continue anyway?</text>\n<option value=\"yes\" desc=\"\"/>\n<option default=\"1\" value=\"no\" desc=\"\"/>\n</prompt>\n<message type=\"error\">Repository &apos;google-chrome&apos; is invalid.\n[google-chrome|http://dl.google.com/linux/chrome/rpm/stable/x86_64] Valid metadata not found at specified URL\nPlease check if the URIs defined for this repository are pointing to a valid repository.\n</message>\n<message type=\"warning\">Skipping repository &apos;google-chrome&apos; because of the above error.</message>\n<message type=\"error\">Some of the repositories have not been refreshed because of an error.</message>\n\n<search-result version=\"0.0\">\n<solvable-list>\n<solvable status=\"installed\" name=\"openSUSE-2016-106\" kind=\"patch\" edition=\"1\" arch=\"noarch\" repository=\"update-oss\"/>\n<solvable status=\"installed\" name=\"openSUSE-2016-38\" kind=\"patch\" edition=\"1\" arch=\"noarch\" repository=\"update-oss\"/>\n</solvable-list>\n</search-result>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<prompt id=\"15\">", "<text>Signature verification failed for file &apos;repomd.xml&apos; from repository &apos;google-chrome&apos;.", "Warning: This might be caused by a malicious change in the file!", "Continuing might be risky. Continue anyway?</text>", "<option value=\"yes\" desc=\"\"/>", "<option default=\"1\" value=\"no\" desc=\"\"/>", "</prompt>", "<message type=\"error\">Repository &apos;google-chrome&apos; is invalid.", "[google-chrome|http://dl.google.com/linux/chrome/rpm/stable/x86_64] Valid metadata not found at specified URL", "Please check if the URIs defined for this repository are pointing to a valid repository.", "</message>", "<message type=\"warning\">Skipping repository &apos;google-chrome&apos; because of the above error.</message>", "<message type=\"error\">Some of the repositories have not been refreshed because of an error.</message>", "", "<search-result version=\"0.0\">", "<solvable-list>", "<solvable status=\"installed\" name=\"openSUSE-2016-106\" kind=\"patch\" edition=\"1\" arch=\"noarch\" repository=\"update-oss\"/>", "<solvable status=\"installed\" name=\"openSUSE-2016-38\" kind=\"patch\" edition=\"1\" arch=\"noarch\" repository=\"update-oss\"/>", "</solvable-list>", "</search-result>", "</stream>"]}
```

**Comment by andytom** [comment]
I think you want @jasonmader not me.

**Pull request closed without merging**
