### PR TITLE
Feature/tag elb

### PR DESCRIPTION
**Pull request by welex91**
Tag ELBs with boto 2. Uses a lot of core/cloud/amazon/ec2_tag code for consistent look and feel.

### CODE REVIEW

**Comment by jonhadfield** [comment]
@welex91 Hoping for this functionality to be added soon, so thought I'd respond with some very opinionated, but hopefully helpful, feedback:
- Why not integrate with ec2_elb_lb module?
- When declaring state as present it should set the tags to those defined, removing any not specified. It currently appends without removing existing which isn't the declarative behaviour I'd expect.
- When declaring state absent, I'd expect it to remove all tags from the elb. Maybe the only parameters should be the name of the load balancer and the tags param for the dict? In that case, if you want to remove tags you leave an empty value.
- Not sure of purpose of state 'list'? Why not just set a parameter called 'elb_tags' to contain the dict when calling module.exit_json so it can be accessed after Register?
- As recently pointed out to me by @joelthompson you can tidy up the module definition with [required_if](https://github.com/ansible/ansible-modules-core/search?utf8=%E2%9C%93&q=required_if). So if you are going to go with state: absent and require tags, then it saves the additional checks.

**Comment by welex91** [comment]
**@jonhadfield** Thanks for the feedback, here's my thinking:
- It's a standalone extras module right now, since I'm not sure whether the right place is ec2_elb_lb or ec2_tag. 
- the state logic is based on ec2_tag, I agree it is not quite declarative. Not sure what the right solution is here. The _list_ state is also from ec2_tag, my understanding is that it should go into ec2_elb_facts instead ?
- thanks for the pointer to required_if, I'll incorporate that.

**Comment by Constantin07** [comment]
I agree with @jonhadfield that it's better to integrate into ec2_elb_lb. There are other modules which have 'tags' option too.

**Comment by robynbergeron** [comment]
Thanks @welex91 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by welex91** [comment]
@jonhadfield and @Constantin07 : I'll add the list part to ec2_elb_facts and the present/absent parts to ec2_elb_lb. Thanks for the feedback.

**Comment by Constantin07** [comment]
Thanks @welex91. Meanwhile I went for AWS CLI equivalent:

```
- name: Tag ELB
  command: >
    aws elb add-tags --load-balancer-names "{{ elb_lb_res.elb.name }}"
    --tags "Key=Env,Value={{ env }}" "Key=Name,Value={{ elb.name }}"
    --region "{{ aws_region }}"
  tags: elb
```

**Pull request closed without merging**
