### PR TITLE
allow to specify versions with zypper

### LINKED ISSUE #2158: allow to specify version number when installing with zypper
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

packaging/os/zypper.py
##### ANSIBLE VERSION

2.2, devel
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

any Suse distro
##### SUMMARY

Allow to put version information in the package name and handle that correctly.
##### STEPS TO REPRODUCE

Things that should work:

```
- zypper: name=openssh>=6.6 state=present
- zypper: name=openssh=6.6 state=present
```

Allowed operators in zypper: `<`, `>`, `<=`, `>=`, `=`. Version should be `[0-9.-]*`
Tests for those are also needed.
##### EXPECTED RESULTS

The package should be installed under the given version restrictions. Output/diffs should handle the version info correctly and not put it as part of the package name.
##### ACTUAL RESULTS

Depending on the case this is broken. `state=absent` does not work with versions, the rest is not fully tested.

### PR DESCRIPTION
**Pull request by robinro**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

packaging/os/zypper.py
##### ANSIBLE VERSION

devel
##### SUMMARY

Allow version information to be added to package names
- fixes #2158
- handles version-specifiers (>,<,>=,<=,=) correctly
- adds option "oldpackge", which is passed to zypper
  - this is implied as soon as a version is specified
  - it can be used independently to allow downgrades coming from repos
- also add `__main__` check
- when a version is given, the package will always be updated within the allowed range, even when `state=present`

### CODE REVIEW

**Comment by robinro** [comment]
Currently if a version is specified it updates the package also if `state=present`. This is because all version checking is left to zypper, which updates if possible. I would document this and leave it.

The alternative is to do the version checking in the module instead, which would add quite a bit of code and in the end would introduce bugs, because zypper can deal with alternative names and capabilities, which is impossible to implement without looking into all packages.

Opinions on that?

**Comment by robinro** [comment]
@agx @alxgu 
If you have time, please have a look and tell me what you think of this PR.

**Comment by agx** [comment]
Looks o.k. to me (without having tested it). It might be worth extending the integration tests test/integration/roles/test_zypper/ to verify the new behaviours.

**Comment by gregdek** [comment]
This PR is a work-in-progress. @robinro, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by gregdek** [comment]
Thanks @robinro for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@agx I'm unsure how to best add version info to the integration tests. I already dislike that the tests use external repositories and would prefer some local repo setup with custom packages, but this is a lot more work.

**Comment by robinro** [comment]
The changes are now squashed and rebased and ready to get merged.
shipit

**Comment by agx** [comment]
Hi,
On Sat, Jul 16, 2016 at 07:53:21AM -0700, Robin Roth wrote:

> @agx I'm unsure how to best add version info to the integration tests. I already dislike that the tests use external repositories and would prefer some local repo setup with custom packages, but this is a lot more work.

Having a separate repo that has stable data (or even better gets set up
during the tests) would indeed be much nicer but at least relations like
<= or > could be tests already since I don't expect the used repo to
have lower versions than currently.

**Comment by gregdek** [comment]
Thanks @robinro. Since you are one of the maintainers (@robinro) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
