### PR TITLE
Added module win_package (was #618)

### PR DESCRIPTION
**Pull request by trondhindenes**
This was #618 but I screwed up my rebase so resubmitting. param "ensure" is replaced by "state" (with "ensure" stil being a valid alias)

### CODE REVIEW

**Comment by bcoca** [comment]
ping @jhawkesworth , @cchurch

**Comment by jhawkesworth** [comment]
Just noticed I had been testing earlier version of this - which works fine, but want to check with latest version (and on v2).  So not forgotten about but just want to test a bit more before give thumbs up.

**Comment by trondhindenes** [comment]
@jhawkesworth any update on your testing? It should be pretty much exactly the same code you've been testing earlier,  with the exception of the "state" param.

**Comment by jhawkesworth** [comment]
finally got back to retesting this today - sorry for the long delay.  I'm +1 so please
shipit
@gregdek / @bcoca

**Comment by gregdek** [comment]
Thanks @jhawkesworth for the +1 and @trondhindenes for the module code. Marking for inclusion.

**Comment by gregdek** [comment]
cc: @ansible/core for merging

**Comment by tksarah** [comment]
@trondhindenes Hello , Is this modules included in the next release(v2.0)? If it is so, I think you might need to be modified to "version_added:" for .py file.

**Comment by trondhindenes** [comment]
Good call. It's been sitting in PR for awhile. Greg, what do you think is the correct version? Should I state 1.9 or 2.0?

**Comment by tksarah** [comment]
@trondhindenes  Thank you
I found some issues. #984

**Pull request merged**
