### PR TITLE
add zabbix proxy support to zabbix_host

### PR DESCRIPTION
**Pull request by eikef**

### CODE REVIEW

**Comment by resmo** [comment]
+1

**Comment by gregdek** [comment]
@cove Please review this PR; if you +1, we will merge

**Comment by bcoca** [comment]
needs rebase

**Comment by cove** [comment]
+1, rebase aside

**Comment by gregdek** [comment]
@eikef if you can rebase, we have a +1 and can merge.

**Comment by eikef** [comment]
Will look at it this weekend, swamped until then :-)

**Comment by eikef** [comment]
should be ready now. :-)

**Comment by gregdek** [comment]
Merged -- thanks @eikef and thanks @cove for the review.

**Comment by bcoca** [comment]
~~missing version_added for the new option~~

yep, sorry, missed the part of this being a new module in 2.0 ... ignore that comment

**Comment by eikef** [comment]
Not really required IMHO since this module has not been in a released version; the module itself carries that tag for the (as yet unreleased) 2.0 version.

**Pull request merged**
