### PR TITLE
New module ec2_lc_facts

### PR DESCRIPTION
**Pull request by psykotox**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_lc_facts
##### ANSIBLE VERSION

Target: Ansible 2.2
##### SUMMARY

A new module to gather facts about AWS Autoscaling Launch Configurations

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @psykotox for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by psykotox** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @psykotox for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @psykotox for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by psykotox** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @psykotox for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fmachen** [comment]
shipit

**Comment by tbaranes** [comment]
shipit

**Comment by gundalow** [comment]
I've added bot_broken as I would have expected the shipit label to be added after the two reviews on 25th July

**Comment by resmo** [comment]
Thanks!

**Pull request merged**
