### PR TITLE
Fix gitlab validate_certs type declaration

### PR DESCRIPTION
**Pull request by ginkel**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

gitlab_*
##### ANSIBLE VERSION

```
ansible 2.1.0.0 (detached HEAD b599477242) last updated 2016/06/02 23:26:42 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 04a871d007) last updated 2016/06/02 23:26:55 (GMT +200)
  lib/ansible/modules/extras: (fix-gitlab-validate_certs e27d1e66ac) last updated 2016/06/02 23:36:43 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Using the gitlab_\* modules in Ansible 2.1.0.0 results in the following error:

```
implementation error: unknown type <type 'bool'> requested for validate_certs
```

This PR fixes that issue by bringing the declaration in line with parameter declaration documented in the module development guidelines (quoted type).

Before:

```
ansible-playbook -i hosts/hetzner playbooks/gitlab-training.yml

PLAY [GitLab Training] *********************************************************

TASK [setup] *******************************************************************
ok: [training.vm.tgbyte.net]

TASK [training/gitlab : create GitLab users] ***********************************
failed: [training.vm.tgbyte.net -> localhost] (item=1) => {"failed": true, "item": 1, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=2) => {"failed": true, "item": 2, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=3) => {"failed": true, "item": 3, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=4) => {"failed": true, "item": 4, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=5) => {"failed": true, "item": 5, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=6) => {"failed": true, "item": 6, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=7) => {"failed": true, "item": 7, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=8) => {"failed": true, "item": 8, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=9) => {"failed": true, "item": 9, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=10) => {"failed": true, "item": 10, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=11) => {"failed": true, "item": 11, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}
failed: [training.vm.tgbyte.net -> localhost] (item=12) => {"failed": true, "item": 12, "msg": "implementation error: unknown type <type 'bool'> requested for validate_certs"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @playbooks/gitlab-training.retry

PLAY RECAP *********************************************************************
training.vm.tgbyte.net     : ok=1    changed=0    unreachable=0    failed=1   
```

After:

```
ansible-playbook -i hosts/hetzner playbooks/gitlab-training.yml

PLAY [GitLab Training] *********************************************************

TASK [setup] *******************************************************************
ok: [training.vm.tgbyte.net]

TASK [training/gitlab : create GitLab users] ***********************************
changed: [training.vm.tgbyte.net -> localhost] => (item=1)
changed: [training.vm.tgbyte.net -> localhost] => (item=2)
changed: [training.vm.tgbyte.net -> localhost] => (item=3)
changed: [training.vm.tgbyte.net -> localhost] => (item=4)
changed: [training.vm.tgbyte.net -> localhost] => (item=5)
changed: [training.vm.tgbyte.net -> localhost] => (item=6)
changed: [training.vm.tgbyte.net -> localhost] => (item=7)
changed: [training.vm.tgbyte.net -> localhost] => (item=8)
changed: [training.vm.tgbyte.net -> localhost] => (item=9)
changed: [training.vm.tgbyte.net -> localhost] => (item=10)
changed: [training.vm.tgbyte.net -> localhost] => (item=11)
changed: [training.vm.tgbyte.net -> localhost] => (item=12)

PLAY RECAP *********************************************************************
training.vm.tgbyte.net     : ok=2    changed=1    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ginkel. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
thanks for this fix. could you make the pr to devel, we'll cherry-pick it to 2.1 afterwards.

**Comment by ginkel** [comment]
@resmo Done. Should I close this PR or would you like to keep it open as a backport reminder?

**Comment by resmo** [comment]
Thanks again.

**Comment by ginkel** [comment]
You're welcome! :-)

**Pull request merged**
