### PR TITLE
Added update_catalog and some error handling

### PR DESCRIPTION
**Pull request by dermute**
Hello,
pkgutil doesn't update it's catalog from the repository by default. Adding the option 'update_catalog' allows to force an update before installing oder upgrading an package. But it is not enabled by default, to keep the default behaviour of pkgutil.
Moreover I added some errorhandling.

### CODE REVIEW

**Comment by dermute** [comment]
Any hints why the continuous-integration is failing? It works in my environment.

**Comment by bcoca** [comment]
we test in multiple environments and this fails in one of them, just remove the inline if and do something like this:

```
if err:
  msg = err
else:
   msg = out
module.fail_json(msg=msg)
```

**Comment by robynbergeron** [comment]
Thanks @dermute. Since you are a maintainer of this module, we are marking this PR for inclusion.

**Comment by dermute** [comment]
I will fix the bug next week.

**Pull request merged**
