### PR TITLE
return tzfile value from _verify_timezone

### LINKED ISSUE #3335: Timezone: global name 'tzfile' is not defined
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
timezone

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
Host: Arch
Client: CentOS 6.8

##### SUMMARY
As of https://github.com/ansible/ansible-modules-extras/commit/e29584ad70d2f4e0a8ef02781d7bc7e977ff0e69 timezone is broken again. If I go back to https://github.com/ansible/ansible-modules-extras/commit/df35d324d62e6034ab86db0fb4a56d3ca122d4b2 it works fine again.

##### STEPS TO REPRODUCE
Run playbook with a timezone defined.

##### EXPECTED RESULTS
Timezone set properly, no errors.

##### ACTUAL RESULTS
Receive the fatal error below.

```
fatal: [vagrant-noc-server]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.50.3 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 462, in <module>\r\n    main()\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 435, in main\r\n    tz = Timezone(module)\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 306, in __init__\r\n    self.update_timezone += ' %s /etc/localtime' % tzfile\r\nNameError: global name 'tzfile' is not defined\r\n", "msg": "MODULE FAILURE"}
```

### PR DESCRIPTION
**Pull request by ssummer3**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
timezone

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
tzdata is undefined at line 306 in SystemdTimezone.init

Modified _verify_timezone to return verified tzfile, and SystemdTimezone.init to create
a local tzfile variable.

Fixes #3335 

```
tzfile is undefined in NosystemdTimezone.__init__; create local tzfile variable by using _verify_timezone() to return existing file
```

### CODE REVIEW

**Comment by bcoca** [comment]
#3336

**Comment by tmshn** [comment]
Both this pr and #3336 looks fine 👍 (Merging either of them will be ok)

**Comment by gregdek** [comment]
Thanks @ssummer3. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by coreaut** [comment]
Hi @ssummer3,
sorry for reopening but the fix results now in another error message:

```
FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to somehost closed.
", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_03WOeD/ansible_module_timezone.py\", line 464, in <module>
    main()
  File \"/tmp/ansible_03WOeD/ansible_module_timezone.py\", line 440, in main
    tz.check(phase='before')
  File \"/tmp/ansible_03WOeD/ansible_module_timezone.py\", line 185, in check
    value[phase] = self.get(key, phase)
  File \"/tmp/ansible_03WOeD/ansible_module_timezone.py\", line 381, in get
    file = open(filename, mode='r')\r\nTypeError: coercing to Unicode: need string or buffer, tuple found
", "msg": "MODULE FAILURE"}
```
In this case the variable filename is `('/etc/timezone',)`

This happened on ubuntu 14.04 with the following ansible task:
```
  - name: set timezone
    timezone:
      name: "Europe/Vienna"
    notify: restart cron
```

Tested with Ansible 2.2.0.0

Tested with the timezone.py from 8885e0c

Because there is no official release with this fix, I wrote it here. Hope that's ok.

**Comment by tmshn** [comment]
@Nebelwolf Hey, thanks for reporting!
But the bug you encountered seems nothing to do with this PR.
I made the patch that may fix this, so could you try this? 👉 #3572
(Give me comments on that PR, not this 😉 )

**Review by mhbrown — COMMENTED** [review]
Nice! @bcoca do you know if this was left out of Ansible 2.3.0? I'm noticing issues using the timezone module with that version...
```
Thursday 15 December 2016  23:36:45 +0000 (0:00:00.393)       0:00:04.326 ***** 
fatal: [XX.XX.XX.XXX]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to XX.XX.XX.XXX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_PQlvnM/ansible_module_timezone.py\", line 467, in <module>\r\n    main()\r\n  File \"/tmp/ansible_PQlvnM/ansible_module_timezone.py\", line 440, in main\r\n    tz = Timezone(module)\r\n  File \"/tmp/ansible_PQlvnM/ansible_module_timezone.py\", line 311, in __init__\r\n    self.update_timezone += ' %s /etc/localtime' % tzfile\r\nNameError: global name 'tzfile' is not defined\r\n", "msg": "MODULE FAILURE"}
```

**Pull request merged**
