### PR TITLE
Fixes for ecs_taskdefinition

### PR DESCRIPTION
**Pull request by steynovich**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

ecs_taskdefinition module
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

```
FIX: fix for not creating new task definition when a revision is given
FIX: return taskdefinition when task is created
FIX: more flexible passing variables to allow faster adoption of new features
FIX: some generic code styling
FEATURE: support task IAM Role
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @steynovich. To the current maintainers, @Java1Guy, @rmorlok please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @steynovich for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by steynovich** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @steynovich. To the current maintainers, @Java1Guy, @rmorlok please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @steynovich for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rmorlok** [comment]
Hey @steynovich #2357 has merged that fixed a lot of problems with that module. It looks like you have support for the IAM role in here in addition to fixes that may overlap with what went in. If you take a look at what's changed, rebase, we can look at getting that in.

**Comment by gregdek** [comment]
@steynovich A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
