### PR TITLE
Use helper function for new module and rename

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

aws_mfa_devices renamed to iam_mfa_device_facts
##### ANSIBLE VERSION

2.2
##### SUMMARY

The module 'aws_mfa_devices' was merged very quickly before I had a chance to review.

I have made the following changes:

Renamed the module to iam_mfa_device_facts - the module uses a boto3 call list_mfa_devices.  Ansible usually name any AWS modules using a list call as a _facts module.  This helps decrease ambiguity.  As this module isn't in a release yet this should be OK as is.

I utilized the helper function camel_dict_to_snake_dict to keep the code DRY and also slightly changed the return value - using mfa_devices rather than devices as we want to try and stay as true to boto as we can.

I also improved the boto3 exception handling as per the guidelines, some minor pep8 changes and changed the boto3 message to the message used by most other modules for consistency sake.

Mentioning @gundalow and @dorianj as original reviewers

Also want to mention @gregdek - this module got merged very fast.  Perhaps there should be a bit of a time limit to allow everyone to review.  I must admit, i don't get the change to review the repo for new PRs every day or even every couple of days.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gregdek** [comment]
Thanks @wimnat for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
ping @pwnall

**Comment by wimnat** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @wimnat for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
@pwnall - please could you review this one when you get a chance?

**Comment by gregdek** [comment]
@ansible/core This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nitzmahone** [comment]
LGTM, thanks for the updates!

**Comment by pwnall** [comment]
Sorry I sat on this without doing anything. I didn't feel qualified to make a decision on the name change. Thank you very much @nitzmahone for the decision, and @wimnat for the patience!

**Comment by nitzmahone** [comment]
@pwnall: No worries- in the future, feel free to just weigh in with a "no opinion" or ¯_(ツ)_/¯ if you find yourself in that boat. :)

**Pull request merged**
