### PR TITLE
Basic ability to set masquerade options from ansible, according to current code design/layout (mostly)

### PR DESCRIPTION
**Pull request by codehopper-uk**
I needed to be able to set masquerade Boolean from my ansible playbook, which didn't exist. Here it is if it's useful...

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @codehopper-uk for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by codehopper-uk** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @codehopper-uk. To the current maintainers, @maxamillion please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by maxamillion** [comment]
:+1: shipit

**Comment by gregdek** [comment]
Thanks again to @codehopper-uk for this PR, and thanks @maxamillion for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
