### PR TITLE
Update noop and debug processing for puppet

### PR DESCRIPTION
**Pull request by emonty**
Detailed-exitcodes during noop break things. Also, logdest can be a
file.

This is a sync with some recent changes encountered from openstack-infra/ansible-role-puppet.

### CODE REVIEW

**Review by cboylan — COMMENTED** [review]
Yup this looks good. The white space is all shifted to happen at the beginning of the flags which was inconsistent before.

**Comment by gregdek** [comment]
Thanks again to @emonty. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @nibalizer) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nibalizer** [comment]
Looks like the upstream ref is https://review.openstack.org/#/c/371774/

**Review by nibalizer — APPROVED** [review]
:shipit: looks good to me

**Pull request closed without merging**
