### PR TITLE
asa_template is now deprecated

### PR DESCRIPTION
**Pull request by gundalow**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

asa_template

### CODE REVIEW

**Comment by bcoca** [comment]
since this is added in 2.2 .. why not just delete it?

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by gundalow** [comment]
Maintainers added for `extra/network/asa` in https://github.com/ansible/ansibullbot/commit/c3da5050b9e4c9199d9d83ed12493c182de9cdca

**Comment by gregdek** [comment]
Thanks again to @gundalow. This module is going into community review.

We notice that you are one of the maintainers (@gundalow, @privateip) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Review by Qalthos — APPROVED** [review]

**Pull request merged**
