### PR TITLE
Initial Commit for Infinidat Ansible Modules

### PR DESCRIPTION
**Pull request by GR360RY**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

- infini_export
- infini_export_client
- infini_fs
- infini_host
- infini_pool
- infini_vol
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 7b2f15453d) last updated 2016/10/08 22:54:07 (GMT +300)
  lib/ansible/modules/core: (detached HEAD ae6992bf8c) last updated 2016/09/14 11:06:17 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD afd0b23836) last updated 2016/09/14 11:06:22 (GMT +300)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Modules for managing Infinidat Infinibox storage. Separate modules to create/delete/modify pools, volumes, filesystems, hosts and exports.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @GR360RY for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GR360RY** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @GR360RY for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @GR360RY for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GR360RY** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @GR360RY for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @GR360RY for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@GR360RY A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@GR360RY Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
