### PR TITLE
removing | from description so docs render properly in RTD

### PR DESCRIPTION
**Pull request by nateprewitt**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

timezone.py
##### ANSIBLE VERSION

devel
##### SUMMARY

The timezone module was added a couple of weeks ago but for some reason `- |` was used at the beginning of each description string which causes Sphinx to render incorrect html as seen [here](https://docs.ansible.com/ansible/timezone_module.html)

This fixes the issue raised in ansible/ansible#16624 by removing the seemingly unnecessary pipe character.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by nateprewitt** [comment]
Is it @tmshn we need a "shipit" from?

**Comment by tmshn** [comment]
Oops sorry for insufficient test around webdocs, it LGTM.
I qualify your modification as shipit, if I'm authorized to do it.

Actually, I didn't know that we don't need `|` (so called [block style](http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines)) to express multi line strings on YAML. Also, I didn't know that Sphinx fails to parse if table cells contain line breaks...(is this a bug of Sphinx???)

Just FYI, here's the difference of what is produced:

<details>

#### Block style (with `|`)

This is the old version I wrote.

**Source YAML**

``` yaml
options:
  name:
    description:
      - Name of the timezone for the system clock.
        Default is to keep current setting.
    required: false
  hwclock:
    description:
      - Whether the hardware clock is in UTC or in local timezone.
        Default is to keep current setting.
        Note that this option is recommended not to change and may fail
        to configure, especially on virtual environments such as AWS.
    required: false
    aliases: ['rtc']
```

**Obtained RST**
Although this looks okay as HTML...

``` html
    <table border=1 cellpadding=4>
    <tr>
    <th class="head">parameter</th>
    <th class="head">required</th>
    <th class="head">default</th>
    <th class="head">choices</th>
    <th class="head">comments</th>
    </tr>
            <tr>
    <td>hwclock<br/><div style="font-size: small;"></div></td>
    <td>no</td>
    <td></td>
        <td><ul></ul></td>
        <td><div>Whether the hardware clock is in UTC or in local timezone.
Default is to keep current setting.
Note that this option is recommended not to change and may fail
to configure, especially on virtual environments such as AWS.
</div></br>
        <div style="font-size: small;">aliases: rtc<div></td></tr>
            <tr>
    <td>name<br/><div style="font-size: small;"></div></td>
    <td>no</td>
    <td></td>
        <td><ul></ul></td>
        <td><div>Name of the timezone for the system clock.
Default is to keep current setting.
</div></td></tr>
        </table>
    </br>
```

**Obtained HTML**
here, some tags are escaped (like `<` -> `&lt;`)!
I have no idea why this happens.

``` html
<table border=1 cellpadding=4>
<tr>
<th class="head">parameter</th>
<th class="head">required</th>
<th class="head">default</th>
<th class="head">choices</th>
<th class="head">comments</th>
</tr>
        <tr>
<td>hwclock<br/><div style="font-size: small;"></div></td>
<td>no</td>
<td></td>
    <td><ul></ul></td>
    <td><div>Whether the hardware clock is in UTC or in local timezone.<p>Default is to keep current setting.
Note that this option is recommended not to change and may fail
to configure, especially on virtual environments such as AWS.
&lt;/div&gt;&lt;/br&gt;</p>
<blockquote>
<div><blockquote>
<div><dl class="docutils">
<dt>&lt;div style=&#8221;font-size: small;&#8221;&gt;aliases: rtc&lt;div&gt;&lt;/td&gt;&lt;/tr&gt;</dt>
<dd>&lt;tr&gt;</dd>
</dl>
</div></blockquote>
<p>&lt;td&gt;name&lt;br/&gt;&lt;div style=&#8221;font-size: small;&#8221;&gt;&lt;/div&gt;&lt;/td&gt;
&lt;td&gt;no&lt;/td&gt;
&lt;td&gt;&lt;/td&gt;</p>
<blockquote>
<div>&lt;td&gt;&lt;ul&gt;&lt;/ul&gt;&lt;/td&gt;
&lt;td&gt;&lt;div&gt;Name of the timezone for the system clock.</div></blockquote>
</div></blockquote>
<p>Default is to keep current setting.
&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;</p>
<blockquote>
<div><blockquote>
<div>&lt;/table&gt;</div></blockquote>
<p>&lt;/br&gt;</p>
```

#### Flow style (without `|`)

This is the new version @nateprewitt wrote (and same as block style with `>-`).

**Source YAML**

``` yaml
options:
  name:
    description:
      - |
        Name of the timezone for the system clock.
        Default is to keep current setting.
    required: false
  hwclock:
    description:
      - |
        Whether the hardware clock is in UTC or in local timezone.
        Default is to keep current setting.
        Note that this option is recommended not to change and may fail
        to configure, especially on virtual environments such as AWS.
    required: false
    aliases: ['rtc']
```

**Obtained RST**

``` html
    <table border=1 cellpadding=4>
    <tr>
    <th class="head">parameter</th>
    <th class="head">required</th>
    <th class="head">default</th>
    <th class="head">choices</th>
    <th class="head">comments</th>
    </tr>
            <tr>
    <td>hwclock<br/><div style="font-size: small;"></div></td>
    <td>no</td>
    <td></td>
        <td><ul></ul></td>
        <td><div>Whether the hardware clock is in UTC or in local timezone. Default is to keep current setting. Note that this option is recommended not to change and may fail to configure, especially on virtual environments such as AWS.</div></br>
        <div style="font-size: small;">aliases: rtc<div></td></tr>
            <tr>
    <td>name<br/><div style="font-size: small;"></div></td>
    <td>no</td>
    <td></td>
        <td><ul></ul></td>
        <td><div>Name of the timezone for the system clock. Default is to keep current setting.</div></td></tr>
        </table>
    </br>
```

**Obtained HTML**

``` html
<table border=1 cellpadding=4>
<tr>
<th class="head">parameter</th>
<th class="head">required</th>
<th class="head">default</th>
<th class="head">choices</th>
<th class="head">comments</th>
</tr>
        <tr>
<td>hwclock<br/><div style="font-size: small;"></div></td>
<td>no</td>
<td></td>
    <td><ul></ul></td>
    <td><div>Whether the hardware clock is in UTC or in local timezone. Default is to keep current setting. Note that this option is recommended not to change and may fail to configure, especially on virtual environments such as AWS.</div></br>
    <div style="font-size: small;">aliases: rtc<div></td></tr>
        <tr>
<td>name<br/><div style="font-size: small;"></div></td>
<td>no</td>
<td></td>
    <td><ul></ul></td>
    <td><div>Name of the timezone for the system clock. Default is to keep current setting.</div></td></tr>
    </table>
</br>
```

</details>

**Comment by resmo** [comment]
lgtm as well

**Pull request merged**
