### PR TITLE
Add idempotence to ec2_eni when private_ip_address is supplied

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE
- Bugfix Pull Request

Fix for https://github.com/ansible/ansible-modules-extras/issues/2084
##### COMPONENT NAME

ec2_eni
##### ANSIBLE VERSION

2.1
##### SUMMARY

Idempotence when private_ip_address is supplied, minor bug fix and pep8 fixes

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @wimnat. This module is going into community review.

We notice that you are one of the maintainers (@wimnat) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @wimnat. Since you are one of the maintainers (@wimnat) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@wimnat the patch is not applicable to the stable-2.1 branch, would you please create a PR for stable-2.1 as well?

**Pull request merged**
