### PR TITLE
New module: s3_bucket_sync

### PR DESCRIPTION
**Pull request by raben2**
- s3_sync.py Simple but performant tool to sync two buckets on s3

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by jhawkesworth** [comment]
Hi @raben2 - can I suggest that you rename your pull request so people can see what modules you would like to contribute.
Also, since your modules seem to have quite different purposes (s3, elasticache) maybe split them into separate pull requests so people interested in just one don't need to test and review both before they can give approval.

**Comment by raben2** [comment]
thanks for the suggestion, i suppose the request fits the extras repo since both modules are testet internaly.

**Comment by tedder** [comment]
I'd like to propose renaming s3_sync to s3_bucket_sync.

**Comment by raben2** [comment]
Hi @tedder thanks i did rename the module. Maybe you'll add a ship_it ;)

**Comment by gregdek** [comment]
@raben2 please split this into two PRs. As it stands, this will require potential reviewers to test/review _both_ modules, and we have few enough people reviewing new modules as it is. Thanks.

**Comment by gregdek** [comment]
When you've turned this into a single-module PR, type "ready_for_review" and we'll put it back into community review. Thanks!

**Comment by tedder** [comment]
@raben2 tag me when you've split and I'll review both.

**Comment by gregdek** [comment]
Thanks @tedder. Good to see you. :)

**Comment by raben2** [comment]
Elasitcache_parameters module is now deleted from this PR and moved to [#1993](https://github.com/ansible/ansible-modules-extras/pull/1993)

**Comment by gregdek** [comment]
Thanks @raben2 -- note the travis failures you're seeing; no RETURN info is provided in the documentation. We ask that you document return info. Fix that up and let us know by commenting "ready_for_review". Thanks!

**Comment by raben2** [comment]
Elasitcache_parameters module is now deleted from this PR and moved to [#2033](https://github.com/ansible/ansible-modules-extras/pull/2033)

**Comment by raben2** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tedder** [comment]
Is this the correct PR for s3_bucket_sync? I don't remember travis failing + all the merge/rebase commits. Anyhow, it hangs on my OSX machine while running like this:

```
- s3_bucket_sync: bucket_from="test2a-contentbucket-fjotg7jdqshd" bucket_to="test2c-contentbucket-ng8vsl8gmp55" max_processes=4 log=true
```

I think it has finished the uploads (based on my network activity) but there are still a couple processes running:

```
68376 ttys002    0:02.22 .../Python.app/Contents/MacOS/Python /usr/local/bin/ansible-playbook -i localhost, s3copy.yml -vvvv
68406 ttys002    0:00.31 /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 .../s3_bucket_sync; rm -rf /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/ >/dev/null 2>&1
68407 ttys002    0:05.83 .../Python.app/Contents/MacOS/Python /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/s3_bucket_sync
68410 ttys002    0:00.14 .../Python.app/Contents/MacOS/Python /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/s3_bucket_sync
```

I've used ellipsis to prune the length of those PS lines.

Want to add some logging/debugging to indicate what it's waiting for? Looking in dtruss I see this:

```
68873/0x68d3f:  write_nocancel(0x2, "Exception in thread Thread-3:\nTraceback (most recent call last):\n  File \".../Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 810, in __bootstrap_inner\n    self.run()\n  File \"/usr/local/Cellar/python/2", 0x2F9)    = 761 0
```

I can see a few of those, but there's no more context. Boo for Ansible swallowing so much of the message.

I then ran it against a remote EC2 and got the same behavior- two processes running at the end. This is a small bucket- about 80 little files- so I know it isn't in the middle of a long process:

```
ubuntu    8012  0.0  0.1   4440   640 pts/0    Ss+  21:12   0:00 /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/ >/dev/null 2>&1
ubuntu    8013  0.0  3.7 209236 18980 pts/0    Sl+  21:12   0:00 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync
ubuntu    8016  0.0  3.0 278124 15412 pts/0    Sl+  21:12   0:00 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync
```

**Comment by tedder** [comment]
@gregdek why did you add the Windows tag? I assume you meant to add an AWS tag?

**Comment by gregdek** [comment]
@tedder The Windows tag was added automatically by our triage bot because there are 237 files in this pull request, including Windows files and Networking files and Cloud files and All The Files.

Which is, uh, probably not what we want. :)

@raben2 please rebase this PR so that it only contains the file you're proposing to add. Thanks!

**Comment by raben2** [comment]
@gregdek  the pr is rebased with the actual devel branch. I don't see why travis is failing on rebase with ec2_vpc_net_facts.py
Auto-merging cloud/amazon/ec2_vpc_net_facts.py

CONFLICT (add/add): Merge conflict in cloud/amazon/ec2_vpc_net_facts.py

Failed to merge in the changes.

Patch failed at 0001 New module - ec2_vpc_net_facts

Same issue on [https://github.com/ansible/ansible-modules-extras/pull/2033](#2033l)

**Comment by raben2** [comment]
@tedder 
i did not test the module yet using osx. 
but if you set log: True you will get a log file of the processes within your working directory

**Comment by gregdek** [comment]
@raben2 sorry, but if there are 236 file changes in the PR, that means you're not working with a clean branch. Look at the "files changed" tab at the top of this page and it should be evident to you. That's why Travis is failing.

I strongly recommend that you close this PR and create a new one that includes only the file you wish to change.

**Comment by raben2** [comment]
moved to [#2055](https://github.com/ansible/ansible-modules-extras/pull/2055)

**Pull request closed without merging**
