### PR TITLE
Add new module mvn_get for resolving and dowloading artifacts from Maven repositories

### PR DESCRIPTION
**Pull request by jirutka**
This module downloads artifacts from Maven repository; resolves version of the artifact, but does _not_ resolve its dependencies. It’s intended just for fetching single artifact from repository, nothing more.

_Copied from https://github.com/ansible/ansible/pull/7630._

### CODE REVIEW

**Comment by cemo** [comment]
+1

**Comment by sivel** [comment]
This module should use `ansible.module_utils.urls` instead of using urllib2 directly.

**Comment by sivel** [comment]
Additionally with that, it should probably inherit some of the args and docs as well.

**Comment by jirutka** [comment]
> This module should use ansible.module_utils.urls instead of using urllib2 directly.

Okay, thanks for suggestion, I’ll update it.

> Additionally with that, it should probably inherit some of the args and docs as well.

I don’t understand this, how inherit args/docs?

**Comment by sivel** [comment]
It looks like there might not be any shared docs for urls, but at least for shared args look at `get_url` and its use of `url_argument_spec()`

Some other modules use `extends_documentation_fragment` for inheriting doc fragments.

**Comment by gregdek** [comment]
Adding "owner_pr" since @jirutka owns a module in Extras

**Comment by gregdek** [comment]
@jirutka if you can address @sivel's concerns and get his +1, we will merge this module.

**Comment by gregdek** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and i
f the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements,
 please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developin
g_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by gregdek** [comment]
So according to the new guidelines, this is in "needs_revision" because @sivel's outstanding issues have yet to be resolved.

@jirutka, please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by yuppie-flu** [comment]
Hi all! I believe you should close this request cause module for a maven artifact downloading already exists in 2.0: http://docs.ansible.com/ansible/maven_artifact_module.html

**Comment by robynbergeron** [comment]
@jirutka A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@jirutka Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to contributor inactivity.

**Pull request closed without merging**
