### PR TITLE
Module to retrieve facts about an AWS Cloudformation stack

### PR DESCRIPTION
**Pull request by amcconnell**
We have the need to lookup values from the stack outputs of a Cloudformation Stack created by a different playbook. The existing ec2_lc module does not support this use case.
This module takes the stack name, and returns the following:

``` json
{
    "changed": false, 
    "stack": {
        "capabilities": [
            "CAPABILITY_IAM"
        ], 
        "creation_time": "2015-06-04T17:45:36.573000", 
        "description": "Resources for enterprise event notifications", 
        "disable_rollback": false, 
        "id": "arn:aws:cloudformation:us-east-1:xxxxxxxxxxxxxxxxx", 
        "name": "business-events-qa", 
        "notification_arns": [], 
        "outputs": {
            "AccountLinkageTopicArn": "arn:aws:sns:us-east-1:12345:accountLinkage-qa", 
            "AccountNominatedTopicArn": "arn:aws:sns:us-east-1:12345:accountNominated-qa", 
            "TestDLQUrl": "https://sqs.us-east-1.amazonaws.com/713901513416/TESTDLQUrl-qa"
        }, 
        "parameters": {}, 
        "status": "UPDATE_COMPLETE", 
        "tags": {
            "Environment": "qa"
        }, 
        "timeout_in_minutes": null
    }
}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @amcconnell for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes, which can be contributed by anyone other than the author of the new module:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

More information about the review process can be seen here: 
https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

Thanks again for submitting your Ansible module!

**Comment by viper233** [comment]
I was looking to implement something similar to this via lookup plugins for resources and outputs (perhaps parameters).
https://github.com/ansible/ansible/pull/12880
Any comments would be welcome.

**Comment by loia** [comment]
needs_revision

@amcconnell Looks good overall.  It worked for me when I tested but I had some comments below related to module guidelines.

Documentation:
- Change `version_added` to 2.1
- Add `requirements` with `boto>={min version}`
- Remove `region`parameter and add `ec2` to `extends_documentation_fragment` list as this includes the `region` parameter for you
- Add the `RETURN` structure

Code:
- Remove unused imports: `datetime, json`
- Remove `region` from `argument_spec` as this is already included by `ec2_argument_spec`and it shouldn't be mandatory as it could be loaded from other sources e.g. environment variable, boto config or AWS profile.
- Use `connect_to_aws(boto.cloudformation, ...)` as per [AWS guidelines](https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/GUIDELINES.md) which validates that `region` was loaded from one of the sources above.

**Comment by mixja** [comment]
To be useful this would also need to return the stack resources in the output, and should return the template as an output property.

**Comment by gregdek** [comment]
Thanks @amcconnell for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@amcconnell A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@amcconnell Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amcconnell** [comment]
Given that there is a new, more functional implementation of cloudformation_facts now, I don't think that my implementation has much to offer. Closing.

**Pull request closed without merging**
