### PR TITLE
Fixes #2736 - dont overwrite undefined parameters

### LINKED ISSUE #2736: s3_bucket versioning parameter is required
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

s3_bucket
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

NONE
##### OS / ENVIRONMENT

Mac OS X 10.11.6
##### SUMMARY

When running a play to perform a change other than changing the versioning of the bucket, Ansible will assume that versioning needs to be turned off (default is no).  In all documentation, this parameter is marked as not required.  But if I perform an iteration over many s3 buckets to add something as simple as a tag, some of which need to have versioning enabled (for Cross Region Replication), it will suspend versioning on the buckets that have versioning enabled.  
##### STEPS TO REPRODUCE

```

---

- hosts: localhost
  tasks:
  - name: Tag S3 buckets
    s3_bucket: {name: "{{ item }}", tags:{Application: "S3"}}
    with_items:
      - policy-test-rwetzelberger
```

##### EXPECTED RESULTS

I expect to see that the s3 bucket named "policy-test-rwetzelberger" has a tag verified to have or added called "S3".  This bucket had versioning enabled.  Versioning that is enabled should not be suspended.
##### ACTUAL RESULTS

```
ansible-playbook -vvvv s3-tag.yml
No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: s3-tag.yml ***********************************************************
1 plays in s3-tag.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: <username>
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1471356881.14-189485368299932 `" && echo ansible-tmp-1471356881.14-189485368299932="` echo $HOME/.ansible/tmp/ansible-tmp-1471356881.14-189485368299932 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/m2/5vh7dqn90gz834mv6swzzdzmh8qf0x/T/tmpiE06ET TO /Users/<username>/.ansible/tmp/ansible-tmp-1471356881.14-189485368299932/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/<username>/.ansible/tmp/ansible-tmp-1471356881.14-189485368299932/setup; rm -rf "/Users/<username>/.ansible/tmp/ansible-tmp-1471356881.14-189485368299932/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Tag S3 buckets] **********************************************************
task path: /Users/<username>/fork-ansible-playbooks/Gio/tasks/s3-tag.yml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: <username>
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1471356885.59-45084579463130 `" && echo ansible-tmp-1471356885.59-45084579463130="` echo $HOME/.ansible/tmp/ansible-tmp-1471356885.59-45084579463130 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/m2/5vh7dqn90gz834mv6swzzdzmh8qf0x/T/tmpVvlVdL TO /Users/<username>/.ansible/tmp/ansible-tmp-1471356885.59-45084579463130/s3_bucket
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/<username>/.ansible/tmp/ansible-tmp-1471356885.59-45084579463130/s3_bucket; rm -rf "/Users/<username>/.ansible/tmp/ansible-tmp-1471356885.59-45084579463130/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=policy-test-rwetzelberger) => {"changed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "ec2_url": null, "force": false, "name": "policy-test-rwetzelberger", "policy": null, "profile": null, "region": null, "requester_pays": false, "s3_url": null, "security_token": null, "state": "present", "tags": {"Application": "S3"}, "validate_certs": true, "versioning": false}, "module_name": "s3_bucket"}, "item": "policy-test-rwetzelberger", "name": "policy-test-rwetzelberger", "policy": null, "requester_pays": false, "tags": {"Application": "S3"}, "versioning": {"MfaDelete": "Disabled", "Versioning": "Suspended"}}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

s3_bucket
##### ANSIBLE VERSION

ansible 2.2.0
##### SUMMARY

The s3_bucket was applying defaults to a bucket even if they were undefined.  This meant that if it conflicted with what was configured in aws then it would make a change.

With this change, if the parameter is not defined by the user, no change will be made in aws.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @wimnat for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @wimnat. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryanwetzelberger** [comment]
I have tested and confirmed it fixes issue #2736

**Comment by wimnat** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @wimnat. Since you are one of the maintainers (@wimnat) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amenonsen** [comment]
@ryansb @wimnat this change broke an existing playbook where I invoked `s3_bucket` with a policy specified as inline JSON. Reverting the patch fixed the problem. Sorry, I don't have time to investigate further right now.

**Comment by wimnat** [comment]
@amenonsen please open a new issue when you have the chance

**Comment by amenonsen** [comment]
@wimnat @ryansb The new code seems clearly broken at a quick glance. If `current_policy` is `None` (as it would be for a newly-created bucket), then the module will ignore any policy, because everything to do with `policy` (i.e., the module parameter) is wrapped inside an `if current_policy is not None:` (line 204).

**Comment by ryansb** [comment]
@amenonsen @wimnat I've made a PR with a fix, can you try it out in your envs as well before I merge it (and add to stable-2.2)?

**Comment by ryansb** [comment]
See #3091 for a fix to this change.

**Pull request merged**
