### PR TITLE
Fix issue in activating the VM disk while attaching disk

### PR DESCRIPTION
**Pull request by nijinashok**
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

Ovirt
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel)
```
##### SUMMARY

Currently <active> tag is passed within the disk element which is
incorrect. Currently the xml is passed as

```
<disk_attachment>
.....
<disk id="9955097a-0a6a-44ad-985a-dccd027a67fb">
    <active>true</active>
</disk>
......
</disk_attachment>
```

This should be

```
<disk_attachment>
.....
  <active>true</active>
  <disk id="9955097a-0a6a-44ad-985a-dccd027a67fb"/>
.....
</disk_attachment>
```

As a result, disk will remain inactive even though the
default option is true.

### CODE REVIEW

**Comment by machacekondra** [comment]
Thanks.

**Comment by machacekondra** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @nijinashok for this PR, and thanks @machacekondra for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fabianvf** [comment]
Is there any way we could backport this to 2.2.1?

**Pull request merged**
