### PR TITLE
Ansible Artifactory Modules

### PR DESCRIPTION
**Pull request by pr4th4m**
##### ISSUE RAISED
#2815
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

Artifactory
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Ansible Modules for JFrog Artifactory

Following artifactory modules are covered:
    - Artifactory Users
    - Artifactory Groups
    - Artifactory LDAP
    - Artifactory Repositories
    - Artifactory Permissions
    - Artifactory ApiKey

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @pratz for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @pratz for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@pratz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by pr4th4m** [comment]
Messed up this pull request, will create a new one.

**Comment by tchia04** [comment]
Is there a new pull request to replace this one?

**Comment by fracklen** [comment]
@pratz Is there a new pull request to replace this one?

**Comment by pr4th4m** [comment]
@tchia04 Sorry for the late reply.
@fracklen Will raise new PR soon.

**Comment by Akasurde** [comment]
@pratz @fracklen This repository is closed. Please open a new PR [here](https://github.com/ansible/ansible/compare)

**Pull request closed without merging**
