### PR TITLE
Feature Pull Request: New shrink lvol option

### PR DESCRIPTION
**Pull request by Yannig**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

lvol
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1d6608e84f) last updated 2016/04/29 23:18:16 (GMT +200)
  lib/ansible/modules/core: (detached HEAD e78ee3b128) last updated 2016/04/29 23:19:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ca310f3d15) last updated 2016/04/29 23:19:49 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Allow lvol to not shrink logical volume if size is lower than the defined size.

This allow to ignore error of oversized logical volume when customizing your FS size outside of Ansible.

Before :

``` yaml
    - lvol: lv=test-lv size=128m vg=test
    - lvol: lv=test-lv size=32m  vg=test
```

```
TASK [lvol] ********************************************************************
changed: [debian]

TASK [lvol] ********************************************************************
fatal: [debian]: FAILED! => {"changed": false, "failed": true, "msg": "Sorry, no shrinking of test-lv without force=yes."}
```

After:

``` yaml
    - lvol: lv=test-lv size=128m vg=test
    - lvol: lv=test-lv size=32m  vg=test shrink=no
```

```
TASK [lvol] ********************************************************************
changed: [debian]

TASK [lvol] ********************************************************************
ok: [debian]
```

Playbook example:

``` yaml

---

- name: "Test PV/LV"
  hosts: debian
  gather_facts: no
  tasks:
    - lvol: lv=test-lv vg=test state=absent force=yes
    - lvg: vg=test pvs=/dev/sdb
    - lvol: lv=test-lv size=128m vg=test
    - lvol: lv=test-lv size=32m  vg=test
      ignore_errors: yes
    - lvol: lv=test-lv size=32m  vg=test shrink=no
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Yannig. To the current maintainers, @jhoekx, @abulimov please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Yannig** [comment]
Any news?

**Comment by abulimov** [comment]
Sorry for the delay! Thank you @Yannig, everything looks good to me.

shipit!

**Comment by gregdek** [comment]
Thanks again to @Yannig for this PR, and thanks @jhoekx, @abulimov for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Yannig** [comment]
Thanks !

**Pull request merged**
