### PR TITLE
added module for OpenStack Cinder

### PR DESCRIPTION
**Pull request by hhamalai**

### CODE REVIEW

**Comment by sivel** [comment]
This is partially a duplicate of https://github.com/ansible/ansible-modules-extras/pull/92

#92 also moves forward with the newly decided naming convention of openstack modules.

cc @emonty

**Comment by gregdek** [comment]
@sivel @emonty if this is actually deprecated by #92 (which itself has been broken out into many core modules), then we should probably just close this. Any reason not to?

**Comment by emonty** [comment]
Yes - we should just close this

**Comment by gregdek** [comment]
Thanks @hhamalai for the PR, and sorry we couldn't ultimately merge it.

**Pull request closed without merging**
