### PR TITLE
Win dns zone reload

### PR DESCRIPTION
**Pull request by teochenglim**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

Module: win_dns_reload_zone
##### ANSIBLE VERSION

```
devel
```
##### SUMMARY

```
To reload windows DNS zone after edited any changes, including insert, modify and delete.
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by teochenglim** [comment]
ready_for_review

**Comment by jhawkesworth** [comment]
Hi, sorry looks like this still has conflicts.
Please read http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

I think maybe you need to git fetch upstream and git rebase upstream/devel or maybe reset your fork, so that it is the same as current devel, then create your branch, add your module and then create your PR.  Git can be tricky to get used to but it is worth getting used to it.

**Comment by teochenglim** [comment]
ready_for_review

**Comment by jhawkesworth** [comment]
sorry you still have lots of unrelated changes in here.

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by teochenglim** [comment]
ready_for_review

**Comment by teochenglim** [comment]
ready_for_review

**Comment by teochenglim** [comment]
ready_for_review

**Comment by gundalow** [comment]
@teochenglim Thanks for this new module. It appears you've got a lot of other changes listed here. When creating/updating a PR (Pull Request) it's often useful to review the "Files Changed" tab.

Have a look at the following page for details on how to clean up this branch

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

If you still have issues please join `#ansible-devel` on Freenode

**Comment by teochenglim** [comment]
re-open at  #2660

**Pull request closed without merging**
