### PR TITLE
Add vMotion Module

### PR DESCRIPTION
**Pull request by bedecarroll**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME
- vmware_vmotion
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Not all environments use VMware DRS (Distributed Resources Scheduler) to move virtual machines between hosts and this module will allow users to push VMs around in a VMware cluster. This can also be useful in cases where there is a need to ensure a VM is on a particular host at the time of a playbook run.

As per other VMware modules this requires pyVmomi to function. Users simply specify the VM name and the destination host with the ability to disable SSL certificate checking. An example task is below:

```
- name: Move VM
      local_action:
        module: vmware_vmotion
        hostname: 'vcenter'
        username: 'ansible'
        password: <pw>
        vm_name: 'testvm'
        destination_host: 'host2'
        validate_certs: No
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @bedecarroll for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bedecarroll** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @bedecarroll. To the current maintainers, @jcpowermac, @mtnbikenc, @chrrrles please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Hi @bedecarroll, the module looks pretty solid, good job.

I noticed you didn't make use of https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/vmware.py. It seems you have some similar code in this module, it would make sense to consolidate.

**Comment by bedecarroll** [comment]
Hi @resmo thank you for looking at my module. I'm a bit embarrassed to say but I didn't even realise the base vmware utilities were there. I've refactored my code to use everything in the base library which has cut down the amount of code significantly, which is a good thing. Thank you!

**Comment by resmo** [comment]
@bedecarroll no problem :) I even noticed you can strip down the docs as well. there is a doc fragment here https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs_fragments/vmware.py for common arguments used  in the vmware utils. So you could remove these docs in your module as well and "include" the docs like this https://github.com/bedecarroll/ansible-modules-extras/blob/ec5b72dfb28faef266824e53ea3237bedd4682a4/cloud/vmware/vmware_host.py#L63

**Comment by bedecarroll** [comment]
Hi @resmo sorry for the back and forth on this. I've updated to use the include squashed all the commits to keep the history clean. The build is unfortunately failing due to issues in other modules but I only made documentation changes in mine. Thank you!

**Comment by resmo** [comment]
@bedecarroll no need to apologize. Could you rebase your PR to get rid of the unrelated test failure?

**Comment by bedecarroll** [comment]
@resmo done! I pulled in the latest commits from devel as it seems the test failures have been fixed. Thanks!

**Comment by resmo** [comment]
shipit

Tested with vSphere 5.1.0:

Note: I was not able to use validate_certs=false with pyvomi pyvmomi-5.5.0.2014.1.1, updated to pyvmomi-6.0.0.2016.6 worked.

## compatibly improvement

Probably one little compatibly improvement: In some other vmware modules e.g. http://docs.ansible.com/ansible/vmware_dvs_host_module.html#this-is-an-extras-module the esx host param is named `esxi_hostname` so it would make sense to keep this name. The way you could change it is to just update the docs like this:

``` yaml
...
esxi_hostname:
   description:
     - Name of the end host the VM should be running on
  required: True
  aliases: ['destination_host', 'destination']
...
```

but you don't change the python code, only add another alias 

``` python
...
destination_host=dict(required=True, aliases=['destination', 'esxi_hostname'], type='str'),
...
```

## Results:

```
 $ ../ansible/hacking/test-module -m cloud/vmware/vmware_vmotion.py -a "username=moserre password=$PW hostname=vcenter-mgmt.stxt.media.int destination_host=cu01-pod01-esx06.stxt.media.int vm_name=i-70-6485-VM  validate_certs=no" 
* including generated source, if any, saving to: /home/resmo/.ansible_module_generated
* ziploader module detected; extracted module source to: /home/resmo/debug_dir
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"username": "moserre", "vm_name": "i-70-6485-VM", "hostname": "vcenter-mgmt.stxt.media.int", "destination_host": "cu01-pod01-esx06.stxt.media.int", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "validate_certs": false}}, "running_host": "cu01-pod01-esx06.stxt.media.int", "changed": true}


***********************************
PARSED OUTPUT
{
    "changed": true, 
    "invocation": {
        "module_args": {
            "destination_host": "cu01-pod01-esx06.stxt.media.int", 
            "hostname": "vcenter-mgmt.stxt.media.int", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "moserre", 
            "validate_certs": false, 
            "vm_name": "i-70-6485-VM"
        }
    }, 
    "running_host": "cu01-pod01-esx06.stxt.media.int"
}

 $ ../ansible/hacking/test-module -m cloud/vmware/vmware_vmotion.py -a "username=moserre password=$PW hostname=vcenter-mgmt.stxt.media.int destination_host=cu01-pod01-esx06.stxt.media.int vm_name=i-70-6485-VM  validate_certs=no"
* including generated source, if any, saving to: /home/resmo/.ansible_module_generated
* ziploader module detected; extracted module source to: /home/resmo/debug_dir
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"username": "moserre", "vm_name": "i-70-6485-VM", "hostname": "vcenter-mgmt.stxt.media.int", "destination_host": "cu01-pod01-esx06.stxt.media.int", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "validate_certs": false}}, "changed": false}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "destination_host": "cu01-pod01-esx06.stxt.media.int", 
            "hostname": "vcenter-mgmt.stxt.media.int", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "moserre", 
            "validate_certs": false, 
            "vm_name": "i-70-6485-VM"
        }

 $ ../ansible/hacking/test-module -m cloud/vmware/vmware_vmotion.py -a "username=moserre password=$PW hostname=vcenter-mgmt.stxt.media.int destination_host=cu01-pod01-esx05.stxt.media.int vm_name=i-70-6485-VM  validate_certs=no" --check
* including generated source, if any, saving to: /home/resmo/.ansible_module_generated
* ziploader module detected; extracted module source to: /home/resmo/debug_dir
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"username": "moserre", "vm_name": "i-70-6485-VM", "hostname": "vcenter-mgmt.stxt.media.int", "destination_host": "cu01-pod01-esx05.stxt.media.int", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "validate_certs": false}}, "running_host": "cu01-pod01-esx05.stxt.media.int", "changed": true}


***********************************
PARSED OUTPUT
{
    "changed": true, 
    "invocation": {
        "module_args": {
            "destination_host": "cu01-pod01-esx05.stxt.media.int", 
            "hostname": "vcenter-mgmt.stxt.media.int", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "moserre", 
            "validate_certs": false, 
            "vm_name": "i-70-6485-VM"
        }
    }, 
    "running_host": "cu01-pod01-esx05.stxt.media.int"
}

 $ ../ansible/hacking/test-module -m cloud/vmware/vmware_vmotion.py -a "username=moserre password=$PW hostname=vcenter-mgmt.stxt.media.int destination_host=cu01-pod01-esx06.stxt.media.int vm_name=i-70-6485-VM  validate_certs=no" --check
* including generated source, if any, saving to: /home/resmo/.ansible_module_generated
* ziploader module detected; extracted module source to: /home/resmo/debug_dir
***********************************
RAW OUTPUT

{"invocation": {"module_args": {"username": "moserre", "vm_name": "i-70-6485-VM", "hostname": "vcenter-mgmt.stxt.media.int", "destination_host": "cu01-pod01-esx06.stxt.media.int", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "validate_certs": false}}, "changed": false}


***********************************
PARSED OUTPUT
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "destination_host": "cu01-pod01-esx06.stxt.media.int", 
            "hostname": "vcenter-mgmt.stxt.media.int", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "moserre", 
            "validate_certs": false, 
            "vm_name": "i-70-6485-VM"
        }
    }
}
```

**Comment by gregdek** [comment]
Thanks again to @bedecarroll for this PR, and thanks @jcpowermac, @mtnbikenc, @chrrrles for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
