### PR TITLE
Add new ovirt_mac_pools module

### PR DESCRIPTION
**Pull request by machacekondra**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ovirt_mac_pools

##### ANSIBLE VERSION

```
ansible 2.3
```

##### SUMMARY

This patch adds new module to manage oVirt MAC pools.

### CODE REVIEW

**Comment by machacekondra** [comment]
@mwperina @ryansb

**Review by mwperina — APPROVED** [review]
Looks good to me, thanks! :+1:

**Comment by gregdek** [comment]
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by machacekondra** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
