### PR TITLE
s3_bucket.py - return CORS rules in the output

### PR DESCRIPTION
**Pull request by Constantin07**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ansible-modules-extras/cloud/amazon/s3_bucket.py
##### ANSIBLE VERSION

```
Latest devel 2.1.0
```
##### SUMMARY

This PR adds to the returned output the CORS rules in JSON format.
If CORS are not defined it returns an empty list.

```
TASK: [debug var=s3_result] ***************************************************
ok: [127.0.0.1] => {
    "var": {
        "s3_result": {
            "changed": false,
            "cors": [
                {
                    "allowedheader": [
                        "*"
                    ],
                    "allowedmethod": [
                        "GET",
                        "PUT"
                    ],
                    "allowedorigin": [
                        "http://www.example1.com",
                        "http://www.example2.com"
                    ],
                    "exposeheader": [],
                    "maxageseconds": "180"
                },
                {
                    "allowedheader": [
                        "Authorization"
                    ],
                    "allowedmethod": [
                        "PUT",
                        "POST",
                        "DELETE"
                    ],
                    "allowedorigin": [
                        "http://www.example.com"
                    ],
                    "exposeheader": [
                        "x-amz-server-side-encryption",
                        "x-amz-request-id",
                        "x-amz-id-2"
                    ],
                    "maxageseconds": "3000"
                }
            ],
            "invocation": {
                "module_args": "",
                "module_complex_args": {
                    "name": "cloudtrail-1test",
                    "region": "eu-west-1",
                    "state": "present"
                },
                "module_name": "s3_bucket"
            },
            "name": "cloudtrail-1test",
            "policy": null,
            "requester_pays": false,
            "tags": {},
            "versioning": {}
        }
    }
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Constantin07. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
I would snake_case the key values of the cors rules needs_revision

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
@wimnat What does "snake_case" mean?

**Comment by wimnat** [comment]
snake_case instead of CamelCase

**Comment by Constantin07** [comment]
@wimnat  How about the key names? Should they be snake_cased too?

**Comment by wimnat** [comment]
Ah sorry! My mistake. Snake_case only the key names. Leave the values as is

**Comment by Constantin07** [comment]
@wimnat  Done.

**Comment by gregdek** [comment]
@Constantin07 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
@gregdek In my previous comment I've already addressed the advice given by @wimnat.

ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Constantin07 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
@Constantin07 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Constantin07 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Constantin07 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Constantin07 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
