### PR TITLE
Fixes win_uri module ignoring body argument

### PR DESCRIPTION
**Pull request by iagogarrido**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

win_uri
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Module win_uri ignores body argument. I fixed it.

```
before:
failed: [192.0.2.1] (item=aitem) => {"failed": true, "invocation": {"module_name": "win_uri"}, "item": "aitem", "msg": "Error en el servidor remoto: (500) Error interno del servidor."}

after:
ok: [192.0.2.1] => (item=aitem) => {"base_response": {"CharacterSet": null, "ContentEncoding": "", "ContentLength": 0, "ContentType": "", "Cookies": [{"Comment": "", "CommentUri": null, "Discard": false, "Domain": "adomain", "Expired": false, "Expires": "/Date(-62135596800000)/", "HttpOnly": true, "Name": "aname", "Path": "/", "Port": "", "Secure": false, "TimeStamp": "/Date(1467212510245)/", "Value": "avalue", "Version": 0}], "Headers": ["Content-Length", "Cache-Control", "Date", "Set-Cookie", "Server", "aserver", "X-Powered-By"], "IsFromCache": false, "IsMutuallyAuthenticated": false, "LastModified": "/Date(1467212510368)/", "Method": "POST", "ProtocolVersion": {"Build": -1, "Major": 1, "MajorRevision": -1, "Minor": 1, "MinorRevision": -1, "Revision": -1}, "ResponseUri": "aresponseuri", "Server": "aserver", "StatusCode": 200, "StatusDescription": "OK", "SupportsHeaders": true}, "content": [], "headers": {"Cache-Control": "private, max-age=0", "Content-Length": "0", "Date": "Wed, 29 Jun 2016 15:01:50 GMT", "Server": "aserver", "Set-Cookie": "XXXXXXXXXXXXXXXXXXXXXXXXXXX", "X-Powered-By": "atechnology"}, "invocation": {"module_name": "win_uri"}, "item": "aitem", "raw_content": "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nCache-Control: private, max-age=0\r\nDate: Wed, 29 Jun 2016 15:01:50 GMT\r\nSet-Cookie: XXXXXXXXXXXXXXXXXXXXXXXXXXX\r\nServer: aserver\r\nX-Powered-By: atechnology\r\n\r\n", "raw_content_length": 0, "raw_content_stream": {"CanRead": true, "CanSeek": true, "CanTimeout": false, "CanWrite": true, "Capacity": 10000, "Length": 0, "Position": 0, "ReadTimeout": null, "WriteTimeout": null}, "status_code": 200, "status_description": "OK", "win_uri": {"body": "app=aapp", "content_type": "application/x-www-form-urlencoded", "method": "POST", "url": "aurl", "use_basic_parsing": true}}
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Thanks for your pull request, this will come in handy.

Please can you add something to the documentation (win_uri.py) to say that 'body' response was added in 2.2 in the RETURN section of the documentation?

**Comment by iagogarrido** [comment]
Yes, of course. I added it.

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by jhawkesworth** [comment]
ping @CorwinBrown - are you happy with this change?

**Comment by gregdek** [comment]
kicking to ping current maintainer

**Comment by gregdek** [comment]
Thanks @iagogarrido. To the current maintainers, @blakfeld please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by blakfeld** [comment]
Sorry for the delay. I am @CorwinBrown but that was an account for my old job.

shipit

**Comment by CorwinBrown** [comment]
Just in case:

shipit

**Comment by gregdek** [comment]
Thanks again to @iagogarrido for this PR, and thanks @blakfeld for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
