### PR TITLE
Add boto3 support to ec2_eni_facts

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

ec2_eni_facts
##### ANSIBLE VERSION

n/a
##### SUMMARY

add boto3 support to ec2_eni_facts

### CODE REVIEW

**Comment by wimnat** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @wimnat. Since you are one of the maintainers (@wimnat) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by christonog** [comment]
How are the filters supposed to be applied in boto3? In the playbook, I am filtering based on instance id and the device index. The filters I have are below:

```
- ec2_eni_facts:
    filters:
      attachment.instance-id: "{{ item }}"
      attachment.device-index: 1
    region: "{{ region }}"
  with_items:
   - '{{ instance_ids }}'
```

Below is the exception I am receiving:

```
TASK [ec2-storagecenter : ec2_eni_facts] ***************************************
task path: /home/ec2-user/Ansible/roles/ec2-provision/tasks/ips.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py", line 171, in <module>
    main()
  File "/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py", line 153, in main
    list_ec2_snapshots_boto3(connection, module)
  File "/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py", line 72, in list_ec2_snapshots_boto3
    network_interfaces_result = connection.describe_network_interfaces(Filters=filters)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 524, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 577, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Filters[0].Values, value: 1, type: <type 'int'>, valid types: <type 'list'>, <type 'tuple'>

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_eni_facts"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py\", line 171, in <module>\n    main()\n  File \"/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py\", line 153, in main\n    list_ec2_snapshots_boto3(connection, module)\n  File \"/tmp/ansible__yYIQS/ansible_module_ec2_eni_facts.py\", line 72, in list_ec2_snapshots_boto3\n    network_interfaces_result = connection.describe_network_interfaces(Filters=filters)\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 258, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 524, in _make_api_call\n    api_params, operation_model, context=request_context)\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 577, in _convert_to_request_dict\n    api_params, operation_model)\n  File \"/usr/lib/python2.7/dist-packages/botocore/validate.py\", line 270, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter Filters[0].Values, value: 1, type: <type 'int'>, valid types: <type 'list'>, <type 'tuple'>\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

```
ansible 2.1.0.0
config file = /home/ec2-user/Ansible/ansible.cfg
configured module search path = ['./library']
```

The previous version commited https://github.com/ansible/ansible-modules-extras/commit/1b0250125aabac80b84c6200d272ba6796f329bb#diff-eeb9d8acea1d87cede5d1d16abbe2a58 works.

**Comment by wimnat** [comment]
As a workaround, quote the 1

attachment.device-index: "1"

**Comment by christonog** [comment]
Thanks @wimnat. That worked. Now I just need to change my ansible playbook to accommodate the new returned json (as I'm registering it as a fact), which is no big deal. :-)

**Pull request merged**
