### PR TITLE
Backport pacman updates to 1.9

### PR DESCRIPTION
**Pull request by indrajitr**
Backport the pacman PRs #480, #762, #807, #1018 to stable-1.9

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @indrajitr -- thanks for the PR. 

Marking as owner_pr and tagging for inclusion. cc @ansible/core team for this magic -- note that this is a backport, in case you guys want to eyeball it, and that #1018 needs to be merged first (it is ready / approved, just needs to be merged!).

**Comment by indrajitr** [comment]
I want to add #1037 in the train as well. #1038 has all the incremental updates folded in (which was necessary to avoid merge conflict). You can either apply #1038 after this one, or simply take #1038 only.

I'll update the PR description(s) based on what you guys decide.

**Comment by gregdek** [comment]
Taking out of "shipit" and putting back into "core_review", as it's unclear what our policy for Extras backporting is. I'm not sure we even have one yet.

cc: @ansible/core team for guidance.

**Comment by indrajitr** [comment]
Per @bcoca (https://github.com/ansible/ansible-modules-extras/pull/1038#issuecomment-143894698), only bugfixes should go in. I would close this and propose #1038 instead. That PR has been updated with just the bugfixes. I'll update the description there.

**Pull request closed without merging**
