### PR TITLE
Create/Modify/Delete Tags for ElastiCache Clusters

### PR DESCRIPTION
**Pull request by linuxdynasty**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

elasticache_tag
##### ANSIBLE VERSION

```
2.0.2.0
```
##### SUMMARY
- Add Tags to an ElastiCache Cluster
- Remove Tags to an ElastiCache Cluster
- Update Tags on an ElastiCache Cluster

```
- name: Tag ElasticCache
  local_action:
    module: elasticache_tag
    state: present
    name: test
    region: us-west-2
    tags:
      Name: test
      env: development
      service: webapp
  register: elasticache_tags
- debug:
    var: elasticache_tags
ok: [127.0.0.1] => {
    "elasticache_tags": {
        "arn": "arn:aws:elasticache:us-west-2:123456789876:cluster:test",
        "changed": false,
        "err_msg": "Nothing to update",
        "name": "test",
        "success": true,
        "tags": {
            "Name": "test",
            "env": "development",
            "service": "webapp"
        }
    }
}
```
- Add Tags to an ElastiCache Cluster
- Remove Tags to an ElastiCache Cluster
- Update Tags on an ElastiCache Cluster

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-extras/2233)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@linuxdynasty Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by linuxdynasty** [comment]
@gregdek, this has not been flagged or commented by anyone except for the buildbot. All checks are passing.

**Comment by gregdek** [comment]
Kicking, waiting for reviews/shipits.

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
