### PR TITLE
support for event alert monitors

### PR DESCRIPTION
**Pull request by hypergig**
Datadog has extended the monitors api to include event alert monitors. Just tricking down that change.

### CODE REVIEW

**Comment by robynbergeron** [comment]
@hypergig -- thanks for submitting this PR.

@skornehl -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also pinging @arturaz as owner of the datadog event module -- just in case they have feedback :)

**Comment by skornehl** [comment]
Thanks @hypergig!
shipit

**Comment by gregdek** [comment]
Thanks again to @hypergig for this PR, and thanks @skornehl for reviewing. Marking for inclusion.

**Comment by hypergig** [comment]
It's my pleasure. Thanks all.

**Pull request merged**
