### PR TITLE
Allow easy retrieval of a value stored for a given key

### LINKED ISSUE #3355: clustering/consul_kv.py appears to have undocumented retrieve function
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

clustering/consul_kv.py

##### ANSIBLE VERSION

```
ansible 2.1.2.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

In the github repo, the following line in DOCUMENTATION appears to be truncated:
---snip---
 - If the key represents a prefix then Note that when a value is removed, the existing
    value if any is returned as part of the results.
---snip---

Viewing the source, there appears to be a "retrieve" command that is not mentioned anywhere in the docs.

### PR DESCRIPTION
**Pull request by sgargan**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
clustering/consul_kv.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel 715b800ef1) last updated 2016/09/07 20:25:29 (GMT +100)
  lib/ansible/modules/core: (detached HEAD cbd9e07f19) last updated 2016/08/24 23:26:56 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD beaa0c6c22) last updated 2016/08/24 23:27:02 (GMT +100)
```

##### SUMMARY
Adds a simple documented way to retrieve the value stored for a key in the consul kv store.
Fixes #3355

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @sgargan. This module is going into community review.

We notice that you are one of the maintainers (@sgargan) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @sgargan. Since you are one of the maintainers (@sgargan) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
closes #3355. shipit

**Pull request closed without merging**
