### PR TITLE
Elasticsearch add esusers module

### PR DESCRIPTION
**Pull request by barryib**
Add new module for shield users management https://www.elastic.co/guide/en/shield/2.1/managing-users.html#managing-users

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @barryib for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by morganchristiansson** [comment]
+1

**Comment by gregdek** [comment]
Thanks @barryib for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by barryib** [comment]
Hello @gregdek,

It was because this pull request is becoming old. It's from January.
I've changed version from 2.1 to 2.2 to pass CI tests

**Comment by barryib** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @barryib for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by evgkrsk** [comment]
shipit

**Comment by barryib** [comment]
Hello,

I'm closing this PR in favor of #2528, which now support the shield API introduced by ES 2.3.

@evgkrsk @morganchristiansson thanks for your shipit comments on that new PR.

**Pull request closed without merging**
