### PR TITLE
Made win_iis_webapppool Strict Compliant

### PR DESCRIPTION
**Pull request by blakfeld**
This module was failing on me. It appears to be due to Strict being toggled. This change gets the module working as expected.

### CODE REVIEW

**Comment by robynbergeron** [comment]
@blakfeld -- thanks for this PR. 

@henrik -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by henrik** [comment]
Wrong Henrik.

**Comment by jhawkesworth** [comment]
Can't test right now but the code for the fix looks like it would fix the problem.

May also fix https://github.com/ansible/ansible-modules-extras/issues/1093 and https://github.com/ansible/ansible-modules-extras/issues/1097

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
