### PR TITLE
Make Homebrew-related modules run on Python 3

### PR DESCRIPTION
**Pull request by dirn**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
- `homebrew`
- `homebrew_cask`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
The current state of the `homebrew` and `homebrew_cask` modules doesn't allow them to be run using Python 3+. These changes address that.

Using the modules currently results in:
```
Traceback (most recent call last):
  File \"/var/folders/4j/c4n27w1s50n3k9521j_z_dzh0000gn/T/ansible_k3jmyixf/ansible_module_homebrew.py\", line 870, in <module>
    main()
  File \"/var/folders/4j/c4n27w1s50n3k9521j_z_dzh0000gn/T/ansible_k3jmyixf/ansible_module_homebrew.py\", line 859, in main
    upgrade_all=upgrade_all, install_options=install_options)
  File \"/var/folders/4j/c4n27w1s50n3k9521j_z_dzh0000gn/T/ansible_k3jmyixf/ansible_module_homebrew.py\", line 338, in __init__
    install_options=install_options, )
  File \"/var/folders/4j/c4n27w1s50n3k9521j_z_dzh0000gn/T/ansible_k3jmyixf/ansible_module_homebrew.py\", line 351, in _setup_instance_vars
    for key, val in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

These changes allow the modules to run successfully.

Both the `homebrew` and `homebrew_cask` modules iterate over
dictionaries using `iteritems`. This is a Python 2-specific method whose
behavior is similar to `items` in Python 3+. The `iteritems` function in
the six library was designed to make it possible to use the correct
method.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dirn. To the current maintainers, @indrajitr please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by indrajitr** [comment]
shipit

Thanks @dirn!

**Comment by gregdek** [comment]
Thanks again to @dirn for this PR, and thanks @indrajitr for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Merged to both devel and stable-2.2.  This fix should make it into 2.2.1

**Pull request merged**
