### PR TITLE
haproxy: fail when backend host is not found

### PR DESCRIPTION
**Pull request by ggermis**
A suggested fix for the bug reported at #523. A new parameter is added: _fail_on_not_found_ which will result in a failure whenever the backend host is not found. To keep backward compatibility, I set the default value to _false_ so existing playbooks should keep working as-is

I'm not sure about the version i put in the version_added field ("2.0") for the new _fail_on_not_found_ parameter, so if that should change, please let me know

I also added output to include more state so that it's easier to see what is going on by just using the -v flag

```
changed: [33.33.33.100 -> 33.33.33.100] => (item=33.33.33.100) => {"changed": true, "command": ["get weight service/node-1; disable server service/node-1"], "item": "33.33.33.100", "output": ["1 (initial 1)"], "state_after": [{"status": "MAINT", "weight": "1"}], "state_before": [{"status": "UP", "weight": "1"}]}
```

About the refactoring, you can now ask for the status of a specific backend host which comes in useful when you need to inspect state (or determine existence). I had a feeling that the multiple ways of parsing output for "show stat" was a result of this missing primitive

There also was a lot of duplications of code in the haproxy module and different ways of parsing the "show stat" output which have now also been unified to use the csv.DictReader so that you can access elements based on column name rather than index

IMO, it should now be easier to add new features when needed (eg: waiting for sessions to reach 0)

Let me know what you think, any remarks / comments welcome

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ggermis. @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@ravibhure This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ravibhure** [comment]
+1 shipit

**Comment by robynbergeron** [comment]
Thanks again to @ggermis for this PR, and thanks @ravibhure for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
can you fix your commit history? you seem to have an unwanted merge

**Comment by ggermis** [comment]
sorry about that.. merged a bit too much to resolve a conflict from devel branch... did a git reset  / rebase to fix. Should be ok now, only the networking/haproxy.py file changed

**Comment by ggermis** [comment]
any news on when this might be merged? Thanks

**Comment by gregdek** [comment]
@ggermis A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by ggermis** [comment]
@gregdek thanks for the ping, but afaik the issue was that I accidentally added some extra files to my initial commit (because of a merge). I fixed that a while ago (see comment of Jan 21st) so that the only file that changed is haproxy.py . Unless there's some other issue I need to have a look at, I think the pull request is ok to merge. Cheers

**Comment by gregdek** [comment]
@ggermis Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi

If you are happy with this please
- Squash into one commit (rather than two)
- Add the text `ready_for_review` which should trigger Ansibull-bot to get this moving again

**Comment by ggermis** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ggermis. To the current maintainers, @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ravibhure** [comment]
shipit

Thanks @ggermis and @gregdek

**Comment by gregdek** [comment]
Thanks again to @ggermis for this PR, and thanks @ravibhure for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @ggermis for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ggermis** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ggermis. To the current maintainers, @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ggermis** [comment]
the only change was the version_added on the fail_on_not_found option. @ravibhure can you please check and give a shipit? Thank you

**Comment by ravibhure** [comment]
shipit

**Pull request merged**
