### PR TITLE
Use mongodb query instead of loop to retrieve users

### PR DESCRIPTION
**Pull request by Lujeni**

### CODE REVIEW

**Comment by gregdek** [comment]
@elliotttf Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by resmo** [comment]
owner seems unresponsive. 
shipit

**Comment by bcoca** [comment]
this query was added in 2.6 (i know people still using 2.4) can we make this 'version dependent'?

**Comment by Lujeni** [comment]
@bcoca There is any documentation to integrate a `version dependance` pls?

**Comment by bcoca** [comment]
in this same plugin there is already a check for 2.5 version in line 166

**Comment by gregdek** [comment]
@Lujeni Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by Lujeni** [comment]
@gregdek Hello, sorry for the delay. I will added the version dependency this week. Thanks

**Comment by Lujeni** [comment]
Hello,

@gregdek @bcoca I am not sure to well understand the dependency check.
What do you mean when you say:

> this query was added in 2.6 [...]

It's about the `find_one` method throught `pymongo`?

thanks

**Comment by bcoca** [comment]
mongodb 2.6, yes, the find_one query

**Comment by Lujeni** [comment]
Hello,

This method is also available for the 2.6 version:
https://api.mongodb.org/python/2.6.3/api/pymongo/collection.html#pymongo.collection.Collection.find_one

I am a bit confused.

**Comment by bcoca** [comment]
@Lujeni yes, that is what i said, it was added in 2.6, my concern is people still using 2.4

**Comment by Lujeni** [comment]
@bcoca The `find_one` method is present since 1.X version imho
http://api.mongodb.org/python/1.3/api/pymongo/collection.html#pymongo.collection.Collection.find_one

**Comment by Lujeni** [comment]
@bcoca Hi.
Are you agree with my last comment? Thanks

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by Lujeni** [comment]
@gregdek 

> @bcoca Hi.
> Are you agree with my last comment? Thanks

I am still waiting the response.
I was disagree to add a version dependent check in the code if it's unecessary

**Comment by gregdek** [comment]
@bcoca ping for further explanation here?

**Comment by gregdek** [comment]
Thanks @Lujeni. To the current maintainers, @lujeni please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
`shipit`

**Comment by gregdek** [comment]
Thanks again to @Lujeni for this PR, and thanks @lujeni for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Lujeni for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Lujeni for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
This PR is useless now since few modifications (e.g. https://github.com/ansible/ansible-modules-extras/pull/2920).

**Pull request closed without merging**
