### PR TITLE
osx_defaults: add "host" attribute

### PR DESCRIPTION
**Pull request by wincent**
This allows us to configure defaults using the `-currentHost` or `-host` arguments to the `defaults` executable.

### CODE REVIEW

**Comment by wincent** [comment]
First PR here, so feedback especially welcome.

**Comment by gregdek** [comment]
Thanks @wincent. @frenck please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@frenck This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@frenck still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Moving this to review by the @ansible/core team. @wincent thanks for your PR and your patience.

**Comment by frenck** [comment]
I'm sorry @gregdek & @wincent for my late response.

Nevertheless, great addition! 

shipit

**Comment by wincent** [comment]
@gregdek: looks like this is good to ship now, but somehow has slipped through the cracks.

**Comment by wincent** [comment]
Ping: @robynbergeron, @gregdek

Any action needed on my part to get this merged?

**Comment by resmo** [comment]
Looks good. shipping it. 
version_added is missing but not a big deal, I am adding it after the merge.
Thanks for the patience.

**Pull request merged**
