### PR TITLE
make examples more consistent

### PR DESCRIPTION
**Pull request by yauh**
instead of the alias `name` the proper attribute `user should be used in the examples

### CODE REVIEW

**Comment by bcoca** [comment]
actually, we prefer name as it is more consistent with other modules

**Comment by yauh** [comment]
Might I ask why you advocate `user` in the detailed parameters listing if you prefer `name`? Consistency should be achieved, so either use `name` in the examples or `user` in the options. I am fine with both, but having this mixture is confusing.

**Comment by bcoca** [comment]
that is what the PR #264 is for

**Comment by yauh** [comment]
Wonderful, thanks!

**Pull request closed without merging**
