### PR TITLE
Lxc container config fixes

### PR DESCRIPTION
**Pull request by evgeni**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

lxc_container
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 005dc84aa7) last updated 2016/04/10 12:57:27 (GMT +200)
  lib/ansible/modules/core: (detached HEAD c52f475c64) last updated 2016/04/10 12:57:46 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 5abb914315) last updated 2016/04/10 12:57:50 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

There are three bugs in the handling of `container_config` in `lxc_container`:
- entries that share the same prefix might end up overwritten or written in the wrong order
- duplicate entries with different whitespace are not handled properly
###### Example for 1:

old config:

```
lxc.network.ipv4.gateway=auto
lxc.network.ipv4=192.0.2.1
```

change `lxc.network.ipv4=192.0.2.1` to `lxc.network.ipv4=192.0.2.2` in the playbook and rerun it, you end up with the following config:

```
lxc.network.ipv4.gateway=auto
lxc.network.ipv4=192.0.2.2
lxc.network.ipv4=192.0.2.1
```
###### Example for 2:

the following will produce four entries, even though they are technically identical:

```
container_config:
  - "lxc.network.flags=up"
  - "lxc.network.flags =up"
  - "lxc.network.flags= up"
  - "lxc.network.flags = up"
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @evgeni. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by slash3g** [comment]
This patch also fixes  #1998.

**Comment by evgeni** [comment]
Mhhh. This is actually not totally correct. A container config _can_ have duplicate keys, e.g. lxc.include :(

**Comment by slash3g** [comment]
Good point @evgeni!
We could add a flag for each key/value pair to choose if we want to replace the value o append it to the set of current values (defaulting to the most common case, i.e. replacement). We would also need a way to remove pairs.
I was thinking about something like:

```
container_config:
  - "lxc.network.flags = up" # this would replace the current value
  - pair="lxc.start.auto = 1" action=replace
  - pair="lxc.include = common.conf" action=append
  - pair="lxc.include = old_common.conf" action=remove
  - pair="lxc.network.ipv4" action=remove # this would remove all the pairs with key=lxc.network.ipv4
```

**Comment by evgeni** [comment]
@slash3g technically we could yeah, not sure I'd like to write such complicated configs, thought. No, I don't have a better idea yet :(

**Comment by cloudnull** [comment]
a long while back in the original version of this module, which was included in the ansible-lxc-rpc product, we attempted to write a config parser that would make the module do something similar to what is being proposed by @slash3g. Sadly we found the potential, and in some cases requirement, to have duplicate keys in various orders (some times strict order in terms of network interfaces) to be a burden we simply did not want to carry or develop for. Since then the we've found it simpler to drop an include file in the base config and template the companion file as needed which keeps the container configs neat and tidy. Its really not the best programmatic solution however it does work well enough.

I too would be interested in creating a proper solution however given the potential for miserable complexity I too am not sure I would like to take on such an effort at this time.

**Comment by cloudnull** [comment]
needs_revision

**Comment by gregdek** [comment]
Thanks @evgeni for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by evgeni** [comment]
@cloudnull shall we then maybe reduce this pr to c03e77a and 8db3a63 as those are real bugfixes? then we can use 0e763bb as a starting point for a new issue "not optimal config parsing" and let it get some more input from other users?

**Comment by cloudnull** [comment]
@evgeni +1 that sounds very sensible. I, like you, would love to come up with an intelligent parser however I've just not found the time to invest in it but I think it'd be great to get that conversation started in a new issue.

**Comment by evgeni** [comment]
ready_for_review

@cloudnull there, I droped the overwrite commit and moved it to the issue we already had in #1998, let's discuss there

**Comment by gregdek** [comment]
Thanks @evgeni. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cloudnull** [comment]
shipit

LGTM -- thank you for putting this together @evgeni

**Comment by gregdek** [comment]
Thanks again to @evgeni for this PR, and thanks @cloudnull for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
