### PR TITLE
Fixes get_fw_rule NotImplemented error on 11.6 BIG-IP

### PR DESCRIPTION
**Pull request by mhite**
This pull request fixes issue #109. According to the BIG-IP iControl documentation, the get_fw_rule() API call is no longer supported on virtual servers as of 11.6. I have removed the reference to it.

### CODE REVIEW

**Comment by bcoca** [comment]
I'm not that familiar with obsolescence in the F5 family, does it make sense to detect the version and keep the call for those that have older models?

**Comment by mhite** [comment]
@bcoca - Looking at the API documentation, there is a ton of get_fw_rule_\* API calls that were introduced in 11.3 and 11.5. The bigip_facts module was only calling a single one of them (get_fw_rule, introduced in 11.3). All of their get_fw_rule_\* related API calls were then ripped out in 11.6 breaking all backward compatability. In the documentation for the API calls they removed, they refer you to use another API call which is also removed in the same version. It's a mess on their end right now as far as I can tell.

Until there is some stability in how F5 implements the get_fw_rule\* stuff in the VirtualServer API, I am happy just removing the single call we do today. Alternatively, I can catch the suds WebFault exception like I do with MethodNotFound and just ignore it. I'm happy to go that route if you are more comfortable with that approach.

BTW, here is the link to the VirtualServer API information:

https://devcentral.f5.com/wiki/iControl.LocalLB__VirtualServer.ashx

You can see just how much they ripped out if you just search for get_fw_rule on that page.

**Comment by mhite** [comment]
I've also opened pull-request #273 as an alternative solution.

**Comment by bcoca** [comment]
merged #273 instead

**Pull request closed without merging**
