### PR TITLE
Add a new option immediate= to immediately apply a permanent change

### PR DESCRIPTION
**Pull request by mscherer**
Currently, either you apply the change in the configuration
of firewalld ( without permanent=True ), or you apply it live.
I most of the time want to do the 2 at the same time, ie open the
port ( so I can use the service ) and make sure it stay open on reboot.

### CODE REVIEW

**Comment by mscherer** [comment]
This was first on https://github.com/ansible/ansible/pull/9115 

So I am ok with tweaking the message, but i am a bit short on idea of what to use instead. 
I would suggest: "Operation applied to on-disk configuration", and "Operation applied to live firewall". Instead of "Permanent operation" and "Non permanent operation".  Thoughts ?

**Comment by mpdehaan** [comment]
Thanks!

stick a "version_added: '1.8'" on this argument and it's good to go.

We'll merge core much faster given the split.

**Comment by ghost** [comment]
@mpdehaan : it's there now.

**Comment by maxamillion** [comment]
+1 LGTM.
I added a comment on the old PR before the split and this looks good, I was curious about feedback for the needs_revision tag? (Or maybe that doesn't mean what I think it means.)

**Comment by josephholsten** [comment]
@mpdehaan does this need anything else for merge? Seems like this repo is a bit under water. Anything we can do to help keep on top of outstanding PRs?

**Comment by bcoca** [comment]
can you change 'version added' to 1.9?

**Comment by mscherer** [comment]
Yep, just did.

**Comment by maxamillion** [comment]
Is the `needs_revision` label still applicable here?

**Comment by ghost** [comment]
good question.

**Pull request merged**
