### PR TITLE
Add module to manage Digital Ocean DNS records with Ansible.

### PR DESCRIPTION
**Pull request by dopry**
##### Issue Type:
- New Module Pull Request
##### Plugin Name:

digital_ocean_dns_record
##### Ansible Version:

1.?
##### Summary:

This creates a digital_ocean_domain_record module which allows developers to manage DNS records on digital ocean.
## 

I find these long drawn out templates super discouraging as a contributor.  I understand they're helpful internally, but you might try to minimize it.

### CODE REVIEW

**Comment by pogotech** [comment]
I am trying to fix the build failures, but I am not used to how github does the pull requests and I ended up creating #1745 I am not sure if I should leave or close #1745. If I should close it, I will try to merge my fixes into this pull request.

**Comment by dopry** [comment]
It's fine as long as you're preserving my initial commit and working from
there. I'm fairly sure it was originally written for 1.3 ish..

On Fri, Feb 26, 2016 at 9:43 AM, pogotech notifications@github.com wrote:

> I am trying to fix the build failures, but I am not used to how github
> does the pull requests and I ended up creating #1745
> https://github.com/ansible/ansible-modules-extras/pull/1745 I am not
> sure if I should leave or close #1745
> https://github.com/ansible/ansible-modules-extras/pull/1745. If I
> should close it, I will try to merge my fixes into this pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-extras/pull/1744#issuecomment-189308866
> .

## 

Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by pogotech** [comment]
Your commit is preserved. I cloned the ansible repo, pulled your commit
made the mods and pushed it to my repo, then made the pull request.

**Comment by dopry** [comment]
Danke.

**Comment by gregdek** [comment]
Thanks @dopry for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by dopry** [comment]
superceded by #1745

**Pull request closed without merging**
