### PR TITLE
Add firmware upgrade module.

### PR DESCRIPTION
**Pull request by hulquest**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

storage/netapp/netapp_e_controller_firmware.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 11ae3793d5) last updated 2016/09/29 08:38:30 (GMT -600)
  lib/ansible/modules/core: (detached HEAD 7808f42aff) last updated 2016/09/28 11:22:30 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 881d2f95a8) last updated 2016/09/28 11:22:35 (GMT -600)
  config file = /home/khulques/ansible.cfg
  configured module search path = ['/home/khulques/src/projects/ansible-modules-extras/storage/netapp', '/home/khulques/src/projects/ansible_eseries/ansible_modules']
```
##### SUMMARY

Adding a module that will update (upgrade or downgrade) controller firmware for the E/EF platform.  I had to include an exception for this file in shippable.sh because it needs the requests module to perform multipart/form-data POST ops.  The firmware file is local, pushed to the proxy, and then installed by the storage array.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @hulquest. This module is going into community review.

We notice that you are one of the maintainers (@hulquest) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hulquest** [comment]
I'm comfortable with this module given the testing I've done.  If no comments from the core team particularly the use of requests, shipit.

**Comment by gregdek** [comment]
Thanks @hulquest. Since you are one of the maintainers (@hulquest) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @hulquest for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hulquest A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
