### PR TITLE
Fixed bug to recognize haproxy changes.

### PR DESCRIPTION
**Pull request by autotune**
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bugfix Pull Request
##### Ansible Version:
- ansible 2.0.0 (devel 31d06886d5)
##### Ansible Configuration:
- Default configuration. Nothing has been modified except for /etc/ansible/hosts file. 
##### Environment:
- CentOS Linux release 7.1.1503 (Core)
##### Summary:

I'm not sure if this is the most "elegant" solution out there, but seeing as how there's no way to get the status of an individual server in haproxy via /var/run/haproxy.sock interface this will at least get the job done. Basically as long as haproxy keeps the status states in the documentation here: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9.2 and weight is always the next relative stat this fix should remain bug-free itself. Happy to discuss alternatives here and make modifications if agreed to get the +1 to merge with master. 
##### Steps To Reproduce: Configure frontend and backend as noted below. Change weight or state to a new value. This was tested in VirtualBox hence 10.0.2.15 as bridged interface with port forwarding http rule.

[beadams@ansibledev 523]$ cat haproxy.yaml
- hosts: 10.0.2.15
  tasks:
  - name: modify haproxy host
    523_haproxy: state=enabled host=web3 weight=50% 
- hosts: 10.0.2.15
  tasks:
  - name: modify haproxy host state
    
    haproxy: state=enabled host=web1 weight=50% 

[beadams@ansibledev 523]$ egrep -i "web|frontend|backend" /etc/haproxy/haproxy.cfg|grep -v #
frontend http-in
    default_backend localnodes01
backend localnodes01
    server  web1 10.0.2.15:8080 check
    server  web2 10.0.2.15:8080 check
    server  web3 10.0.2.15:8080 check
##### Expected Results:

The "changed" exit status will be set to true if status of server is changed or weight, otherwise will be set to false.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @autotune. @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ravibhure** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @autotune for this PR, and thanks @ravibhure for reviewing. Marking for inclusion.

**Comment by autotune** [comment]
Sure thing, always glad to be of help! @robynbergeron @gregdek @ravibhure

**Pull request merged**
