### PR TITLE
Fixed #237 - improved embedded JSON support handling

### LINKED ISSUE #237: rabbitmq_parameter fails when passing dynamically generated json
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.8.2
  configured module search path = None

Tested also on ansible 1.9
ansible 1.9 (devel 8f06ba2bc1) last updated 2015/02/05 11:16:37 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/05 11:16:50 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/05 11:17:01 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 600fc15b42) last updated 2015/02/05 11:17:13 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 77485f6c6a) last updated 2015/02/05 11:17:36 (GMT +200)
  configured module search path = None
##### Environment:

OS X 10.9.5 > Ubuntu 14.04
##### Summary:

Passing non-hardcoded json (through templating) to rabbitmq_parameter's "value" argument raises an exception. It works when hardcoding the json though.
##### Steps To Reproduce:

Here's an example playbook with one successful task (the first one), and two failing tasks (the next two) which both raise the same exception (see below). All of them are supposed to do the same thing.

```
- hosts: my-host
  tasks:
        - set_fact:
              upstream_list:
                    - upstream: "test"
                    - upstream: "test2"
              json_upstreams: '[{"upstream":"test1"},{"upstream":"test2"}]'

        - rabbitmq_parameter:
              component: federation-upstream-set
              name: test-upstream-set
              value: '[{"upstream":"test1"},{"upstream":"test2"}]'
           sudo: yes

        - rabbitmq_parameter:
              component: federation-upstream-set
              name: test-upstream-set
              value: '{{ json_upstreams }}'
           sudo: yes

        - rabbitmq_parameter:
              component: federation-upstream-set
              name: test-upstream-set
              value: '{{ upstream_list|to_json }}'
           sudo: yes
```
##### Expected Results:

Set a federation-upstream-set parameter to the default vhost.
##### Actual Results:

The two failing tasks raise the same exception. The output from ansible with -vvvv is as follows:

```
<my-host> ESTABLISH CONNECTION FOR USER: xxxx
<my-host> REMOTE_MODULE rabbitmq_parameter name=test-upstream-set component=federation-upstream-set vhost=/
<my-host> EXEC ssh -C -vvv -o ForwardAgent=yes -o ControlMaster=auto -o     ControlPersist=30m -o ControlPath="xxxx/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o     KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-k
eyex,hostbased,publickey -o PasswordAuthentication=no -o User=xxxx -o ConnectTimeout=10 my-    host /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=xxxxxx] password: " -u root /bin/sh -c         '"'"'echo SUDO-SUCCESS-xxxxxx; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
failed: [my-host] => {"failed": true, "parsed": false}
SUDO-SUCCESS-xxxxxx
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /xxxxx/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 102: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 58450
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
[sudo via ansible, key=xxxxx] password: Traceback (most recent call last):
  File "<stdin>", line 1717, in <module>
  File "<stdin>", line 142, in main
  File "<stdin>", line 104, in set
  File "<stdin>", line 88, in _exec
  File "<stdin>", line 1566, in run_command
  File "/usr/lib/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
```
##### Tentative solution:

From what I've seen while troubleshooting the issue, the problem comes from the rabbitmq_parameter module being passed a list to its "value" argument. It is then passed to AnsibleModule::run_command, which assumes it is a string and passes it through os.path.expanduser.
I've managed to correct this behavior by setting the value to `value if type(value) == str else json.dumps(value)`.
I can submit a more complete patch or pull request if this is indeed a bug and not an issue in my playbook.

### PR DESCRIPTION
**Pull request by romanek-adam**
Fixed #237 - improved embedded JSON support handling.

### CODE REVIEW

**Comment by Lujeni** [comment]
imho, add the import after the documentation

**Comment by gregdek** [comment]
@chrishoffman Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@chrishoffman This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@chrishoffman still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by chrishoffman** [comment]
I think the only thing that needs to change is the json import.  I believe ansible needs to support older versions of python.  See https://github.com/ansible/ansible-modules-extras/blob/devel/system/puppet.py.

needs_revision

**Comment by bcoca** [comment]
you can leave out the json import as the shared basic.py already includes one for you (with correct version handling)

**Comment by gregdek** [comment]
Thanks @romanek-adam for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by romanek-adam** [comment]
I followed @bcoca's advice and got rid of the json import from the patch.

ready_for_review

**Comment by chrishoffman** [comment]
shipit

**Comment by romanek-adam** [comment]
The commit has been merged into stable-1.9 but the PR has been assigned to 2.1.0 milestone. Why is that?

**Comment by bcoca** [comment]
cause i did not realize it was not pointing ade :devel as it should have ... reverting this.

**Comment by romanek-adam** [comment]
Opened another PR for the devel branch: ansible/ansible-modules-extras/pull/1530

**Pull request merged**
