### PR TITLE
oVirt/RHEV module

### PR DESCRIPTION
**Pull request by t-v**
I remade the pull request, because I noticed my firewalld module accidently slipped in the request.
(former one: https://github.com/ansible/ansible-modules-extras/pull/165)

Original comment:
I created a module to control the oVirt/RHEV API.
I also (just) noticed there was another ansible module already that did this, but it also lacks some featured I need very much. 
Most explicit, multi disk and multi nic environments.
This also gives the option to control your bootoptions and HA & memory reservation

I have compared it a bit, and it looks like a complete rewrite, but with some more functionality.
The other reason I made it as a new module is that if I would add these features, it would break the old one.
## Especially since the disks and nics use complex arguments

In meanwhile I also rebased this branch on the current devel + fixed an issue with ovirt/rhevm where the default nic sorting on mac give issues.
Due to this bug, you can't tell what your 1st interface is, so all nics will be created with a default name and than be renamed and added to the correct networkinteface after their creation.

### CODE REVIEW

**Comment by detiber** [comment]
Why not add this to the existing ovirt module?  As I see it, you could leave the existing disk arguments (disk_alloc, disk_int, instance_disksize) as well as add the new disks arguments and make them mutually exclusive.

Something like this:

``` python
module = AnsibleModule(
  argument_spec = dict(
  state = ...
  ),
  mutually_exclusive = [
    ['disks', 'disk_alloc'],
    ['disks', 'disk_int'],
    ['disks', 'disk_instance_disksize']
  ]
)
```

The same could be done for any other new arguments that would introduce a breaking change.

**Comment by t-v** [comment]
Because I fear that might break more than do good.
That's why I started with a complete rewrite of it.

If you check the difference between them, you'll also notice there are too many differences to just merge them and make some values mutually exclusive. To make this happen it would require another rewrite and make things unnecessary complex.

(Just my opinion, and also the reason I made this a totally new module.)

**Comment by detiber** [comment]
@TimothyVandenbrande my only concern would be that having 2 different ovirt modules will lead to confusion (both for users and devs that wish to add future features).  Possibly support the old arguments with a deprecation notice and clearly mark the supporting code so that at a future date (possibly with the release of 2.0, the legacy code can be removed)?

**Comment by t-v** [comment]
I checked it on a required argument (url)
So now, if url is being used, I will take the old argumentspec and if the complex arguments are being used, I'm using the new one.

Currently, it's an ugly fix. Since this is how I quickfixed it.
if (the 'url' variable is being used):
  use all the old stuff
else:
  use what I currently do.

But luckily it works both ways. I could create a machine with the old arguments and I could create one with the new ones.

The advantage of not fully merging them would also be, if we decide to remove the old code, that can be done easily since nothing is intertwined. It's just one big, but ugly, if...else statement.

**Comment by gregdek** [comment]
Hey @TimothyVandenbrande looks like you've got a lot of bleedover from other branches into this commit -- your'e touching a bunch of windows files.  Can you rebase/clean up this PR and get the ovirt/rhev patches isolated?

**Comment by t-v** [comment]
cleaned up my commit + rebased to latest devel

**Comment by t-v** [comment]
so @gregdek, pls review again.

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande.

This is one of those cases where we don't yet have a clear process: how do we handle full module rewrites? 

Going to kick to the core team, not just for a review of the module itself, but for a discussion of policy. Thanks for the rewrite, and thanks for your patience while we figure out how to handle it.

**Comment by t-v** [comment]
Of course, no problem.
I had to rewrite it because in its current state it was limited to 1 disk
and 1 interface which was not usuable for my situation. This is the one we
keep using at work and are fine tuning whenever it's needed. This us also
the reason that when it'll get implemented, we'll be able to push all
updates we do and in that way keep the development of this alive as ovirt
keeps evolving.

**Comment by gregdek** [comment]
OK, we haven't touched this and we never had the discussion. :)

Starting again: my first concern is, "would this break backward compatibility with the existing module?" If it would, I'd be inclined to reject it and ask for revisions to the existing module.

My second concern is, "why should the original author see their module rewritten without an attempt to integrate with it?" Assuming the answer to the first question is acceptable, I would defer to @vincentvdk for the answer to this question.

**Comment by gregdek** [comment]
I'm also removing the new_plugin label because it isn't.

**Comment by t-v** [comment]
On tour 1st question, yes it is backwards compatibel. I check the given arguments and based upon that the old code gets chosen.
And for the 2nd question. If he wants to, he can implement the code. The main reason I rewrote it, was because it wasn't usuable at all for my infrastructure. I am maintaining and using that one currently on an almost daily basis. I also have no issues in keep using it as a plugin the way I am now. Just thought the community might gain of it. But if it is too much, just close it.
I have the plugin currently running on my infrastructure so it won't give me issues.

**Comment by gregdek** [comment]
OK, we still need to sort out the policy for complete rewrite of existing modules and we don't currently have one. This one will have to wait until after the 2.0 release. Bumping for bookkeeping purposes.

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by vincentvdk** [comment]
Will this replace the existing module? It's not really clear at the moment..

My original idea was to split up the functionality in modules. The current module was only meant for vm related operations, but more stuff was added later. 

Anyway, the company I work for has moved our rhev setup so I was unable to look at issues with the current ovirt module. So now i'm not sure this is still usefull for me to spend time on. I'd rather see the functionality split up instead of rewriting complete modules.

my 2cts

**Comment by t-v** [comment]
If this tends to be such a big issue, I can just cancel this pull request.
I assumed it would be a great addition, but if it is too much hassle, I
will just close it. I don't need it to be merged, since I have been using
it for 2y as a custom module, so I can keep doing that.

**Comment by t-v** [comment]
@gregdek 
ready_for_review

**Comment by t-v** [comment]
In case you're interested, this is a gist of the custom module I still work daily with:
https://gist.github.com/TimothyVandenbrande/cfee762589d69ac6f0d7.js

If the request actually goes through, I'm willing to update and add the functionality to it, but until than, I just feel it would be a waste of precious development and testing time.
I hope you can understand.

**Comment by vincentvdk** [comment]
@TimothyVandenbrande it's not a big issue at all. Someone just need to decide what to do with the 2 ,modules. If that means using yours, that is perfectly fine for me. But I would like to know how we proceed forward so we don't work on stuff that becomes "useless".. // @gregdek

**Comment by bcoca** [comment]
so we allow for deprecating modules and creating a new one that takes over, this lets the user still use the old module for a while and move to the new one on their own schedule.

its not clear to me from reading the posts if the new module here is completely backwards compatible or not.

There is also the point of splitting this into multiple modules, I don't know enough about the usage or interface to say one way or another, so please enlighten me.

**Comment by t-v** [comment]
Upon the request of Jason I made a switch based on the arguments being used
to use the old modules, or the new modules.

But yes, my original though was creating it as a totally new module instead
of adapting the old one. This gives users the choice to use the one they
wish.

My preference still goes to using 2 different modules instead of merging
everything together.

**Comment by t-v** [comment]
For your convenience, I also made a pullrequest with the other named module, without the actual merge of the old parameters. That one has a different name and is not backwards compatible with the other ovirt module.
https://github.com/ansible/ansible-modules-extras/pull/1383

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande. @vincentvdk please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@vincentvdk This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@vincentvdk still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by vincentvdk** [comment]
@gregdek @robynbergeron  when I look at the diff, this is more a rewrite. imho only the author can decide whether this can be 'shipped' or not. As stated before, if you want to replace the existing module, go ahead.

**Comment by srgvg** [comment]
Tossing 2 cents, it would seem to me that
- the author field should be extended with the new author, not replaced, or at least some attribution should be respected
- the commits should be squashed together into one commit with one clear and concise commit message; ansible's git history is already enough of a nice example on how to not write commit messages (mine included)
- there still is no guideline, or even a start of an idea for one, on how to handle big rewrites such as these, which remains a problem, if not the biggest issue
- it seems to  @bcoca touched the right concerns, some of which were also mentioned by @vincentvdk, which were at least in part answered by @TimothyVandenbrande 
- having such a PR lingering for months is a problem, but luckily 2.0 is out so no more excuses! yay!

Given code stability to end users in mind, it seems to me this should at the very least be introduced as a separate module, with eventually a deprecation warning, so users can choose hot to move forward. AS nothing gets ever decently tested in such matters, I'm pretty sure this would break things for $people.

@gregdek @robynbergeron I obviously bumped in here because @vincentvdk told me about it, but it seems this is a good topic to discuss on the summit. Can you put this on the agenda?

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by t-v** [comment]
@gregdek ready_for_review

(Sorry, accidently pressed the close button.)

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@TimothyVandenbrande A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@TimothyVandenbrande Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
