### PR TITLE
Updates to Sendgrid Module

### PR DESCRIPTION
**Pull request by juliedavila**
This adds the following options to the sendgrid module. To use them you need to pip install sendgrid (docstring updated with the req)

api_key
cc
bcc
attachments
from_name
html_body
headers

### CODE REVIEW

**Comment by gregdek** [comment]
@makaimc Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by mattmakai** [comment]
@kunal732 any chance you can take a look at this? you're more familiar with current Sendgrid API than I am

**Comment by kunal732** [comment]
:+1:  thanks @makaimc i'll take a look at this later today

**Comment by juliedavila** [comment]
Yo @kunal732 friendly ping.

**Comment by juliedavila** [comment]
@kunal732 ping ping?

**Comment by tima** [comment]
shipit

**Pull request merged**
