### PR TITLE
Correct problem with changed:true

### PR DESCRIPTION
**Pull request by daveres**
I have just changed a small piece of this module to avoid to return always that the task is changed

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @daveres. @smadam813 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by daveres** [comment]
Hi,

It's the first time I correct some code in Github. I will follow the guide you comment in the future.

Regards,

**Comment by smadam813** [comment]
Thanks @daveres for the contribution.

shipit

**Comment by nitzmahone** [comment]
What's weird is that I can't make the original one break (which is disconcerting, since at first glance the expression should not match), but the fix is fine- thanks!

**Comment by nitzmahone** [comment]
cherry-picked to stable-2.0 as well

**Pull request merged**
