### PR TITLE
Add XenServer module

### PR DESCRIPTION
**Pull request by ahill00**
This module gathers facts about a XenServer host, gathering them in a single
connection instead of multiple xe commands.

### CODE REVIEW

**Comment by ahill00** [comment]
Previously discussed here: https://github.com/ansible/ansible/pull/7727

**Comment by bcoca** [comment]
as in the original ticket, I think this should be renamed to xenserver_facts

**Comment by gregdek** [comment]
Thanks for submitting your module to Ansible Extras. Our policy is that each new module needs to be reviewed and approved by at least two official module reviewers, the list of whom can be found here: https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Because you’re already an approved reviewer, we assume that you’ve reviewed your own module; you just need to find one other person to review, and you’re all set.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by gregdek** [comment]
@andyhky A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by ahill00** [comment]
Thanks @gregdek I'll update later this week.

**Comment by ahill00** [comment]
@bcoca - apologies on the thread dig, but I've updated this submission with renamed module.

**Comment by gregdek** [comment]
Thanks @andyhky. Putting back into core_review.

**Pull request merged**
