### PR TITLE
Fixed problem with pymongo compatibility

### LINKED ISSUE #11: mongodb_user works incorrectly with old pymongo
##### Environment:

OSX 10.7 -> Ubuntu precise
##### Summary:

mongodb_user works incorrectly with old pymongo (~2.1). 
Tested with 2.7.2, work correctly.
##### Steps To Reproduce:
- Fresh mongo instance with auth enabled, no users
- ansible host  -m mongodb_user -a "database=admin user=test roles=root password=test state=present"
##### Expected Results:

Creates new user
##### Actual Results:

Changed = false

This code block supposed to fail on non-existant user:

```
        try:
           client[db_name].authenticate(user, password)
           if state == 'present':
              module.exit_json(changed=False, user=user)
        except OperationFailure:
           if state == 'absent':
              module.exit_json(changed=False, user=user)
```

But it is exiting correctly and continue. 
### Old issue

https://github.com/ansible/ansible/issues/8899

### PR DESCRIPTION
**Pull request by UnderGreen**
Fixed problem with compatibility MongoDB Server and PyMongo package.

Fixes #11

### CODE REVIEW

**Comment by Lujeni** [comment]
@UnderGreen @bcoca Hello, according to the [mongodb documentation](https://docs.mongodb.org/ecosystem/drivers/python/#python-driver), only the compatibility between `mongodb 3.2` and the driver must be check.

imho, this PR need a `revision`.

**Comment by gregdek** [comment]
Thanks @UnderGreen for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by UnderGreen** [comment]
@Lujeni not sure. Need a check full list of compatibility. https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-python

**Comment by UnderGreen** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @UnderGreen. To the current maintainers, @lujeni please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
> @Lujeni not sure. Need a check full list of compatibility. https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-python

your right, i was wrong. (i checked the language compatibility)

`shipit`

**Comment by gregdek** [comment]
Thanks again to @UnderGreen for this PR, and thanks @lujeni for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Would this count as a fix for #11 ?

**Pull request merged**
