### PR TITLE
verify existence when cleanup and fire

### PR DESCRIPTION
**Pull request by robberphex**
- When cleanup, reverse current working version.
- When finalize/fire a new version, check new version's existence.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @RobberPhex. @ramondelafuente please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ramondelafuente** [comment]
What is the problem being fixed? I.e. in what scenario would the cleanup remove the current working version? (maybe I have an unclear picture of how you are using the cleanup function)

**Comment by ramondelafuente** [comment]
shipit

And just because the word "shipit" alone does not convey any enthousiasm, I'm adding some additional emoticons!
:tada: :balloon: :+1: :birthday: :dancers: 

Thanks for your PR, @RobberPhex

**Comment by gregdek** [comment]
Thanks again to @RobberPhex for this PR, and thanks @ramondelafuente for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
@RobberPhex could you flatten the commits?

**Comment by robberphex** [comment]
@bcoca squashed commits, and resolve some conflicts. Do you need re-review this?

**Pull request merged**
