### PR TITLE
Fix 2725 - version backport 2.1

### PR DESCRIPTION
**Pull request by h0nIg**
this is the fix https://github.com/ansible/ansible-modules-extras/pull/2920 backported to 2.1

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @h0nIg. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @h0nIg for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by h0nIg** [comment]
@gregdek the maintainer @lujeni created this on his repository, but he is unavailable right now. could you please include this fix?

**Comment by resmo** [comment]
Hi @h0nIg, this module in devel branch and in stable-2.1 have diverted. 

I am not 100% sure, if this fix in devel will apply correctly but it seems that the function `check_compatibility` is not used in this module at all in stable-2.1 branch and must not be included in the patch. 

Could you verify the patch works for 2.1 and remove the `check_compatibility` function?

needs_info

**Comment by h0nIg** [comment]
@resmo done your fix, removed check_compatibility

**Comment by resmo** [comment]
LGTM

**Review by Lujeni — COMMENTED** [review]
The travis build is failed.
I am not aware with the ansible ci.

@resmo any idea ?

```
 fatal: no such branch: stable-2.1
```

Thanks

**Comment by resmo** [comment]
@Lujeni can be ignored, I was already inspecting this issue but didn't find the problem.

**Comment by Lujeni** [comment]
@resmo ok thanks !

`shipit`

**Pull request merged**
