### PR TITLE
Add boto3 and boto3_wait modules

### PR DESCRIPTION
**Pull request by ericcitaire**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

boto3 and boto3_wait
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

These two modules make AWS API calls using boto3. The general idea is to avoid using AWS CLI when Ansible does not provide a dedicated Ansible module, especiallly for new services (ie. Lambda, Kinesis, etc.).
##### EXAMPLE

``` yaml
- name: Describe running EMR Clusters
  boto3:
    name: emr
    region: us-east-1
    operation: list_clusters
    parameters:
      ClusterStates:
        - STARTING
        - BOOTSTRAPPING
        - RUNNING
        - WAITING
  changed_when: False
  register: emr

- set_fact:
    emr_cluster_exists: "{{ emr.response.Clusters | selectattr('Name', 'equalto', 'my-jobflow') | list | length > 0 }}"

- set_fact:
    emr_cluster_id: "{{ emr.response.Clusters | selectattr('Name', 'equalto', 'my-jobflow') | map(attribute='Id') | first }}"
  when: emr_cluster_exists

# if 'my-jobflow' cluster does not exist, create it.
- name: Create EMR Cluster
  boto3:
    name: emr
    region: us-east-1
    operation: run_job_flow
    parameters:
      Name: my-jobflow
      Applications:
        - Name: Hive
      Instances:
        KeepJobFlowAliveWhenNoSteps: True
        Ec2KeyName: my-key
        Ec2SubnetId: subnet-xxxxxxx
        EmrManagedSlaveSecurityGroup: sg-xxxxxxx
        EmrManagedMasterSecurityGroup: sg-xxxxxxx
        InstanceGroups:
          - InstanceCount: 1
            InstanceRole: MASTER
            InstanceType: m1.medium
            Market: ON_DEMAND
          - InstanceCount: 1
            InstanceRole: CORE
            InstanceType: m1.medium
            Name: Core Instance Group
            Market: ON_DEMAND
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      ReleaseLabel: emr-4.6.0
      VisibleToAllUsers: True
  when: not emr_cluster_exists
  register: emr_create

- set_fact:
    emr_cluster_id: "{{ emr_create.response.JobFlowId }}"
    emr_cluster_exists: True
  when: not emr_cluster_exists

- name: Wait for EMR Cluster to be running
  boto3_wait:
    name: emr
    region: us-east-1
    until: cluster_running
    parameters:
      ClusterId: "{{ emr_cluster_id }}"
    delay: 30
    max_attempts: 50
```

### CODE REVIEW

**Comment by sivel** [comment]
Im not sure how I feel about these.  However you should use 4 space indentation in the python code instead of 2.

**Comment by admscale** [comment]
Good idea (personnaly tired of super long and ugly aws cli lines in playbooks ...).

**Comment by ericcitaire** [comment]
@sivel I fixed the indentation.

**Comment by gregdek** [comment]
Thanks @ericcitaire for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mikedlr** [comment]
Looking through the modules they seem to take the approach of taking everything from botocore and importing it.  I think this is the _only_ way that Ansible will ever manage to keep up with AWS, so whether it's great or not it's inevitable and I think it should be done if ansible wants to be a tool for managing services on AWS.

However, this has one nasty implication, which is the same problem with the AWS tools.  Inside the module are a huge number of undocumented configuration parameters.  The interface will be continually extended and difficult to discover.  The way this is handled in AWS seems to be A) auto-generate documentation from the interface definitions and B) provide examples for every service and preferably many calls per service.   Is there a way to do the same for this module?

With awscli and boto3 the discovery is partly handled by people doing the following:

1. make the definition manually using the console
2. run the awscli to see what is returned from that definition
3. create a CLI command which matches the returned definition 

It would really help users to have a tutorial which shows how to do the same thing for the boto3 module.

**Pull request closed without merging**
