### PR TITLE
new module Elasticache params

### PR DESCRIPTION
**Pull request by raben2**
ISSUE TYPE

New Module Pull Request

COMPONENT NAME

eleasticache_parameters
ANSIBLE VERSION

2.2

SUMMARY

This module allows you to configure elasicache parameter tables for redis or memcached elasticache resources

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
