### PR TITLE
Respect include.* directives by default.

### PR DESCRIPTION
**Pull request by kmaris**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

git_config
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /Users/kmaris/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This change enables a default behavior to respect include.\* directives in git config files. Since this module specifies a scope for all operations aside from list_all (which _does_ by default honor include.\* directives) it makes sense to default to always respect the directives and behave consistently across module options.

For the example below, my `~/.gitconfig` has the following section:

```
[include]
  path = ~/.gitconfig.local
```

And `~/.gitconfig.local` has (among other sensitive info not to include in vcs):

```
[user]
  name = Kevin Maris
  ........
```

Before the change:

```
./hacking/test-module -m lib/ansible/modules/extras/source_control/git_config.py -a 'list_all=yes'

{
    "changed": false, 
    "config_values": {
        "alias.br": "branch", 
        "alias.branches": "branch -a", 
        .........
        "user.name": "Kevin Maris", 
        .........
    }, 
    "invocation": {
        "module_args": {
            "list_all": true, 
            "name": null, 
            "repo": null, 
            "scope": null, 
            "value": null
        }
    }, 
    "msg": ""
}

./hacking/test-module -m lib/ansible/modules/extras/source_control/git_config.py -a 'name=user.name'

{
    "changed": false, 
    "config_value": "", 
    "invocation": {
        "module_args": {
            "list_all": false, 
            "name": "user.name", 
            "repo": null, 
            "scope": null, 
            "value": null
        }
    }, 
    "msg": ""
}

./hacking/test-module -m lib/ansible/modules/extras/source_control/git_config.py -a 'name=user.name --scope=global'

{
    "changed": false, 
    "config_value": "", 
    "invocation": {
        "module_args": {
            "list_all": false, 
            "name": "user.name", 
            "repo": null, 
            "scope": "global", 
            "value": null
        }
    }, 
    "msg": ""
}

```

After the change:

```

{
    "changed": false, 
    "config_values": {
        "alias.br": "branch", 
        "alias.branches": "branch -a", 
        .........
        "user.name": "Kevin Maris", 
        .........
    }, 
    "invocation": {
        "module_args": {
            "list_all": true, 
            "name": null, 
            "repo": null, 
            "scope": null, 
            "value": null
        }
    }, 
    "msg": ""
}

./hacking/test-module -m lib/ansible/modules/extras/source_control/git_config.py -a 'name=user.name'

{
    "changed": false, 
    "config_value": "", 
    "invocation": {
        "module_args": {
            "list_all": false, 
            "name": "user.name", 
            "repo": null, 
            "scope": null, 
            "value": null
        }
    }, 
    "msg": ""
}

./hacking/test-module -m lib/ansible/modules/extras/source_control/git_config.py -a 'name=user.name scope=global'

{
    "changed": false, 
    "config_value": "Kevin Maris", 
    "invocation": {
        "module_args": {
            "list_all": false, 
            "name": "user.name", 
            "repo": null, 
            "scope": "global", 
            "value": null
        }
    }, 
    "msg": ""
}

```

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by kmaris** [comment]
If you need a maintainer I'd be happy to do so.

**Comment by gregdek** [comment]
Thanks @kmaris. To the current maintainers, @djmattyg007 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by djmattyg007** [comment]
shipit

**Comment by djmattyg007** [comment]
I wasn't aware that `--includes` existed. Nice work!

**Comment by gregdek** [comment]
Thanks again to @kmaris for this PR, and thanks @djmattyg007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
