### PR TITLE
fixed not resolving latest to snapshot for MD5 check when the file ex…

### PR DESCRIPTION
**Pull request by gedl**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When a "latest" file existes locally, the module was ignoring the fact it could be a snapshot for the MD5 check. Latest and snapshot are not a disjunction as the latest version might be (and usually is) a snapshot. 
The change was a simple change in the order the checks are made in "find_uri_for_artifact". If the artifact version is "latest" then we look up the latest version. If it happens to be a snapshot, the following condition will also deal with that properly.
Previously if the latest version lookup came back as a snapshot, the snapshot if statement would not be executed, and therefore time stamp and build number suffixes would not be added. This was causing the subsequent lookup for the artifact to fail, as a the snapshot build file in the remote repository would have the timestamp and build number appended to it.

```
No changes
```

### CODE REVIEW

**Comment by gedl** [comment]
It's the first time a check fails in my PRs but I believe this is unrelated to my change.

Can somebody advise ?

**Comment by gregdek** [comment]
Thanks @gedl for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gedl** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @gedl. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chrisisbeef** [comment]
Nice work @gedl 

shipit

**Comment by gregdek** [comment]
Thanks again to @gedl for this PR, and thanks @chrisisbeef for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
