### PR TITLE
Add a 'requirements:' field to cloudflare_dns doc

### PR DESCRIPTION
**Pull request by alikins**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

network/cloudflare_dns.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 409d95d67e) last updated 2016/07/28 12:58:29 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/07/27 15:10:26 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/07/27 15:10:26 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides


```
##### SUMMARY

cloudflare_dns.py makes use of the python
2.6 features (the string .format() method).

### CODE REVIEW

**Comment by bcoca** [comment]
is there any reason aside from the format that the module cannot support 2.4?

**Comment by alikins** [comment]
Afaict, it's just the .format usage.

But there is a lot of it and I have no way to test the module in anger.

**Comment by gregdek** [comment]
Thanks @alikins for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@alikins A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
