### PR TITLE
Adding install_options to homebrew_cask

### PR DESCRIPTION
**Pull request by enriclluelles**
I just went ahead and did a copycat of what was going in the homebrew module for this

### CODE REVIEW

**Comment by gregdek** [comment]
@danieljaouen Please look at this PR; if you give it a +1, we will merge.

**Comment by enriclluelles** [comment]
@bcoca @gregdek @danieljaouen any chance to merge this?

**Comment by gregdek** [comment]
Let's give @danieljaouen a bit more time to review.

If he doesn't, we will then have to select a new maintainer for the module. But let's give it a bit more time.

**Comment by gregdek** [comment]
OK, looks like @danieljaouen is unavailable to review, and he's the only listed author. I will ask the core team to review. If they accept, @enriclluelles, would you consider becoming maintainer of this module for future pull requests?

**Comment by enriclluelles** [comment]
absolutely

**Comment by oli-g** [comment]
Please merge this, I need it too! :cat:

**Comment by gregdek** [comment]
OK. Time's up!

@enriclluelles you are the new maintainer of this module. :) Before checking it in, though, please do me a favor and your name and Github ID to the authors: field in the documentation. Once you've done that, mark this PR as "ready_for_review" and we'll mark it for inclusion.

**Comment by enriclluelles** [comment]
@gregdek I did what you asked, rebased and solved a minor conflict with the devel branch, but I can't apply the label as I'm not a collaborator of the repo, could you do that for me?

**Comment by gregdek** [comment]
Thanks @enriclluelles. Sorry for the delay in relabelling. 

@danieljaouen Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
We have a new maintainer! Thanks @indrajitr. Please review this PR when you can; see guidelines above.

**Comment by gregdek** [comment]
@danieljaouen This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by indrajitr** [comment]
@gregdek will come back to this, might have to fold #167 with this one.

**Comment by cybertk** [comment]
+1, it's very useful especially for `--appdir`

**Comment by robynbergeron** [comment]
@danieljaouen still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Hm. Bot trouble! We said @indrajitr was the maintainer, but didn't update the maintainers file.

So @indrajitr, this one is on your plate. Give us a needs_revision or shipit as you see fit. Thanks!

**Comment by gregdek** [comment]
@indrajitr This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by indrajitr** [comment]
shipit, of course!

NB: I thought I had commented on this earlier (https://github.com/ansible/ansible-modules-extras/pull/544#issuecomment-162332579), But I forgot to label it with 'shipit', my apologies.

**Comment by elnappo** [comment]
Just as a note. From homebrew cask README:

> Important: At some point in the future Homebrew-cask will change its behaviour from linking apps to moving them. See issue [#13201](https://github.com/caskroom/homebrew-cask/issues/13201) for details.

from issue [#13201](https://github.com/caskroom/homebrew-cask/issues/13201):

> apps will be moved to /Applications by default.

**Comment by enriclluelles** [comment]
@elnappo that's true, but should you need to add pass any other options to brew cask, this branch has all the code you need for that

**Comment by indrajitr** [comment]
Indeed, `appdir` default is changing, but the option would probably be around -- in case the user wants a different location and the cask allows that (without enforcing `require_location`).

Also, as @enriclluelles stated, this (long overdue) fix allows additional cask options to be passed along and brings feature parity with homebrew module.

**Comment by gregdek** [comment]
Hmm, looks like there's a travis issue here -- @enriclluelles can you check that out? When travis passes, comment with ready_for_review and we'll put it back into review. Sorry for the delay.

**Comment by gregdek** [comment]
@enriclluelles A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@enriclluelles Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by indrajitr** [comment]
@gregdek What's the travis issue here? The failed build points to a different module.
I am marking this as ready_for_review _and_ shipit once again and have this retried on travis.

ready_for_review
shipit

**Comment by gregdek** [comment]
The problem is that the PR is so old that it's pulling in a spurious failure from an old branch when it's trying to compare for merge. 

@enriclluelles if you can rebase this against the latest devel, the travis error should go away and we can merge based on @indrajitr review.

Alternately, if @enriclluelles is unavailable, @indrajitr you might consider submitting a new PR with the changes against the latest devel.

**Comment by indrajitr** [comment]
@gregdek, created #2086 that covers this one.

**Comment by gregdek** [comment]
Thanks @enriclluelles for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by indrajitr** [comment]
Now that #2086 has been merged, this can be closed.

**Pull request closed without merging**
