### PR TITLE
Add diff mode output to debconf module

### PR DESCRIPTION
**Pull request by towolf**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

debconf
##### ANSIBLE VERSION

```
ansible 2.2.0 (group_lists_to_group_sets 162cc8179e) last updated 2016/07/06 01:02:16 (GMT +200)
  lib/ansible/modules/core: (devel a8072f9ef0) last updated 2016/06/07 09:13:22 (GMT +200)
  lib/ansible/modules/extras: (add_diff_mode_to_debconf 74b75e7cbd) last updated 2016/07/07 10:58:41 (GMT +200)
  config file = /home/towolf/src/ansible/users/tobias.wolf/ansible.cfg
  configured module search path = ['library']
```
##### SUMMARY

Support diff such that the previous and current settings are visible
without debug output and just with `--diff` if requested.

```
--- before
+++ after
 @@ -1,3 +1,3 @@
 {
-    "debconf/priority": "high"
+    "debconf/priority": "low"
 }

```

Support diff such that the previous and current settings are visible
without debug output and just with `--diff` if requested.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @towolf. To the current maintainers, @bcoca please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by towolf** [comment]
@bcoca, would you merge this for 2.2? It's really simple and my colleague keeps pestering me about it.

**Comment by resmo** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @towolf for this PR, and thanks @bcoca for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
As @bcoca has probably some more core work to do, I reviewed and merged, hopefully that is ok, since it is pretty straight forward change.

Thanks @towolf!

**Pull request merged**
