### PR TITLE
vca_vapp: host is required

### PR DESCRIPTION
**Pull request by soniah**
See line approx 85 of **pyvcloud/vcloudair.py**. It presumes host is
provided and then crashes if not provided.

```
:param host: (str): The vCloud Air Host. Varies by service type.
                  Valid values are https://vchs.vmware.com and https://vca.vmware.com
<snip>
if not (host.startswith('https://') or host.startswith('http://')):
  host = 'https://' + host
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @soniah. @privateip @chrrrles please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by chrrrles** [comment]
Thanks for the bug report and pull request.  This error is actually caused by a bug in module_utils/vca.py - host should only be specified if using the 'vcd' service_type, and this was not properly checked for by the code.  

This should be fixed by this PR:  https://github.com/ansible/ansible/pull/13509

**Comment by chrrrles** [comment]
The PR addressing this bug (https://github.com/ansible/ansible/pull/13509) has been merged with 2.1 - going to talk with team about strategies for cherrypicking this fix (and others) into the other releases.

**Comment by soniah** [comment]
:+1:

**Pull request closed without merging**
