### PR TITLE
Added ec2_ami_find module to search for Amazon AWS EC2 AMI

### PR DESCRIPTION
**Pull request by apolloclark**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

cloud / amazon / ec2_ami_find
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added new module to support searching for EC2 AMI images. This Pull Request is based on a previous one, found here:
https://github.com/ansible/ansible-modules-extras/pull/1710#issuecomment-232686774

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @apolloclark for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
@apolloclark i would maybe take the code that was at https://github.com/ansible/ansible-modules-extras/pull/1710 and use that as a base.

This module should be named "_facts" and be written using boto3 (like the 1710 PR is).

**Comment by bcoca** [comment]
This module already exists in core. https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_ami_find.py

**Comment by apolloclark** [comment]
@bcoca ok, cool, I didn't notice that with the new 2.0 release. Is there a module to do the same type of searching for Autoscaling Groups?

**Pull request closed without merging**
