### PR TITLE
Fix Kubernetes API auth regression from 393e43b8

### PR DESCRIPTION
**Pull request by cao**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

clustering/kubernetes
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

Commit 393e43b8 renames url_username and url_password to username and password, which breaks authentication to a Kubernetes API endpoint as fetch_url() in ansible.module_utils.urls relies on url_username and url_password being set.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by resmo** [comment]
Please removed the commit fc266518934cc337165b91eda1880eeafdea130e . I know the build will fail but this is "ok" in this case.

**Comment by cao** [comment]
Removed commit fc26651.

**Comment by gregdek** [comment]
Thanks @cao for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mattclay** [comment]
Tests on shippable failed because this PR branch was created before shippable was enabled. If you rebase the branch the tests will pass, although in this case the tests will just no-op since there are no tests for this module.

**Comment by cao** [comment]
I rebased my branch to origin/devel, which took care of Shippable.

Travis builds are failing because of the missing `version_added` (which were added in fc26651 but which itself was removed upon request).

**Comment by resmo** [comment]
Thanks @cao, 

One thing I noticed to be done, please set aliases for the "old" args `username` and `password`, in the docs

``` yaml
url_password:
  description:
    - The HTTP Basic Auth password for the API I(endpoint). This should be set unless using the C('insecure') option.
  default: null
  aliases: [ username ]
```

as well in the arg_spec

``` python
...
url_username=dict(default="admin", aliases=['username']),
...
```

**Comment by cao** [comment]
Respective aliases added in 289125e.

**Comment by resmo** [comment]
LGTM

**Pull request merged**
