### PR TITLE
Update sl_vm.py

### PR DESCRIPTION
**Pull request by mlasalmo**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```
##### SUMMARY

```
<!--- Paste verbatim command output here, e.g. before and after your change -->
```

There was a mistype in DATACENTER list with 'lon2', changed to 'lon02'.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mlasalmo. To the current maintainers, @mcltn please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mcltn** [comment]
Thanks @mlasalmo. 

shipit

**Comment by gregdek** [comment]
Thanks again to @mlasalmo for this PR, and thanks @mcltn for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cjbirk** [comment]
How on earth are you supposed to authenticate with this module with no 'api_key' or user/pass option? Why is this not documented?

**Comment by mcltn** [comment]
@cjbirk This module requires you to have the SoftLayer python library installed as well. You then specify your credentials as you would for this library, in a config file. It is not wise to keep your credentials in a playbook it self. Here's a link to the SoftLayer library and instructions to setup a config file. [link](http://softlayer-python.readthedocs.io/en/latest/config_file.html)

**Comment by cjbirk** [comment]
@mcltn Great, except that you should probably let people know they need to export shell variables in order to authenticate.  What if you want to use ansible vault as well? Thanks for the fast reply.

**Pull request merged**
