### PR TITLE
VMware vCenter license module

### PR DESCRIPTION
**Pull request by kamsz**
This PR adds ability to add or remove license for vCenter Server asset.

Playbook

```
- name: Assign license to vCenter
  local_action:
    module: vmware_vcenter_license
    hostname: "{{ vcenter_ip_address }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    license_key: "{{ vcenter_license_key }}"
    state: present
```

Example run:

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0
1 plays in vmware_vcenter_license.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: kamil
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454415448.03-217700199907341 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454415448.03-217700199907341 )" )'
127.0.0.1 PUT /tmp/tmp0PJGEb TO /home/kamil/.ansible/tmp/ansible-tmp-1454415448.03-217700199907341/setup
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/kamil/.ansible/tmp/ansible-tmp-1454415448.03-217700199907341/setup; rm -rf "/home/kamil/.ansible/tmp/ansible-tmp-1454415448.03-217700199907341/" > /dev/null 2>&1'
ok: [localhost]

TASK [Add license] *************************************************************
task path: /home/kamil/Documents/repositories/vmware_vcenter_license.yml:4
ESTABLISH LOCAL CONNECTION FOR USER: kamil
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454415448.32-89207372398986 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454415448.32-89207372398986 )" )'
localhost PUT /tmp/tmpT5Ale_ TO /home/kamil/.ansible/tmp/ansible-tmp-1454415448.32-89207372398986/vmware_vcenter_license
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/kamil/.ansible/tmp/ansible-tmp-1454415448.32-89207372398986/vmware_vcenter_license; rm -rf "/home/kamil/.ansible/tmp/ansible-tmp-1454415448.32-89207372398986/" > /dev/null 2>&1'
changed: [localhost -> localhost] => {"changed": true, "invocation": {"module_args": {"_ansible_check_mode": false, "_ansible_debug": false, "_ansible_diff": false, "_ansible_no_log": false, "_ansible_verbosity": 4, "hostname": "10.91.97.30", "license_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "state": "present", "username": "administrator@vsphere.local"}, "module_name": "vmware_vcenter_license"}}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0

```

### CODE REVIEW

**Comment by sivel** [comment]
@kamsz This PR has failed the travis tests due to missing `RETURN` documentation.  All modules contributed for 2.1 or after are required to have a `RETURN`

**Comment by kamsz** [comment]
@sivel What in case if module returns only "changed"? Should I leave the RETURN statement empty as I did?

**Comment by bcoca** [comment]
i'm looking into adding a common_returns fragments like we do with docs from other modules.

**Comment by kamsz** [comment]
@bcoca Any example so I can follow? Not sure what I should modify.

**Comment by bcoca** [comment]
nothing yet, its still vaporware (its in my head, its a scary and dark place so sometimes it takes time to get things out)

**Comment by gregdek** [comment]
Thanks @kamsz for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by resmo** [comment]
code looks good, however I am missing 'idempotence' 

It seems to me the module just uses a command style add and remove. As a ansible user I would expect the module would check the state and return ok, if no action is needed.

I have no idea if this is possible to query the license first or check if it is different (or handle it by catching the right exception) by the vmware API.

If not, I would make a note, that this module does not support idempotence.

needs_info

**Comment by kamsz** [comment]
@resmo as far as I know it's not possible to retrieve full license key. Because of that it's not possible to compare it with the new key.

**Comment by bcoca** [comment]
you could query the licensemanager info and try to match the data, also if we set a unique label (checksum of license?) it might help

**Comment by gregdek** [comment]
Thanks @kamsz for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@kamsz Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
