### PR TITLE
Add bridge support to nmcli module.

### PR DESCRIPTION
**Pull request by yangliping**
Can add bridge and bridge-slave connection now.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @yangliping. @alcamie101 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@alcamie101 This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@alcamie101 still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Thanks @yangliping for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@yangliping A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by yangliping** [comment]
@gregdek The failing check is related to other cloud modules. It can not be fixed in nmcli network module itself. Do I need to fix bugs in other modules in order to apply this PR?

**Comment by gregdek** [comment]
Sorry @yangliping -- this needs to be rebased to clear the Travis issue.

**Comment by gregdek** [comment]
@yangliping A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@yangliping Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by yangliping** [comment]
@gregdek The errors are relating to centurylink's cloud modules. To fix the Travis CI build failed issue, all centurylink modules have to use ansible.module_utils.urls instead of requests. Somebody should fix those modules first.

# 

./cloud/centurylink/clc_aa_policy.py

# 

ERROR: requests import found, should use ansible.module_utils.urls instead

# 

./cloud/centurylink/clc_alert_policy.py

# 

ERROR: requests import found, should use ansible.module_utils.urls instead

# 

./cloud/centurylink/clc_blueprint_package.py

# 

ERROR: requests import found, should use ansible.module_utils.urls instead

**Comment by gregdek** [comment]
Understood. A good opportunity for you to make those fixes and get the credit, if you so choose. :)

**Comment by gregdek** [comment]
@yangliping A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@yangliping Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@yangliping A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@yangliping Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
