### PR TITLE
Strict-Mode fixes

### PR DESCRIPTION
**Pull request by nitzmahone**
Changes to missing member handling to support running top-level script under Strict-Mode v2 (as Ansible 2.0.0 does now)

cc: @cchurch

### CODE REVIEW

**Comment by chrrrles** [comment]
Possible fix for https://github.com/ansible/ansible-modules-extras/issues/1167

**Comment by petemounce** [comment]
lgtm - passes_guidelines. Have not tested; don't have win2008r2 available right now.

**Comment by gregdek** [comment]
Thanks @petemounce -- assuming you're comfortable that the risk is low here, so marking for inclusion.

**Comment by petemounce** [comment]
@gregdek yup, cool

**Pull request merged**
