### PR TITLE
Packet Host Compute Module

### PR DESCRIPTION
**Pull request by baldwinSPC**
This is a compute module for [Packet Host](https://www.packet.net/). It exposes functionality to create, remove, start, and stop bare-metal servers.

### CODE REVIEW

**Comment by sivel** [comment]
```
============================================================================
./cloud/packet/packet.py
============================================================================
ERROR: No RETURN documentation provided
```

**Comment by baldwinSPC** [comment]
@sivel Looks like we're passing now. Let us know how the review goes and if the PR can be merged or not. /cc @crunchywelch

**Comment by crunchywelch** [comment]
+1 lgtm, very exciting!

**Comment by danehans** [comment]
@baldwinSPC I'm interested in testing the module. I have an ansible an ansible 1.9.4 and 2.0.1.0 test environment and a Packet.net account. How can I go about adding your code to test a deployment?

**Comment by danehans** [comment]
@baldwinSPC looks like I found a doc that will help me test the module [1]. Do you have an example playbook that I can use for testing?

[1] http://docs.ansible.com/ansible/developing_modules.html#module-paths

**Comment by baldwinSPC** [comment]
thanks for helping us test @danehans You should be able to use the following:

https://github.com/StackPointCloud/ansible-modules-extras/blob/feature/packet-server-module/cloud/packet/packet.py#L104-L111

The example below that one shows you how to pass some user-data to the instance, too.

**Comment by baldwinSPC** [comment]
hey @danehans just pinging you to see if you were able to test this out against Packet.

Also, @sivel, will this PR be merged at some point? Or is there anything we need to do to ensure it can be merged? Just wondering if there's something outstanding. Tx.

**Comment by gitschaub** [comment]
@baldwinSPC I'll be testing this out for @danehans and co sometime today (hopefully). I'll hit you up when I have some results.

**Comment by gitschaub** [comment]
@baldwinSPC This is great! I'm excited to get this integrated into one of our projects. Tested with ansible 1.9.4, an issue or two and a few questions:

Issues:
- "present" state creates a new device regardless if their are previous devices. Should only create devices if not already present. 
- If there are multiple nodes with the same hostname, only the first matching node (not sure if deterministic) gets modified. Not sure if hostname duplication is something packet should be preventing, or if this module should capture all nodes with the matching hostname.
- Minor typo in your examples, "name" for device creation should be "hostname". Your documentation reflects requirement correctly. https://github.com/StackPointCloud/ansible-modules-extras/blob/feature/packet-server-module/cloud/packet/packet.py#L118

Questions:
- Do you plan to include ip address management using Packet's API?
- Is it possible to add a parallelization option for tasks with multiple devices? Individual tasks can take quite a long time, especially if we wait for each device to complete before moving to the next.

**Comment by danehans** [comment]
@crunchywelch would appreciate your feedback on ^

**Comment by crunchywelch** [comment]
I'll let @baldwinSPC comment on the Issues listed, as for the Questions, IP address management is available on the API currently, not sure how much work it would be to add to the ansible module. You can also certainly deploy multiple devices at the same time, I'd recommend issuing the device create commands, collecting the instance ids in the responses, and then iterating over those ids to get the provisioning status until they are all done. Does that make sense? Is that what you were asking?

This is very exciting, thanks for the help and interest everyone!

**Comment by danehans** [comment]
@baldwinSPC We are very interested in getting this PR merged. Please let us know if we can be of assistance.

**Comment by baldwinSPC** [comment]
@danehans @crunchywelch @adamschaub Just letting ya'll know I'm seeing the thread, but am tied up with some release stuff on our end for some April things. I hope to circle back to this either this weekend or Monday.

**Comment by danehans** [comment]
@baldwinSPC sounds good. Thanks for the update.

**Comment by gitschaub** [comment]
@crunchywelch Thanks for the response. My questions are more directed towards making use of these aspects of the API inside the module. Would love to see it dispatch device creation in parallel instead of blocking, easily enough done as you've outlined. Love how straight forward the API is.

**Comment by crunchywelch** [comment]
@adamschaub cool, thanks for the kind words! definitely let me know if we can help out with anything on the packet end. cheers!

**Comment by danehans** [comment]
@baldwinSPC How are thing coming along with your release stuff? Are you still planning on coming back to this PR in the near future?

**Comment by baldwinSPC** [comment]
@danehans @adamschaub I'm back on this PR now. Got caught up with some product activity within the company so this had to take a backseat. I'm working on some of the issues now.

**Comment by danehans** [comment]
@baldwinSPC Great to hear. Thanks for the update.

**Comment by aukjan** [comment]
+1

**Comment by baldwinSPC** [comment]
Given this PR has been languishing for some time and the bots keep pinging me, I'm going to go ahead and close this for now. We'll re-open once we have more bandwidth / resources to focus efforts on completing this. Feel free to ping me if there are any questions.

**Pull request closed without merging**
