### PR TITLE
Retention

### PR DESCRIPTION
**Pull request by greg-hellings**
Adds a sub-module to the File section that allows you to define a retention/removal policy for files or folders under a given root.

### CODE REVIEW

**Comment by bcoca** [comment]
doesn't this overlap with find + file modules?

**Comment by greg-hellings** [comment]
You can replicate the results with find + file, but I wouldn't say it overlaps with them. It removes the need to customize sorting and array slicing in the playbooks and gives single-line access to the behavior.

**Comment by bcoca** [comment]
it seems better suited to a role (I need to publish my 'tidy' role), modules that just aggregate what other modules can already do are not really that useful.

**Comment by greg-hellings** [comment]
Why is there a template module, which treads on the ability to do copy + lineinfile? Then why are there any modules outside of shell? The decomposition could become drastic if having a module wrap other functionality is considered a bad idea. :-/

**Comment by bcoca** [comment]
He, I would be happy to delete lineinfile (i always recommend template use above this module). But those are not the same comparisons. 

Shell is there as a fallback for when a module does not exist that can handle an issue, it is not recommended for general use.

If we follow your logic to the other extreme to have a module for every time you can avoid using 2 modules or a module + filter would require us to have millions of modules. Lets keep the discussion from absurd extremes, it is not productive.

**Comment by gregdek** [comment]
Apologies @greg-hellings, but a strong -1 from a core contributor is sufficient grounds to close this PR.

**Comment by greg-hellings** [comment]
I'm still befuddled by @bcoca's opposition. This is not a trivial thing to accomplish with a role. The steps that must be gone through to replicate this module are:

Find appropriate entries within a directory
Store the results
Sort them appropriately
Slice the array
Delete the remainder of the slice

For something as fundamental as retention, this seems worth inserting into a module to me. Is it possible to achieve without a crafted module? Yes. But then again, anything is attainable with only a few basic modules.

Asking people to craft roles to handle logic this complicated seems unnecessary. As someone once told me: Ansible is not a programming language.

**Pull request closed without merging**
