### PR TITLE
Fix bad merge of #555 (mv bigip_gtm_virtual_server)

### PR DESCRIPTION
**Pull request by alikins**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

f5/
network/f5/
network/f5/bigip_gtm_virtual_server.py
##### ANSIBLE VERSION

b6b04795c3fdeccf17eb0556d3f26855755ece2a
##### SUMMARY

When merging https://github.com/ansible/ansible-modules-extras/pull/555, I use 'git format-path' and 'git am' instead of merge/rebase/cherry-pick (I think to avoid some odd rebasing for what was only a new module). I must of applied it from the wrong dir and added it to the wrong top level dir.

This pr moves it to the right place.
And removes the otherwise empty f5/ and it's 0 length **init**.py

f5/ was the wrong directory. Move it to network/f5
and remove f5/.

### CODE REVIEW

**Comment by gundalow** [comment]
Thanks for the quick fix. Looks good (assuming Travis passes)

**Comment by gregdek** [comment]
Thanks @alikins. To the current maintainers, @mhite, @caphrim007 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @alikins for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
