### PR TITLE
Added redrive policy options to sqs_queue

### PR DESCRIPTION
**Pull request by nadirollo**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloud/amazon/sqs_queue
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Adds the possibility to define a redrive policy to configure the SQS queue to send messages to another queue after a specified number of retries.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @nadirollo. To the current maintainers, @loia please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @nadirollo for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nadirollo** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @nadirollo. To the current maintainers, @loia please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by loia** [comment]
Thanks for the PR!  Sorry about the delay on the review.

shipit

**Comment by gregdek** [comment]
Thanks again to @nadirollo for this PR, and thanks @loia for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
