### PR TITLE
Add some more locales to LOCALE_NORMALIZATION

### PR DESCRIPTION
**Pull request by kmalov**
I found some Russian locales missed in system/locale_gen.py dict LOCALE_NORMALIZATION. I added these locales to LOCALE_NORMALIZATION and some more.

### CODE REVIEW

**Comment by gregdek** [comment]
@AugustusKling Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by AugustusKling** [comment]
Looks good to me, so "shipit".

I'm wondering though if the already existing mapping is a good idea at all. Perhaps the problem of the differenct representations could be solved by lowercasing and stripping `-`, too. That would get rid of an ever expanding mapping. I'm just not sure if we can generalize all variants like that.
Such an improvement does not need to hinder the proposed commit, tough.

**Comment by gregdek** [comment]
Thanks @AugustusKling for the review and @kmalov for the patch. Marking for inclusion.

**Comment by kmalov** [comment]
I agree mapping is bad idea but it works. I thought about lowering and
stripping and compared it with number of locales need to be added to
LOCALE_NORMALIZATION. The number of "broken" locales seemed to me quite
small so adding all of them to LOCALE_NORMALIZATION looks better for me
then rewriting fix_case().

2015-08-29 13:26 GMT+03:00 Augustus Kling notifications@github.com:

> Looks good to me, so "shipit".
> 
> I'm wondering though if the already existing mapping is a good idea at
> all. Perhaps the problem of the differenct representations could be solved
> by lowercasing and stripping -, too. That would get rid of an ever
> expanding mapping. I'm just not sure if we can generalize all variants like
> that.
> Such an improvement does not need to hinder the proposed commit, tough.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-extras/pull/890#issuecomment-135968988
> .

## 

Малов Константин
e-mail: constantine.malov@gmail.com
моб.: +7 919 966 222 0

**Comment by gregdek** [comment]
cc: @ansible/core for merge

**Pull request merged**
