### PR TITLE
Add configuration options to VMWare portgroup

### PR DESCRIPTION
**Pull request by camradal**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

vmware
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

VMWare port group module is missing security options that are available through the UI and APIs.
These settings must be set explicitly, as they don't have a default enable/disable value.
Adding following configuration settings:
- Promiscuous Mode
- MAC Address Changes
- Forged Transmits

More info in the [official documentation](https://pubs.vmware.com/vsphere-51/topic/com.vmware.vsphere.networking.doc/GUID-74E2059A-CC5E-4B06-81B5-3881C80E46CE.html)

```
changed: [localhost] => {"changed": true, "invocation": {"module_args": {"forged_transmits": null, "hostname": "10.146.27.244", "mac_changes": null, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "portgroup_name": "network-1", "promiscuous_mode": true, "switch_name": "switch-1", "username": "root", "validate_certs": false, "vlan_id": 0}, "module_name": "vmware_portgroup"}}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @camradal. To the current maintainers, @jcpowermac, @mtnbikenc, @chrrrles please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jcpowermac** [comment]
Looks good to me 👍

**Comment by chrrrles** [comment]
Thanks for the PR -- rather than adding params for every option, I feel it might be better to instead have a single dictionary param for NetworkPolicy.  It would also be nice to see an documentation example for using this new feature.

**Comment by resmo** [comment]
Maintainer has improvement suggestion,  marking this PR in a needs info state.
needs_info

**Comment by gregdek** [comment]
@camradal, a community member requested some information about this PR; for that reason, we put this PR into the 'needs_info' state.

When you have answered the questions, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by camradal** [comment]
I'll resubmit the PR with suggested changes shortly.

**Comment by gregdek** [comment]
@camradal A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by camradal** [comment]
Updated according to @chrrrles suggestions, including network_policy dict setting and better documentatiton.
ready_for_review

**Comment by chrrrles** [comment]
+1!  

Although you should squash these commits.

**Comment by gregdek** [comment]
Thanks again to @camradal for this PR, and thanks @jcpowermac, @mtnbikenc, @chrrrles for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Github has a button for squashing and merging since a couple of months :) Thanks!

**Pull request merged**
