### PR TITLE
Add 'latest' to homebrew_cask_module options

### LINKED ISSUE #1345: homebrew_cask module requires force option
**Issue Type:**

Feature Enhancement

**Summary**

There are situations where you'd want to force reinstall/update casks in order to get the latest security update. Java being a prime example. 
An option to make use of casks --force flag would help perhaps adding **latest** as an option

### PR DESCRIPTION
**Pull request by anthonygreen**
The **latest** option wraps a  `brew update` and `brew cask install --force` to ensure the cask installed is the latest version available

closes #1345

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @anthonygreen. @danieljaouen please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@danieljaouen This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@danieljaouen still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Looks like we changed the owner of this module to @indrajitr and this PR didn't get updated accordingly.

@indrajitr can you take a look and mark as shipit or needs_revision as appropriate? Thanks!

**Comment by indrajitr** [comment]
needs_revision

Overall makes sense. But wondering if we should consider `force: True` instead for the sake of being consistent with other _well-known_ packaging modules to reduce element of surprise.

Besides, `state: latest` usually doesn't imply `--force` switch being passed on to the internal call in any of the packaging modules (apt, homebrew, yum etc.). Since `brew cask` is different in that it doesn't have `state: latest` in conventional sense, we might want to omit that from `state` options anyway.

Also, not sure if we should wrap `brew update` when there is a dedicated module to serve the purpose. Maybe, we can document that instead?

**Comment by gregdek** [comment]
Thanks @anthonygreen for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by anthonygreen** [comment]
@indrajitr I consider it is better for the API to be intention revealing rather than implementation revealing.
If Homebrew Cask were to alter their API the underlying implementation could change without behavioural change

**Comment by gregdek** [comment]
@anthonygreen A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by anthonygreen** [comment]
@gregdek I've commented on the change request

**Comment by indrajitr** [comment]
Like I mentioned, `state: latest` doesn't imply `--force` switch in any of the exiting package modules and this is a considerable deviation (element of surprise) to an user of other package modules. The current [Cask recommendation](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks) is a workaround and is expected to change (note the line: _"We are working on improving this."_ in the instruction).

My suggestion would be to introduce and document usage of `force: True` instead of silently attaching `--force` with `state:latest`. This also allows better control to playbook authors.

Also `brew update` is expected to be subsumed under brew module (without duplication). In general, most overlapping cask functionalities are expected to be gradually folded into parent brew functionalities and cask functionalities are expected to be standard `brew` subcommand.

@gregdek, we should bounce this off with @ansible/core team members and have them weigh in as well.

**Comment by anthonygreen** [comment]
@indrajitr Thanks I hadn't picked up on that. I'll withdraw the PR until the situation with Casks API becomes clear but `force: True` is the wrong way to go. API's should be intention revealing not implementation revealing.

**Pull request closed without merging**
