### PR TITLE
Initial release of bigip_node_rest module.

### PR DESCRIPTION
**Pull request by waffie1**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

bigip_node_rest
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel dd32ba406a) last updated 2016/03/30 13:12:30 (GMT -400)
  lib/ansible/modules/core: (detached HEAD c52f475c64) last updated 2016/03/30 13:12:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 5abb914315) last updated 2016/03/30 13:13:28 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

This is a new module to manage F5 BIG-IP nodes.  This version uses the iControl REST interface instead of the SOAP interface that the current modules use.  I decided to go this route for two reasons.
1. in the bigip_virtual_server module, the protocol and protocol profile are hard coded to TCP.  After trying to edit the existing module to allow for customization of these fields, I discovered that with iControl SOAP, you can set these options on VS creation, but due to circular dependencies in the interface, it cannot be changed later.  iControl SOAP lacks a 'modify' option for the tcp profile like REST and tmsh have.  With only add and remove, you cannot add because it already exists, and you cannot remove due to dependencies(it actually silently fails to remove the tcp profile)  See https://devcentral.f5.com/questions/using-python-bigsuds-for-replacing-tcp-profile for a discussion on this problem.  This may be fixed in a future release, but I require this feature now.  I am also assuming there will be other features that are better implemented in REST than with SOAP.
2. suds is giving me SOAPpy flashbacks with its current support, or lack there of.  Though suds-jurko works well, this is the last network device I have still using SOAP.

Though my current need is a modified bigip_virtual_server, I decided to start with node because it is significantly less difficult to implement.   I also believe I have implemented all available options(as of bigip v11.5.3) for nodes(added ration, rateLimit, connectionLimit, monitor and logging support)

I'm looking for feedback from the community if these are useful to others, or if creating these modules is a waste of time or counter-productive to the efforts of others.

I plan to create REST based modules for all of the following, some of which do not currently exist.
- bigip_monitor
- bigip_pool
- bigip_virtual_server
- bigip_certificate_upload
- bigip_sslprofile
- bigip_config_sync
- gtm_pool
- gtm_wideip

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @waffie1. To the current maintainers, @mhite please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
What I've discussed with @caphrim007 in the past was to add something like a `transport` parameter in which the user can select REST or SOAP rather than having a bunch of duplicate modules. This allows one common module that can support the broadest versions of F5 BIG-IP software and preferred transport.

There are also unfortunately some things that we've come across that can only be done in SOAP and not REST. As we discover these, @caphrim007 attempts to open tickets internally at F5 to get them resolved, but it's not yet a perfect situation.

In any case, I'd love for you to look at how to integrate your potential changes into the existing module rather than asking to submit a new module.

What are your thoughts?

**Comment by caphrim007** [comment]
I would reeeeeeaaaaallly rather not have separate modules for the REST ones. The suds ones should go the way of the dodo. F5's official position is that, while SOAP is not dead, it is certainly being given that stern look saying "please...go die".

So myself and others are absolutely 100% on your side @waffie1. The slightly contentious point about what to do about it is what I have been experimenting with and discussing with @mhite. As noted, neither API is 100% complete and you need to use some combination of both to get everything that you want done.

Additionally, there is the problem that 11.6 was when the REST API went GA. It was available before that, but only as an Early Release, and therefore went through some revs of major breaking changes. To support < 11.6.0, you need to still support SOAP.

My approach to the ansible modules, in general, has been
1. Try to do it in REST (f5-sdk)
2. If you can't do it in REST, try to do it in SOAP (bigsuds)
3. If you cannot do it in SOAP, try to do it over CLI (paramiko)
4. If you can't do it over CLI, raise and Exception.

Note that if you reach anything > 1, myself and the rest of F5 consider that a bug! If you cannot externally open a bug, then please navigate your way to the f5-ansible github repo and open a bug there. I will feed them back to PM and the dev cycle, yada yada yada.

Also, the REST code itself that is coming out of F5 will be using the f5-sdk code as it is what drives our OpenStack LBaaS plugin; more about it can be found here.

https://github.com/F5Networks/f5-common-python

I equate it to something like Shade where Monty put the kibosh on any OpenStack development that did not use shade.

As @mhite mentioned, I (at one point) had a connection param, but due to the nature of needing to support multiple versions and not be able to support all features with a single API (and the need to deprecate APIs in the future), an unholy marriage of both APIs into a single module with bugs being opened to address missing functionality in REST is probably the way we'll go moving forward.

If you want to follow along on module development for unstable F5 ansible modules, I would urge you to check out this repo here.

https://github.com/F5Networks/f5-ansible

In this repo we do rapid development that includes breaking changes and making many poor decisions around design etc etc before we commit to something. When we finally commit to something, then we can try to upstream it in ansible proper.

My reasoning behind this is because ansible deserves stable modules and during their unstable phase, I don't want to clutter their github tracker or mailing list with unnecessary chatter. If you work via the f5-ansible repository, you also get built-in automation testing of your module on multiple platforms as I have the repo hooked up to a test harness in-house.

We could _greatly_ use your help on creating some of the modules you mentioned

bigip_certificate_upload
bigip_sslprofile
bigip_config_sync

as an example.

Would you be willing to join us over there?

**Comment by mhite** [comment]
Sorry, to be clear, the desired outcome is for all new and existing modules to attempt the following:

Try to do it in REST (f5-sdk)
If you can't do it in REST, try to do it in SOAP (bigsuds)
If you cannot do it in SOAP, try to do it over CLI (paramiko)
If you can't do it over CLI, raise and Exception.

We definitely need people to give that a shot for the existing ones and help test the new ones @caphrim007 has baking in the F5-repo (https://github.com/F5Networks/f5-ansible).

To kick this off, I actually have been attempting to begin assembling tests for the existing modules included with Ansible in the spirit of the testing framework @caphrim007 is using in the F5 repo. See https://github.com/mhite/mhite-f5-ansible for that. So just to be clear, there is no point of contention at this point -- only healthy discussion and in the end @caphrim007's suggestion is the right balance between backward compatibility, supporting as many F5 devices as possible, and moving the access method forward to where F5 sees the API platform going. Sorry if I created any confusion with my previous `transport` comment. 

As a side tangent, I'd like to actually get a README.md checked into the f5 directory that's included with Ansible to outline some of this stuff.

**Comment by waffie1** [comment]
I am not opposed to this, it certainly seems like the best option.  I think
I avoided this because of how differently the two APIs are.   I felt like
there were 3 options to accomplish this.
1. Branch the main function based on transport, which I think it probably a
   bad idea.
2. Add a transport branch to the functions that make SOAP API calls to make
   REST calls.  I don't really like this idea, but it seems this least
   intrusive to implement.  It just didn't seem the best way to implement
   REST, and most of the work would be mapping the input/output of REST calls
   to provide the same I/O that the SOAP calls provide to the main function.
3. Take a different approach to try and create a main function that is less
   dependent on the types of calls a particular API needs.

I didn't like the first 2 options, and didn't think option 3 was a good
place to get started with involvement in this project.  I am a network
engineer after all, not a professional programmer, and I am sure my
perspective on this is pretty limited.

So with that, how would you prefer to see a transport option implemented?
If you have a completely different approach you would take, please share.

Kevin

**Comment by waffie1** [comment]
Yes, I will be happy to join you over there.   I'll back off on the
transport option for existing modules and work on the 3 other modules you
said were of interest.

**Comment by caphrim007** [comment]
Thanks @waffie1. We will see you over there

**Comment by gregdek** [comment]
Thanks @waffie1 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@waffie1 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@waffie1 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
