### PR TITLE
a new module named rsyncd can used for managing rsyncd.conf module entries.

### PR DESCRIPTION
**Pull request by rongzeng54**
##### Issue Type:

Please pick one and delete the rest:
- New Module Pull Request
##### Plugin Name:

rsyncd
##### Ansible Version:

```
ansible 1.9.4
```
##### Summary:

Always people need manage the rsyncd.conf file.
Such as one rsync module's path is too open or something is wrong, you need modify it.
Or you need create a new rsync module for rsyncd.
The module will help you.
##### Example output:

```
{
    "changed": true, 
    "module_name": "gen", 
    "rsyncd_file": "/etc/rsyncd.conf"
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @rongzeng54 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by sivel** [comment]
I'm not convinced that this should be a plugin.  It seems easy enough to template this out.  I'm thinking that a role that handles this instead of a new module is preferable.

Additionally, this PR contains another module `pkill.py` which shouldn't be here.

**Comment by rongzeng54** [comment]
Thanks @sivel. You are right. I have delete pkill module.

**Comment by gregdek** [comment]
Thanks @rongzeng54 for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by rongzeng54** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @rongzeng54 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rongzeng54** [comment]
ready_for_review

**Comment by rongzeng54** [comment]
ready_for_review

**Comment by mscherer** [comment]
So, why do you close the PR each time ?

**Comment by gregdek** [comment]
Thanks @rongzeng54 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rongzeng54** [comment]
@mscherer  hey, I so sorry. Because it is the first time i use pull requests. So I am not sure how can I commit the latest version except close it.

**Comment by mscherer** [comment]
You can use git push -f to replace the PR, if you push on the same branch.

**Comment by rongzeng54** [comment]
@mscherer  Got it. Thank you.

**Comment by gregdek** [comment]
Thanks @rongzeng54 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@rongzeng54 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@rongzeng54 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@rongzeng54 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@rongzeng54 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
