### PR TITLE
New AWS module for ec2 direct connect virtual interface facts

### PR DESCRIPTION
**Pull request by naslanidis**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ec2_direct_connect_vif_facts
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f39ad1f13a) last updated 2016/05/01 14:01:36 (GMT +1000)
config file = /etc/ansible/ansible.cfg
configured module search path = ['/usr/share/ansible']
```
##### SUMMARY

This module returns a list virtual interfaces (VIF) facts for all direct connect connections in an account or for specific direct connect connections or VIFs. 

```
TASK [print output] ************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "direct_connect_vifs": [
            {
                "amazon_address": "169.254.251.1/30", 
                "asn": 65002, 
                "auth_key": null, 
                "connection_id": "dxcon-fgwr12cv", 
                "customer_address": "169.254.251.2/30", 
                "customer_router_config": null, 
                "location": "EqSY3", 
                "owner_account": "50225223232440", 
                "route_filter_prefixes": [], 
                "virtual_gateway_id": "vgw-123ebd5b", 
                "virtual_interface_id": "dxvif-ffr0gfds", 
                "virtual_interface_name": "TEWT-VIF1", 
                "virtual_interface_state": "available", 
                "virtual_interface_type": "private", 
                "vlan": 1020
            }
         ]
      }
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @naslanidis for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @naslanidis for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by naslanidis** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @naslanidis for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kalyat** [comment]
shipit

**Comment by ljudzia** [comment]
shipit

**Comment by zhujian0805** [comment]
@naslanidis has this been merged? I'm looking for modules for aws direct connect, looks like this pr is not merged.

**Pull request closed without merging**
