### PR TITLE
Adding the ability to update all zypper packages

### LINKED ISSUE #546: zypper feature request: name=* state=latest
To replicate the yum module functionality please allow for updating all packages.  Arguments to replicate this functionality would be "name=\* state=latest".   The command result would be "zypper update"

### PR DESCRIPTION
**Pull request by andytom**
Adding the option to have zypper update all packaged when name=\* state=latest (similar to the yum module). This resolves #546.

### CODE REVIEW

**Comment by alxgu** [comment]
hey, could you please add the disable_recommends option to the update cmd
" 
if disable_recommends and not old_zypper:
            cmd.append('--no-recommends')
"

**Comment by andytom** [comment]
@alxgu Just pushed that know. Is there anything else that needs to be updated? (I also added myself to the list of authors I hope that is ok).

**Comment by alxgu** [comment]
No, looks good to me

**Comment by robynbergeron** [comment]
Thanks @andytom. @dirtyharrycallahan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by andytom** [comment]
Hi @robynbergeron, @dirtyharrycallahan has asked to be removed as the author of this module (see his comment on  #546). Is it sufficient for @alxgu (the other listed author of this module) to review it?

**Comment by alxgu** [comment]
shipit

**Comment by jasonmader** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @andytom for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @andytom. To the current maintainers, @robinro please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@andytom 
I would close this once #2108 is merged. Your changes are included there. Please let me know if you still think something from this PR is missing in #2108.

**Comment by andytom** [comment]
Closing as this is included in #2108.

**Pull request closed without merging**
