### PR TITLE
add fleet_unit module which manges CoreOS systemd services via Fleet

### PR DESCRIPTION
**Pull request by coderfi**
This PR obsoletes https://github.com/ansible/ansible-modules-extras/pull/91
Also see related PR: https://github.com/ansible/ansible-modules-extras/pull/928

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @coderfi --

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
@jeanmertz @jalev @ahjohannessen @veverjak @johnraz @moperacz -- Some of you had feedback for this in the original PR, #91 -- please note that with the new and improved extras PR review process (detailed in the previous comment), your help in reviewing this can help get it in more quickly :)

Also -- hey, @brianredbeard or @kelseyhightower -- do you guys know anyone who might be a good candidate for reviewing this? :) If so, can you nudge them this way? Thanks! :)

**Comment by gregdek** [comment]
Thanks @coderfi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by coderfi** [comment]
Will do. I'll try to get back to this as soon as I can.

**Comment by gregdek** [comment]
@coderfi A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by coderfi** [comment]
Hmm the build seems to be failing due to something outside of the code I touched.

```
Compiling ./clustering/znode.py ...
  File "./clustering/znode.py", line 123
    command_type = 'op' if 'op' in module.params and module.params['op'] is not None else 'state'
```

The 'clustering' directory doesn't even exist in the ansible-modules-extras repo.

My branch is thousands of commits behind the upstream. Maybe syncing it up will fix this build failure?

**Comment by sivel** [comment]
Yes, you should rebase against the current state of devel.

**Comment by gregdek** [comment]
@coderfi Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by coderfi** [comment]
Aww man, this rebase is tedious, there's like 4 months of conflicts I need to resolve. I'm probably doing something wrong since all I did was add my one file.
Researching my options and will try to resolve this today.

**Comment by coderfi** [comment]
Doesn't seem to be anything 'easy' I could do since it's been months since I forked the repo. Any rebase I try is met with numerous conflicts.
Unless some GIT Ninja can recommend otherwise, I'll just fork the latest devel and submit a new pull request on that.

**Comment by gregdek** [comment]
@coderfi A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@coderfi Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
