### PR TITLE
Add docker_api_version param to docker_login module

### PR DESCRIPTION
**Pull request by jsok**
##### Issue Type:

Please pick one and delete the rest:
- Feature Pull Request
##### Plugin Name:

Name of the `docker_login`
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/jsok/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

Adds the ability to specify the Docker API version as a parameter, much like the core `docker` module.
##### Example usage:

``` yaml
- name: login to private Docker remote registry and force reauthentification
  docker_login:
    docker_api_version: 1.19
    registry: your.private.registry.io
    username: yourself
    password: secrets3
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jsok. @olsaki please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by jsok** [comment]
Hi @olsaki, the code from this PR is almost identical to the docker API version code in the core `docker` module, so it's not exactly original work :)

**Comment by jsok** [comment]
Hi @gregdek @olsaki is this something you are interested in reviewing and merging?

**Comment by gregdek** [comment]
Thanks @jsok for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jsok** [comment]
Looks like `docker_login` has been moved to ansible-modules-core instead. PR is no longer applicable.

**Pull request closed without merging**
