### PR TITLE
Added xenvm and moved xenserver_facts

### PR DESCRIPTION
**Pull request by smokes2345**
Included new module for management of VM's using XenAPI in cloud/xenserver.  Propose also moving xenserver_facts to cloud/xenserver

### CODE REVIEW

**Comment by gregdek** [comment]
@smokes2345 thanks for the PR.

Can I ask that we wait on the move of xenserver_facts until we get the new module accepted? Just pull that from the PR? That will make review easier.

Once you've done that, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by smokes2345** [comment]
Lol, I'm new here.  PR?

**Comment by gregdek** [comment]
@smokes2345 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@smokes2345 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity.

**Pull request closed without merging**
