### PR TITLE
Add ignore_default_opts option to portage module

### PR DESCRIPTION
**Pull request by rramthun**
Add ignore_default_opts option to ignore portage default options set in make.conf. Many Gentoo admins use at least -a (ask) as a default option as described in the Gentoo handbook, which causes ansible to wait indefinitely before executing any command.

### CODE REVIEW

**Comment by mpdehaan** [comment]
Thanks for this...

Wondering if this could be shortened to defaults=yes/no possibly?

Good idea?  Bad idea?

**Comment by rramthun** [comment]
Hi Michael,

thanks for your feedback.

> Wondering if this could be shortened to defaults=yes/no possibly?

I think that could be ambigous which defaults are meant. There are
other "defaults" present in the portage configuration, e.g. the defaults
for make.

For this reason I had named the parameter "portage_default_opts=y/n"
in a first patch, but then we'd loose the consistency between Ansible
module parameter and command line parameter, as it is currently present
in this whole module. Secondly it could be misinterpreted as if
Ansible would set some pre-defined portage default options if not
setting "portage_default_opts=n".

So I decided to leave the module parameter named as the cmd line
parameter, so experienced users can simply mimic their well known manual
invocations with Ansible.

**Comment by bcoca** [comment]
can you rebase this?

**Comment by gregdek** [comment]
@rramthun A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closing this PR due to inactivity. Apologies @rramthun -- if you believe we've closed this in error, please feel free to reopen/rebase or create a new PR.

**Pull request closed without merging**
