### PR TITLE
Allow for hosts listening on all ports to be added to F5 pools

### PR DESCRIPTION
**Pull request by jwitko**
Removing the sanity check for ports less than one and also adding a conditional for when the host is defined and the port is specifically zero (assigning the port Zero was causing the previous conditional to evaluate false).  This is useful for pools where you want a node that listens on multiple ports.

### CODE REVIEW

**Comment by darkrain42** [comment]
It's not quite your problem (since the code was existing), but I'm very confused by what that conditional is checking for, and how it could ever evaluate to True (since it translates, AFAICT, to `if 1 > port and port > 65535`, which is never true).

It seems to me that `if not (0 <= port <= 65535):` would be a clearer check.

But the part I was going to add here is that you didn't update the error message when you updated the conditional.

**Comment by jwitko** [comment]
Hey Darkrain42, Thanks for the feedback!  That is a really strange conditional so I'll clean that up as well as the error message.

**Comment by jwitko** [comment]
Hey Paul,

Thanks for the feedback. I've updated the code to be more clear on the
error check and updated the error message.

Best Regards,

Jason

**Comment by robynbergeron** [comment]
@jwitko -- thanks for submitting this PR.  (And to @darkrain42 for your quick review.)

@mhite -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks! :)

**Comment by mhite** [comment]
Good catch, my bad! Thanks for this.

I'd say squash all those into a single commit and then we can accept it.

Current state: needs_revision.

**Comment by gregdek** [comment]
Thanks @jwitko for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@jwitko A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by jwitko** [comment]
Sorry... I'm unsure how to squash it into a single commit?

**Comment by bcoca** [comment]
`git rebase -i HEAD~5`,  then change pick for s on the last 3 commits

**Comment by gregdek** [comment]
@jwitko Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by jwitko** [comment]
Honestly I have been trying to figure out how to squash these commits.  I no longer have the work station I did the actual work on so I don't have anywhere with the git history to squash.  Maybe it is just easier if I close this and resubmit the changes all in 1 commit?  I really want to get this pushed through but I have to admit I'm struggling on the git 'clean up' portion.

**Comment by gregdek** [comment]
@jwitko honestly, I do that all the time. Git can be mean-spirited, lol. Feel free to close and resubmit.

**Comment by jwitko** [comment]
Closing this as I have opened a cleaner pull request here: https://github.com/ansible/ansible-modules-extras/pull/1912

**Pull request closed without merging**
