### PR TITLE
Fix check mode for blockinfile when 'create: yes' is specified

### LINKED ISSUE #2021: blockinfile: check mode and create: yes does not work when file does not exist yet
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

ansible 2.0.1.0  
  config file = /etc/ansible/ansible.cfg  
  configured module search path = Default w/o overrides 
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

CentOS 7.1.1503
##### SUMMARY

ansible-playbook ... --check
Fails my blockinfile task because the file(s) do not exist yet. The create=yes is properly set and during the run the system responds with "no such file or directory" errors.
##### STEPS TO REPRODUCE

Create a playbook that simply deals with a non-existent file:
- name: just testing
  blockinfile:
      dest: /etc/foobar.conf
      create: yes
      block: |
          Just for fun
          Another line 

Now run ansible-playbook --check on the file
##### EXPECTED RESULTS

The --check will fail because the file doesn't exist.
##### ACTUAL RESULTS

Here's the results from the above with --check -vvv:

```
ESTABLISH LOCAL CONNECTION FOR USER: root                                                                                                             
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626 `" && echo "` echo $HOME/.ansib 
le/tmp/ansible-tmp-1460553033.3-236522183380626 `" )'                                                                                                 
localhost PUT /tmp/tmpjnUhnA TO /root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile                                               
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1460553033.3-23 
6522183380626/blockinfile; rm -rf "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/" > /dev/null 2>&1'                                    
An exception occurred during task execution. The full traceback is:                                                                                   
Traceback (most recent call last):                                                                                                                    
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 2457, in <module>                                              
    main()                                                                                                                                            
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 292, in main                                                   
    msg, changed = check_file_attrs(module, changed, msg)                                                                                             
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 166, in check_file_attrs                                       
    if module.set_file_attributes_if_different(file_args, False):                                                                                     
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1308, in set_file_attributes_if_different                      
    return self.set_fs_attributes_if_different(file_args, changed)                                                                                    
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1300, in set_fs_attributes_if_different                        
    file_args['path'], file_args['mode'], changed                                                                                                     
  File "/root/.ansible/tmp/ansible-tmp-1460553033.3-236522183380626/blockinfile", line 1135, in set_mode_if_different                                 
    path_stat = os.lstat(path)                                                                                                                        
OSError: [Errno 2] No such file or directory: '/etc/foobar.conf'                                                                                      

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "blockinfile"}, "parsed": false} 
```

### PR DESCRIPTION
**Pull request by tonyo**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 734bbcb1d3) last updated 2016/06/10 22:10:02 (GMT +200) 
```
##### SUMMARY

This fixes #2021: when check mode was used with `create: yes` and the file didn't exist, the "No such file or directory" exception was raised while trying to read attributes from a non-existent file.
This PR adds an additional check (`if module.check_mode and not path_exists`) and also a check that returned the 'ok' status when the file doesn't exist, and the 'state: absent' was specified (`if not present and not path_exists`). These changes make the module more consistent with the related 'lineinfile' module.

### CODE REVIEW

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by resmo** [comment]
LGTM

/cc the module author if he wants to review it @yaegashi
/cc the reporter of #2021 if he wants to verify the issue is fixed with this change @AdamAtCSD

**Comment by gregdek** [comment]
Thanks again to @rev112 for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
shipping it.

**Pull request merged**
