### PR TITLE
New module = elb_application_lb

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

elb_application_lb
##### ANSIBLE VERSION

2.3
##### SUMMARY

New module for AWS application ELBs.  I have broken with naming convention compared to the classic elb module ec2_elb_lb because ELB is actually a separate part of boto3 and not part of ec2.  I suggest we rename ec2_elb_lb to elb_classic_lb.

I have also not attempted to merge classic and application load balancers in to one module because they are again separate in boto3 API and operate different enough to warrant two modules.

The module is currently unfinished.  I know there are bugs and modification of listeners doesn't work properly at the moment either but i have created the PR to get some feedback from the community as I imagine this module is probably quite sought after.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @wimnat for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by naslanidis** [comment]
@wimnat 

Is there anything in particular you would like tested or potentially some time spent on?

I'm keen to help get this module over the line as we're keen to replace all of our ELB's.

**Comment by wimnat** [comment]
Anything around idempotentcy.  See what happens after multiple runs with changed and unchanged options and also any options i may of missed.  Same goes for the other module.  Thanks!

**Comment by naslanidis** [comment]
@wimnat 

I've added support for updating attributes and you can now modify listeners in my own copy of your PR.  It's rough for the listener function but it's a tricky one because there's nothing to hook on to when doing comparisons. I updated the example as well but it's pretty straight forward and you can easily diff the changes.

https://github.com/naslanidis/ansible-modules-extras/blob/new_AWS_module_elb_lb_application/cloud/amazon/elb_lb_application.py

**Comment by pierreant-p** [comment]
+1

**Comment by wimnat** [comment]
@shaharmor @naslanidis ready_for_review

**Comment by shaharmor** [comment]
@wimnat 
1. wait_timeout missing default of 300
2. `Port` needs to be converted to int: you can add this to the `for key in listener.keys():` loop at the bottom

```
if key == 'Port':
   listener['Port'] = int(listener['Port'])
```

**Comment by aviboru** [comment]
thanks for the modules, they are definitely helpful.
One quick thing to point out which is just a mistypo i believe:
the module being referred to is "module: elb_lb_application" while the module file is "elb_application_lb.py"
please ignore, if this has already been corrected.

When using ALB module i keep getting the below error, am i missing something ??
"module_name": "elb_application_lb"}, "msg": "An error occurred (InternalFailure) when calling the CreateLoadBalancer operation (reached max retries: 4): Unknown", "response_metadata": {"http_headers": {"connection": "close", "content-length": "241", "content-type": "text/xml", "date": "Fri, 02 Dec 2016 06:44:37 GMT", "x-amzn-requestid": "cb188da0-b85a-11e6-8427-e326c3aae2ba"}, "http_status_code": 500, "max_attempts_reached": true, "request_id": "cb188da0-b85a-11e6-8427-e326c3aae2ba", "retry_attempts": 4}}


note: re-post, as i accidentally commented on target group module page.

**Comment by elnur** [comment]
I'd call it `ec2_alb`. Shorter and to the point.

**Comment by gundalow** [comment]
This PR has been prmoved to https://github.com/ansible/ansible/pull/19491 Reviews there are welcome so we can get it merged. Thanks

**Pull request closed without merging**
