### PR TITLE
adding public ip address to ec2_remote_facts

### PR DESCRIPTION
**Pull request by hslee16**
Seems like the ec2_remote_facts module does not currently provide the public ip address of the instance. 

This PR adds the public ip address.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @hslee16. @michaeljs1990 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@michaeljs1990 This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@michaeljs1990 still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by gregdek** [comment]
Thanks @hslee16 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hslee16 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@hslee16 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hslee16** [comment]
@gregdek seems like the devel branch is failing CI. Should I fork from another branch?

**Comment by hslee16** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @hslee16. To the current maintainers, @michaeljs1990, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by amenonsen** [comment]
Since the maintainers haven't said anything yet, let me just say that this commit works for us, and is pretty trivial (and I view it as fixing an oversight in the existing code). I think it should be applied.

**Comment by wimnat** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @hslee16 for this PR, and thanks @michaeljs1990, @wimnat for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fiunchinho** [comment]
Do you have any estimates about when this will be released?

**Pull request merged**
