### PR TITLE
Added reject_with and uid_owner support to iptables module

### PR DESCRIPTION
**Pull request by LuckyGeck**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @LuckyGeck. @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by LinusU** [comment]
Code looks great, but it will probably conflict with #1402 which currently has the ship it status. Let's rebase as soon as that one gets merged?

**Comment by LuckyGeck** [comment]
No problem. Just tell me when to rebase and resubmit :)

**Comment by LinusU** [comment]
@LuckyGeck #1402 is merged now, would you mind rebasing? Thanks

**Comment by LuckyGeck** [comment]
Not sure if everything went ok, but I rebased my commits according to [this manual](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). Please check, if it's ok now.

**Comment by LinusU** [comment]
Almost right, although you accidentally removed `required: false` from `limit_burst` in your last commit. Fix it by adding in that line again, and then amending your commit.

``` sh
git add system/iptables.py
git commit --amend --no-edit
git push --force
```

**Comment by LuckyGeck** [comment]
Ok, fixed. Thanks

**Comment by LinusU** [comment]
No problem, thank you!

'shipit'

**Comment by LinusU** [comment]
Also, Travis are failing because errors in `cloud/amazon/ec2_vol_facts.py` and `cloud/amazon/ec2_vpc_dhcp_options.py` so it shouldn't be related to this pr...

**Comment by gregdek** [comment]
Thanks again to @LuckyGeck for this PR, and thanks @LinusU for reviewing. Marking for inclusion.

**Comment by resmo** [comment]
Thanks @LuckyGeck for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by LuckyGeck** [comment]
ready_for_review

**Comment by LinusU** [comment]
@LuckyGeck 

``` text
============================================================================
./system/iptables.py
============================================================================
ERROR: version_added for new option (uid_owner) should be 2.1. Currently 0.0
ERROR: version_added for new option (reject_with) should be 2.1. Currently 0.0
```

**Comment by gregdek** [comment]
Thanks @LuckyGeck. To the current maintainers, @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by LinusU** [comment]
'shipit'

**Comment by resmo** [comment]
Thanks again to @LuckyGeck for this PR, and thanks @LinusU for reviewing. Marking for inclusion.

**Pull request merged**
