### PR TITLE
Create elasticache_parameter_group module

### PR DESCRIPTION
**Pull request by frenchfrywpepper**
Created an elasticache_parameter_group module that enables
creation / deletion / modification of the cache_parameter_group.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @jsdalton @defionscode @bennojoy

**Comment by robynbergeron** [comment]
Hi @frenchfrywpepper  -- Adding new process. We will be evaluating all new module PRs according to this process, effective immediately. 

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by frenchfrywpepper** [comment]
@robynbergeron Should I add the tags works_for_me and passes_guidelines myself? Or will someone else be doing that.

**Comment by Etherdaemon** [comment]
Hi @frenchfrywpepper,

I'm trying to use your module but it doesn't appear to support boto profiles?

Play is:

```
- name: Ensure parameter group is created - not using default for flexibilty
  elasticache_parameter_group:
    region: us-west-1
    profile: personal
    state: present
    name: vc-memcached-params
    cache_parameter_group_family: memcached1.4
    description: Memcached Parameter Group
```

Error is:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/Etherdaemon/.ansible/tmp/ansible-tmp-1455844355.54-151778008516129/elasticache_parameter_group", line 2351, in <module>
    main()
  File "/Users/Etherdaemon/.ansible/tmp/ansible-tmp-1455844355.54-151778008516129/elasticache_parameter_group", line 119, in main
    region, ec2_url, aws_connect_kwargs = get_aws_connection_info(module)
  File "/Users/Etherdaemon/.ansible/tmp/ansible-tmp-1455844355.54-151778008516129/elasticache_parameter_group", line 2291, in get_aws_connection_info
    if not boto_supports_profile_name():
  File "/Users/Etherdaemon/.ansible/tmp/ansible-tmp-1455844355.54-151778008516129/elasticache_parameter_group", line 2207, in boto_supports_profile_name
    return hasattr(boto.ec2.EC2Connection, 'profile_name')
AttributeError: 'module' object has no attribute 'ec2'

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "elasticache_parameter_group"}, "parsed": false}
```

**Comment by gregdek** [comment]
Thanks @frenchfrywpepper for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@frenchfrywpepper A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by frenchfrywpepper** [comment]
I hope to have a look at this in the next week and address the feedback.

**Comment by gregdek** [comment]
@frenchfrywpepper Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by frenchfrywpepper** [comment]
@Etherdaemon I'm not able to reproduce what you described. I just tested myself using boto 2.39.0 and the latest ansible devel:HEAD. Can you provide more information about what versions you are using?

**Comment by gregdek** [comment]
@frenchfrywpepper A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@frenchfrywpepper Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@frenchfrywpepper A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
There also would be my attempt to the issue [#2058](https://github.com/ansible/ansible-modules-extras/pull/2058)

**Comment by gregdek** [comment]
@frenchfrywpepper Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
