### PR TITLE
Avi Vantage Ansible Module

### PR DESCRIPTION
**Pull request by grastogi23**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

network/avi
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Avi Vantage Ansible module that provides modules for updating Avi configuration.

```

```

### CODE REVIEW

**Comment by grastogi23** [comment]
As requested by @gregdek, Here is a clean pull request from the avinetworks/ansible-modules-extras. It has 82 new ansible modules.

**Comment by gregdek** [comment]
Thanks @grastogi23 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by grastogi23** [comment]
Hi @gregdek 
The build is failing for python 2.4. Is that a requirement for the modules? 
thanks,
gaurav

"2016-09-28 21:30:47 + python2.4 -m compileall -fq -x '(/cloud/|/clustering/consul._.py|/clustering/znode.py|/database/influxdb/|/database/mssql/|/monitoring/zabbix._.py|/network/f5/|/notification/pushbullet.py|/packaging/language/maven_artifact.py|/packaging/os/dnf.py|/packaging/os/layman.py|/remote_management/ipmi/|/univention/|/web_infrastructure/letsencrypt.py)' .
2016-09-28 21:30:47 Compiling ./network/avi/avi_api_session.py ...
2016-09-28 21:30:47   File "./network/avi/avi_api_session.py", line 155
2016-09-28 21:30:47     gparams = deepcopy(params) if params else {}

**Comment by gregdek** [comment]
Oh... this is actually a new module with 82 new files. That's a very large PR. 

Will need to consult with the Ansible team about this. I don't know that we even have the capacity to review a module submission of this size any time soon.

ping @privateip since this is in the network space

**Comment by grastogi23** [comment]
@gregdek :) yes, we are going full force on it. Ansible Rocks!

**Comment by gregdek** [comment]
@grastogi23 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@grastogi23 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by thaumos** [comment]
@grastogi23 ignore the comment above. It's an automated bot.

**Comment by gregdek** [comment]
@grastogi23 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Closing as replaced by a the above prmoved PR

**Pull request closed without merging**
