### PR TITLE
Filtering out messages from MySQL server

### PR DESCRIPTION
**Pull request by banyek**
You can decide if MySQL server complains should be shown or not. 
You can filter out nogthing/warnings/errors.

### CODE REVIEW

**Comment by bcoca** [comment]
still have the issue with the name as 'all' also seems to filter out errors

**Comment by banyek** [comment]
Oh, now I get what you meant. 
Ok, I'll fix this soon

**Comment by gregdek** [comment]
@banyek According to our new policy, we will auto-merge any changes you request, since you are the author of this module. I'm assuming that you don't want to merge this PR yet because it's not quite right, yes?  In which case, could we close it until you're ready with the new PR?

**Comment by banyek** [comment]
sweet <3

**Pull request closed without merging**
