### PR TITLE
Adding new ec2 security group facts module.

### PR DESCRIPTION
**Pull request by shousper**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ec2_group_facts
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

New module provides EC2 security group facts via boto3.

Implementation essentially exposes the same features as the boto3 API for `describe_security_groups`, including group names, ids and the filters.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @shousper for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by MichaelBaydoun** [comment]
There are three new module pull requests, including this one, that seem to cover the same functionality
https://github.com/ansible/ansible-modules-extras/pull/1939
https://github.com/ansible/ansible-modules-extras/pull/1908
https://github.com/ansible/ansible-modules-extras/pull/1352

**Comment by wimnat** [comment]
I've already reviewed #1908. Can we close this one?

**Comment by gregdek** [comment]
Thanks @shousper for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@shousper A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@shousper Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@shousper A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@shousper Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by shousper** [comment]
Others appear to be working on better solutions. I'll close this off.

**Pull request closed without merging**
