### PR TITLE
add force= option to allow force installation/removal of packages

### PR DESCRIPTION
**Pull request by isotopp**
address issue #881

### CODE REVIEW

**Comment by gregdek** [comment]
@skinp Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@skinp a quick reminder to review this PR when you can :)

**Comment by skinp** [comment]
shipit

**Comment by isotopp** [comment]
\o/

**Comment by gregdek** [comment]
Thanks @isotopp for the patch, and thanks @skinp for the review. Marking for inclusion.

**Comment by bcoca** [comment]
added missing version_added

**Comment by isotopp** [comment]
"version_added" - noted that such a thing exists. Thanks!

**Pull request merged**
