### PR TITLE
added fact modules for clc_group and clc_server modules

### PR DESCRIPTION
**Pull request by popurisiva**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

cloud/centurylink/clc_group_fact.py
clc_server_fact.py
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file =
  configured module search path =
```
##### SUMMARY

New fact modules have been added for centutylink cloud. 
clc_server_fact is a fact module for the existing clc_server module
clc_group_fact is a fact module for the existing clc_group module

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @popurisiva for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@popurisiva A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by popurisiva** [comment]
I will be making changes to the modules shortly to make it ready for review

**Comment by popurisiva** [comment]
@gregdek , I am little confused about the error "ERROR: requests import found, should use ansible.module_utils.urls instead"

Can you please provide a documentation around the best usage of urls in place of requests module?

**Comment by gregdek** [comment]
@popurisiva sorry I missed this. 

"When fetching URLs, please use either fetch_url or open_url from ansible.module_utils.urls rather than urllib2; urllib2 does not natively verify TLS certificates and so is insecure for https."

http://docs.ansible.com/ansible/developing_modules.html

**Comment by popurisiva** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @popurisiva. To the current maintainers, @clc-runner please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jufkes** [comment]
shipit

**Pull request closed without merging**
