### PR TITLE
Adds documentation fragment to bigip modules

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

bigip_\* modules in network/f5
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

This patch removes the common documentation bits and replaces them
with a doc fragment that already exists in core

### CODE REVIEW

**Comment by caphrim007** [comment]
@gundalow the travis error is not related to this PR

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@srvg, @perzizzle, @mhite, @caphrim007, @Etienne-Carriere) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by srgvg** [comment]
shipit

**Comment by perzizzle** [comment]
shipit

**Comment by caphrim007** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @caphrim007. Since you are one of the maintainers (@srvg, @perzizzle, @mhite, @caphrim007, @Etienne-Carriere) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Thanks for rebasing this do Travis is  green. 

I hope using docs_fragments will make it much easier for you.

**Comment by gundalow** [comment]
Merged!

**Pull request merged**
