### PR TITLE
Added parted module

### PR DESCRIPTION
**Pull request by ColOfAbRiX**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

parted
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 89c826df9d) last updated 2016/09/16 15:12:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 48d932643b) last updated 2016/09/16 15:13:15 (GMT +000)
  lib/ansible/modules/extras: (feature/gluster_volume 95f4f52167) last updated 2016/09/19 16:44:19 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The module is a wrapper around the linux command parted intened to work with disk partitions.
The module implements the parted commands as described by command documentation. 
It can be used to read information about the existing configuration, create, update or remove partitions as with the parted command itself

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ColOfAbRiX for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ColOfAbRiX** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ColOfAbRiX for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bbgrk** [comment]
This module would be most welcome.
Or something similar written with parted python api (pyparted).

Thanks!

**Comment by ColOfAbRiX** [comment]
I wasn't aware of that module, it's definitely worth a look, although it would be one more dependency for the module.

I know, meanwhile you can do as I do: configure the `library` variable into `ansible.cfg` and paste this script there.

Hope the Ansible team will have a look at this soon.

**Comment by pshchelo** [comment]
I've been developing something similar too, but this version looks much better, would really like to see this functionality available in Ansible.

@DRN88 pyparted indeed looks cool, but there is one problem - it is not published to PyPI, and thus is not installable with pip. As there are no pre-built wheels, installing it from source requires installation of the whole Python build tool chain, which is quite suboptimal at runtime.
OTOH it is available from system packages (at least I'm seeing one in Ubuntu as 'python-parted' and 'python3-parted'), so might be good to install that way.

@ColOfAbRiX have you considered a possibility to pass several partitions to create in one invocation of the module? (possibly can be done with one invocation to create a partition table if needed and actual partitions via block+with_items, but still...)
As for 'pyparted', you could try/import it, and have two different paths in the code (or may be even two different modules?) as the pyparted-based one will be much cleaner and Pythonic.

**Comment by ColOfAbRiX** [comment]
Thanks @pshchelo.

I though of multiple partitions at the time but I opted for simplicty. This module is a wrapper around parted and in my view, it should be as minimal as possible. I also skipped semantic checks for this reason. For pyparted you're right, it would be more pythonic and this should be a good reason enough, it might be my next work!

I also have to deal with the merge they did of the former two repositories and understand how to get my change migrated.

**Comment by ColOfAbRiX** [comment]
I've migrated the pull request to: https://github.com/ansible/ansible/pull/19812

**Comment by gundalow** [comment]
Reviews welcome on https://github.com/ansible/ansible/pull/20399

**Pull request closed without merging**
