### PR TITLE
Add auth basic support on Zabbix modules (issue #1647)

### PR DESCRIPTION
**Pull request by thelan**
Here is a patch to add auth basic support on zabbix modules.

Please tell me if i need to rebase this patch on another branch.

### CODE REVIEW

**Comment by sivel** [comment]
```
============================================================================
./monitoring/zabbix_group.py
============================================================================
ERROR: version_added for new option (http_login_password) should be 2.1. Currently 0.0
ERROR: version_added for new option (http_login_user) should be 2.1. Currently 0.0

============================================================================
./monitoring/zabbix_host.py
============================================================================
ERROR: version_added for new option (http_login_password) should be 2.1. Currently 0.0
ERROR: version_added for new option (http_login_user) should be 2.1. Currently 0.0

============================================================================
./monitoring/zabbix_hostmacro.py
============================================================================
ERROR: version_added for new option (http_login_password) should be 2.1. Currently 0.0
ERROR: version_added for new option (http_login_user) should be 2.1. Currently 0.0

============================================================================
./monitoring/zabbix_maintenance.py
============================================================================
ERROR: version_added for new option (http_login_password) should be 2.1. Currently 0.0
ERROR: version_added for new option (http_login_user) should be 2.1. Currently 0.0

============================================================================
./monitoring/zabbix_screen.py
============================================================================
ERROR: version_added for new option (http_login_password) should be 2.1. Currently 0.0
ERROR: version_added for new option (http_login_user) should be 2.1. Currently 0.0
```

**Comment by thelan** [comment]
Hello,

I've updated the repository with the missing variable in documentation.

**Comment by eikef** [comment]
needs_revision

**Comment by eikef** [comment]
zabbix_hostmacro will fail due to missing initialization of a variable, and documentation for the added timeout parameter in zabbix_maintenance would be good. Otherwise this looks good. With those two changes, it's ready to ship :)

**Comment by robynbergeron** [comment]
Thanks @thelan. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience.

**Comment by thelan** [comment]
No problem.
As this is my first contribution to such project, i need to familiarize myself with.
I'll review the code based on the previous comment and then update the repository.

**Comment by eikef** [comment]
It might be best to rebase this onto the current devel branch, unless you see a pressing reason to add this feature to the 2.0 branch. From what I can see it looks like it should apply cleanly there, and it would be applied quicker :-)

And no worries, this is also my first time maintaining these modules in this project :-)

**Comment by thelan** [comment]
I'm closing this request in favor of this new: #1748

**Pull request closed without merging**
