### PR TITLE
Add install_args and package_parameters for win_chocolatey module

### PR DESCRIPTION
**Pull request by legleux**
Adds parameters for additional installation arguments for installer packages and package_parameters for chocolatey itself.
Also adds -ignoredependencies flag for installing chocolatey packages whose dependencies are already satisfied, but chocolatey's dependent package is not appropriate (or broken as it were.)

-edit: removed question eleventear answered

### CODE REVIEW

**Comment by gregdek** [comment]
@trondhindenes @petemounce @elventear @smadam813 

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by elventear** [comment]
@legleux I would be better if you documented what you are contributing in the description first, and then ask questions. Or ask the questions on the conversation thread. 

I think the positional parameters are just overzealous programming from my part and from the most part could be removed. I checked the `Choco-Upgrade` function and there is just one place where the positional information is used, but it is not necessary per se.

I don't really understand how they prevented you to do what you wanted, but I don't think it would be an issue if you do away with them if you think that makes the code better. Just make sure it still works after that :smile:.

**Comment by legleux** [comment]
Thanks for the info. I've been out of town for a few weeks and will get my bearings here again. I don't believe it was positional parameters preventing me from doing anything, more of just a design decision question.

**Comment by legleux** [comment]
looks like I did that wrong. I don't want to merge 20 commits, just one!

**Comment by legleux** [comment]
Think I fixed it.

**Comment by robynbergeron** [comment]
Hi @legleux -- thanks for your updates to this PR. And hope you had a lovely out of town trip. :)

@elventear, since you took a look at this previously ... and copying @trondhindenes @petemounce @smadam813 as well -- sending this back to you all for another review.

Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks, everyone!

**Comment by superquadratic** [comment]
How about renaming the parameters to `install_args`, `params` and `ignore_dependencies`?

When looking at other modules, there seems to be a preference for "snake_case" and shorthand names (like [`src`, `dest`](http://docs.ansible.com/ansible/win_copy_module.html#options), [`extra_args`](http://docs.ansible.com/ansible/win_msi_module.html#options)).

**Comment by superquadratic** [comment]
I incorporated my suggestions and some more changes in a new, extended PR: #1295

**Comment by gregdek** [comment]
@smadam813 This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by smadam813** [comment]
I will take a look at this today.  Sorry for the delay.

**Comment by smadam813** [comment]
@gregdek After catching up, this PR can be closed.  #1295 supersedes this PR.

**Comment by gregdek** [comment]
Thanks @legleux for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Thanks @smadam. Closing per your recommendation.

@legleux thanks for submitting the PR, and sorry this one wasn't the one merged, but at least the functionality is in!

**Pull request closed without merging**
