### PR TITLE
Adding params option into the yumrepo module

### PR DESCRIPTION
**Pull request by jtyr**
To address the issue #1305.

### CODE REVIEW

**Comment by jtyr** [comment]
@detiber Please feel free to review it.

**Comment by robynbergeron** [comment]
Hi @jtyr -- thanks for submitting this PR. Since you're the maintainer, we can merge this PR without any other approval -- but if you'd rather wait for @detiber to take a look at it, we can hang on :) I'll check back and see what you'd prefer.

**Comment by jtyr** [comment]
@robynbergeron I would like to wait for @detiber  to test it first.

**Comment by jtyr** [comment]
@detiber Any chance you could test this patch any time soon?

**Comment by detiber** [comment]
@jtyr my apologies for taking so long to reply, I'm not able to give it a run-through right now, but I see no issues with the implementation based on reviewing the diff.

Thanks for adding the feature!

@robynbergeron :+1: from me based on a code review.

**Comment by jtyr** [comment]
@detiber Thanks for the review.

@robynbergeron Please go ahead and merge it. I'm sure @detiber will test it before the Ansible v2.1 is release so we will catch any possible bugs.

**Comment by jtyr** [comment]
@robynbergeron @gregdek @bcoca Please could this be merged?

**Comment by ke3vin** [comment]
I just happened to stumble across this today as it looks like exactly what I need.  I just did a quick test and it looks like it's not quite complete.  I wanted to add the line 'priority=N' to my repo, to use yum_plugin_priorities. The problem is that all of the parameters, including extras defined using this new method, are checked against the 'allowed_params' array, and anything not found there is silently ignored.  So, if your goal is to allow a truly generic list of params, there will need to be additional work done to augment/circumvent the allowed_params check.  If you're merely trying to allow folks to specify only params that are already in the allowed_params array, then your changes are fine as is.
If I come up with something, I'll send an update.

**Comment by jtyr** [comment]
Thanks for testing the patch. The priority parameter is not included as it's not listed in the man page of [yum.conf](http://man7.org/linux/man-pages/man5/yum.conf.5.html). Please could you find where the priority parameter is documented and open a new issue to add it into the `yumrepo` module? Once added, the `params` overrides should allow you to use it.

**Comment by ke3vin** [comment]
Yep, I can certainly do that- the 'priority' parameter is specific to the yum-plugin-priorities plugin.  I was hoping that your intent with this patch was to enable the specification of generic parameters, so that it could support any of the yum plugins out there ( or any to be developed in the future ), without having to update the base yumrepo module each time.

**Comment by jtyr** [comment]
I see. Please let me review it and I will comment here with the result.

**Comment by jtyr** [comment]
I think we should leave this patch as it is. The strict list of parameters have one big advantage - it automatically checks for the type of the input value. If there are plugins which require to add parameters into the `[repository]` section, I'm keen to add them on demand.

@ke3vin please go ahead and create a new issue requesting to add the `priority` parameter.

**Comment by abadger** [comment]
Merged to devel thanks!

**Pull request merged**
