### PR TITLE
Fixed bug of timezone module

### PR DESCRIPTION
**Pull request by tmshn**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
`timezone` module

##### ANSIBLE VERSION
2.2

##### SUMMARY

Fixed the bug of `timezone` module reported in https://github.com/ansible/ansible-modules-extras/pull/3337#issuecomment-263910419.

### CODE REVIEW

**Comment by coreaut** [comment]
@tmshn Hi,
thanks for the patch. With #3572 and #3337 the module is working again.
Sorry for the comment in #3337, I should have read the complete source beforehand :sweat_smile:.

**Comment by gregdek** [comment]
This PR is a work-in-progress. @tmshn, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by gregdek** [comment]
Thanks again to @tmshn. This module is going into community review.

We notice that you are one of the maintainers (@tmshn) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tmshn** [comment]
Okay, it's ready. Plz shipit ⛵️

**Comment by gregdek** [comment]
Thanks @tmshn. Since you are one of the maintainers (@tmshn) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
backported for 2.2.1

**Pull request merged**
