### PR TITLE
mongodb_user login_password with missing login_user not caught

### PR DESCRIPTION
**Pull request by solomongifford**
This fixes issue  #363

### CODE REVIEW

**Comment by solomongifford** [comment]
Ok, all three Issues I reported are represented in this pr, each in its own commit.

**Comment by gregdek** [comment]
@elliotttf please review this PR; if you +1, we will merge

**Comment by elliotttf** [comment]
:+1: I haven't used this in ages but static review looks good to me.

**Comment by gregdek** [comment]
Hmmm... "haven't used in ages" is maybe not the most ringing endorsement I've ever heard, but ok. :)  (If you want to turn over module ownership, maybe @solomongifford  would pick it up?)

Merging. Thanks @elliotttf for the review, and thanks @solomongifford for the PR.

**Comment by elliotttf** [comment]
Indeed. If anyone else wants to take over this, go for it :+1:

**Comment by solomongifford** [comment]
Thanks @elliotttf for the review and @gregdek for the merge.  We are actively using the module so I'd be happy to continue supporting it.  I don't have multiple versions of mongo installed so my weakest contribution will be the backwards compatibility to the older versions of mongo.

**Comment by gregdek** [comment]
Thanks @solomongifford ... I'll add you as the primary "author" for now (I'm strongly considering adding a separate "maintainer" in the docs, but that's for another day.)

**Comment by gregdek** [comment]
Actually, I won't do that -- I'll let you do that. :) @solomongifford please add your pertinent info to the "author" field as a PR and ping me, and I will pull. Thanks!

**Comment by bcoca** [comment]
author is a list, so we can have several entries there

**Pull request merged**
