### PR TITLE
Use ansible-testing project to validate basic module requirements

### PR DESCRIPTION
**Pull request by sivel**
This PR introduces using https://github.com/sivel/ansible-testing to the extras modules.  We can look at extending to core after successful testing on extras.

As of now there are some excluded modules, as they are currently failing the checks.

There are a few PRs/Issues recently opened to address a few of the failures:

~~https://github.com/ansible/ansible-modules-extras/pull/1059~~
~~https://github.com/ansible/ansible-modules-extras/pull/1060~~
~~https://github.com/ansible/ansible-modules-extras/pull/1058~~
~~https://github.com/ansible/ansible-modules-extras/pull/1057~~
~~https://github.com/ansible/ansible-modules-extras/issues/1061~~

cc @gregdek

### CODE REVIEW

**Comment by gregdek** [comment]
Excellent!

**Comment by gregdek** [comment]
And looks like all the PRs associated have been merged as well.

**Comment by gregdek** [comment]
FYI, I'm planning to merge this more or less immediately after the 2.0 release.

**Comment by sivel** [comment]
Sounds good to me.  I figured that was the idea.

**Comment by bcoca** [comment]
so this PR seems to have other commits in it, going to look at remaining update, would like to merge this soon

**Comment by sivel** [comment]
It does have some other commits around fixing very small targeted issues that cause some modules to fail.  In general however I have added exclusions to modules which have larger problems.

**Pull request merged**
