### PR TITLE
add proper 'changed' return, add support for partitioned netscaler

### PR DESCRIPTION
**Pull request by davemac30**
Adds partition support. In order to do this, the module has to maintain a session with the netscaler, hence the introduction of a custom urllib2 opener which has cookie support added. As a by-product, it was fairly trivial to add a status check on the netscaler resource being managed and, therefore, a proper 'changed' status return.

Also adds improved error reporting from netscaler.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @davemac30 -- thanks for submitting this PR. 

@dominis -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks!

**Comment by dominis** [comment]
@robynbergeron I don't want to be a smartass but most of those checks could be automatized and I don't see why I should spend human time checking them manually

**Comment by sivel** [comment]
@dominis we are working on that, however we are not quite there yet.

Additionally, amongst spending human time, you should be actually testing the changes as well.

**Comment by davemac30** [comment]
Hi @robynbergeron, the module doesn't totally adhere to the guidelines. It never did. My PR doesn't make it any better or worse in this regard. I could maybe spend some time tidying it up, however, if @dominis is the ulimate approver, then I'd like his/her buy-in.

**Comment by davemac30** [comment]
@robynbergeron you might as well close this. @dominis clearly is going to bother looking at it. I can work from my fork.

**Comment by bcoca** [comment]
cc @privateip can you give this a once over?
@davemac30 would you be interested in becoming a maintainer of this module?

**Comment by gregdek** [comment]
@dominis it's true that our checks aren't up to snuff quite yet; we'll have those in after we release 2.0, and that will help everyone's efforts. We are continually working to improve our tools for maintainers.

In the meantime, though, as the submitter of this module originally, part of the deal is that you agree to keep the module well-maintained. When we accept your code upstream, we also expect you to be part of the upstream effort to maintain that code. That means responding to issues and pull requests in a timely manner. If you're not willing to do that work, just let me know and I'll remove you as maintainer.

Putting this into pending_action.

**Comment by robynbergeron** [comment]
@dominis still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by robynbergeron** [comment]
@dominis This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by dominis** [comment]
I'm really sorry for the late reply. Unfortunately I have no access to the lovely netscalers anymore so I would be really grateful if someone could continue to maintain this module in the future.

**Comment by gregdek** [comment]
Thanks for the heads up @dominis. 

@davemac30 this is now under review by the core team, which might take a while; thanks for your continued patience.

**Comment by davemac30** [comment]
Thanks @gregdek - good to know.

Actually, though, now I've seen the new network stuff that's coming into Ansible 2.0, I wonder if a completely fresh approach to NetScaler, more in line with the command/config/template pattern is more appropriate than what we have here.

I'm happy to get involved with testing, however, at present, the time available to me to contribute code (not to mention my ability to actually write code) is limited.

**Comment by gundalow** [comment]
@davemac30 In regards to your comment above. The new networking modules got released as part of Ansible 2.2, does that change any of this, see https://www.ansible.com/network-automation for more information. If you've like to discuss this more feel free to join the Network meeting in `#ansible-meetin` see https://github.com/ansible/community/blob/master/MEETINGS.md for schedule and how to add it to the agenda.

**Comment by gregdek** [comment]
Thanks @davemac30 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@davemac30 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
