### PR TITLE
Add logicmonitor.py and logicmonitor_facts.py

### PR DESCRIPTION
**Pull request by woz5999**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @woz5999 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
shipit

**Comment by tima** [comment]
This PR is a continuation of #1441.

**Comment by billcobbler** [comment]
shipit

**Comment by jimi-c** [comment]
Looks good, however there are a lot of documentation formatting errors:

<pre>
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:49: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:52: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:53: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:56: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:58: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:60: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:63: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:67: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:70: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:72: WARNING: Definition list ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:74: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:75: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:78: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:80: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:82: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:85: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:89: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:92: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:94: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:95: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:98: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_facts_module.rst:102: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:49: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:51: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:52: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:55: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:57: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:58: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:61: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:63: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:66: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:67: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:70: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:72: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:74: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:77: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:79: WARNING: Definition list ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:81: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:82: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:85: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:87: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:89: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:92: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:94: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:95: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:98: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:102: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:105: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:109: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:112: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:116: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:119: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:123: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:126: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:128: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:129: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:132: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:134: WARNING: Definition list ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:137: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:138: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:141: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:143: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:144: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:147: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:149: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:154: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:155: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:158: ERROR: Unexpected indentation.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:160: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/devel/ansible/docsite/rst/logicmonitor_module.rst:162: WARNING: Block quote ends without a blank line; unexpected unindent.
</pre>

Please get those cleaned up and we'll merge this in.

**Comment by gregdek** [comment]
@woz5999 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by woz5999** [comment]
Nothing but problems trying to update pull requests and pass travis tests. Looks like I'm opening my third ...

**Pull request closed without merging**
