### PR TITLE
monit: Add retry for pending/initializing services

### PR DESCRIPTION
**Pull request by gaqzi**
If there are already ongoing actions for a process managed by monit, the
module would exit unsuccessfully. It could also give off false positives
because it did not determine whether the service was started/stopped
when it was in a pending state. Which might be turning the service off,
but the action was to start it.

For example "Running - pending stop" would be regarded as the service
running and "state=enabled" would do nothing.

This will make Ansible wait for the state to finalize, or a timeout decided
by the new `max_retries` option, before it decides what to do.

This patch is related to issue #244 and aims to fix it. I'm a bit unsure of 
the procedure to deal with patches between version 2 and 1.9-stable, 
should I create another pull request for 1.9-stable since this is a bug?

### CODE REVIEW

**Comment by bcoca** [comment]
cc @dstoflet

**Comment by gaqzi** [comment]
@mpeters [raised a good point](https://github.com/ansible/ansible-modules-extras/issues/244#issuecomment-108910990) in #244 that we're not waiting around when reloaded is being issued. I'll have a look at it and work at incorporating that with this PR as well.

**Comment by mpeters** [comment]
Currently we don't allow the "pending" status to be valid when doing an "unmonitor" like we do for everything else. That's not a flaw in your patch, but a flaw in the original that can be fixed by this work.

Line 152 should be changed from:

```
if status in ['not monitored']:
```

to

```
if status in ['not monitored'] or 'unmonitor pending' in status:
```

**Comment by gregdek** [comment]
Looks like this needs to be rebased -- also @dstoflet are you available to review?

**Comment by gregdek** [comment]
@gaqzi A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by gregdek** [comment]
Closed due to inaction.

**Comment by gaqzi** [comment]
@gregdek sorry for the late reply. :)

I have now rebased my branch to the current latest. 
Can this be re-opened or should I do a new pull request?

**Comment by bcoca** [comment]
hmm, github is not allowing us to reopen, so I guess you need to resubmit

**Pull request closed without merging**
