### PR TITLE
Feature/ec2 vpc igw

### PR DESCRIPTION
**Pull request by wimnat**
Module by @erydo rebased to latest ansible-modules-extras

For review by @defionscode

Obsoletes PR https://github.com/ansible/ansible-modules-core/pull/321

### CODE REVIEW

**Comment by willthames** [comment]
:+1: lgtm

My only doubt is the name - whether it should be ec2_vpc_internet_gateway or even vpc_internet_gateway (the boto module is boto.vpc, not boto.ec2.vpc after all). But not really a blocker.

**Comment by gregdek** [comment]
+1 from @willthames and the implicit +1 from module owner @wimnat means we should be ready to go. @bcoca give it a final once-over and merge?

**Comment by gregdek** [comment]
Welp, I'm going to test the strength of our policy by not waiting for @bcoca's final once-over. I'm just gonna merge. :)  Thanks @winmat for the code, and thanks @willthames for the review!

**Comment by wimnat** [comment]
Gulp! It's not my code!  Thanks to @erydo -- someone else to blame! haha

**Comment by gregdek** [comment]
Well, @wimnat, I presume you reviewed it before you submitted it.

Right? Right?

**Comment by bcoca** [comment]
aside from adding a default to a required: true field, it all looked ok

**Comment by juliedavila** [comment]
Hmm, so my P/R https://github.com/ansible/ansible-modules-core/pull/1133

Has IGW functionality, given that this was merged in, perhaps I should change my PR to not have IGW functionality?

**Comment by wimnat** [comment]
@defionscode Sorry, I thought that your module took in to account this one along with ec2_vpc_route_table and ec2_vpc_subnet.  I think it's good to actually have igw as a separate module as it is a separate network component of the vpc just like the route tables and subnets.  If you remove it from your PR i think that'd be good.  I'm looking forward to being able to test these 4 new modules :)

**Comment by juliedavila** [comment]
Sure, I have no issues with it. I'll make a round of testing with this
first prior to removing mine then update both PRs accordingly.

**Comment by juliedavila** [comment]
@wimnat refactoring is complete for https://github.com/ansible/ansible-modules-core/pull/1133

Took out IGW functionality

**Pull request merged**
