### PR TITLE
Bug fixes and minor enhancements to CenturyLink cloud modules

### PR DESCRIPTION
**Pull request by popurisiva**
Here is the list of changes
1) Added RETURN doc string for all modules
2) Fixed few typos
3) Fixed a bug with clc_group module to return the right group dict
4) Added the capability to create/update/delete bare metal servers with clc_server module.

### CODE REVIEW

**Comment by gregdek** [comment]
Hi @popurisiva -- could you please go through and add the "author:" field to each of these modules, per the guidelines? We need to make sure that we know who to assign issues and PRs to, and the author: field is the mechanism we use to do that.

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by popurisiva** [comment]
ready_for_review

**Comment by gregdek** [comment]
So if we use @clc-runner as the author here, you @popurisiva will not be authorized to ok merges to these modules. Is that what you want?

**Comment by popurisiva** [comment]
@gregdek , clc-runner is a team account which I am part of. It is associated to our team email alias so anyone can work on the issues reported including me. Hope this answers your question.

**Comment by bcoca** [comment]
@popurisiva the field is a list, so you can add yourself AND the team alias, I'm fine with the current update, feel free to add yourself and others to the authors/maintainers list

**Pull request merged**
