### PR TITLE
Allow any custom chocolatey source

### PR DESCRIPTION
**Pull request by ernstk**
This is to allow for a local source (for instance in the form of artifactory)

### CODE REVIEW

**Comment by petemounce** [comment]
Relates to conversation in #398.

**Comment by gregdek** [comment]
@trondhindenes @petemounce If either of you give it a +1 we will merge.

**Comment by trondhindenes** [comment]
Seems legit. I would maybe make sure that the doc file (win_chocolatey.py) gets updated with the new capabilities aswell.

**Comment by gregdek** [comment]
@trondhindenes should we wait for the capabilities update to merge this patch, or no?

**Comment by trondhindenes** [comment]
Its probably ok to just merge it in, and then have @ernstk do another pr with the documentation update. I'm a sucker for precise documentation :-)

**Comment by ernstk** [comment]
Very happy to do that.

**Comment by ernstk** [comment]
Excuse me @trondhindenes but where exactly do I find the docs to update?

**Comment by gregdek** [comment]
Merged! Thanks @ernstk and thanks @trondhindenes for the review.

**Comment by trondhindenes** [comment]
@ernstk you need to update win_chocolatey.py so that the documentation/examples match the actual functionality of the module.

**Pull request merged**
