### PR TITLE
Fix SNS topic attribute typo

### PR DESCRIPTION
**Pull request by nand0p**
topic_attributes 'Policy' is capitalized

### CODE REVIEW

**Comment by joelthompson** [comment]
:shipit:

**Comment by robynbergeron** [comment]
Thanks @nand0p. @joelthompson please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks again to @nand0p for this PR, and thanks @joelthompson for reviewing. Marking for inclusion.

**Comment by nand0p** [comment]
@joelthompson added myself to authors in this PR, as i feel i have a good understanding of this module after working closely thru it, and would be happy to help maintain. please let me know if this is not appropriate and i should remove.

**Pull request merged**
