### PR TITLE
Escape parameter string before converting to hash table

### PR DESCRIPTION
**Pull request by georgefrank**
Fix for issue https://github.com/ansible/ansible-modules-extras/issues/1195

### CODE REVIEW

**Comment by gregdek** [comment]
@smadam813 Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by smadam813** [comment]
Tested.  Works great, thanks @georgefrank!

@gregdek shipit

**Comment by robynbergeron** [comment]
Marking for inclusion - thanks to @smadam813 for the review and to @georgefrank for the PR, and to @dreamcat4 for the bug report (#1195).

cc @ansible/core team :)

**Comment by nitzmahone** [comment]
@georgefrank Thanks for the fix. One last thing before we merge this - could you squash the 3 commits down to a single? We're merging into two branches (stable-2.0 and devel), so single commits make that process a lot easier.

**Comment by georgefrank** [comment]
It should be down to just one commit now. Thanks!

**Pull request merged**
