### PR TITLE
Filtering out warning levels added

### PR DESCRIPTION
**Pull request by banyek**
If mysql gets replication user data in CHANGE MASTER TO command, it warns user. It is a valid scenario, when you want filter out this messages.

### CODE REVIEW

**Comment by banyek** [comment]
It's still needed to merge I guess

**Comment by bcoca** [comment]
instead of warnings filter this looks more like an errors filter in which you can have a level of warnings

**Comment by banyek** [comment]
Originally it was only a warnings filter, but lately I just add a feature of filter different levels of errors/warnings, true.
Should I rename it?

**Comment by bcoca** [comment]
yes, its not good when a new parameter is misleading

**Pull request closed without merging**
