### PR TITLE
apache2 reload module added

### PR DESCRIPTION
**Pull request by qmaxquique**

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this module to Ansible Extras. 

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by resmo** [comment]
-1
the module functionality already covered by a core module (service).

**Comment by qmaxquique** [comment]
Thank you @resmo . I'm closing this pull request.
How do you do to reload apache gracefully with the service module ? (apachectl graceful)

**Comment by resmo** [comment]
@qmaxquique sorry for not explaining why I gave a -1. no need for closing the PR because of that.

IMHO it is a special case and the service module might not have a graceful but as you mentioned it, you can use `command` as well in a handler. I do not see any benefit to have a separate module for it. Or did I miss anything? Where do you see the benefit?

**Comment by bcoca** [comment]
I would not add a module for every service X special option that service module does not have coded, I would actually look at adding a 'execute with this freeform option' to the service module.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible-modules-core/issues/1616

**Pull request closed without merging**
