### PR TITLE
Fix gw4/gw6 typo

### PR DESCRIPTION
**Pull request by opoplawski**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

nmcli
##### Summary:

Fix gw4/gw6 typo

### CODE REVIEW

**Comment by gregdek** [comment]
@opoplawski this appears to fail travis; please review the travis build failure. When you've fixed this issue, please relabel as ready_for_review and we will put it back into community review. Thanks!

**Comment by gregdek** [comment]
@opoplawski A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@opoplawski Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
The travis failure is from a different change:

```
============================================================================
./windows/win_iis_website.py
============================================================================
ERROR: version_added for new option (site_id) should be 2.1. Currently 0.0
```

Which was fixed https://github.com/ansible/ansible-modules-extras/commit/41a719ce71a02e171c289070c9eb3bae80f36831

I suspect the travis build needs to get restarted somehow.

**Comment by gregdek** [comment]
@opoplawski A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
It seems all checks pass now, so I don't know what else might be a holdup.

**Comment by gregdek** [comment]
@opoplawski Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by opoplawski** [comment]
It would be nice if a human could actually look at this instead just a bot.

**Pull request merged**
