### PR TITLE
Add kube-resource module

### PR DESCRIPTION
**Pull request by ubreu**
- Ansible version of "kubectl" CLI command
- This module allows you to create, delete and update kubernetes resources, such as replication controllers, services, endpoints, namespaces and secrets
- See http://kubernetes.io/ and http://kubernetes.io/v1.1/docs/user-guide/kubectl-overview.html

### CODE REVIEW

**Comment by mscherer** [comment]
Ins't it duplicate with https://github.com/ansible/ansible-modules-extras/pull/1229 ?

**Comment by ubreu** [comment]
@mscherer: Ah I somehow missed that PR! Yes, this module does sth. very similar.

**Comment by robynbergeron** [comment]
Thanks @ubreu for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by sivel** [comment]
Due to the similarity in PRs with #1229 I'm going to go ahead and close this.

**Pull request closed without merging**
