### PR TITLE
grub2_hash new module

### PR DESCRIPTION
**Pull request by dawud**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

grub2_hash
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The OS supplied tool `grub2-mkpasswd-pbkdf2(3)` is interactive by default.
`grub2_hash` generates a PBKDF2 hash suitable for use in a GRUB2 configuration
file.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dawud for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dawud** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @dawud for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @dawud for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dawud** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @dawud for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
