### PR TITLE
Added support for DNS SRV records in 'dnsmadeeasy' module

### PR DESCRIPTION
**Pull request by sysreq0**
This patch implements support for SRV records and catches up with the module's documentation that indicates SRV records are supported, but are actually not per the comment on line 207:

```
# TODO SRV type not yet implemented
```

### CODE REVIEW

**Comment by gregdek** [comment]
@briceburg Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by briceburg** [comment]
shipit

thanks @gregdek and @sysreq0 for the contribution!

**Comment by gregdek** [comment]
Thanks again to @sysreq0 for this PR, and thanks @briceburg for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
SRV type was already documented, does this fix the handling being broken or does it improve on it?

**Comment by briceburg** [comment]
@bcoca I can't test ATM, but this would fix a broken implementation. From memory,  the srv record requires a special payload.

**Comment by briceburg** [comment]
@sysreq0 could you document and/or add an example for handling arv records to the header comments as well? As this stands, it's a bit unclear.

**Comment by sysreq0** [comment]
@bcoca @briceburg  It is indeed documented in the code, but it wasn't implemented. See line 207 for this comment:

```
# TODO SRV type not yet implemented
```

I should probably remove this comment as part of the pull request, now to think of it. This pull request implements support for SRV records and thus catches up with the documentation that's already there.

**Pull request merged**
