### PR TITLE
Add Infiniband support

### PR DESCRIPTION
**Pull request by ke3vin**
This patch adds Infiniband support to the nmcli module

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ke3vin. @alcamie101 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by sivel** [comment]
```
============================================================================
./network/nmcli.py
============================================================================
ERROR: version_added for new option (transport_mode) should be 2.1. Currently 0.0
ERROR: version_added for new option (parent) should be 2.1. Currently 0.0
ERROR: version_added for new option (p_key) should be 2.1. Currently 0.0
```

**Comment by gregdek** [comment]
@alcamie101 This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @ke3vin for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
@ke3vin A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ke3vin** [comment]
Looks like the build is failing with version number issues- I'm not sure how to resolve those.  Is  'version_added' supposed to be updated every time someone adds a parameter to a module?

ready_for_review

**Comment by gregdek** [comment]
@ke3vin when you add new functionality options, as you document those options, you must document the version in which those options were added. The absence of those is why the build is failing. Add them and you'll be back in review. :)

**Comment by gregdek** [comment]
@ke3vin A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ke3vin** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ke3vin. To the current maintainers, @alcamie101 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
