### PR TITLE
add lxc support, without dropping openvz

### PR DESCRIPTION
**Pull request by frogu**
Proxmox VE 4 drops openvz in favour of lxc. This change detects the underlying mechanism and makes the appropraite API call.

### CODE REVIEW

**Comment by gregdek** [comment]
@UnderGreen Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@UnderGreen This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by UnderGreen** [comment]
Looks fine. :shipit: :+1:

**Comment by gregdek** [comment]
Thanks again to @frogu for this PR, and thanks @UnderGreen for reviewing. Marking for inclusion.

**Pull request merged**
