### PR TITLE
Fixes the bigip_selfip module to respect traffic groups

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

network/f5/bigip_selfip.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

The code for traffic groups was not being tested and therefore
had errors associated with it. It is now covered in coverage tests
and bugs that were found in it have been fixed.

See this issue for details
https://github.com/F5Networks/f5-ansible/issues/28

### CODE REVIEW

**Comment by caphrim007** [comment]
@mhite @gundalow for 2.2 merge as part of bugfix process

**Comment by gundalow** [comment]
@mhite Let me know if you are happy with this and I'll merge it

**Comment by mhite** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @caphrim007 for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Bug fix in isolated code so I'm allowing this into 2.2.

**Pull request merged**
