### PR TITLE
new module for sync of s3 buckets

### PR DESCRIPTION
**Pull request by raben2**
ISSUE TYPE

New Module Pull Request

COMPONENT NAME

s3_bucket_sync
ANSIBLE VERSION

2.2

SUMMARY

With this module you can sync the contents of two s3 buckets

### CODE REVIEW

**Comment by tedder** [comment]
re-adding my comment from 1368, fails on OSX with the 1.9.x branch. I added the log at the end.

Is this the correct PR for s3_bucket_sync? I don't remember travis failing + all the merge/rebase commits. Anyhow, it hangs on my OSX machine while running like this:

```
- s3_bucket_sync: bucket_from="test2a-contentbucket-fjotg7jdqshd" bucket_to="test2c-contentbucket-ng8vsl8gmp55" max_processes=4 log=true
```

I think it has finished the uploads (based on my network activity) but there are still a couple processes running:

```
68376 ttys002    0:02.22 .../Python.app/Contents/MacOS/Python /usr/local/bin/ansible-playbook -i localhost, s3copy.yml -vvvv
68406 ttys002    0:00.31 /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 .../s3_bucket_sync; rm -rf /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/ >/dev/null 2>&1
68407 ttys002    0:05.83 .../Python.app/Contents/MacOS/Python /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/s3_bucket_sync
68410 ttys002    0:00.14 .../Python.app/Contents/MacOS/Python /Users/ted/.ansible/tmp/ansible-tmp-1460925805.38-165691623484871/s3_bucket_sync
```

I've used ellipsis to prune the length of those PS lines.

Want to add some logging/debugging to indicate what it's waiting for? Looking in dtruss I see this:

```
68873/0x68d3f:  write_nocancel(0x2, "Exception in thread Thread-3:\nTraceback (most recent call last):\n  File \".../Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 810, in __bootstrap_inner\n    self.run()\n  File \"/usr/local/Cellar/python/2", 0x2F9)    = 761 0
```

I can see a few of those, but there's no more context. Boo for Ansible swallowing so much of the message.

I then ran it against a remote EC2 and got the same behavior- two processes running at the end. This is a small bucket- about 80 little files- so I know it isn't in the middle of a long process:

```
ubuntu    8012  0.0  0.1   4440   640 pts/0    Ss+  21:12   0:00 /bin/sh -c LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/ >/dev/null 2>&1
ubuntu    8013  0.0  3.7 209236 18980 pts/0    Sl+  21:12   0:00 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync
ubuntu    8016  0.0  3.0 278124 15412 pts/0    Sl+  21:12   0:00 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1460927529.39-175618365867305/s3_bucket_sync
```

Here's what the s3_sync looks like:

```
INFO:root:next marker at filename.jpg
INFO:root:##################################
INFO:root:final run reached 79
```

**Comment by raben2** [comment]
dear @tedder i think it is an easy one. The module waits until the first queue is filled up with 100 elements to start the sync itself.
Sorry but i testet it with much bigger buckets. I think i should add a note to the documentation.

**Comment by tedder** [comment]
I don't see a constant of 100 in there anywhere- and in any case, I assume you're going to fix that? Because "must have at least 100 items to use this" is suboptimal.

**Comment by raben2** [comment]
You are right, i was mixing that up with something. It's been a while since i worked on that.

I was just adding the module_exit.json to the ending condition.

**Comment by tedder** [comment]
Yup. Works now.
- worksforme

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
@tedder thanks for the test. It would be great if you can add the "ship_it" flag ;)

**Comment by tedder** [comment]
[I think it needs another reviewer](https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md#new-modules).

**Comment by knorrkator** [comment]
ship_it

**Comment by MichaelBaydoun** [comment]
not sure the bot will pick that up, remove the underscore between ship and it

**Comment by gregdek** [comment]
Thanks @raben2 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @raben2 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
