### PR TITLE
Fix python-consul lock_delay so that invalid units are not required

### LINKED ISSUE #2153: consul_session: consul.session.create() requires a lock_delay without units
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

consul_session
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

```
pip freeze | grep consul
python-consul==0.6.0
```
##### SUMMARY

When creating a consul session, the module requires passing a unit with the `lock_delay` parameter. This is not a valid option in the [underlying python-consul module](http://python-consul.readthedocs.io/en/latest/#consul.base.Consul.Session), which states `lock_delay is an integer of seconds`.

Fix here: https://github.com/quantopian/ansible-modules-extras/commit/763c8f75c19b926618d1a066ec792c058872fd43  
##### STEPS TO REPRODUCE

``` yaml
    - name: Register new session
      consul_session:
        name: "{{ consul_session_name }}"
```

`ansible-playbook -i 'localhost,' -c local consul.yml`
##### EXPECTED RESULTS
- successful playbook execution
- successful creation of a named session in consul
##### ACTUAL RESULTS

```
fatal: [ec2.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"checks": null, "datacenter": null, "delay": "15s", "host": "localhost", "id": null, "name": "foo", "node": null, "port": 8500, "state": "present"}, "module_name": "consul_session"}, "msg": "Could not create/update session No JSON object could be decoded"}
```

A local debug session provided the error:

```
[10] > /usr/lib/python2.7/json/decoder.py(384)raw_decode()
-> raise ValueError("No JSON object could be decoded")
(Pdb++) locals()
{'s': u'Request decode failed: time: unknown unit ss in duration 15ss', 'self': <json.decoder.JSONDecoder object at 0x7f9a3bb48ed0>, 'idx': 0}
```

### PR DESCRIPTION
**Pull request by irlevesque**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

consul_session
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes https://github.com/ansible/ansible-modules-extras/issues/2153

When creating a consul session, the module requires passing a unit with the lock_delay parameter. This is not a valid option in the [underlying python-consul module](http://python-consul.readthedocs.io/en/latest/#consul-session), which states lock_delay is an integer of seconds.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @irlevesque. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tonycapone** [comment]
@sgargan @irlevesque Any idea when this fix will get merged in? The consul_session module is currently broken without it.

**Comment by irlevesque** [comment]
The Travis build failed, but not on any changes in this PR:

```
Applying: make yum module work with older yum for rhel5 :(
Using index info to reconstruct a base tree...
M   yum
<stdin>:16: trailing whitespace.
            my.conf.cache = 0 
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: fix up latest so it behaves like latest should
Using index info to reconstruct a base tree...
M   yum
Falling back to patching base and 3-way merge...
Auto-merging yum
CONFLICT (content): Merge conflict in yum
Failed to merge in the changes.
Patch failed at 0087 fix up latest so it behaves like latest should
The copy of the patch that failed is found in:
   /home/travis/build/ansible/ansible-modules-extras/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

I'm not sure how to trigger another build, other than a no-op commit... @gregdek can you help?

**Comment by gregdek** [comment]
Re-ran travis and it failed again. @irlevesque try rebasing against head. If it still doesn't pass Travis, ping me and we'll look deeper.

**Comment by irlevesque** [comment]
Opened a new PR that's rebased off HEAD: https://github.com/ansible/ansible-modules-extras/pull/2335

**Pull request closed without merging**
