### PR TITLE
Add win_ec2config module for AWS ec2config setup & use

### PR DESCRIPTION
**Pull request by petemounce**
Documentation: http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/UsingConfig_WinAMI.html#UsingConfigXML_WinAMI
Note: This only covers the functionality I needed it to have. There's lots more possible.

### CODE REVIEW

**Comment by gregdek** [comment]
Adding @owner_pr flag because @petemounce is co-owner of other Extras modules

**Comment by gregdek** [comment]
Hey @willthames -- here's a curiosity. Do your proposed AWS guidelines fit with Windows code, or no?

**Comment by willthames** [comment]
@gregdek as currently written, not at all I'm afraid! However, the underlying principles of relying on some common modules that do things like handle security tokens in addition to normal aws keys might be applicable. But the code is so different in powershell compared to python that about the only thing that applies is 'Naming Things'!

**Comment by gregdek** [comment]
Yeah, thought not. Well, if there's any useful reviewing you can do in the context of AWS, feel free -- but we'll probably have to kick over to the Windows crew for an additional review -- @trondhindenes @elventear @jhawkesworth

**Comment by petemounce** [comment]
@gregdek @willthames - are you talking about ansible/ansible-lint?

**Comment by trondhindenes** [comment]
I'm afraid I don't work on AWS atm, so I'm not able to contribute here :-(

**Comment by willthames** [comment]
@petemounce no, the new GUIDELINES.md 
https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/GUIDELINES.md
which I wrote without windows in mind, I'm afraid!

**Comment by gregdek** [comment]
Ah, right. So this intersection of AWS+Windows may prove tricky, as none of our current Windows reviewers are heavy AWS users, and I suspect that none of our AWS reviewers are heavy Windows users.

Hmmm.

Welp! @petemounce it may be that you're doing some pathfinding for us here -- and the point of Extras is to allow us to bring in new modules more easily in these kinds of cases. So let's make sure that the module conforms generally from a syntax/standards POV, and if everyone's happy with that, I'm in favor of just bringing it in.  If it has issues, they'll all come directly to you. :)

**Comment by petemounce** [comment]
That's ok; I'm a heavy AWS+ Windows user. I'm more ignorant about amiable guidelines than those ;-)

**Comment by petemounce** [comment]
Amiable=ansible but with more auto complete :-/

**Comment by petemounce** [comment]
@willthames @gregdek in fact, those guidelines are talking about writing modules that manipulate AWS APIs - this module doesn't do that. This module is about configuring the [AWS Windows ec2config](https://aws.amazon.com/developertools/5562082477397515), which manages things like setting the administrator password according to the EC2 instance's keypair, whether or not to push logs to Cloudwatch, and some other things.

This module essentially 
- arranges for (an incomplete subset of) that configuration to be settable via the module - it writes the XML files that the windows service takes config from.
- allows the ec2config service to be triggered to sysprep the windows instance and make it possible to create an AMI from it

I'm happy for this to be merged on the basis that I'll support it. As I mentioned, it currently just supports the sliver of ec2config that I needed it to.

**Comment by acaire** [comment]
@petemounce Tested fine with 2012 R2, except the Sysprep exec as we bypass it due to slow boot times for ASG instances.

The first example uses 'user_data' and 'password' params (with an invalid example of password) but it looks like you opted for Ec2HandleUserData and Ec2SetPassword instead.  Personally i'd run with 'userdata' and 'password' for simplicity.  Ideally you'd also refer to EC2Config with correct casing.

I'd use this module if you went all out and included all available options especially given PR processing times and release lag, otherwise in my experience it's easier and faster to run the following example 15-line PS, or just template out the file.

```
$EC2SettingsFile="C:\Program Files\Amazon\Ec2ConfigService\Settings\Config.xml"
$xml = [xml](get-content $EC2SettingsFile)
$xmlElement = $xml.get_DocumentElement()
$xmlElementToModify = $xmlElement.Plugins

foreach ($element in $xmlElementToModify.Plugin)
{
    switch ($element.name)
        {
            "Ec2HandleUserData" { $element.State="Enabled" }
            "Ec2SetPassword" { $element.State="Enabled" }
        }
}

$xml.Save($EC2SettingsFile)
```

**Comment by gregdek** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by gregdek** [comment]
@petemounce I'm going to interpret @acaire comments above as "needs_revision".

Please make the suggested revisions, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by gregdek** [comment]
@petemounce A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by petemounce** [comment]
Hey; sorry, yes, I intend to revise.

##

**Comment by shaunbrady** [comment]
@petemounce My company is starting to control Windows instances on EC2.  Would love to see this finished/revised.  Let me know if I can help.

**Comment by gregdek** [comment]
@petemounce Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by petemounce** [comment]
I'm not going to get the time to work on this further in the meantime,
sadly.

##

**Comment by gregdek** [comment]
@petemounce A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@petemounce A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by petemounce** [comment]
I'm not going to get back to this any time soon, sorry.

**Pull request closed without merging**
