### PR TITLE
add password_filter option, to filter out any line containing the wor…

### PR DESCRIPTION
**Pull request by Jmainguy**
…d password

At $work we need to see what changed on a system, but we don't want to see passwords in plaintext, so we filter out the password in puppet runs.

Also we have like 19 lines of Info which is spam and useless to us, so I am filtering it out here as well. If other people actually like those lines I will remove it.

### CODE REVIEW

**Comment by Jmainguy** [comment]
cc @emonty whatcha think

**Comment by emonty** [comment]
lgtm ... @nibalizer

**Comment by gregdek** [comment]
@emonty are you saying ship this, or are you waiting for further feedback?

**Comment by emonty** [comment]
@gregdek further feedback - I'm in the room with the human who needs to look at it now - will shake him in a moment

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Jmainguy** [comment]
@emonty What did the human who looked at it in the room with you say?

**Comment by gregdek** [comment]
Thanks @Jmainguy. @emonty please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@emonty This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Jmainguy** [comment]
@robynbergeron Thank you for the reminder, rebase complete.

**Comment by gregdek** [comment]
Thanks @Jmainguy. @emonty please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@emonty This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@emonty @nibalizer still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by emonty** [comment]
:shipit:

**Comment by nibalizer** [comment]
What info lines are you seeing? Assuming your on an olderish 3.x series you might see an Info line for every pluginsync'd thing, which hopefully we could discard with a more specific regex.

The core of the patch is also dubious to me. Under what parts of Puppet are you logging passwords? If you have execs that log passwords you can set logoutput => false, if you have a custom type/provider you can mark parameters as secret(see the mysql module for an example).

Can you share the examples of getting password output with this module?

**Comment by Jmainguy** [comment]
I currently get 48 lines of info per run where I work. So filtering that out was very desirable for me. Here is what a typical run looks like + what a file with a password would look like.

```
[root@example ~]# puppet agent -t
notice: Ignoring --listen on onetime run
info: Retrieving plugin
info: Loading facts in /var/lib/puppet/lib/facter/candlepin.rb
info: Loading facts in /var/lib/puppet/lib/facter/path.rb
info: Loading facts in /var/lib/puppet/lib/facter/jenkins.rb
info: Loading facts in /var/lib/puppet/lib/facter/facter_jboss_server_peer_id.rb
info: Loading facts in /var/lib/puppet/lib/facter/netmask.rb
info: Loading facts in /var/lib/puppet/lib/facter/juicerversions.rb
info: Loading facts in /var/lib/puppet/lib/facter/example_portal_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/services_tier.rb
info: Loading facts in /var/lib/puppet/lib/facter/nagios_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/ora_connection.rb
info: Loading facts in /var/lib/puppet/lib/facter/rhsversion.rb
info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/yum_proxy.rb
info: Loading facts in /var/lib/puppet/lib/facter/geo.rb
info: Loading facts in /var/lib/puppet/lib/facter/apache_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/aws.rb
info: Loading facts in /var/lib/puppet/lib/facter/misc.rb
info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
info: Loading facts in /var/lib/puppet/lib/facter/concat_basedir.rb
info: Loading facts in /var/lib/puppet/lib/facter/mountpoints.rb
info: Loading facts in /var/lib/puppet/lib/facter/environment_sla.rb
info: Loading facts in /var/lib/puppet/lib/facter/area.rb
info: Loading facts in /var/lib/puppet/lib/facter/hardware_platform.rb
info: Loading facts in /var/lib/puppet/lib/facter/rhev.rb
info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
info: Loading facts in /var/lib/puppet/lib/facter/collectd_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/env.rb
info: Loading facts in /var/lib/puppet/lib/facter/iptables.rb
info: Loading facts in /var/lib/puppet/lib/facter/vdsm_is_configured.rb
info: Loading facts in /var/lib/puppet/lib/facter/os_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/mod_passenger.rb
info: Loading facts in /var/lib/puppet/lib/facter/metrics.rb
info: Loading facts in /var/lib/puppet/lib/facter/mysql.rb
info: Loading facts in /var/lib/puppet/lib/facter/environment.rb
info: Loading facts in /var/lib/puppet/lib/facter/domain.rb
info: Loading facts in /var/lib/puppet/lib/facter/host_details.rb
info: Loading facts in /var/lib/puppet/lib/facter/reversedomain.rb
info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
info: Loading facts in /var/lib/puppet/lib/facter/raid.rb
info: Loading facts in /var/lib/puppet/lib/facter/wwnn_list.rb
info: Loading facts in /var/lib/puppet/lib/facter/physical_interfaces.rb
info: Loading facts in /var/lib/puppet/lib/facter/mta.rb
info: Loading facts in /var/lib/puppet/lib/facter/lvm_support.rb
info: Loading facts in /var/lib/puppet/lib/facter/rhn.rb
info: Loading facts in /var/lib/puppet/lib/facter/primary_interface.rb
info: Caching catalog for example.com
info: Applying configuration version '1456962850'
notice: /File[/etc/motd]/content: 
--- /etc/motd   2016-03-02 20:01:13.323655368 -0500
+++ /tmp/puppet-file20160302-11190-2mz1cp-0 2016-03-02 20:03:10.122665321 -0500
@@ -25,4 +25,3 @@

-password=hunter2

info: FileBucket adding {md5}fa03b2d9096363ba5810fcc5236a8969
info: /File[/etc/motd]: Filebucketed /etc/motd to puppet with sum fa03b2d9096363ba5810fcc5236a8969
notice: /File[/etc/motd]/content: content changed '{md5}fa03b2d9096363ba5810fcc5236a8969' to '{md5}184e0d52dbaecd53fd8999d3bfd25540'
notice: Finished catalog run in 52.22 seconds

[root@example ~]# puppet agent --version
2.7.23
```

As you can see, puppet happily printed out the password I hid inside /etc/motd. As we have many servers and puppet modules written by many authors, we do not know ahead of time every file that could possibly contain a password.

**Comment by nibalizer** [comment]
That is a pretty old puppet yep. End of life even.

I'm pretty sure https://docs.puppetlabs.com/puppet/latest/reference/type.html#file-attribute-show_diff would work either at a global level or a per-resource level. Would that work for you?

**Comment by Jmainguy** [comment]
@nibalizer While that is true, that if we have show_diff false, then passwords wont be exposed. However ${work} wants to see the differences, minus the password. That being said, arbitrarily filtering on the word password will only catch some passwords. passwd wouldn't be caught, token wouldn't be caught, pw= wouldn't be caught etc etc etc.

**Comment by nibalizer** [comment]
Ok. Well so long as you're aware of this being a sortof janky solution I'm ok with it. Can you move the substrs that block out the Info notices behind a different conditional? With those two conditionals in hand, we can probably merge this.

**Comment by Jmainguy** [comment]
@nibalizer Yeah, I think for this to be useful, and catch all magical strings people do not want, I should change filter_password: to filter_regex, and then try and filter out based on the regex they provide. I will update here once I have that in place.

**Comment by nibalizer** [comment]
@Jmainguy oh that's fantastic. Great idea.

**Comment by Jmainguy** [comment]
@nibalizer @emonty Check it out now as filter_regex. Here is an example.

```
[root@phy01 test]# ansible -i hosts all -m puppet
centos7.soh.re | SUCCESS => {
    "changed": false, 
    "rc": 0, 
    "stdout": "Notice: Ignoring --listen on onetime run\nInfo: pointless\nJa Ja\nPassword is neat huh\nI love emonty\n", 
    "stdout_lines": [
        "Notice: Ignoring --listen on onetime run", 
        "Info: pointless", 
        "Ja Ja", 
        "Password is neat huh", 
        "I love emonty"
    ]
}
[root@phy01 test]# ansible -i hosts all -m puppet -a "filter_regex='(?i)Info:.*|(?i).*password.*|(?i)Notice: Ignoring --listen.*'"
centos7.soh.re | SUCCESS => {
    "changed": false, 
    "rc": 0, 
    "stdout": "************Regex filtered out************\n************Regex filtered out************\nJa Ja\n************Regex filtered out************\nI love emonty\n", 
    "stdout_lines": [
        "************Regex filtered out************", 
        "************Regex filtered out************", 
        "Ja Ja", 
        "************Regex filtered out************", 
        "I love emonty"
    ]
}
```

**Comment by nibalizer** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks again to @Jmainguy for this PR, and thanks @emonty @nibalizer for reviewing. Marking for inclusion.

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Jmainguy** [comment]
@gregdek 'ready_for_review'

**Comment by gregdek** [comment]
Thanks @Jmainguy. To the current maintainers, @emonty, @nibalizer please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nibalizer** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks again to @Jmainguy for this PR, and thanks @emonty, @nibalizer for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Jmainguy** [comment]
@gregdek thanks for the heads up, give it a look now.

**Comment by gregdek** [comment]
Thanks @Jmainguy. To the current maintainers, @emonty, @nibalizer please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Jmainguy for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nibalizer** [comment]
Ah sorry I didn't see this back on community review from rebase. :shipit:

**Comment by nibalizer** [comment]
:shipit:

**Comment by Jmainguy** [comment]
I no longer work in a puppet shop and have lost interest. Closing this.

**Pull request closed without merging**
