### PR TITLE
Adds style conventions to bigip_pool

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

network/f5/bigip_pool.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

A number of coding conventions have been adopted for new F5 modules
that are in development. To ensure common usage across the modules,
this module needed to be updated to reflect those conventions.

No functional code changes were made.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @caphrim007 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mattclay** [comment]
Tests on shippable failed because this PR branch was created before shippable was enabled. If you rebase the branch the tests will pass, although in this case the tests will just no-op since there are no tests for this module.

**Comment by caphrim007** [comment]
@mattclay let me do that right now

**Comment by caphrim007** [comment]
@mattclay i rebased on devel and it's still failing??

**Comment by caphrim007** [comment]
@mattclay good to go

**Comment by caphrim007** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @caphrim007. Since you are one of the maintainers (@mhite, @caphrim007) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
