### PR TITLE
ec2_vpc_route_table module: Fixing create / delete order. Correct default value for propagating_vgw_ids

### PR DESCRIPTION
**Pull request by stefanhorning**
##### ISSUE TYPE
- Fixing Pull Request
##### COMPONENT NAME

cloud/amazon/ec2_vpc_route_table.py
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Minimum fixes to make this module work correctly.

### CODE REVIEW

**Comment by stefanhorning** [comment]
Seems simillar to https://github.com/ansible/ansible-modules-extras/pull/1511 although this one is a less intrusive change.

**Comment by gregdek** [comment]
Thanks @stefanhorning. To the current maintainers, @erydo, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanhorning** [comment]
I guess as https://github.com/ansible/ansible-modules-extras/pull/1511 has already received shipit flagging we can close this PR

**Comment by stefanhorning** [comment]
#1511 has finally been merged, closing this one.

**Pull request closed without merging**
