### PR TITLE
Adding modules for ca, keytool, and certificates

### PR DESCRIPTION
**Pull request by zer0glitch**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

ca
certificate
keytool
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /etc/ansible/modules
```
##### SUMMARY

The purpose of this module bundle is to allow for the creation of a Certificate Authority, or utilize an existing Certificate Authority to generate server certificates for IIS, Java keystores, and servers that utilize pem based key and certificates pairs.   Additionally, the certificate module supports create user generated certificates to test against servers that require a certificate to access the system.  

```
ca test:
ansible -i /etc/ansible/hosts glitch -M ../ansible-modules-extras/ -m ca -a 'certdir="./certs" subj="/DC=com/DC=example/CN=CA/"'
glitch | SUCCESS => {
    "changed": true, 
    "changes": [
        "Wrote openssl.cnf file.", 
        "Created private directory.", 
        "Created certs directory.", 
        "Created serial file.", 
        "Created index.txt file", 
        "Created CA certificate.", 
        "Converted CA certificate to DER format."
    ], 
    "success": true
}

# Create a server certificate
ansible -i /etc/ansible/hosts glitch -M ../ansible-modules-extras/ -m   certificate -a 'cadir="./certs" certname="server.example.com" subj="/DC=com/DC=example/CN=server/" p12password="my_super_secret"'
glitch | SUCCESS => {
    "changed": true, 
    "changes": [
        "Created server cnf for server.example.com.", 
        "Created private key for server.example.com.", 
        "Created certificate request for server.example.com", 
        "Signed certificate for server.example.com", 
        "Created key-cert PEM file for server.example.com", 
        "Created PKCS12 version of the Private Key/Certificate Pair for server.example.com"
    ], 
    "success": true
}

# Create a user certificate
ansible -i /etc/ansible/hosts glitch -M ../ansible-modules-extras/ -m   certificate -a 'cadir="./certs"  certname="client.example.com" subj="/DC=com/DC=example/CN=client/" p12password="{{some_env_var}}" certtype="client" p12password="my_super_secret"'
glitch | SUCCESS => {
    "changed": true, 
    "changes": [
        "Created server cnf for client.example.com.", 
        "Created private key for client.example.com.", 
        "Created certificate request for client.example.com", 
        "Signed certificate for client.example.com", 
        "Created key-cert PEM file for client.example.com", 
        "Created PKCS12 version of the Private Key/Certificate Pair for client.example.com"
    ], 
    "success": true
}

# Revoking a certificate
ansible -i /etc/ansible/hosts glitch -M ../ansible-modules-extras/ -m   certificate -a 'cadir="./certs" certname="server.example.com" subj="/DC=com/DC=example/CN=server/" p12password="my_super_secret" state=absent'
glitch | SUCCESS => {
    "changed": true, 
    "changes": [
        "Removed private key for server.example.com.", 
        "Removed certificate request for server.example.com", 
        "Removed certificate for server.example.com", 
        "Removed key-cert PEM file for server.example.com", 
        "Removed PKCS12 version of the Private Key/Certificate Pair for server.example.com"
    ], 
    "success": true
}

ansible -i /etc/ansible/hosts glitch -M ../ansible-modules-extras/ -m keytool -a 'cadir="./certs" certname="host1.example.com" store_password="changeit"  certtype="keystore" src_password="my_super_secret"'
glitch | SUCCESS => {
    "changed": false, 
    "changes": [], 
    "errors": [], 
    "msg": "", 
    "path": "./certs/keystores/host1.example.com.keystore.jks", 
    "state": "absent", 
    "success": true
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @zer0glitch for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by zer0glitch** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @zer0glitch for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bhundven** [comment]
Just curious if this is still on the radar?
It would be nice to not have to write a bunch of custom stuff in a role to use keytool, and just have this in a module.

**Pull request closed without merging**
