### PR TITLE
Support --to-destination for DNAT

### PR DESCRIPTION
**Pull request by Deepakkothandan**
Issue Type:

```
Feature Pull Request
```

Plugin Name:

iptables
Ansible Version:

ansible 2.0.0.2
Summary:

When creating the iptable rule with jump as DNAT, the module fails to execute as --to-destination parameter is not passed to iptables. So added an extra parameter to the module named dnat_destination to specify the destination IP address while specifying a DNAT rule in PREROUTING CHAIN .
Example output:

while specifying jump=DNAT, --to-destination has to be specified else the module fails to excute

### CODE REVIEW

**Comment by resmo** [comment]
Thanks @Deepakkothandan for the PR! The doc for the new argument is missing, it seems it was lost in the merge conflict resolving. Let me know if I can help.

**Comment by gregdek** [comment]
@Deepakkothandan A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Deepakkothandan** [comment]
@gregdek I added the documentation for the new parameter on the very same day

**Comment by gregdek** [comment]
@Deepakkothandan yes, so I see. Thanks for that. You're supposed to let us know by saying "ready_for_review" but our bot didn't tell you that. We have since fixed our bot to tell you that. :) It should go back into community review with the next bot run.

**Comment by gregdek** [comment]
Thanks @Deepakkothandan. To the current maintainers, @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by LinusU** [comment]
I think that there is already an open pull request for this. On mobile so can't link atm...

**Comment by Deepakkothandan** [comment]
Hi Linus, the other pull request was created by me, as it had some issues ,
I was asked close the old PR and create a new PR.. This is the new PR

**Comment by LinusU** [comment]
I was referring to #1971

**Comment by resmo** [comment]
Thanks @Deepakkothandan for your contribution, but the PR #1971 which addresses the same functionality has been merge. Feel free to update your PR if #1971 misses anything.

**Comment by gregdek** [comment]
Thanks @Deepakkothandan for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Deepakkothandan for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Deepakkothandan A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Deepakkothandan** [comment]
@gregdek Another pull request with the same feature has already been merged #1971

**Comment by gregdek** [comment]
Thanks @Deepakkothandan! Closing this one.

**Pull request closed without merging**
