### PR TITLE
New facts module for AWS VPC Peering

### PR DESCRIPTION
**Pull request by Etherdaemon**
Retrieves AWS VPC Peering details using AWS methods. Requires Boto3.
- Gets various details related to AWS VPC Peers
  Filters can be found http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcPeeringConnections.html

### CODE REVIEW

**Comment by mmochan** [comment]
+1 I need this module

**Comment by robynbergeron** [comment]
Thanks @Etherdaemon for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Etherdaemon** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Etherdaemon for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
