### PR TITLE
IRC module: Added style= and more colors.

### PR DESCRIPTION
**Pull request by Jmainguy**
Used to be part of the commit message, and now I edited it to say this

### CODE REVIEW

**Comment by Jmainguy** [comment]
Renamed some of the colors, so some people might have different colors displayed based on existing playbooks, but the colors they enjoyed are still there, just under a new name. Grabbed names and codes from https://github.com/myano/jenni/wiki/IRC-String-Formatting.

**Comment by willthames** [comment]
@Jmainguy can you adhere to standard commit message practices? (short <56 char title, fuller description in the commit message body). Then you PRs won't have truncated titles with the rest overflowing into comments.

**Comment by willthames** [comment]
Presumably you can have coloured and formatted messages at the same time.

I wonder if bold, underline and swap should be a separate argument called e.g. format, so you could have `irc: msg="Hello world" color="green" format="bold"`.

Also, can we make colour an alias for color? :)

Perhaps 'swap' would be better named 'reverse'

**Comment by Jmainguy** [comment]
@willthames added your suggestions. colour alias, I went with style instead of format, changed swap to reverse, and added italic even though it doesn't work in my preferred client, it does work in others.

**Comment by willthames** [comment]
It could still use a `git commit --amend` but I approve of the code changes.

**Pull request merged**
