### PR TITLE
Use filters attribute rather than eni id 

### PR DESCRIPTION
**Pull request by wimnat**
Matches the new ec2_vpc_route_table_facts and ec2_vpc_subnet_facts modules

shipit

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @wimnat -- thanks for the PR.

Marking as owner_pr and ready to ship :)

**Comment by robynbergeron** [comment]
Apparently I am having a day where I can't differentiate between cloud and windows when labeling PRs. Yikes :\

**Comment by bcoca** [comment]
this change breaks backwards compatiblity

**Comment by wimnat** [comment]
The module hasn't been released yet so I think the change is ok

**Pull request merged**
