### PR TITLE
Multiple small fixes to gluster_volume

### PR DESCRIPTION
**Pull request by ottok**
I stated using the GlusterFS module and noticed it was broken in many ways. Now it actually works in a production environment.

### CODE REVIEW

**Comment by gregdek** [comment]
Wait... are you hardcoding IP addresses here? I'm guessing that's not right...

**Comment by ottok** [comment]
@gregdek That line is part of documentation, it is an example and OK

**Comment by gregdek** [comment]
Oh, right. My mistake.

**Comment by gregdek** [comment]
@rosmo Please review this PR; if you give +1, we will merge.

**Comment by rosmo** [comment]
+1 from me, looks good.

**Comment by gregdek** [comment]
Merged. Thanks @ottok and thanks @rosmo for the review!

**Pull request merged**
