### PR TITLE
add monitor configuration to module "bigip_node"

### PR DESCRIPTION
**Pull request by sebfere**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME
- bigip_node
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = ./modules
```
##### SUMMARY

This pull request adds the capability to configure the monitors on the LocalLB Node, based on the [F5 API](https://devcentral.f5.com/wiki/iControl.LocalLB__NodeAddressV2.ashx) and the existing source code to set the monitor configuration on the **bigip_pool** module.

New parameters are:
- monitor_type
- monitors
- quorum

The behavior, sanity checks and error messages are the same as in the module bigip_pool.

Log before:

```
TASK [bigip_node] **************************************************************
task path: /home/sebfere/alm_trunk/plays/bigip/bigip.yml:61
changed: [testserver -> localhost] => {"changed": true, "invocation": {"module_args": {"description": "my test node", "host": "X.X.X.X", "monitor_state": "enabled", "name": "testserver", "partition": "Common", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "server": "bigip.mydomain.com", "session_state": "enabled", "state": "present", "user": "admin", "validate_certs": true}, "module_name": "bigip_node"}}
```

The resulting node fact using **bigip_facts** module:

```
"/Common/testserver": {
    "address": "X.X.X.X", 
    "connection_limit": 0, 
    "description": "my test node", 
    "dynamic_ratio": 1, 
    "monitor_instance": [], 
    "monitor_rule": {
        "monitor_templates": [], 
        "quorum": 0, 
        "type": "MONITOR_RULE_TYPE_NONE"
    }, 
    "monitor_status": "MONITOR_STATUS_UNCHECKED", 
    "object_status": {
        "availability_status": "AVAILABILITY_STATUS_BLUE", 
        "enabled_status": "ENABLED_STATUS_ENABLED", 
        "status_description": "Node address does not have service checking enabled"
    }, 
    "rate_limit": 0, 
    "ratio": 1, 
    "session_status": "SESSION_STATUS_ENABLED"
}
```

Log after:

```
TASK [bigip_node] **************************************************************
task path: /home/sebfere/alm_trunk/plays/bigip/bigip.yml:61
changed: [testserver -> localhost] => {"changed": true, "invocation": {"module_args": {"description": "my test node", "host": "X.X.X.X", "monitor_state": "enabled", "monitor_type": "and_list", "monitors": ["/Common/icmp"], "name": "testserver", "partition": "Common", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "quorum": null, "server": "bigip.mydomain.com", "session_state": "enabled", "state": "present", "user": "admin", "validate_certs": true}, "module_name": "bigip_node"}}
```

The resulting node fact using **bigip_facts** module:

```
"/Common/testserver": {
    "address": "X.X.X.X", 
    "connection_limit": 0, 
    "description": "my test node", 
    "dynamic_ratio": 1, 
    "monitor_instance": [
        {
            "enabled_state": true, 
            "instance": {
                "instance_definition": {
                    "address_type": "ATYPE_EXPLICIT_ADDRESS", 
                    "ipport": {
                        "address": "X.X.X.X", 
                        "port": 0
                    }
                }, 
                "template_name": "/Common/icmp"
            }, 
            "instance_state": "INSTANCE_STATE_UP"
        }
    ], 
    "monitor_rule": {
        "monitor_templates": [
            "/Common/icmp"
        ], 
        "quorum": 0, 
        "type": "MONITOR_RULE_TYPE_SINGLE"
    }, 
    "monitor_status": "MONITOR_STATUS_UP", 
    "object_status": {
        "availability_status": "AVAILABILITY_STATUS_GREEN", 
        "enabled_status": "ENABLED_STATUS_ENABLED", 
        "status_description": "Node address is available"
    }, 
    "rate_limit": 0, 
    "ratio": 1, 
    "session_status": "SESSION_STATUS_ENABLED"
}
```

### CODE REVIEW

**Comment by sebfere** [comment]
Forgot to add labels:
- feature_pull_request
- networking

**Comment by gregdek** [comment]
Thanks @sebfere. To the current maintainers, @mhite please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
Looks good at first glance! I'll give it a quick run this weekend. Would be nice to solicit some community testers, too.

**Comment by mhite** [comment]
I gave it a quick run. Looks good. 

shipit

**Comment by gregdek** [comment]
Thanks again to @sebfere for this PR, and thanks @mhite for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @sebfere for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sebfere** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @sebfere. To the current maintainers, @mhite please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
Ran the following test playbook:

```
---

- name: Create node
  bigip_node:
      server: "{{ inventory_hostname }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: present
      host: "{{ node_host }}"
      name: "{{ node_name }}"
      description: "{{ node_description }}"
      partition: "{{ node_partition }}"
      monitor_type: "{{ node_monitor_type }}"
      monitors: "{{ node_monitors }}"
      quorum: "{{ node_quorum }}"

  register: result
  tags:
    - create

- name: Assert create node
  assert:
    that:
      - result|changed
  tags:
    - create

- name: Create node - idempotent check
  bigip_node:
      server: "{{ inventory_hostname }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      state: present
      host: "{{ node_host }}"
      name: "{{ node_name }}"
      description: "{{ node_description }}"
      partition: "{{ node_partition }}"
      monitor_type: "{{ node_monitor_type }}"
      monitors: "{{ node_monitors }}"
      quorum: "{{ node_quorum }}"
  register: result
  tags:
    - create

- name: Assert create node - idempotent check
  assert:
    that:
      - not result|changed
  tags:
    - create

- name: Change node description
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    name: "{{ node_name  }}"
    description: "new {{ node_description }}"
    partition: "{{ node_partition }}"
  register: result
  tags:
    - update

- name: Assert change node description
  assert:
    that:
      - result|changed
  tags:
    - update

- name: Change session state
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    name: "{{ node_name  }}"
    session_state: disabled
    partition: "{{ node_partition }}"
  register: result
  tags:
    - update

- name: Assert change node session state
  assert:
    that:
      - result|changed
  tags:
    - update

- name: Delete node
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    state: absent
    name: "{{ node_name }}"
    partition: "{{ node_partition }}"
  register: result
  tags:
    - delete

- name: Assert delete node
  assert:
    that:
      - result|changed
  tags:
    - delete

- name: Delete node - idempotent check
  bigip_node:
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    state: absent
    name: "{{ node_name }}"
    partition: "{{ node_partition }}"
  register: result
  tags:
    - delete

- name: Assert delete node - idempotent check
  assert:
    that:
      - not result|changed
  tags:
    - delete
```

Looks good:

```
PLAY [Test the bigip_node module] **********************************************

TASK [__bigip_node : Create node] **********************************************
changed: [REDACTED]

TASK [__bigip_node : Assert create node] ***************************************
ok: [REDACTED]

TASK [__bigip_node : Create node - idempotent check] ***************************
ok: [REDACTED]

TASK [__bigip_node : Assert create node - idempotent check] ********************
ok: [REDACTED]

TASK [__bigip_node : Change node description] **********************************
changed: [REDACTED]

TASK [__bigip_node : Assert change node description] ***************************
ok: [REDACTED]

TASK [__bigip_node : Change session state] *************************************
changed: [REDACTED]

TASK [__bigip_node : Assert change node session state] *************************
ok: [REDACTED]

TASK [__bigip_node : Delete node] **********************************************
changed: [REDACTED]

TASK [__bigip_node : Assert delete node] ***************************************
ok: [REDACTED]

TASK [__bigip_node : Delete node - idempotent check] ***************************
ok: [REDACTED]

TASK [__bigip_node : Assert delete node - idempotent check] ********************
ok: [REDACTED]

PLAY RECAP *********************************************************************
REDACTED    : ok=12   changed=4    unreachable=0    failed=0
```

Can you please squash the various commits into one and resolve the merge conflict Travis seems to be barking about? I think we're good to merge once that is done.

Thank you.

**Comment by mhite** [comment]
needs_revision

**Comment by gregdek** [comment]
Thanks @sebfere for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sebfere** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @sebfere. To the current maintainers, @mhite, @caphrim007 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
shipit

**Comment by caphrim007** [comment]
@sebfere can you add some examples to the EXAMPLES documentation block?

**Comment by gregdek** [comment]
Thanks again to @sebfere for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
And yes, enhancing the examples string is always appreciated!

**Comment by gregdek** [comment]
Thanks @sebfere for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sebfere** [comment]
Added an example with a single monitor.
Thanks for the reminder, quickly figure out how to use a module is indeed great ;)

**Comment by sebfere** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @sebfere. To the current maintainers, @mhite, @caphrim007 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
Looks good, but needs to be squashed into one commit.

needs_revision

**Comment by sebfere** [comment]
@mhite this is already one commit, the other ones are merges from remote-tracking branch.
My contribution applies only on the bigip_node file.

Should I also merge all these together ?

**Comment by mhite** [comment]
Yeah, we don't want the merge commits.

**Comment by sebfere** [comment]
So, ready to ship it ? Don't want an extra rebase ;)

**Comment by mhite** [comment]
Code looks good, but there are 5 merge commits present in the commit history. My understanding is that we don't want that in there.

**Comment by caphrim007** [comment]
+1 squash them please

**Comment by gregdek** [comment]
Thanks again to @sebfere for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
Discussed this briefly in #ansible-devel -- folks there are under the impression that new GitHub PR merge/squash functionality discussed in https://github.com/blog/2141-squash-your-commits will address the issue.

**Pull request merged**
