### PR TITLE
Added a source parameter for setting the JIT client name

### PR DESCRIPTION
**Pull request by foozmeat**
/cc @andsens @mbobakov @DazWorrall @abadger

### CODE REVIEW

**Comment by andsens** [comment]
Looks great!

shipit

**Comment by robynbergeron** [comment]
Thanks @foozmeat. @andsens please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
Thanks again to @foozmeat for this PR, and thanks @andsens for reviewing. Marking for inclusion.

**Comment by gregdek** [comment]
ping @ansible/core team for this shipit

**Pull request merged**
