### PR TITLE
Fix problem with 'restarted' state not restarting the apppool when it is in running state

### PR DESCRIPTION
**Pull request by nlandais**
Scenario: I have a webappool running but I need to recycle it after making a config change.
Problem: In the current implementation, a restart does not happen when  my app pool is running since the Start-WebAppPool cmdlet is used to  perform the recycling action.
Proposed fix: Invoke the Restart-WebAppPool cmdlet to restart an App Pool regardless of App Pool running state

### CODE REVIEW

**Comment by robynbergeron** [comment]
@nlandais -- thanks for submitting this PR.

@whenrik -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks!

**Comment by henrikwallstrom** [comment]
shipit

**Comment by henrikwallstrom** [comment]
@nlandais thanks for the PR!

**Comment by gregdek** [comment]
Thanks again to @nlandais for this PR, and thanks @whenrik for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
@nlandais could you flatten these commits?

**Comment by nlandais** [comment]
@bcoca Done

**Comment by bcoca** [comment]
i'm still seeing 12 commits

**Comment by nlandais** [comment]
Messed up the rebasing, closing the pull request and re-opened as #1371. Sorry

**Pull request closed without merging**
