### PR TITLE
fixes issue creating table when no range_key_name is defined 

### PR DESCRIPTION
**Pull request by sclausson**
Issue: https://github.com/ansible/ansible-modules-extras/issues/841

### CODE REVIEW

**Comment by sclausson** [comment]
Looks like something was wrong with CI so closing/re-opening

**Comment by gregdek** [comment]
@loia Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by sclausson** [comment]
shipit

**Comment by gregdek** [comment]
@loia ping -- are you available to review this PR?

**Comment by loia** [comment]
@gregdek Sorry for the delay, looks good to me.

shipit

**Comment by gregdek** [comment]
Thanks @loia for the review, and thanks @sclausson for the PR. Marking for inclusion.

**Comment by gregdek** [comment]
cc: @ansible/core for merge

**Pull request merged**
