### PR TITLE
Metadata for extras modules

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
Metadata for all modules

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @abadger for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by gundalow — APPROVED** [review]
ship_it

**Comment by abadger** [comment]
Refreshed the metadata with the latest list of modules, support-owner, and status.

The following 32 modules were not listed in the list and therefore received the default metadata:
```
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/cloudstack/cs_region.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_affinity_labels.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_affinity_labels_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_clusters.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_clusters_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_datacenters.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_datacenters_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_external_providers.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_external_providers_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_groups.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_groups_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_mac_pools.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_networks.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_networks_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_nics.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_nics_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_permissions.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_permissions_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_quotas.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_quotas_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_storage_domains.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_storage_domains_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_templates.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_templates_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_users.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_users_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_vmpools.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_vmpools_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/cloud/ovirt/ovirt_vms_facts.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/database/postgresql/postgresql_schema.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/network/a10/a10_server_axapi3.py',
 '/srv/ansible/vanilla/lib/ansible/modules/extras/network/ipinfoio_facts.py'
```

**Comment by abadger** [comment]
Merged

**Pull request merged**
