### PR TITLE
Let's Encrypt module

### LINKED ISSUE #1545: Enhancement idea: Let's Encrypt module
I've seen various people implement their own, but I'd love to see this as either an Extras module to start, or ideally a Core module in the long term.

HTTPS is viable, and free. :-)

### PR DESCRIPTION
**Pull request by mgruener**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

letsencrypt
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 848b015ce6) last updated 2016/05/08 20:41:33 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/08 21:10:26 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 431591c2b4) last updated 2016/05/08 21:10:26 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

This module allows the management off ssl certificates using Let's Encrypt or basically any
service using the ACME protocol. Right now this module is based on draft 02 of the ACME
protocol ([draft-ietf-acme-acme-02](https://tools.ietf.org/html/draft-ietf-acme-acme-02)).

Tests (which might need some more work) can be found at https://github.com/mgruener/ansible/blob/tests_letsencrypt/test/integration/roles/test_letsencrypt/tasks/main.yml

Hopefully having a native module for this in ansible will help bringing the great work the guys
at Let's Encrypt do to even more people.

Fixes #1545

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mgruener for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
This PR is a work-in-progress. @mgruener, when you're ready to have this PR reviewed, please remove WIP from the title of the PR.

**Comment by mgruener** [comment]
Ready for review @gregdek

**Comment by gregdek** [comment]
Thanks @mgruener for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mgruener for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgruener** [comment]
@gregdek ready_for_review

**Comment by gregdek** [comment]
Thanks @mgruener for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
great module thanks! 
shipit

**Comment by evgkrsk** [comment]
shipit

**Comment by resmo** [comment]
good job @mgruener, thanks for reviewing @raben2 @evgkrsk

**Pull request merged**
