### PR TITLE
Define external_ids ’type' in openvswitch_bridge

### PR DESCRIPTION
**Pull request by blake**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

openvswitch_bridge
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/blake/Documents/p/autodeploy/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The external_ids 'type' was not defined in the argument spec of openvswitch_bridge. This caused 'external_ids' to be converted to a string leading to an error when later calling exp_external_ids.items().

```
Before:
TASK [Set OVS bridge external-id] ********************************
fatal: [192.0.2.1]: FAILED! => {"changed": false, "failed": true, "msg": "'str' object has no attribute 'items'"}

After:
TASK [Set OVS bridge external-id] *******************
changed: [192.0.2.1]
```

This commit fixes this issue.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @blake. To the current maintainers, @stygstra please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
shipit

**Comment by ghost** [comment]
Thanks for the bug fix, @blake!

**Comment by gregdek** [comment]
Thanks again to @blake for this PR, and thanks @stygstra for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
