### PR TITLE
Check sooner for connectivity, before we call fw.getDefaultZone

### LINKED ISSUE #1138: FirewallD Module Fails with backtrace when firewalld cannot be contacted
**Issue Type:** Bug Report

**Ansible Version**:

```
ansible 2.0.0 (devel 6b419db9fa) last updated 2015/10/21 13:15:31 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dc51e1ae41) last updated 2015/10/21 13:15:36 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD eeeb1264d3) last updated 2015/10/21 13:15:36 (GMT +200)
```

**Environment:**
Ubuntu hosts managing Centos7 targets in multi-environment setups, some of these are Vagrant VMs.

**Summary**:
firewalld is disabled on our Vagrant VMs; there the firewalld tasks fail with a misguiding backtrace.

**Steps To Reproduce:**

```
ansible -m service -a "name=firewalld state=stopped" host1 
ansible -m firewalld -a "port=80/tcp state=enabled permanent=true" host1 
```

**Expected Results:**

Something more informative than the backtrace deep from Python.

**Actual Results:**

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 2366, in <module>
  File "<stdin>", line 278, in main
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/slip/dbus/polkit.py", line 103, in _enable_proxy
    return func(*p, **k)
  File "<string>", line 2, in getDefaultZone
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1917, in getDefaultZone
    return dbus_to_python(self.fw.getDefaultZone())
AttributeError: 'NoneType' object has no attribute 'getDefaultZone'

fatal: [host]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

**Note**:
This report is an almost 1-to-1 copy from https://github.com/ansible/ansible/issues/6911 with the same fix. The patch (actually checking for fw.connected) was undone with https://github.com/ansible/ansible-modules-extras/commit/6f2b61d2d88294ea7938020183ea613b7e5e878d

### PR DESCRIPTION
**Pull request by mscherer**
Fix #1138.

Also drop the check for AttributeError since that's already tested
anyway with if FW_VERSION < "0.2.11".

### CODE REVIEW

**Comment by robynbergeron** [comment]
@mscherer -- thanks for submitting this PR. 

@maxamillion -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Note that this is a fix for #1138. 

Thanks (and hugs to both of you! :D)

**Comment by gregdek** [comment]
@maxamillion This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@maxamillion still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by maxamillion** [comment]
:+1: shipit

**Comment by robynbergeron** [comment]
Thanks again to @mscherer for this PR, and thanks @maxamillion for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
this seems dupe of #1133

**Comment by mscherer** [comment]
Yeah, the 2 commits fix the same problem. Then I guess we can just remove the dead code, I will take a look later.

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @maxamillion please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by maxamillion** [comment]
:+1: shipit

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @maxamillion for reviewing. Marking for inclusion.

**Pull request merged**
