### PR TITLE
zabbix_maintenance: Stop using api removed in zabbix 3.0

### PR DESCRIPTION
**Pull request by kepstin**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

zabbix_maintenance
##### Summary:

Partial fix for #1759 (only fixes maintenance module, others are affected as well)

The zabbix modules currently use API that was deprecated in zabbix 2.4, and removed in zabbix 3.0. This commit removes the use of the deprecated API from the zabbix_maintenance module, which also simplifies the code a bit.

### CODE REVIEW

**Comment by eikef** [comment]
Looks good to me, thank you for the PR :)

**Comment by eikef** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @kepstin. @eikef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks again to @kepstin for this PR, and thanks @eikef for reviewing. Marking for inclusion.

**Pull request merged**
