### PR TITLE
Updated ec2_vpc_nat_gateway to use AWSRetry decorator

### PR DESCRIPTION
**Pull request by linuxdynasty**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_vpc_nat_gateway
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

Updated ec2_vpc_nat_gateway to use the AWSRetry.backoff decorator. Also added fix, to make sure all output is returned in lower case. This module depends on the Pull Request [AWSRetry](https://github.com/ansible/ansible/pull/17039).

---

This change is [Reviewable](https://reviewable.io/reviews/ansible/ansible-modules-extras/2721)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @linuxdynasty. This module is going into community review.

We notice that you are one of the maintainers (@linuxdynasty) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by akurniawan** [comment]
hi @linuxdynasty, since you're doing PR I want to file a suggestion for this module. In `wait_for_status` function within `while wait_timeout > time.time():` loop, you put `time.sleep(polling_increment_secs)` within `else` section, is it better to put `time.sleep` outside `try except`? it would be a bit dangerous since it will do an api call repeatedly without sleeping if we got an exception. I'm filing this request because when I ran this module and waiting for nat_gateway to be created, suddenly I couldn't open my aws console saying the API call has reached its maximum limit. I'm not really sure whether this is the root cause, I will check it tomorrow morning

**Comment by ryansb** [comment]
@linuxdynasty are you intentionally deleting all those tests?

**Comment by linuxdynasty** [comment]
@ryansb I did delete the api integration tests from the PR.

**Comment by linuxdynasty** [comment]
@akurniawan, This is AWS rate limiting the number of api requests that come in. Which this PR gets around by applying the AWSRetry decorator. To answer your question, when provisioning to AWS and you are creating x amount of resources, it is possible that you will receive that Rate Limiting error in the AWS console.

**Comment by linuxdynasty** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @linuxdynasty. Since you are one of the maintainers (@linuxdynasty) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @linuxdynasty for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansb** [comment]
@linuxdynasty looks good to me, but the test changes need to be made to the `ansible/ansible` repo, since that file was moved in cf524673e1de7cb227fefd9716b0d73dc971dafc

**Pull request closed without merging**
