### PR TITLE
mssql_db: new module (extended)

### PR DESCRIPTION
**Pull request by h0nIg**
extension of pull request: https://github.com/ansible/ansible-modules-extras/pull/189

fixes:
- added kerberos support (username is empty)
- fix syntax problems related to sql injection change
- added autocommit setting to import stuff not allowed within transaction
- fix automated tests

### CODE REVIEW

**Comment by vedit** [comment]
@h0nIg Looks great, I'll do some testing, but as far as I remember I had to wrap some commands with autocommit because it wouldn't work otherwise.

**Comment by robynbergeron** [comment]
Thanks @h0nIg for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by MotoBuddy** [comment]
passes_guidelines shipit

**Comment by rkraneis** [comment]
shipit

**Comment by vedit** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @h0nIg for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by h0nIg** [comment]
changed version to 2.2, because this failed the build @gregdek

**Comment by gregdek** [comment]
@h0nIg A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by h0nIg** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @h0nIg for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by h0nIg** [comment]
@gregdek this pull request already received three shipit comments by @rkraneis @vedit and @MotoBuddy, the only issue was related to the wrong version. please include this pull request

**Comment by gregdek** [comment]
Adding to next new modules review meeting

**Comment by gundalow** [comment]
shipit

**Comment by robynbergeron** [comment]
Marking for shipment - agreed in 5/25 meeting.

**Comment by abadger** [comment]
I think this is going to fail in travis due to not passing python3 syntax checks.  If you rebase the PR onto the latest devel, I think travis will show you what lines need to be changed.  This page has some hints that will probably get the module passing the syntax check: http://docs.ansible.com/ansible/developing_modules_python3.html

**Comment by abadger** [comment]
needs_revision

**Comment by abadger** [comment]
I have some time today so I'll look at updating so that python3 syntax checks pass right now.

**Comment by abadger** [comment]
fixed the python3 syntax, rebased, and squashed into three commits (by author).  The three commits are:
- b827b7398c791325f54199edb7bd6615c2e14eba
- e7e36209832bc6de3eb4854045da5961073c839a
- 0e4a023a7e883743e92ddfcd097b3a60d86b1608

Since the pymssql library requires python-2.7 and above, I added that requirement to the documentation and ported the exception syntax to python3 style instead of using get_exception().

Thanks to @vedit and @h0nIg for all the work they've put into this!  Looking forward to future requests to keep this module working well :-)

**Pull request closed without merging**
