### PR TITLE
Initial commit: dirty ssh command to manage network devices over CM s…

### PR DESCRIPTION
**Pull request by yurilaaziz**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
ConsoleManagement dirtyssh

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides


```

##### SUMMARY

I write this module to be used by network engineer for initial configuration of network switchers or routers. kind of theses devices should be configured via Console. of course Ansible can't connect to a device via console servers with badly implemented ssh server.

I tested this module with : 
Switch : Juniper EX xx
Console Server : Digi CM 32 

origin : https://github.com/yurilaaziz/ansible-dirtyterminal

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @yurilaaziz for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by yurilaaziz** [comment]
ready_for_review

**Comment by gundalow** [comment]
@privateip @Qalthos FYI

**Comment by gregdek** [comment]
Thanks @yurilaaziz for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by yurilaaziz** [comment]
@privateip @Qalthos can you check this please @gregdek

**Comment by gundalow** [comment]
@yurilaaziz This will need moving to `ansible/ansible` repo. This is currently down, next week if you follow http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo that will guide you through that process.

**Pull request closed without merging**
