### PR TITLE
Jira will return a HTTP status code 201 on some actions, fx. 'comment'.

### PR DESCRIPTION
**Pull request by rudimeyer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

module: jira
##### ANSIBLE VERSION

ansible 2.0.2.0
##### SUMMARY

In some cases Jira REST API will return a HTTP Status code 201, fx. after a comment action on a existing Jira Issue.
'201' is added to the acceptable HTTP Status codes: (200, 201, 204).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @rudimeyer. To the current maintainers, @tarka please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tarka** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @rudimeyer for this PR, and thanks @tarka for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by offlinehoster** [comment]
Can we please merge this? @bcoca @sivel 
As in https://github.com/ansible/ansible-modules-extras/pull/2122 i created also a PR, because i did not see this one here.

If you/we can merge this, i could close #2122 

Thanks

**Comment by offlinehoster** [comment]
:+1:  thanks @bcoca

**Pull request merged**
