### PR TITLE
Add honeybadger_deployment module

### PR DESCRIPTION
**Pull request by stympy**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

honeybadger_deployment
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Adds a module to notify [Honeybadger.io](https://www.honeybadger.io/) about deployments.
##### NOTES

Moved from https://github.com/ansible/ansible/pull/7320 and https://github.com/ansible/ansible-modules-extras/pull/32

### CODE REVIEW

**Comment by stympy** [comment]
@gregdek As requested, here is the new PR -- third time's the charm, right? :)

Can you point me to an explanation for this test failure?

```
ansible-validate-modules ansible-modules-extras/monitoring/honeybadger_deployment.py
============================================================================
ansible-modules-extras/monitoring/honeybadger_deployment.py
============================================================================
ERROR: No RETURN documentation provided
```

**Comment by stympy** [comment]
@gregdek Nevermind, I got it. This PR should be ready to go. Let's see if we can get it merged before it's 2nd birthday. :)

**Comment by gregdek** [comment]
Thanks @stympy for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @stympy for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stympy** [comment]
Nothing has changed on this PR in the past month, so why is there a status change by the bot?

**Comment by gregdek** [comment]
@stympy A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stympy** [comment]
@gregdek Can I get an actual human to look at this?  The plugin works, I have updated it multiple times over the past two years to meet the changing requirements of this project, and yet here it lingers.  I would really like to get this merged. :)

**Comment by gregdek** [comment]
Added to next week's new module review.

**Comment by robynbergeron** [comment]
Okay, in meeting -- Gundalow is going to review this one post-meeting and we should be able to get mark it for shipment, assuming all looks well, which it seems to thus far. More soon!

**Comment by gundalow** [comment]
Hi,
Thank you for this module.

Apologies it seem to have gotten stuck

I'm happy with this module

@abadger Can you please
- Merge
- Update version_added
- Fix py3.4. Only issue seems (when using 3.5) to be the exception on line 125

**Comment by abadger** [comment]
Rebased, fixed the version and python3 syntax issues and merged to devel: 76cbe306451d0ecc95c6ac1787c03cd4cf22b0d8 4b4557eb97bcabe5d920c44eb4f60a2deb8c5d67

Thanks for working on this for your persistence on this!  looking forward to future pull requests to keep this updated :-)

**Comment by stympy** [comment]
Woot! Thanks! 💯

**Pull request closed without merging**
