### PR TITLE
Add cloudstack loadbalancer modules

### PR DESCRIPTION
**Pull request by DazWorrall**
This is a continuation of #982 after I had to delete my fork

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @DazWorrall. Pinging @resmo since he's the guy to approve this one, as he was in the previous PR.

Adding new_module boilerplate for housekeeping purposes also.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
Just leaving a note here that I believe @resmo has been on a well-deserved vacation (or at least, what looks like a vacation, judging by the beach photos on twitter...) -- thanks @DazWorrall for your patience :)

**Comment by resmo** [comment]
@robynbergeron touché. But back at work now, would be great if it could make it into ansible v2 before release... working on it @DazWorrall

**Comment by DazWorrall** [comment]
I'm around this week, let me know if you want any more changes making. Fwiw, we're using these modules in production at the moment.

**Comment by robynbergeron** [comment]
@resmo -- thanks. Let us know when you get a chance to eyeball it and we'll keep it moving :)

**Comment by resmo** [comment]
@DazWorrall made a PR to your repo with my final changes.

**Comment by DazWorrall** [comment]
LGTM

**Comment by resmo** [comment]
works_for_me (see integration tests)
passes_guidelines

**Comment by bcoca** [comment]
can you flatten the commits?

**Comment by resmo** [comment]
@bcoca see new PR #1125

**Pull request closed without merging**
