### PR TITLE
Added support for IIS AppPool identities

### PR DESCRIPTION
**Pull request by trondhindenes**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

win_acl
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### SUMMARY

Adds support for IIS Application Pool identities, ref #1433

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @trondhindenes. This module is going into community review.

We notice that you are one of the maintainers (@schwartzmx, @trondhindenes) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by trondhindenes** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @trondhindenes. Since you are one of the maintainers (@schwartzmx, @trondhindenes) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by trondhindenes** [comment]
shipit

**Comment by schwartzmx** [comment]
:+1: shipit

**Pull request merged**
