### PR TITLE
clc_aa_policy : the ansible module to manage anti affinity policies in centurylink cloud

### PR DESCRIPTION
**Pull request by popurisiva**
New module for managing the anti affinity policy has been added for centurylink cloud.
This module adhere to the module development standards and best practices.
With this module, users can create or delete anti affinity policies in centurylink clould

### CODE REVIEW

**Comment by gregdek** [comment]
@popurisiva Thanks for submitting this new module.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, and receives no -1 votes, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by popurisiva** [comment]
Thank you @gregdek for the update.
This module adheres to the module guidelines and is similar to other pull request (#698) which has been merged a while back.
We look forward to implement comments if any.

**Comment by popurisiva** [comment]
Any update on this PR?

**Comment by gregdek** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by popurisiva** [comment]
@bcoca , Is there any update on this PR?
Please let me know if any changes or action required at my end.

**Pull request merged**
