### PR TITLE
Module: win_timezone

### PR DESCRIPTION
**Pull request by schwartzmx**
This was part of a discussion on a currently open PR https://github.com/ansible/ansible-modules-extras/pull/213.  We decided to separate the timezone functionality.

I'm open to suggestions on name and param name, if `win_timezone` is bad or likewise with the `timezone` param let me know.  

Thanks

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for pulling this code out @schwartzmx -- much appreciated.

Pinging Windows crew for reviews: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by trondhindenes** [comment]
@schwartzmx could you replace yor hard-coded paths with the correct env variables, like "C:\Windows"--> $env:Systemroot and so on? I know I'm picky but still :-)

**Comment by trondhindenes** [comment]
Also, required arguments/options can be handled as such:
(here the argument "path" is a required one).
`$path = Get-Attr -obj $params -name path -failifempty $true -resultobj $result`
The powershell.ps1 script will take care of spitting out a sensible error to the user if the argument isn't specified (when the $failifempty prop is set to $true). I find it quite handy.

**Comment by schwartzmx** [comment]
Yep can do that after lunch. That's pretty easy fix.  And no worries,
that's a better idea anyway.

**Comment by trondhindenes** [comment]
Sweet.
One more thing: exe files are a bit tricky, there's a good chance your try/catch block won't errors from tzutil..
Therefore, after each time you call the tzutil.exe you could add this:
`if ($LASTEXITCODE -ne 0)
{
    throw "some error happened"
}`
The throw statement will send execution into your catch block where you've already handled it.

**Comment by schwartzmx** [comment]
@trondhindenes a little later than I expected.  Ended up just using `tzutil.exe` because `C:\windows\system32` is already included by default in `$env:path`.  This is also how `msiexec.exe` is called in the `win_msi` module.   Also made the other changes you noted,  let me know if I need to alter or fix these.  Thanks.

**Comment by trondhindenes** [comment]
Sweet! I'll get this one tested over the weekend, if noone else jumps on.

**Comment by schwartzmx** [comment]
thanks :+1:

**Comment by schwartzmx** [comment]
any updates on this @trondhindenes ?

**Comment by gregdek** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by gregdek** [comment]
@trondhindenes any time to re-review this one?

**Comment by gregdek** [comment]
Or any Windows folks: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by nitzmahone** [comment]
Works for me- thanks for the module, and sorry for the delay in getting it merged!

**Pull request merged**
