### PR TITLE
Ignore warning of MySQLdb instead of throwing an error fixes #719

### LINKED ISSUE #719: mysql_replication module:  warning from MySQLdb.Warning result in failed task
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
ansible 1.9.2
  configured module search path = None
##### Ansible Configuration:

```
[defaults]
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
gathering = smart

# if set to a persistant type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
# fact_caching = memory

fact_caching = jsonfile
fact_caching_connection = /tmp/ansiblefacts

```
##### Environment:

Running from Debian 8
Managing Debian 8
##### Summary:

When running a playbook to setup MySQL replication with a task doing  mode=changemaster the task failed, after a warning from MySQLdb. The warning complains about "Sending passwords in plain text without SSL/TLS is extremely insecure"
##### Steps To Reproduce:

Create a playbook to setup mysql and replication with a task like this which should be run on slave MySQL to declare the master host : 

```
- name: Change the master in slave to start the replication
  mysql_replication: mode=changemaster master_host={{ mysql_repl_master }} master_log_file={{ repl_stat.File }} master_log_pos={{ repl_stat.Position }} master_user={{ mysql_replication_user }} master_password={{ mysql_replication_user_password }}
```
##### Expected Results:

```
TASK: [mysql | Change the master in slave to start the replication] *** 
changed: [mysql2.preprod]
```
##### Actual Results:

```
failed: [mysql2.preprod] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 2001, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 379, in main
    changemaster(cursor, chm, chm_params)
  File "/root/.ansible/tmp/ansible-tmp-1437058776.53-24949336144903/mysql_replication", line 174, in changemaster
    cursor.execute(query, chm_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 176, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 92, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Sending passwords in plain text without SSL/TLS is extremely insecure.

```

### PR DESCRIPTION
**Pull request by nadley**
Small patch to fix the issue #719

### CODE REVIEW

**Comment by gregdek** [comment]
@banyek Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please give it a +1; at that point, we will merge.

**Comment by banyek** [comment]
I think it should be merged, because this is an annoying but, but I am not sure if this filtered warning behaviour is not better if user implicate it?
But yeah, this is a needed feature, so +1, but I guess it could be made a bit more flexibile.

**Comment by bcoca** [comment]
we can capture the warnings and add them to the results returned from the module

**Comment by nadley** [comment]
So what is the conclusion ? Should I do something more on this pull request to be accepted ?

**Comment by bcoca** [comment]
do not ignore the warning, but capture them and pass them to the results in a warnings=listofwarnings key

**Comment by nadley** [comment]
Ok I'm going to look to this point and update the pull request. Thanks.

**Comment by gregdek** [comment]
@nadley Still waiting on that update. :)

Once you've made the suggested revisions, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by robynbergeron** [comment]
@nadley -- A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by nadley** [comment]
@robynbergeron 

Thanks for remembering me this PR. As I have forget it. I actually have no time to work on it and need to rebuild an environment to test it. So I'll close it for the moment and reopen it when I'll have time to fix it.

**Comment by grypyrg** [comment]
We should merge this pull request. mysql_replication is not that useful on modern MySQL as it's always giving that warning when you are not using SSL.
Most companies do not use SSL at all for replication, so this is a critical issue.

**Comment by grypyrg** [comment]
@banyek: can you spend some time to test and merge this request?
Let me know if you need anything else. I want to avoid having a custom ansible-extra module for my clients to make it work.

**Comment by banyek** [comment]
@robynbergeron I can't check this in the near future, but I think it is an important feature - I trust in Kenny's code, but I don't want to merge it without checking it. 
Please find an owner asap.

**Comment by straight-shoota** [comment]
I'd really like to see this resolved. I'm not familiar with developing ansible modules or in python at all. But what would need to be done to get this done?

**Comment by grypyrg** [comment]
@straight-shoota All it needs is a single word change as marked in commit 290254d

**Comment by straight-shoota** [comment]
@grypyrg Yeah I know, I've already applied that patch to my local ansible. But I think this issue should also be fixed in the official release.

**Comment by Jmainguy** [comment]
@grypyrg @straight-shoota  what do you think about bcoca's comment

```
do not ignore the warning, but capture them and pass them to the results in a warnings=listofwarnings key
```

**Comment by grypyrg** [comment]
:+1: on @bcoca's comment.

**Pull request closed without merging**
