### PR TITLE
Dnf autoinstall

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

packaging/os/dnf.py
##### ANSIBLE VERSION

```
devel (2.3)
```
##### SUMMARY

We decided that package manager modules are allowed to install their dependencies if they can.  This PR implements that.

### CODE REVIEW

**Comment by abadger** [comment]
Fixes https://github.com/ansible/ansible/issues/14427

**Comment by gregdek** [comment]
Thanks @abadger. To the current maintainers, @ignatenkobrain, @DJMuggs please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by DJMuggs** [comment]
shipit

**Comment by abadger** [comment]
Merged to devel.  This should be in 2.3.0 when it comes out.  If other people are interested, they should be able to backport it without issue.

**Pull request merged**
