### PR TITLE
New module asa_config

### PR DESCRIPTION
**Pull request by ogenstad**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

network/asa/asa_config
##### ANSIBLE VERSION

Target: Ansible 2.2
##### SUMMARY

Module to change configuration on a Cisco ASA device, works a lot like the ios_config module.

This module depends on [this PR](https://github.com/ansible/ansible/pull/15992).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ogenstad for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the Travis issue, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

needs_revision

**Comment by ogenstad** [comment]
Hi, it's not just an issue of running the tests again?

**Comment by gundalow** [comment]
@ogenstad Not in this case, there is something in the git history that needs manual poking.

**Comment by ogenstad** [comment]
Ok, seems strange when I just added a standalone file to a new branch from devel. But I'll take a lookl

**Comment by gundalow** [comment]
It's hit a few new module PRs,  so not anything specificly broken that you've done. 

Thanks

**Comment by ogenstad** [comment]
Seems to be an issue with some older commit when the tests do the rebasing. 

I'm not really sure what I should do with this.

```
Applying: make yum module work with older yum for rhel5 :(
Using index info to reconstruct a base tree...
M   yum
<stdin>:16: trailing whitespace.
            my.conf.cache = 0 
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: fix up latest so it behaves like latest should
Using index info to reconstruct a base tree...
M   yum
Falling back to patching base and 3-way merge...
Auto-merging yum
CONFLICT (content): Merge conflict in yum
Failed to merge in the changes.
Patch failed at 0087 fix up latest so it behaves like latest should
The copy of the patch that failed is found in:
   /home/travis/build/ansible/ansible-modules-extras/.git/rebase-apply/patch
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
```

**Comment by gundalow** [comment]
If you swing via # ansible-devel on Freenode (IRC) someone there should be able to help.

**Comment by gregdek** [comment]
Thanks @ogenstad for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ogenstad** [comment]
With some help from #ansible-devel I got passed the previous error. However now the tests fail due to:

ERROR: DOCUMENTATION fragment missing: asa

This is due to the fact that this PR depends on https://github.com/ansible/ansible/pull/15992. How should I handle that?

**Comment by ogenstad** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ogenstad for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @ogenstad for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Shipping it.

**Pull request merged**
