### PR TITLE
New module asa_command

### PR DESCRIPTION
**Pull request by ogenstad**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

network/asa/asa_command
##### ANSIBLE VERSION

Target: Ansible 2.2
##### SUMMARY

Module to run commands on a Cisco ASA unit, works much like the similar ios_command module.

This module depends on [this PR](https://github.com/ansible/ansible/pull/15992).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ogenstad for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the Travis issue, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

needs_revision

**Comment by gregdek** [comment]
Thanks @ogenstad for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ogenstad** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ogenstad for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by privateip** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @ogenstad for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Shipping it.

**Pull request merged**
