### PR TITLE
amazon/ec2_vpc_igw: Allow internet gateways to be tagged

### PR DESCRIPTION
**Pull request by gechr**
This PR makes it possible to tag Internet Gateways, heavily based on [cloud/amazon/ec2_vpc_subnet.py](https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/ec2_vpc_subnet.py).

Would be a good idea to factor out the common code (e.g. tagging) in the Amazon modules in future to avoid duplication, but that's probably best picked up as a separate PR.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @gechr. @erydo please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gechr** [comment]
Oops, accidentally hit close, re-opening!

**Comment by aioue** [comment]
+1

**Comment by brandond** [comment]
+1, with my PR to fix state: absent

**Comment by gechr** [comment]
@brandond Nice catch, merged. Would have been more correct to not pass `tags` in the first place, since the parameter isn't used, but I'm not too fussed either way!

**Comment by brandond** [comment]
@gechr yeah, I considered pulling the argument out of the call, but I kind of liked the idea of present and absent having the same signature, even if it's not used at the moment. Also, looks like the build is now failing since 'tags' requires version_added: "2.2"

**Comment by gechr** [comment]
@brandond Fixed & squashed everything into a single commit.

**Comment by aturetta** [comment]
+1

**Comment by aioue** [comment]
Any movement with this?

**Comment by aioue** [comment]
@gechr did this get raised against ansible/ansible?

**Pull request closed without merging**
