### PR TITLE
have a timezone file before using

### LINKED ISSUE #3335: Timezone: global name 'tzfile' is not defined
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
timezone

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
Host: Arch
Client: CentOS 6.8

##### SUMMARY
As of https://github.com/ansible/ansible-modules-extras/commit/e29584ad70d2f4e0a8ef02781d7bc7e977ff0e69 timezone is broken again. If I go back to https://github.com/ansible/ansible-modules-extras/commit/df35d324d62e6034ab86db0fb4a56d3ca122d4b2 it works fine again.

##### STEPS TO REPRODUCE
Run playbook with a timezone defined.

##### EXPECTED RESULTS
Timezone set properly, no errors.

##### ACTUAL RESULTS
Receive the fatal error below.

```
fatal: [vagrant-noc-server]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.50.3 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 462, in <module>\r\n    main()\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 435, in main\r\n    tz = Timezone(module)\r\n  File \"/tmp/ansible__7aiLU/ansible_module_timezone.py\", line 306, in __init__\r\n    self.update_timezone += ' %s /etc/localtime' % tzfile\r\nNameError: global name 'tzfile' is not defined\r\n", "msg": "MODULE FAILURE"}
```

### PR DESCRIPTION
**Pull request by bcoca**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

timezone 

##### ANSIBLE VERSION

```
2.2
```

##### SUMMARY

made refactored method now pass file back to caller
fixes #3335

### CODE REVIEW

**Comment by tmshn** [comment]
Both this pr and #3337 looks fine 👍 (Merging either of them will be ok)

**Comment by gregdek** [comment]
Thanks @bcoca. To the current maintainers, @tmshn please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tmshn** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks again to @bcoca for this PR, and thanks @tmshn for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
