### PR TITLE
ansible modules for centurylink cloud

### PR DESCRIPTION
**Pull request by popurisiva**
New modules are added for centurylink cloud.
All of these modules adhere to the module development standards and best practices.
Please review and help us merge these changes

### CODE REVIEW

**Comment by bcoca** [comment]
I would suggest submitting them individually or one at a time, as the review will be much faster to get the first included and by then any patterns that need correcting will be obvious. Also reviewers can check one module in a short time, but all require a bigger commitment to do a batch.

**Comment by popurisiva** [comment]
Thank you @bcoca for the comment. We will send individual pull requests for each of the modules. We will send just one module for the first pull request. We will apply all review comments to the the rest of the modules as we go along and send the remaining requests once our first pull request is merged

**Comment by popurisiva** [comment]
We have raised a separate pull request with just one module in it.
Please let me know if I can close this pull request. I just want to make sure if there is no pending work in-progress from your side on this pull request.

**Comment by bcoca** [comment]
closing this as they have been resubmitted individually

**Pull request closed without merging**
