### PR TITLE
Make use of ec2 doc_fragment and update code to ensure check of region

### PR DESCRIPTION
**Pull request by wimnat**
Add ec2 doc fragment as already done for core modules https://github.com/ansible/ansible-modules-core/commit/c4f64d822ce5ef9300c06433ac85a0bbfee0a75c

### CODE REVIEW

**Comment by bcoca** [comment]
sorry, it seems we have a misunderstanding, i was only asking for the code changes in the original PR, not that you update the docs for all the modules (i already did that). 

I though your question about PR and my response about direct commit was about how I had updated it, not how I wanted you to update it.

**Comment by wimnat** [comment]
Do you want me to modify the PR so you can still merge the code changes for checking region parameter across the modules or is the change too big?

That's what I did for https://github.com/ansible/ansible-modules-core/pull/2217 but again, is this PR too big?

**Comment by robynbergeron** [comment]
Hi @wimnat -- thanks for this.

@bcoca -- looking to you for answers :)

**Comment by bcoca** [comment]
yes, just go back to original and make that change, im ok with doing sweeping siimple doc changes, but this is a bit more than what i would want to review and test at a time, we can address each module individually when it comes to code

**Comment by robynbergeron** [comment]
Okay! @wimnat -- back to you. I'm trying to interpret what the "original" is here that is referred to and I'm not sure if it's https://github.com/ansible/ansible-modules-core/issues/2217 or something else -- in any case ... I'm going to assume you know what is needed at this point :)

If this just needs closing, I think you can close it since you opened it. If it needs revising, let us know with a ready_for_review comment when it's revised. :) I'm marking this as needs_revision for the moment since @bcoca is asking for a change to "the original" ...

Thanks, @wimnat! :D

**Comment by robynbergeron** [comment]
(Also, @wimnat -- it looks like this may need a rebase -- just an FYI!)

**Comment by wimnat** [comment]
Closing as per @bcoca comment.

Code is good though so might resubmit through separate PRs for each module

**Pull request closed without merging**
