### PR TITLE
network/openvswitch_bridge.py: Check VLAN ID only under fake bridge

### PR DESCRIPTION
**Pull request by keithnoguchi**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

network/openvswitch_bridge.py

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

The following change introduces VLAN range check, even if the bridge is the normal
branch, non-fake.  The patch moves the VLAN ID check only under the fake bridge
case.

```
commit 1ca889bc738c9419f7409171531144f5adf258f9
Author: Thierno IB. BARRY <ibrahima.br@gmail.com>
Date:   Tue Oct 25 06:46:21 2016 +0200

    openvswitch_bridge: add fake bridge support (#3054)

    * openvswitch_bridge: add fake bridge support

    * openvswitch_bridge: check if vlan is between 0 and 4095

```

r: @barryib

### CODE REVIEW

**Comment by keithnoguchi** [comment]
Hi @barryib and @resmo,

Let me know if this PR makes sense to you.  I have a playbook which doesn't have any VLAN and, without this patch, I got error saying `Invalid VLAN ID...`.  I can add vlan=0 but that breaks backward compatibility for the non fake bridge case.

Let me know your thought!

**Comment by barryib** [comment]
Hello @keinohguchi thanks for this PR. LGTM 👌 

cc @stygstra

**Comment by keithnoguchi** [comment]
Cool and thank you, @barryib, for your quick review!  Let me know if you need anything from my side!

Cheers!

I'll be at OVS conn in San Jose, today.  Hope we can see you there. :)

**Comment by gregdek** [comment]
Thanks @keinohguchi. To the current maintainers, @stygstra please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @keinohguchi for this PR, and thanks @stygstra for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
