### PR TITLE
Proposed new notification module: BearyChat

### PR DESCRIPTION
**Pull request by tonyseek**
BearyChat (https://bearychat.com) is a Slack alternative service.

CC @loddit @bearyinnovative

### CODE REVIEW

**Comment by bcho** [comment]
+1 for this module

**Comment by robynbergeron** [comment]
Thanks @tonyseek for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Thanks @tonyseek for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tonyseek** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @tonyseek for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by shonenada** [comment]
shipip

**Comment by shonenada** [comment]
shipit

**Pull request closed without merging**
