### PR TITLE
Added profitbricks_firewall_rule module

### PR DESCRIPTION
**Pull request by edevenport**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

profitbricks_firewall_rule
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The profitbricks_firewall_rule module allows firewall rules to be assigned to network interfaces.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @edevenport. To the current maintainers, @baldwinSPC please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by baldwinSPC** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @edevenport for this PR, and thanks @baldwinSPC for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by baldwinSPC** [comment]
shipit

**Comment by edevenport** [comment]
Hello @gregdek - I was wondering if any further action is required for this merger? We already have another PR ready to be submitted. Thank you.

**Comment by gregdek** [comment]
Hi @edevenport -- we're in feature freeze for 2.2 right now, so no new modules are being merged until 2.3.

**Comment by bcoca** [comment]
this PR has extra updates that seem like unrelated fixes to the new plugin

**Comment by gregdek** [comment]
Thanks @edevenport. To the current maintainers, @baldwinSPC please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
@bcoca The NIC updates in this PR relate to their output which is used by the firewall module.

**Comment by baldwinSPC** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @edevenport for this PR, and thanks @baldwinSPC for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
@gregdek @bcoca - Is there anything else required before this PR can be merged?

**Comment by gregdek** [comment]
@edevenport looks like this needs to be rebased. Please check out @bcoca comments. Thanks!

**Comment by gregdek** [comment]
Thanks @edevenport. To the current maintainers, @baldwinSPC please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
@gregdek - Rebase has been completed.

**Comment by gregdek** [comment]
Thanks @edevenport for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @edevenport. To the current maintainers, @baldwinSPC please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
And here we go again... Can we get a 'shipit'?

**Comment by gregdek** [comment]
putting back into shipit

**Comment by baldwinSPC** [comment]
shipit

sorry for the delay in review.

**Comment by gregdek** [comment]
Thanks @edevenport for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by edevenport** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @edevenport. To the current maintainers, @baldwinSPC please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by baldwinSPC** [comment]
@gregdek shipit

**Pull request closed without merging**
