### PR TITLE
Added new module opendj_backendprop for updating backend settings opendj

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

opendj_backendprop
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

This module will update the configuration setting in the OpenDJ backend. This module will make use of the command 'dsconfig', which is installed with the installation of OpenDJ

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @dj-wasabi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
Hi,
Thanks for these new opendj modules.

Can you please move this and related modules to `extras/identity/opendj/`. This will allow a sensible logical grouping.

You may need to create `__init__.py` in both of the new directories

At the same time can you please update https://github.com/ansible/ansibullbot/blob/master/MAINTAINERS-EXTRAS.txt to set yourself as the maintainer of of `identity/opendj/`. This means you will receive notifications on GitHub when someone raises a PR against any of these modules.

**Comment by dj-wasabi** [comment]
Hi @gundalow 

I moved the module to the mentioned directories, but the CI checks fails. What am I doing wrong?

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the Travis issue, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

**Comment by dj-wasabi** [comment]
I tried to fix this. I even created a new branch but I keep getting errors. The information on the provided page doesn't help me much. Any suggestions to fix it?

**Comment by gundalow** [comment]
Hi,
Swing via `#ansible-devel` on Freenode IRC and there should be someone there that can guide you. Occasionally git really does live up to its name :(

**Pull request closed without merging**
