### PR TITLE
ProfitBricks Data Center Module

### PR DESCRIPTION
**Pull request by baldwinSPC**
@bcoca @gregdek Here's the first PR with the datacenter module.

### CODE REVIEW

**Comment by bcoca** [comment]
you seem to have an extra commit here, in any case I'll wait to review any of the other modules until the compute module makes it in

**Comment by baldwinSPC** [comment]
@bcoca OK, the compute module has gone through. Is there anything I need to do with this PR? Just checking to see if I need to make changes before it can be accepted. Tnx!

**Comment by bcoca** [comment]
remove the extra commits, you seem to have it in all the PRs

**Comment by baldwinSPC** [comment]
roger. tnx.

**Comment by baldwinSPC** [comment]
@bcoca Closing this one in favor of the new one I just opened [here](https://github.com/ansible/ansible-modules-extras/pull/801).

**Pull request closed without merging**
