### PR TITLE
Modified win_acl to accept Security Identifiers (SID) for Windows' users and groups

### PR DESCRIPTION
**Pull request by alxwest**
We use SIDs in our server configuration for most things (setting application pools and application settings) so allowing win_acl to accept SIDs allows use to only have 1 variable for a specified user as opposed to 2 (SID and user name).

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Hey @alxwest I see you've closed this, but the pr contains a handy looking win_xml module.  Can I ask you have any plan to create a separate PR for win_xml - I'd certainly be interested in testing it if you do?

Jon

**Comment by alxwest** [comment]
Hi @jhawkesworth 

Yes I do. I've got my branches in a muddle. Once sorted I'll let you know.

Cheers

Alex

**Comment by alxwest** [comment]
Hi @jhawkesworth 

I've created a branch for win_xml (https://github.com/alxwest/ansible-modules-extras/tree/win_xml). It's not perfect and comments/PRs would be gratefully received!

Cheers

Alex

**Comment by jhawkesworth** [comment]
Thank you.  I'll take a look.

**Pull request closed without merging**
