### PR TITLE
Convert ec2_vpc_subnet module to boto3

### PR DESCRIPTION
**Pull request by brandond**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_vpc_subnet
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Update ec2_vpc_subnet to use boto3. Along the way, we also get the capability to control the 'MapPublicIpOnLaunch' subnet attribute. Parameters and return values are unchanged.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @brandond. To the current maintainers, @erydo please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
This PR doesn't not maintain backward compatibility as stated in the AWS guidelines.

@brandond you'd have to change this to make it worth with both boto and boto3

**Comment by brandond** [comment]
@wimnat working with both boto and boto3 seems like a high bar to set. Most new modules only work with boto3; why is there resistance to upgrading existing modules to use it instead? In particular, the modify_subnet_attribute call required to set the 'map public up on launch' flag is only available in boto3. While it would have been easy enough for me to make this a dual-lib module and simply add that new functionality, I thought it would be better (in terms of future state) to do the work to convert the whole module over. Is that not encouraged?

**Comment by wimnat** [comment]
@brandond - I agree with you.  However, unfortunately, the Ansible core team do not.  This discussion was had a little while ago with the release of Ansible 2.0 and it was decided that for the time being, existing modules must remain backward compatible with boto and new functionality that is only supported in boto3 must be added in a way that doesn't break the module for people who only have boto.

If you want to post in the Google Ansible devel group voicing your support of allowing us to move modules to boto3 I definitely encourage it.

But, as of now, we need to keep support for boto.  There's more detail in the guidelines which i directed you to in another comment :)

**Comment by brandond** [comment]
@wimnat thanks for the background. I'll take a look at refactoring to only require boto3 if I need to call modify_subnet_attribute. Is there a good dual-version module that you'd recommend using as a reference point?

**Comment by juliedavila** [comment]
Yeah, this would be fine if the module wasn't already part of a release (part of 2.0). You don't _need_ to refactor so that it only uses boto3 if modiefy_subnet_attribute is needed, alternatively, you can keep your code as-is really while keeping the original boto code in. The logic can simply do an import check and let the rest of the logic follow. 

Though, tbh, I almost want to bring it up with the mailing list again. A good part of me feels it's ok to break backwards compatibility when the burden to users is simply a `pip install boto3`.  The thing that would need to be validated is that the returned JSON structure contains the at least same key/values as the original (more key/vals are ok, obv) so that way they don't wont need to refactor the code, just install a new package.

**Comment by gregdek** [comment]
Thanks @brandond for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@brandond A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@brandond Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
