### PR TITLE
Distinguish between untagged and tagged vlans

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

network/f5/bigip_vlan.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

We were incorrectly making VLANS always be untagged when they could
be either tagged or untagged. This change corrects the arguments to
the vlan module to allow for specifying either untagged or tagged
interfaces. The arguments are mutually exclusive

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @caphrim007 for this PR, and thanks @mhite, @caphrim007 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
A small hint, as you can also pass just one item to a list arg spec, e.g.

``` yaml
tagged_interfaces: 
  - example
```

is identical to

``` yaml
tagged_interfaces: example
```

it can make sense to set an alias `aliases=['tagged_interface']`for the singular case:

``` yaml
tagged_interface: example
```

Just a hint, not a "blocker", do you want to add an alias before I merge?

**Comment by caphrim007** [comment]
@resmo Did not know that. I'll add examples and aliases right quick

**Comment by caphrim007** [comment]
@resmo do i need to add mutual exclusion for aliases?

**Comment by resmo** [comment]
@caphrim007 no need to add mutual_exclusions for these.

**Pull request merged**
