### PR TITLE
Add Openstack Server Group support

### PR DESCRIPTION
**Pull request by mwik**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

cloud/openstack/os_server_group
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel fffd4b7b46) last updated 2016/07/11 01:24:03 (GMT +200)
  lib/ansible/modules/core: (devel 38e8c7d2d0) last updated 2016/07/11 01:03:01 (GMT +200)
  lib/ansible/modules/extras: (os_server_group eeb7de26d1) last updated 2016/07/11 01:19:26 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

A module for handling Openstack server groups.

Server groups can be associated with scheduler policies such as affinity or anti-affinity, which in turn controls how the scheduler places new instances on physical hosts. To use this feature set `scheduler_hints: group=<name>` when creating a new instance with os_server.

The code is based on os_security_group.py

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mwik for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@mwik A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mwik** [comment]
@gregdek Yes I intend to fix this PR when I return from vacation next week.

**Comment by mwik** [comment]
@gregdek Now this PR should be ready_for_review

**Comment by gregdek** [comment]
Thanks @mwik. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by omgjlk** [comment]
Thi looks good to me. shipit

**Comment by gregdek** [comment]
Thanks again to @mwik for this PR, and thanks @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by lingxiankong** [comment]
Does shade support update_server_group function? OpenStack itself doesn't support it.

**Comment by omgjlk** [comment]
That's a great question @LingxianKong 

I don't see a way in the API to update a server group. I also don't see a way to do this in shade.  Nice catch.

needs_revision

this module can't work as is.

**Comment by mwik** [comment]
Nice catch @LingxianKong! Obviously I never tested updating a server group, only creating and deleting. Now, would it be ok for the module to fail when trying to update a server group? If so I can rework the patch. I don't think working around the missing update api by deleting and re-creating the server group will work, as that will probably lose the group members. But I'll need to check that.

**Comment by omgjlk** [comment]
What other modules do is just not attempt to modify. If the group exists, they just return with nothing changed.

It might be _nice_ if you go a step further and if your request doesn't match what's found (like the policy) then throw an error.

**Comment by lingxiankong** [comment]
This is what I did in my PR (yes, a duplicate one, just FYI), https://github.com/ansible/ansible-modules-extras/pull/2702

and there is also another one doing the same thing: https://github.com/ansible/ansible-modules-extras/pull/2211

**Comment by gregdek** [comment]
Thanks @mwik for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@j2sol @emonty @shrews maybe one of you can provide guidance as to which of these three seemingly conflicting new module PRs we should pursue? #2545 or #2702 or #2211?

**Comment by gregdek** [comment]
Closing because @j2sol has given shipit to #2702, which this conflicts with. Thanks @mwik for your PR; sorry it wasn't the one we went with.

**Pull request closed without merging**
