### PR TITLE
cloud amazon ECS cluster module

### PR DESCRIPTION
**Pull request by Java1Guy**
A new module for dealing with ECS clusters in AWS, including a fact-getting module.

### CODE REVIEW

**Comment by bennojoy** [comment]
@Java1Guy couple of things .. 
ansible-doc ecs-cluster gives a traceback, can you please check the formatting.
version_added should be 2.0
repeat parameter is not documented.
couple of places we have 'self.module.fail_json(msg=str(e))' sometimes the exceptions themselves might not give a clue what is wrong so if you could add the context where it failed it would be very helpful
eg: self.module.fail_json(msg= "Exception during cluster creation" + str(e))

**Comment by Java1Guy** [comment]
Thanks for the note... I made the changes.  I'm not sure what steps to take to see the ansible-doc, but there was some extra stuff which i took out, so hopefully it formats properly now.

**Comment by robynbergeron** [comment]
Hi @Java1Guy -- thanks for submitting this new module. I noticed that your module doesn't have an author: line in it with your name & github ID -- can you update that, so it adheres to the guidelines (http://docs.ansible.com/developing_modules.html#module-checklist)? 

When you're done, please add a comment with the text "ready_for_review" and we will continue with the review process. Thanks!

**Comment by Java1Guy** [comment]
ready_for_review

**Comment by gregdek** [comment]
Hey @bennojoy can you re-review here?

If you're happy with it, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If not, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Pull request merged**
