### PR TITLE
Add quotes for non-floats decimals

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
*

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

@gundalow

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Fale. To the current maintainers, @smadam813, @bpennypacker, @mcodd, @kavu, @hkariti please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bpennypacker** [comment]
looks good, thanks.

shipit

**Comment by mcodd** [comment]
shipit

**Comment by kavu** [comment]
shipit

**Pull request merged**
