### PR TITLE
elasticsearch_plugin: add force option and some improvements

### PR DESCRIPTION
**Pull request by barryib**
##### ISSUE TYPE

- Feature Pull Request
- Bugfix Pull Request
##### COMPONENT NAME

elasticsearch_plugin
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

- Add force option to remove and re-install plugins. This can be useful for plugin update or with Elasticsearch update
- Add check mode
- Avoid using parameters when they are not needed (#1785)
- Fix bug when using proxy (#2603)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @barryib. To the current maintainers, @ThePixelDeveloper please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by barryib** [comment]
@ThePixelDeveloper Any comments or suggestions on this PR?

**Comment by barryib** [comment]
ping @ThePixelDeveloper

**Comment by barryib** [comment]
@gregdek @ThePixelDeveloper Should I remove the feature request and leave only bug fixes to speed up this review?

**Comment by ThePixelDeveloper** [comment]
Sorry about not reviewing this in a timely manner.

@barryib Can you split your PRs into the summary points you suggested? It'll allow me to go through and review them quickly and make it easy for me to confirm what they're doing?

```
* Add force option to remove and re-install plugins. This can be useful for plugin update or with Elasticsearch update
* Add check mode
* Avoid using parameters when they are not needed (#1785)
* Fix bug when using proxy (#2603)
```

Ping me when you're done and I can review them before the end of today.

**Comment by barryib** [comment]
@ThePixelDeveloper I submitted these following PRs:
- elasticsearch_plugin: Fix bug when using proxy #2838
- elasticsearch_plugin: rewrite module to not use unsupported parameters #2839

I will submit 2 others to add check mode and force option, when #2838 #2839 are merged. Because those future PR will be taken from them.

**Comment by gregdek** [comment]
Thanks @barryib for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by barryib** [comment]
Closing this PR. See #2838 and #2839

**Pull request closed without merging**
