### PR TITLE
Fixes #3539 "win_robocopy does not return changed properly"

### LINKED ISSUE #3498: win_robocopy:  The variable '$changed' cannot be retrieved because it has not been set.
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_robocopy

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
[defaults]
host_key_checking = no

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes

##### OS / ENVIRONMENT
Running ansible from ubuntu bash on windows 10 anniversary
Running win_robocopy on host windows 2012 R2
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

##### SUMMARY

I get "The variable '$changed' cannot be retrieved because it has not been set." error when I use win_robocopy
##### STEPS TO REPRODUCE

```
- name: Backup files
  win_robocopy:
    src: "{{install_root}}"
    dest: "{{install_root}}.bak"
    purge: yes
    recurse: yes
```

##### EXPECTED RESULTS

win_robocopy works :)
##### ACTUAL RESULTS

win_robocopy fails on
```
Set-Attr $result.win_robocopy "changed" $changed
```

If $changed is initialize to $false, the script works

at line 112 :
```
Set-Attr $result.win_robocopy "return_code" $rc
Set-Attr $result.win_robocopy "output" $robocopy_output

$cmd_msg = "Success"
$changed = $false
If ($rc -eq 0) {
    $cmd_msg = "No files copied."
}
```

**Error stack**

```
TASK [server : Backup files] ***********************************
task path: server/tasks/main.yml:2
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/extras/windows/win_robocopy.ps1
<192.168.33.20> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.33.20
<192.168.33.20> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1479487487.3-247510806404649").FullName | Write-Host -Separator '';
<192.168.33.20> PUT "/tmp/tmpAzBWvQ" TO "C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1479487487.3-247510806404649\win_robocopy.ps1"
<192.168.33.20> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1479487487.3-247510806404649\win_robocopy.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1479487487.3-247510806404649" -Force -Recurse -ErrorAction SilentlyContinue }
An exception occurred during task execution. The full traceback is:
At C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1479487487.3-247510806404649\win_robocopy.ps1:392 char:41
+ Set-Attr $result.win_robocopy "changed" $changed
+                                         ~~~~~~~~
fatal: [ids-server-local]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "win_robocopy"
    },
    "msg": "The variable '$changed' cannot be retrieved because it has not been set."
```

**I can do the PR if you want**

### LINKED ISSUE #3539: win_robocopy does not return changed properly
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_robocopy

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /ansible/ansible_config
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

win_robocopy returns all of it's returned variables inside a win_robocopy node, preventing ansible from reading the changed variable (since it's actually win_robocopy.changed).

##### STEPS TO REPRODUCE

Run a win_robocopy which will make a change with -v or higher.

```
ansible -i hosts all -m win_robocopy -a "src=C:\DirectoryOne dest=C:\DirectoryTwo" -v
```

##### EXPECTED RESULTS

Value of changed = true

##### ACTUAL RESULTS

Value of changed = false
Value of win_robocopy.changed = true

Note: For various reasons I cannot copy/paste from my ansible machine, so I've tried to type enough detail to be useful. I know the fix for this, I'll submit a pull request later.

### PR DESCRIPTION
**Pull request by sherlockmatt**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

win_robocopy

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /ansible/ansible_config
  configured module search path = Default w/o overrides
```

##### SUMMARY

Fixes #3539 "win_robocopy does not return changed properly":
Remove the win_robocopy object from $result. This brings the code in line with the documentation, and correctly sets the changed attribute.

BEFORE:
```
ok: [x.x.x.x] => (item=path/to/file.ext) => {
    "changed": false,
    ...
    "win_robocopy": {
        "changed": true
    },
    ...
```

AFTER:
```
changed: [x.x.x.x] => (item=path/to/file.ext) => {
    "changed": true,
    ...
```

I can't copy and paste from my ansible machine so I've manually typed a shortened output. It should still be enough to get the point though.

Also worth noting that this doesn't fix #3498, that will still need to be merged.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @sherlockmatt. To the current maintainers, @blakfeld please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by blakfeld** [comment]
So, _generally_ I prefer to err on the side of more issues/more specific pull requests, but everything here seems super sane, and I see no reason to fuss over it.

Thanks so much for the PR!

shipit

**Comment by jhawkesworth** [comment]
If I've read this right, this changes the return structure, which could break existing playbooks?
It would be straightforward to fix the playbooks, but I think since its a potentially breaking change, it should at the least be mentioned in the module documentation (and noted in the change log).
@sherlockmatt - would you mind putting a note in the documentation .py?  (change log should get updated on merge).

**Comment by gregdek** [comment]
Thanks again to @sherlockmatt for this PR, and thanks @blakfeld for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sherlockmatt** [comment]
@jhawkesworth Where might I find this documentation .py? This is my first ansible PR :)

EDIT: found it!

EDIT2: The documentation was largely already correct, hence this pull request to make it match. I have changed return_code to rc now though, see below. In case there are still two there, I made the first one incorrectly, and redid it properly. I thought I deleted the wrong one, but it seems to still be here...

**Comment by blakfeld** [comment]
Good call @jhawkesworth!

**Pull request closed without merging**
