### PR TITLE
Add new parameters to taskdefinition module - network_mode and task_r…

### LINKED ISSUE #3015: ecs_taskdefinition new parameter for task role arn (iam role)
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

ecs_taskdefinition
##### ANSIBLE VERSION

2.2
##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### SUMMARY

AWS have recently added the ability to assign an IAM role to a task definition by specifying the ARN of the role.

This PR adds that functionality by defining a new parameter - task_role_arn

### PR DESCRIPTION
**Pull request by wimnat**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ecs_taskdefinition
##### ANSIBLE VERSION

2.2
##### SUMMARY

Resolves #3015 

Adds two new parameters to the module:

task_role_arn 
network_mode

These are new features in AWS

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @wimnat for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @wimnat. To the current maintainers, @Java1Guy, @rmorlok please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rmorlok** [comment]
Hey @wimnat, sorry it's taken so long to look at this. I've got an existing PR (https://github.com/ansible/ansible-modules-extras/pull/2357) that needs to be merged for the `ecs_taskdefinition` module that resolves some other issues. Since it's taken forever to get that merged, I think I'm going to try to add to it to include these new parameters.

**Comment by gregdek** [comment]
Thanks @wimnat for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rmorlok** [comment]
#2357 has merged, so if we can get this rebased we can get it going

**Comment by gregdek** [comment]
@wimnat A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
