### PR TITLE
If and else blocks differs only in using exist_interfaces or exist_…

### PR DESCRIPTION
**Pull request by cinek810**
…interfaces_copy, which are completelly the same. Even if intention was to use exists_interfaces or interfaces comparing this only basinc on length is a poor solution, so I'd suggest to simplify the code with keeping it's current functionality

### CODE REVIEW

**Comment by cinek810** [comment]
Second commit goes with the same pull request, but it's not only code simplification but also new feature.

**Comment by cinek810** [comment]
I merged this pull request with current devel. I think that it adds very nice feature. Just being curious, should I add myself as a coauthor of this module? Can I somehow remove "needs_rebase" tag?

**Comment by cinek810** [comment]
I resolved conflicts one more time, because of another changes in devel...

**Comment by cinek810** [comment]
@bcoca rebased to current devel and squashed to one commit, is it OK now?

**Comment by cinek810** [comment]
@resmo Can you make a review of the commit?

**Comment by gregdek** [comment]
Thanks @cinek810 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cinek810** [comment]
I'll merge commits in a few days

**Comment by gregdek** [comment]
@cinek810 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cinek810** [comment]
@gregdek  commits squashed - I think everything is OK now

**Comment by cinek810** [comment]
@gregdek  I don't know how can I solve this issue - it happens in appling patch for yum module, but this has nothing  related to changes I've introduced to zabbix_host module.

**Comment by gregdek** [comment]
@cinek810 the problem is very likely that the original PR is just too old and is getting fit against an old branch with cruft. If you can rebase against the latest branch, these problems will likely be resolved.

**Comment by cinek810** [comment]
I feel I did something wrong. I pulled the current devel and then I rebased..

**Comment by cinek810** [comment]
@gregdek  OK, I think I finally figured out how to do this appropriatelly. Hope it will be revied/merged before other changes :)

**Comment by gregdek** [comment]
@cinek810 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@cinek810 Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to inactivity. @cinek810 if you want to keep working on it, ping me and we can reopen.

**Pull request closed without merging**
