### PR TITLE
now handles keys protected with a passphrase

### PR DESCRIPTION
**Pull request by ghost**
This is an update to the ec2_win_password module to make it work with passphrase protected keys.

### CODE REVIEW

**Comment by gregdek** [comment]
@rickmendes can you add version added in the doc section (2.0)? Once you do that we'll happily merge.

**Comment by ghost** [comment]
@gregdek Thanks for the reminder. Done.

**Comment by ghost** [comment]
@gregdek As the owner of this module, is there anything I can do to get these updates merged? Thanks.

**Comment by gregdek** [comment]
Gah, looks like a process breakdown; we should have auto-merged the second you fixed version_added as an owner_pr. My fault; I missed it.

And unfortunately, looks like it now needs rebasing. So if you can take care of that, we should be able to merge this basically immediately.

**Comment by ghost** [comment]
@gregdek Rebased as requested. Thanks.

**Pull request merged**
