### PR TITLE
little fix: facts['path'] -> facts['project_path']

### PR DESCRIPTION
**Pull request by stivio**

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @stivio. @ramondelafuente please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ramondelafuente** [comment]
shipit

**Comment by robynbergeron** [comment]
Thanks again to @stivio for this PR, and thanks @ramondelafuente for reviewing. Marking for inclusion.

**Comment by stevenscg** [comment]
@robynbergeron +1 for this PR. Eligible for `rc4`??

I run `deploy_helper` with most of my projects and at least the `state=finalize` portion appears to have been broken in `devel` and `v2.0.0-0.8.rc3`.

Applying this change on top of `rc3` fixes my issue completely.

**Comment by ramondelafuente** [comment]
If at all possible, I agree this should be in RC4. I should probably not have included the feature request that caused this in the RC3 stage but I'm not up to speed with the release cycles/dates so that's my mistake :(

**Comment by ramondelafuente** [comment]
@robynbergeron to be clear: this is a `bugfix` for version 2.0
(not sure if it needs to be labeled that way)

**Comment by stevenscg** [comment]
(thumbsup) Just had to revert back from 2.0.0.0 to the dev build to workaround this.

**Pull request merged**
