### PR TITLE
Add encryption capability to AMI copy

### PR DESCRIPTION
**Pull request by ryansydnor**
This addresses https://github.com/ansible/ansible-modules-extras/issues/1379

This depends on https://github.com/boto/boto/pull/3438

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @ryansydnor. @amir343 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by amir343** [comment]
shipit

**Comment by ryansydnor** [comment]
Depends on https://github.com/boto/boto/pull/3438 being merged and released.

**Comment by gregdek** [comment]
Thanks again to @ryansydnor for this PR, and thanks @amir343 for reviewing. Marking for inclusion.

**Comment by ryansydnor** [comment]
@gregdek - depends on a boto PR being merged. Does marking for inclusion take that into account? If not, I'd remove the tag.

**Comment by ryansydnor** [comment]
@gregdek - Great news! The PR was just merged into boto's develop branch! Still need to update Ansible's dependencies to reflect the changes, but slightly easier on us now.

**Comment by gregdek** [comment]
Thanks @ryansydnor for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansydnor** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @ryansydnor. To the current maintainers, @amir343 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansydnor** [comment]
@gregdek - @amir343 already said shipit 5 months ago.

**Comment by gregdek** [comment]
@ryansydnor thanks for the ping -- bot not smart enough to catch this case. Putting back into shipit.

**Comment by alikins** [comment]
Looks like boto version 2.4.0 ( https://github.com/boto/boto/releases/tag/2.40.0 )has this 
change (https://github.com/boto/boto/commit/51e60352e42cbef3baa117ad35f570cc1b993824)

**Comment by ryansydnor** [comment]
_nods_ 🚢 :shipit:

**Comment by alikins** [comment]
Does this need to check for boto 2.40.0 ?

**Pull request merged**
