### PR TITLE
fix documentation contents and format

### PR DESCRIPTION
**Pull request by Java1Guy**
Apparently it can't auto-merge because the file was deleted in the devel branch...

### CODE REVIEW

**Comment by sivel** [comment]
You are correct.  That module is no longer part of Ansible.  It was removed in https://github.com/ansible/ansible-modules-extras/pull/1025

**Comment by Java1Guy** [comment]
Indeed it was -- the $10,000 question is why?  My speculation was because the documentation was hosed...
fyi - @defionscode

**Comment by sivel** [comment]
@bennojoy can probably explain more, but it seems specifically targeted at removing the facts plugins.  I know there were questions about their inclusion before merging, my guess it was related to that.

**Comment by Java1Guy** [comment]
I guess we'll wait to hear from @bennojoy  - but, if it was due to docs issues, i believe they are resolved (at least i have run all the ecs modules through ansible-doc now).

**Comment by gregdek** [comment]
This is probably a good question to ask in ansible-devel. Closing for now; if there's a reason to reopen down the line, we can do that. For now, though, the module no longer exists.

**Comment by bennojoy** [comment]
@gregdek  @Java1Guy The main reason was i had less bandwidth to check the facts module and fix them and since both modules were in one commit i had to remove them. It is in my todo list to add them back and also we are also thinking if these should be seperate modules or just have one module ecs_facts. Also most of the facts are returned by the module itself to have a working ecs cluster setup but if you think the facts modules are absolutely mandatory i can give priority to add back those modules.

**Comment by Java1Guy** [comment]
I was mostly going with what I perceived to be the convention already established.  The true test will come from anybody actually trying to use the modules, so we'll see.  Thanks for the reply.

**Pull request closed without merging**
