### PR TITLE
add executable parameter to cpanm module

### PR DESCRIPTION
**Pull request by yteraoka**
like other packaging modules (pip, gem)

### CODE REVIEW

**Comment by gregdek** [comment]
@franckcuny Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
I'm interpreting that as a "shipit" -- @yteraoka thanks for the PR, and @franckcuny thanks for the review. Marking for inclusion.

**Comment by gregdek** [comment]
@yteraoka apologies, but it appears that another PR was merged first that conflicts with this one, and it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by yteraoka** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @yteraoka. @franckcuny please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @yteraoka. @franckcuny please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @yteraoka -- moving back to shipit.

**Pull request merged**
