### PR TITLE
Add SQS queue policy attachment functionality

### PR DESCRIPTION
**Pull request by nand0p**
##### Issue Type:
- Feature Pull Request
##### Plugin Name:

cloud/amazon/sqs_queue
##### Ansible Version:

```
ansible 1.9.4
```
##### Summary:

Allows for attaching policy to sqs queue upon create / update

SQS queue has no attribute 'Policy' until one is attached, so this special
case must be handled uniquely

SQS queue Policy can now be passed in as json

### CODE REVIEW

**Comment by sivel** [comment]
```
============================================================================
./cloud/amazon/sqs_queue.py
============================================================================
ERROR: version_added for new option (policy) should be 2.1. Currently 0.0
```

**Comment by nand0p** [comment]
@sivel needs_revision label has been addressed

**Comment by robynbergeron** [comment]
Thanks @nand0p. @loia please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by nand0p** [comment]
@iola added myself to authors in this PR, as i feel i have a good understanding of this module after working closely thru it, and would be happy to help maintain. please let me know if this is not appropriate and i should remove.

**Comment by loia** [comment]
@robynbergeron Questions for you:
1. This PR has the same feature as #1474.  How should this be handled?
   #1474 also includes an additional feature (queue redrive policy) which this PR does not have.
   #1474 was raised first but the author hasn't addressed my review comments from 23-Jan.
   I'd be inclined to merge whichever PR passes code review first and then close/update the other one.  Thoughts?
2. @nand0p has added himself as an author/maintainer of this module which is fine by me.  Any problem with this?

**Comment by loia** [comment]
needs_revision

@nand0p Thanks for the PR.  My review comments:
1. Comparing the existing and new values of `Policy` is not handled correctly as it compares a string to a dict which always results in `changed` to be `True` in the result.  They need to be converted to the same type and also ignore the ordering of JSON keys.  Here's an example of how it could work:

```
def set_queue_attribute(queue, attribute, value, check_mode=False):
    if not value:
        return False

    existing_value = queue.get_attributes(attributes=attribute).get(attribute)

    # convert dict attributes to JSON strings (sort keys for comparing)
    if attribute is 'Policy':
        value = json.dumps(value, sort_keys=True)
        if existing_value:
            existing_value = json.dumps(json.loads(existing_value), sort_keys=True)

    if str(value) != existing_value:
        if not check_mode:
            queue.set_attribute(attribute, value)
        return True

    return False
```

**Comment by gregdek** [comment]
Thanks @nand0p for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nand0p** [comment]
`TASK: [make sqs queue] ******************************************************** 
ok: [localhost] => {"changed": false, "default_visibility_timeout": null, "delivery_delay": null, "maximum_message_size": null, "message_retention_period": null, "name": "sqs-queue-test-001", "policy": {"Id": "arn:aws:sqs:us-east-1:111122223334:sqs-queue-test-001/SQSPolicy", "Statement": [{"Action": "SQS:SendMessage", "Condition": {"ArnEquals": {"aws:SourceArn": "arn:aws:sns:us-east-1:111122223334:sns-topic-test-001"}}, "Effect": "Allow", "Principal": {"AWS": "*"}, "Resource": "arn:aws:sqs:us-east-1:111122223334:sqs-queue-test-001", "Sid": "Sid1455815048098"}], "Version": "2012-10-17"}, "receive_message_wait_time": null, "region": "us-east-1"}`

this should be working now, as it does not return changed=True when the same Policy already exists

ready_for_review

**Comment by gregdek** [comment]
Thanks @nand0p. To the current maintainers, @loia please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by loia** [comment]
@nand0p Thanks, I've tested it and it looks good.

shipit

**Comment by gregdek** [comment]
Thanks again to @nand0p for this PR, and thanks @loia for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
