### PR TITLE
Fixes #2139 issue

### LINKED ISSUE #2139: maven_artifact does not use classifier when constructing destination name of artifact
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 1fc44e4103) last updated 2016/05/02 13:44:52 (GMT +1050)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 13:45:21 (GMT +1050)
  lib/ansible/modules/extras: (devel 1846de2809) last updated 2016/05/02 13:28:20 (GMT +1050)
  config file = xxx/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### OS / ENVIRONMENT

OS X El Capitan v10.11.4
##### SUMMARY

When specifying a classifier for maven_artifact and a directory as the dest parameter, the destination filename is constructed assuming no classifier. I.e.

`artifact_id + "-" + version + "." + extension` vs
`artifact_id + "-" + version + "-" + classifier + "." + extension`

This causes problems when say downloading multiple artifacts with same same groupId:artifactId:version coordinates. Depending of the version of lib/ansible/modules/extras used, either subsequent artifacts are skipped because the destination exists, or is overwritten as the MD5 hash is different.
##### STEPS TO REPRODUCE

```

---
- hosts: test-hosts
  tasks:
    - name: Create temporary directory
      file:
        path: /tmp/ansible-test
        state: directory

    - name: Download Stanford Core NLP
      maven_artifact:
        group_id: edu.stanford.nlp
        artifact_id: stanford-corenlp
        version: 3.6.0
        dest: /tmp/ansible-test/
        state: present

    - name: Download Stanford Core NLP Models
      maven_artifact:
        group_id: edu.stanford.nlp
        artifact_id: stanford-corenlp
        version: 3.6.0
        classifier: models
        dest: /tmp/ansible-test/
        state: present
```
##### EXPECTED RESULTS

Should download two artifacts to

```
/tmp/ansible-test/stanford-corenlp-3.6.0.jar, and
/tmp/ansible-test/stanford-corenlp-3.6.0-models.jar
```
##### ACTUAL RESULTS

One file `/tmp/ansible-test/stanford-corenlp-3.6.0.jar`

### PR DESCRIPTION
**Pull request by abaschen**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

packaging/language/maven_artifact.py
##### ANSIBLE VERSION

Tested in :

```
ansible 2.1.1.0
```
##### SUMMARY

When specifying a snapshot with a classifier, it will retrieve the version number in maven-metadata.xml in metadata/versioning/snapshotVersions then return the correct URL instead of just the latest regardless of the classifier

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @TecHunter. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by TecHunter** [comment]
Hold on, I found out this morning that the issue is still there when fetching corresponding md5 files. Weird because when I tested it last time it was working. I will produce a fix today

**Comment by chrisisbeef** [comment]
Looks good to me! Thanks @TecHunter !

shipit

**Comment by gregdek** [comment]
Thanks again to @TecHunter for this PR, and thanks @chrisisbeef for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by TecHunter** [comment]
This doesn't fix for "latest" version though. It just ignore the classifier. Will try to fix it as well

**Comment by abaschen** [comment]
sorry. misclicked on close...

**Comment by gregdek** [comment]
Thanks @TecHunter for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@TecHunter A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abaschen** [comment]
This commit https://github.com/ansible/ansible-modules-extras/commit/1db36bea62d032f841153f2abd04d84fceb48fa7 fixed the same issue. Closing this one

**Pull request closed without merging**
