### PR TITLE
Support not requiring a full window of data

### PR DESCRIPTION
**Pull request by jjshoe**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

datadog_monitor
##### SUMMARY

Support not requiring a full window of data

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jjshoe. To the current maintainers, @skornehl please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by skornehl** [comment]
@jjshoe Sorry for my delayed answer and thanks for the PR.

There is already another PR doing this (#2653) so let's close this one.

close_me

**Comment by gregdek** [comment]
Thanks @jjshoe. One of the current maintainers, @skornehl, @jjshoe requested to close this PR.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closed as dup of #2653.

**Pull request closed without merging**
