### PR TITLE
Added new module interfaces_file

### PR DESCRIPTION
**Pull request by hryamzik**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

interfaces_file
##### SUMMARY

This module is designed to manage interface options in Debian based systems.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @hryamzik for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @hryamzik for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hryamzik** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @hryamzik for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hryamzik** [comment]
After 18 days in a queue it just got outdated, nice...

**Comment by evgkrsk** [comment]
shipit

**Comment by hryamzik** [comment]
@bcoca, @evgkrsk are there any plans to actually "shipit"?

**Comment by hryamzik** [comment]
Nice.

**Pull request closed without merging**
