### PR TITLE
Resolve error case where state=present fails

### PR DESCRIPTION
**Pull request by Rtzq0**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME
- packaging/os/svr4pkg.py
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

But also probaby anything since then since this file hasn't changed since may 2015
##### SUMMARY

Add "None" to checked options because the variable `rc` is not changed from `None` if the package is already installed.

If you run this once to install a package it works. If you run it a second time you end up with changed == False , failed == True

state=present fails here when the package is already installed because rc is still set to none (192-199) when state=present

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jasonritzke. To the current maintainers, @brontitall please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @jasonritzke for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Rtzq0** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @jasonritzke. To the current maintainers, @brontitall please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
closed by 93472c3c542a68f5be45d4c2381a9d8e82f2f04e in #1852

**Pull request closed without merging**
