### PR TITLE
Unchecked index causes IndexError.

### PR DESCRIPTION
**Pull request by kubilus1**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

crypttab.py
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```

Module from 2.1.0

Running from: ansible 1.9.4
##### SUMMARY

Add a simple length check before indexing to avoid IndexError

Fixes issue #1979 

Before:

failed: [cb] => {"failed": true, "parsed": false}
BECOME-SUCCESS-atlkxchqoylvcpkxtyiajfajozptnvwx
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1459953324.47-72446787071472/crypttab", line 1973, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1459953324.47-72446787071472/crypttab", line 163, in main
    f.write(str(crypttab))
  File "/root/.ansible/tmp/ansible-tmp-1459953324.47-72446787071472/crypttab", line 208, in **str**
    if crypttab[-1] != '\n':
IndexError: string index out of range
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /home/mkubilus/.ssh/config
debug1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.125.87.225 closed.

after:

TASK: [do_stuff | Remove old crypttab entry if necessary] *******************
changed: [stuff]

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @kubilus1. To the current maintainers, @groks please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by groks** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @kubilus1 for this PR, and thanks @groks for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by kubilus1** [comment]
thanks! glad to help.

**Pull request merged**
