### PR TITLE
Add type property to zypper

### PR DESCRIPTION
**Pull request by greghaynes**
To install patterns and other package types a type parameter needs to be
specified to zypper.

### CODE REVIEW

**Comment by alxgu** [comment]
You forgot the documentation. For example - zypper: name=kvm_server type=pattern state=present

I would suggest to change the variable name from install_type to type_of_pkg or only in the package_absent function.

:+1:

**Comment by greghaynes** [comment]
bumping to get this merged

**Comment by alxgu** [comment]
version_added: (2.0?) is missing in the documentation block.

**Comment by robinro** [comment]
Thanks @greghaynes  :+1:

**Pull request merged**
