### PR TITLE
Enable stdout and stderr on sucessful runs, making show_diff useable

### PR DESCRIPTION
**Pull request by Jmainguy**
This adds stdout and stderr to the module, which makes the show_diff choice useful, as it will print it out now.

@emonty Let me know what you think

### CODE REVIEW

**Comment by bcoca** [comment]
cc @emonty

**Comment by Jmainguy** [comment]
@emonty @bcoca whats the deal, Why was https://github.com/ansible/ansible-modules-extras/pull/1260  merged but this wasn't. Would really like some feedback.

**Comment by bcoca** [comment]
Merged cause it had shipit label, I wasn't aware of overlap either or would
have raised the question.

**Comment by Jmainguy** [comment]
Cool, that makes sense. Looks like this still adds some additional stdout, stderr, and color=0 to the module. So I will keep this open. @emonty can you please review this PR?

**Comment by gregdek** [comment]
Trivial. Adding shipit myself.

**Pull request merged**
