### PR TITLE
new module to generate SSL certificates

### PR DESCRIPTION
**Pull request by ghost**
I botched this PR, will resubmit.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @aeibrahim for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by sivel** [comment]
@aeibrahim here is some feedback from our automated module scanning:

```
============================================================================
./web_infrastructure/generate_ssl_cert.py
============================================================================
ERROR: version_added should be 2.1. Currently 2.0
ERROR: No RETURN documentation provided
ERROR: indentation contains tabs. line 276 column 17
ERROR: indentation contains tabs. line 286 column 17
ERROR: indentation contains tabs. line 291 column 98
ERROR: indentation contains tabs. line 295 column 8
ERROR: indentation contains tabs. line 298 column 4
```

**Comment by aeibrahim** [comment]
thanks for the feedback @sivel. I will revise the code and make corrections.

**Comment by aeibrahim** [comment]
I've made some changes to the module. Added more options and support for generating ECDSA certificates. @sivel I ran it through your testing tool and corrected any issues it raised.

**Pull request closed without merging**
