### PR TITLE
Adding the --sudo flag for CPANM use since the sudo: yes on the task …

### PR DESCRIPTION
**Pull request by milad-soufastai**
Add the ability to use --sudo flag with the CPANM module.

### CODE REVIEW

**Comment by bcoca** [comment]
'sudo: yes on the task does not work' <= exactly how is that not working?

sudo on the task should run the whole command under sudo, not add the --sudo flag to the underlying command. The result should be the same but the intermediate build steps would also be run by the sudo user, not just the install steps.

**Comment by milad-soufastai** [comment]
Hi Brian,
Per CPANM: -S, --sudo
Switch to the root user with sudo when installing modules. Use this if you want to install modules to the system perl include path.

Currently using the ansible cpanm module with or without sudo: yes doesn't actually install the modules in system perl include path but under the user path, usually ~/perl5

**Comment by bcoca** [comment]
we should add a explanation as use_sudo is really 'install in system path' in this case, the sudo at the task level does run it as root. Also that use_sudo will not benefit from ansible handling of sudo password prompts.

**Comment by milad-soufastai** [comment]
@bcoca I've updated the description to match closer what the flag does. I'm not sure about the language around the ansible handling of sudo password.

**Comment by bcoca** [comment]
i changed the option name but kept use_sudo as an alias and expanded the description a bit

**Pull request merged**
