### PR TITLE
Fix issue #1406 about win_firewall_rule

### LINKED ISSUE #1406: win_firewall_rule: Doesn't work in ansible v2.x
Hi,
I'm experiencing the following errors in ansible 2:

``` sh
TASK [0_base : Be sure winrm http is disabled] *********************************
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "error": "The property 'Enable' cannot be found on this object. Verify that the property exists.", "failed": true, "msg": ["The rule 'Deny WinRM HTTP' exists."]}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=3    changed=0    unreachable=0    failed=1   

# and

TASK [0_base : Be sure winrm http is disabled] *********************************
fatal: [ga-z170x-g3]: FAILED! => {"changed": false, "error": "The property 'profile' cannot be found on this object. Verify that the property exists.", "failed": true, "msg": ["The rule 'Deny WinRM HTTP' exists."]}

PLAY RECAP *********************************************************************
ga-z170x-g3                : ok=3    changed=0    unreachable=0    failed=1   
```

Where the task being run looks like this in my playbook:

``` yaml
- name: Be sure winrm http is disabled
  win_firewall_rule:
    name: Deny WinRM HTTP
    enable: yes
    profile: Domain,Private,Public
    protocol: tcp
    localport: 5985
    direction: in
    action: block
    state: present
    force: yes
  tags: firewall
```

These errors do not happen on ansible v1.9.4.

### PR DESCRIPTION
**Pull request by ilpianista**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

win_firewall_rule
##### Ansible Version:

```
2.0.x
```
##### Summary:

Fixes #1406.

The plugin was looking for non existent keys from netsh.

I changed the logic to always use 'netsh ... show rule' keywords as keys for $fwsettings map. While the translation (e.g. Enabled -> enable) is performed when invoking 'netsh ... add rule' command.

### CODE REVIEW

**Comment by tcr-ableton** [comment]
As mentioned in the initial issue: I can confirm that @ilpianista patch fixes the problem mentioned by @chrisjsmith for me on Windows 7, 8 and 10 :+1:

**Comment by t-v** [comment]
@gregdek since this has been confirmed as a fix and I can't see any abnormalities in the code, you can shipit

**Comment by gregdek** [comment]
Thanks @ilpianista. @TimothyVandenbrande please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks again to @ilpianista for this PR, and thanks @TimothyVandenbrande for reviewing. Marking for inclusion.

**Comment by resmo** [comment]
also backported to stable-2.0

**Pull request merged**
