### PR TITLE
added win_find module to match find module features...

### PR DESCRIPTION
**Pull request by jborean93**
##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
win_find

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
RIght now there is no easy way to scan windows directories to find files and folders based on search criteria. This can be done using powershell commands and parsing the output but this isn't pretty. To match the majority of the functionality that is available for unix with the find module win_find is designed to achieve a similar output with some slight modifications for Windows.

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Just to say this looks like it will be very useful, many thanks for creating this PR.
Jon

**Comment by jborean93** [comment]
Have added the relevant tests in this pull request https://github.com/ansible/ansible/pull/18330

**Comment by gregdek** [comment]
Thanks @jborean93 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jborean93** [comment]
Changes have been moved into https://github.com/ansible/ansible/pull/19144 after the merge

**Pull request closed without merging**
