### PR TITLE
cloudtrail.py - added sns_topic_name and fixed bug when s3_key_prefix is empty

### PR DESCRIPTION
**Pull request by Constantin07**
##### Issue Type:
- Bugfix Pull Request
- Feature Pull Request
##### Ansible Version:

ansible 2.1.0
##### Ansible Configuration:

Default configuration.
##### Environment:

CentOS Linux release 7.2.1511 (Core) + latest updates.
##### Summary:
1. If the "s3_key_prefix" option is left empty the module works fine on the first run when cloudtrail is created, but fails with error on the subsequent re-runs when it's already enabled in AWS.
2. Fixed some documentation - "s3_bucket_prefix" should be actually "s3_bucket_name" as per code.
3. Added "sns_topic_name" to send notifications to SNS for every log file delivery.
4. Added "logging" option to enable/disable cloudtrail logging.
##### Steps To Reproduce the issue:

```
    cloudtrail:
      region: "{{ aws_region }}"
      include_global_events: true
      s3_bucket_name: "{{ bucket }}"
      name: "{{ trail_name }}"
      state: enabled
```
##### Expected Results:

The module should return output without error.
##### Actual Results:

```
TASK [Enable CloudTrail] ****************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1452902607.98-79421731238958/cloudtrail", line 2440, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1452902607.98-79421731238958/cloudtrail", line 194, in main
    results['view']['S3KeyPrefix']                != s3_key_prefix  or \
KeyError: 'S3KeyPrefix'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "cloudtrail"}, "parsed": false}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
Any updates?

**Comment by gregdek** [comment]
@Constantin007 not at present, because there are no community maintainers for this module. 

If you would be willing to review all subsequent PRs for this module, we could make you the community maintainer. Would you be interested? You would then be able to give a "shipit" to this PR, which would then move it directly to final review.

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
