### PR TITLE
Fix for - Firewalld traces with ALREADY_ENABLED when using port name or re-ordered rich rule

### PR DESCRIPTION
**Pull request by ag-wood**
Fixes ansible-modules-extras issue #1080

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @ag-wood -- thanks for submitting this PR for fixing #1080. (And fixes https://github.com/ansible/ansible/issues/11473 as well, it looks like.)

@maxamillion -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Thanks, everyone! :)

**Comment by gregdek** [comment]
@maxamillion This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by apenney** [comment]
@ag-wood @gregdek I'm trying to ping him on IRC to get him to check this as I suspect i'm hitting the same thing.

**Comment by robynbergeron** [comment]
@maxamillion still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by maxamillion** [comment]
:+1: shipit

**Pull request merged**
