### PR TITLE
Added features to cloudtrail module and new SQS parser

### PR DESCRIPTION
**Pull request by kalpatel01**
If cloudtrail is created manually and then this module is used, the module will crash since keys do not exist in results.  All keys should be checked before being used.

Added the ability to define sns_topics and cloudwatch logs.

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @kalpatel01. @NONE please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@kalpatel01 -- apologies -- this one fell through the cracks with no proper owner listed. 

@ansible/core -- this one belongs to you, maintainers file has been appropriately updated. Please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Changing to core_review since it's owned by the core team.

**Comment by gregdek** [comment]
Closing this PR, as the branch is unmanaged and has hundreds of commits. @kalpatel01 if you want to create a new branch and resubmit this PR, that would be welcome.

**Pull request closed without merging**
