### PR TITLE
letsencrypt: Improve error handling

### PR DESCRIPTION
**Pull request by mgruener**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

web_infrastructure/letsencrypt
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel abbb93e117) last updated 2016/09/06 23:02:31 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a746eff954) last updated 2016/09/06 23:03:03 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 1474bde864) last updated 2016/09/06 23:03:03 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Thanks to ansible/ansible#14915 it is now possible to get the body of a HTTPError response. Add support for the new `info['body']` field returned by `fetch_url`.

Also fix an unexpected HTTP status 202 response from the letsencrypt server when polling the challenge validation.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @mgruener. This module is going into community review.

We notice that you are one of the maintainers (@mgruener) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@mgruener anything left here? Mark for inclusion?

**Comment by mgruener** [comment]
Nope, just forgot to add the final comment

shipit

**Comment by gregdek** [comment]
Thanks @mgruener. Since you are one of the maintainers (@mgruener) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
