### PR TITLE
elasticsearch_plugin: add check mode support

### PR DESCRIPTION
**Pull request by barryib**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

elasticseach_plugin
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add [Check Mode](http://docs.ansible.com/ansible/developing_modules.html#check-mode) support

### CODE REVIEW

**Comment by barryib** [comment]
@ThePixelDeveloper Precedent PRs just got merged. So here is another one which add check mode support.

**Comment by ThePixelDeveloper** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks again to @barryib for this PR, and thanks @ThePixelDeveloper for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Implementing check mode as noop is not the way is misleading the user. Check mode should be used to find out if anything would be changed. if this is not possible check mode should not be implemented and the tasks will be skipped.

I am afraid, for this reason I am -1.

**Comment by barryib** [comment]
@resmo There is no noop. Changes are always returned (See [L202](https://github.com/barryib/ansible-modules-extras/blob/e875c04a4ada481bf9a1f0b02e78cc38134e416d/packaging/elasticsearch_plugin.py#L202) and [L220](https://github.com/barryib/ansible-modules-extras/blob/e875c04a4ada481bf9a1f0b02e78cc38134e416d/packaging/elasticsearch_plugin.py#L210)).

These lines [L146](https://github.com/barryib/ansible-modules-extras/blob/e875c04a4ada481bf9a1f0b02e78cc38134e416d/packaging/elasticsearch_plugin.py#L146) and [L162](https://github.com/barryib/ansible-modules-extras/blob/e875c04a4ada481bf9a1f0b02e78cc38134e416d/packaging/elasticsearch_plugin.py#L162) are only used to avoid running the real command during check mode.

**Comment by barryib** [comment]
@resmo any news on this PR?

**Comment by resmo** [comment]
@barryib ok, I see, nm

LGTM

**Pull request merged**
