### PR TITLE
win_regedit; fixes dword changed error 2273, improved error handling

### PR DESCRIPTION
**Pull request by jhawkesworth**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

win_regedit
##### ANSIBLE VERSION

```
ansible 2.2.0 (tests_regedit_dword 445a88d3e8) last updated 2016/06/12 06:33:30 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 138430f116) last updated 2016/06/12 06:32:34 (GMT +100)
  lib/ansible/modules/extras: (regedit_fixes_new 8e8536f829) last updated 2016/06/15 06:32:38 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides

```
##### SUMMARY

Fixes issue described in #2273 (without breaking binary registry settings)
also adds a check to ensure the registry key is in the powershell ps-drive format following #2412
and removes .GetType().Name comparisons in favour of -is tests (cleaner code)

```
No change in output, but I will create a separate PR which adds integration tests to cover the cases fixed above.
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Argh, still got irrelevant commits.  My git-fu is weak, and I'm out of time (again) to fix it up.  Will try later.

**Comment by gregdek** [comment]
Thanks @jhawkesworth. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @manuel-sousa, @chrishoffman, @romanek-adam, @joshludwig, @smadam813, @dj-wasabi please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
closing so I can have another go at fixing non-relevant commits that have wound up in this PR.

**Comment by jhawkesworth** [comment]
replaced by https://github.com/ansible/ansible-modules-extras/pull/2436

**Pull request closed without merging**
