### PR TITLE
Fixed exception handeling for Python 2.4 and python 3 compatablity

### PR DESCRIPTION
**Pull request by chris-l-weber**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

Source_control directory
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Fixed exception handling for Python 2.4 and python 3 compatibility
Pycon2016 sprints

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @chris-l-weber. To the current maintainers, @dj-wasabi please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dj-wasabi** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @chris-l-weber for this PR, and thanks @dj-wasabi for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by abadger** [comment]
Thanks @chris-l-weber !  Merged to devel.

**Pull request merged**
