### PR TITLE
support proxmox resource pool

### PR DESCRIPTION
**Pull request by roongr2k7**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

cloud/misc/proxmox.py
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

support proxmox resource pool

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @roongr2k7 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by roongr2k7** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @roongr2k7. To the current maintainers, @UnderGreen please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by UnderGreen** [comment]
shipit :shipit:

**Comment by gregdek** [comment]
Thanks again to @roongr2k7 for this PR, and thanks @UnderGreen for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
