### PR TITLE
Changing from v1 to v2 hipchat api format.

### PR DESCRIPTION
**Pull request by pb8226**
I wanted to use v2 of the hip chat api.  I made the necessary changes to use v2 and replaced http with requests for posting JSON to simplify the code.  I have tested this against my hip chat account and all the parameters were working.

### CODE REVIEW

**Comment by sivel** [comment]
Generally speaking all URL interaction should be handled by the functionality provided by `ansible.module_utils.urls` such as using `fetch_url`.  Adding a dependency on `requests` makes this module diverge from standards and also adds a new dependency that will break backwards compatibility.

**Comment by pb8226** [comment]
thanks @sivel , I'll change the code to remove the requests dependency

**Comment by bcoca** [comment]
i'm not currently using hipchat, what happens to those still using v1 of the api? some of these changes seem to indicate users will have to change their plays.

**Comment by pb8226** [comment]
@bcoca I was actually curious how Ansible likes to handle multiple versions of an external API.  Anyone using HipChat via Atlassian will have the v2 of API available to them.  Is it preferred that I make a separate module for the v2 of the HipChat API and then users can choose whichever one they want to use?

**Comment by pb8226** [comment]
@bcoca Another option would be to add a property to the module to state whether to use the v1 or v2 of the hipchat api.

**Comment by bcoca** [comment]
we normally try to keep backwards compatibility to avoid breaking people's playbook, adding an api_version='v2' (defaults to v1) is something that would work.

**Comment by bcoca** [comment]
or if module can figure out which one to use with the currently supplied data, that is also acceptable.

**Comment by pb8226** [comment]
Makes sense, I can probably figure out the version of the api from the "/v2/" in the URL.  So even if the user supplies his own URL I can do a regex on it to see if it's a v1 or v2 format.

**Comment by pb8226** [comment]
Also it seems like it's preferable to not add any new dependencies.  The reason I'm asking is there is a Python HipChat client, but I have no information on how much benefit it would provide.

**Comment by pb8226** [comment]
Changes have been made to use only Ansible libraries for REST calls.  Module changes add support for the V2 of the HipChat API while also being compatible with the V1 HipChat API.  The module defaults to the V1 HipChat API.  If a user explicitly sets the HipChat server URL the module will check if it's a v1 or v2 HipChat URL and use the appropriate format.

**Comment by hostmaster** [comment]
api v1 is market as 'deprecated'. It probably would be better to switch to v2 by default.

**Comment by pb8226** [comment]
@hostmaster The concern with switching to v2 by default was that existing play books might break.

**Comment by hostmaster** [comment]
@pb8226 it will break for sure. v2 has a diferent auth_token.

**Comment by pb8226** [comment]
@hostmaster yep, that's why I added v2 support so I could use the new tokens.  I was discouraged, further up this thread, to make it the default though.

**Comment by hostmaster** [comment]
@pb8226 please have a look at https://github.com/ansible/ansible-modules-extras/pull/674 when you have time

**Pull request merged**
