### PR TITLE
win_updates rewrite for 2.0

### PR DESCRIPTION
**Pull request by nitzmahone**
uses scheduled job to run under a local token (required for WU client)
supports check mode
no external PS module deps

### CODE REVIEW

**Comment by bcoca** [comment]
cc @petemounce @trondhindenes  @jhawkesworth @cchurch

**Comment by gregdek** [comment]
Looking for feedback from @trondhindenes in particular, since this is basically a full rewrite. 

@nitzmahone beyond the comments above, is there a fuller rationale for the rewrite here?

**Comment by trondhindenes** [comment]
In the process of testing right now.

On Fri, Sep 4, 2015 at 4:57 PM, Greg DeKoenigsberg <notifications@github.com

**Comment by nitzmahone** [comment]
@gregdek: The rationale for the rewrite was here: https://groups.google.com/forum/#!topic/ansible-devel/mpE95vytW4M

**Comment by jsmartin** [comment]
+1

**Comment by dyioulos** [comment]
+1.  Works perfectly!

**Comment by trondhindenes** [comment]
nice, +1 from me. Not sure why my name was in the original module, I'm quite sure I didn't write it. But that doesn't matter now.
@nitzmahone I'd be esp interested in your feedback on this https://groups.google.com/forum/#!topic/ansible-devel/JxU3Mgkpckw but we can discuss that in gruops.

**Comment by nitzmahone** [comment]
@bcoca - are we at critical mass for +1's here yet to get this merged? Hoping this can make the 2.0 beta train if possible to get wider testing, especially considering what we're shipping now is 100% broken.

**Pull request merged**
