### PR TITLE
zypper_repository: Prepend --gpg-auto-import-keys before refresh command

### LINKED ISSUE #3086: zypper_repository: Adding repo with import of custom GPG key fails due to wrong command line option ordering
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

packaging/os/zypper_repository.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Latest Git versions of the `packaging/os/zypper.py` and `packaging/os/zypper_repository.py` modules placed in `library/`
##### CONFIGURATION

Running Vagrant with the `ansible_local` provisioner
##### OS / ENVIRONMENT

openSUSE Tumbleweed as Vagrant Base Box
##### SUMMARY

When adding a zypper repository that requires a custom GPG key to be imported, the zypper_repository module fails because it puts the `--gpg-auto-import-keys` command line option at the wrong place in the command line:

```
/usr/bin/zypper --quiet --non-interactive refresh --force --gpg-auto-import-keys -r http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/
```

Zypper differentiates between options _before_ the command (here `refresh`) and _behind_ it. The correct call would be:

```
/usr/bin/zypper --quiet --non-interactive --gpg-auto-import-keys refresh --force -r http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/
```
##### STEPS TO REPRODUCE

Create a playbook such as the following:

```

---
- hosts: all

  tasks:
  - name: "Test adding a repo with custom GPG key"
    zypper_repository:
      name: "Apache_Modules"
      repo: "http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/"
      priority: 100
      auto_import_keys: true
      state: "present"
```

Run Ansible
##### EXPECTED RESULTS

Repository added successfully
##### ACTUAL RESULTS

```
TASK [Required extra repository for auth_schemes defined] **********************
task path: /vagrant/usbstick/ansible/repo-playbook.yml:5
<zeus> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<zeus> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621 `" && echo ansible-tmp-1475574977.19-103534347658621="` echo $HOME/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621 `" ) && sleep 0'
<zeus> PUT /tmp/tmpaE6SGq TO /home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/zypper_repository
<zeus> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ttdgngwywjmakvvnqrltktyuyopcwlhr; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/zypper_repository; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [zeus]: FAILED! => {"changed": false, "cmd": "/usr/bin/zypper --quiet --non-interactive refresh --force --gpg-auto-import-keys -r http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/", "failed": true, "invocation": {"module_args": {"auto_import_keys": true, "autorefresh": true, "description": null, "disable_gpg_check": false, "enabled": true, "name": "Apache_Modules", "overwrite_multiple": false, "priority": 100, "repo": "http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/", "runrefresh": false, "state": "present"}, "module_name": "zypper_repository"}, "msg": "Unknown option '--gpg-auto-import-keys'", "rc": 2, "stderr": "Unknown option '--gpg-auto-import-keys'\n", "stdout": "", "stdout_lines": []}
```

### PR DESCRIPTION
**Pull request by pief**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

packaging/os/zypper_repository.py
##### ANSIBLE VERSION

Current devel HEAD
##### SUMMARY

This makes `--gpg-auto-import-keys` being specified before the `refresh` command when calling out to zypper because zypper differentiates between options _before_ and _behind_ a command.

Fixes #3086.

Before:

```
TASK [Test adding a repo with custom GPG key] **********************************
task path: /vagrant/usbstick/ansible/repo-playbook.yml:5
<zeus> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<zeus> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621 `" && echo ansible-tmp-1475574977.19-103534347658621="` echo $HOME/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621 `" ) && sleep 0'
<zeus> PUT /tmp/tmpaE6SGq TO /home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/zypper_repository
<zeus> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ttdgngwywjmakvvnqrltktyuyopcwlhr; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/zypper_repository; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1475574977.19-103534347658621/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [zeus]: FAILED! => {"changed": false, "cmd": "/usr/bin/zypper --quiet --non-interactive refresh --force --gpg-auto-import-keys -r http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/", "failed": true, "invocation": {"module_args": {"auto_import_keys": true, "autorefresh": true, "description": null, "disable_gpg_check": false, "enabled": true, "name": "Apache_Modules", "overwrite_multiple": false, "priority": 100, "repo": "http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/", "runrefresh": false, "state": "present"}, "module_name": "zypper_repository"}, "msg": "Unknown option '--gpg-auto-import-keys'", "rc": 2, "stderr": "Unknown option '--gpg-auto-import-keys'\n", "stdout": "", "stdout_lines": []}
```

After:

```
TASK [Test adding a repo with custom GPG key] **********************************
task path: /vagrant/usbstick/ansible/repo-playbook.yml:5
<zeus> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<zeus> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475589514.17-163270196254755 `" && echo ansible-tmp-1475589514.17-163270196254755="` echo $HOME/.ansible/tmp/ansible-tmp-1475589514.17-163270196254755 `" ) && sleep 0'
<zeus> PUT /tmp/tmpWfOxCf TO /home/vagrant/.ansible/tmp/ansible-tmp-1475589514.17-163270196254755/zypper_repository
<zeus> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-nyusrkctbtefrnzgewoexyrjkdldgnhp; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1475589514.17-163270196254755/zypper_repository; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1475589514.17-163270196254755/" > /dev/null 2>&1'"'"' && sleep 0'
changed: [zeus] => {"changed": true, "invocation": {"module_args": {"auto_import_keys": true, "autorefresh": true, "description": null, "disable_gpg_check": false, "enabled": true, "name": "Apache_Modules", "overwrite_multiple": false, "priority": 100, "repo": "http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/", "runrefresh": false, "state": "present"}, "module_name": "zypper_repository"}, "repodata": {"alias": "Apache_Modules", "autorefresh": "1", "enabled": "1", "gpgcheck": "1", "name": null, "priority": 100, "url": "http://download.opensuse.org/repositories/Apache:/Modules/openSUSE_Tumbleweed/"}, "state": "present", "warnings": []
```

### CODE REVIEW

**Review by robinro — APPROVED** [review]
LGTM
shipit

**Comment by robinro** [comment]
@ansible
This needs to get into 2.2 stable. It fixes a bug that renders a newly introduced module argument unusable.

**Comment by gregdek** [comment]
Thanks @pief for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by robinro** [comment]
@gregdek The failure is unrelated to the change.

**Comment by resmo** [comment]
I don't see why this should be in need revision state. shipit

**Pull request merged**
