### PR TITLE
Add support for emerge's --getbinpkg and --usepkgoonly

### PR DESCRIPTION
**Pull request by Tatsh**
PORTAGE_BINHOST set-up required

This is a re-do of https://github.com/ansible/ansible/pull/7449

### CODE REVIEW

**Comment by bcoca** [comment]
@Tatsh can you rebase this request?

**Comment by Tatsh** [comment]
Does this look correct? I am not sure if I did this correctly, but basically once I did `git rebase upstream/devel` I had to run `git pull` to be fully up-to-date.

```
$ git rebase upstream/devel 
First, rewinding head to replay your work on top of it...
Applying: Add support for emerge's --getbinpkg and --usepkgoonly
Using index info to reconstruct a base tree...
A       packaging/portage.py
Falling back to patching base and 3-way merge...
Auto-merging packaging/os/portage.py
```

```
$ git status
On branch add-portage-binhost
Your branch and 'origin/add-portage-binhost' have diverged,
and have 156 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working directory clean
```

```
$ git pull
Merge made by the 'recursive' strategy.
$ git status
On branch add-portage-binhost
Your branch is ahead of 'origin/add-portage-binhost' by 157 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
$ git push -u origin add-portage-binhost 
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.28 KiB | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
To git@github.com:Tatsh-ansible/ansible-modules-extras.git
   e2b6d93..c0da6a5  add-portage-binhost -> add-portage-binhost
Branch add-portage-binhost set up to track remote branch add-portage-binhost from origin.
```

**Comment by bcoca** [comment]
no, you seem to have pulled in many other changes.

nomrally you just need to:

```
git pull --rebase
```

assuming origin is the main ansible repo's devel branch, then deal with conflicts if they appear

**Comment by Tatsh** [comment]
I did a forced commit with the one change via patch (I know forced pushes are not preferred in most circumstances). The conflict was caused by moving the file since this pull request was made. I reset the branch fully against latest `devel` and then applied the patch, fixing for the path.

```
git branch -D add-portage-binhost
git checkout -b add-portage-binhost
wget 'https://github.com/Tatsh-ansible/ansible-modules-extras/commit/e2b6d93ec87df1c9df585cb83eeaddb27c5ae0fc.patch'
patch -p1 < e2b6d93ec87df1c9df585cb83eeaddb27c5ae0fc.patch # type package/os/portage.py to patch
git add packaging/
git commit -m "Add support for emerge's --getbinpkg and --usepkgoonly"
git status # 1 commit ahead of upstream
git push -u origin add-portage-binhost --force
```

**Comment by bcoca** [comment]
when it comes to refreshing PRs force is fine, actually only way most of this works. 
.

**Pull request merged**
