### PR TITLE
Unify mysql modules.

### PR DESCRIPTION
**Pull request by Jmainguy**
Added config_file, ssl_ca, ssl_cert, ssl_key, changed connect method, added error checking where a backtrace previoussly was possible

### CODE REVIEW

**Comment by Jmainguy** [comment]
This is reliant on https://github.com/ansible/ansible/pull/13191 getting merged first, and brings this connection method inline with https://github.com/ansible/ansible-modules-core/pull/2447

**Comment by Jmainguy** [comment]
Updated to use unified documentation as well

**Comment by robynbergeron** [comment]
@Jmainguy -- thanks for submitting this PR.

@banyek -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by banyek** [comment]
In fact these checks are fully automatable, but yea, I'll do that when I'll have time. :(

**Comment by bcoca** [comment]
@banyek many of them are, we are working on putting them into travis, still we would like people to review the code before it goes in

**Comment by banyek** [comment]
kudos, here's 12:05am, so I won't do this today, but when I'll have time I will

**Comment by bcoca** [comment]
i assume everyone is awake when i am ... and i DONT SLEEP!
kidding aside, whenever you can is good.

**Comment by Jmainguy** [comment]
@banyek any comments on the code?

**Comment by banyek** [comment]
Sorry I can't, 3 co-workers left in the past few months I don't know how to breathe - I am exhausted.

**Comment by abadger** [comment]
Refactor merged.

**Pull request merged**
