### PR TITLE
homebrew: Improve 'argument_spec' handling

### PR DESCRIPTION
**Pull request by indrajitr**
- Remove choice list for boolean values in `argument_spec` and make it more consistent with core modules
- Add 'package' alias and support for list type for 'name' parameter

NB: Seems like this module is orphaned. Would be happy to take over in the interim to clear the backlogs :)

### CODE REVIEW

**Comment by gregdek** [comment]
@indrajitr you're quite right. :)

So let's do this. Modify this PR to add yourself at the top of the authors: list. When you're done, please add a comment with the text "ready_for_review".  At that point, I'll merge this one.

In the meantime, if you're willing, I'll go through the other open issues around homebrew and ping you on them.

Thanks for your willingness to help with this module!

**Comment by indrajitr** [comment]
ready_for_review

Sure, feel free to!

**Comment by robynbergeron** [comment]
labeling this as owner_pr per @gregdek's comments above... since this merge will essentially make it an owner_pr :)

marking for inclusion, pinging @gregdek via the magical shipit comment since you said you'd merge it :)

@indrajitr -- thanks for adopting this, you rock! :)

**Comment by indrajitr** [comment]
@gregdek, @robynbergeron anything pending here?

Also, would be happy to pitch in and help prevent the _owner_pr_ or _shipit_ PRs from languishing unattended.  Is there anything that can be done to accelerate the feedback/approve/reject cycle?

**Pull request merged**
