### PR TITLE
New module win dns zone reload

### PR DESCRIPTION
**Pull request by teochenglim**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

New module win dns zone reload
##### ANSIBLE VERSION

```
devel
```
##### SUMMARY

```
To reload a Windows DNS zone after add/edit/delete any zone data.
```

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Hi, it looks like you need to rebase your github fork of ansible-modules-extras as you have lots of commits in here which are unrelated to your module.  Please can you fix this so the pull request only contains the new module?  Many thanks,
Jon

**Comment by teochenglim** [comment]
Hi Jon,

removed those un-wanted.

Cheers,
Cheng Lim

Sent from my Samsung device

**Comment by gregdek** [comment]
Thanks @teochenglim for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Hi, there are still 395 files in this PR, so I don't think it contains just your new module.  Have you pushed the changes to your fork (from your local machine)?

**Comment by teochenglim** [comment]
Hi, Ya. I see it is updated in my latest commit. Please see here.
https://github.com/teochenglim/ansible-modules-extras/tree/win_dns_zone_reload

**Pull request closed without merging**
