### PR TITLE
Do not leak root passwd solaris zone

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

solaris_zone
##### SUMMARY

Do set the root password as 'no_log', so this doesn't leak in log, etc. Also fix a small typo in variable name.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @pmarkham please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by pmarkham** [comment]
shipit

**Comment by pmarkham** [comment]
Thanks @mscherer.

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @pmarkham for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
