### PR TITLE
Add consul http checks to consul.py

### PR DESCRIPTION
**Pull request by jemmyw**
Consul module already supports ttl and script checks. This commit adds
http checks.

### CODE REVIEW

**Comment by bcoca** [comment]
cc @sgargan

**Comment by sgargan** [comment]
@jemmyw change looks good, travis is reporting a failure but its not related to your checkin. Looking at the documentation for these http checks, they apparently take a timeout too so it can break out from a service that is non responsive. The default is apparently 10 seconds. I'm not sure if the python-consul api for http check exposed this, but if it does it might be an idea to allow this timeout to be configured too.

There are a bunch of integration tests in the core project that verify all the consul behavior, take a look at these, would be good if you could add tests for your changes there too.

**Comment by jemmyw** [comment]
@sgargan OK, I've added the timeout option and fixed a bug with the script thanks to the integration tests. I'm not sure how to make a referencing PR for the integration tests, but they are here: jemmyw/ansible@9f9f476b6e97da926d6482b8fd737346733667ae

**Comment by gregdek** [comment]
Adding to core_review to advise on integration tests.

**Comment by evanccnyc** [comment]
Be nice to have the ability to specify an additional url to the http check. So you could do http://blah/status etc.

**Comment by abadger** [comment]
Code looks good to me too.  @evanccnyc, did you test that this works for you?  If you could +1 from that standpoint that would be good to know.

@jemmyw For the integration tests, just open a PR against the ansible/ansible repository and post the link here.  Then we can merge both this one and that one at the same time.

**Comment by evanccnyc** [comment]
@jemmyw any chance you can add a way to specify the status url: ie it could check /status or /lb etc?

**Comment by robynbergeron** [comment]
Hi @jemmyw -- 

Hopefully this gives you enough info re: integration tests to go forward. If you want to open a PR for the integration test (as mentioned by @abadger above) and reference it here that would be perfect -- then we can move forward! Thanks.

**Comment by jemmyw** [comment]
@robynbergeron PR for the integration tests https://github.com/ansible/ansible/pull/12589

**Comment by jemmyw** [comment]
@evanccnyc the status url can be specified by setting the http param. i.e. interval=10s http=/status

**Comment by evanccnyc** [comment]
@jemmyw I see, any chance you can provide an example in the example of that or clarify the documentation?

**Comment by robynbergeron** [comment]
@jemmyw -- can you possibly add the the example as requested by @evanccnyc? It looks like the integration tests have already been merged. Let us know, thanks!

**Comment by jemmyw** [comment]
@robynbergeron @evanccnyc example added, and yes the integration tests have been merged.

**Comment by robynbergeron** [comment]
@jemmyw -- thanks for the revision to include examples.  

@evanccnyc -- does this look good to you as far as examples go? Also double-checking again with @sgargan as the module maintainer.

**Comment by evanccnyc** [comment]
Looks good to me shipit.

**Pull request merged**
