### PR TITLE
Clean consul

### PR DESCRIPTION
**Pull request by mscherer**
##### Issue Type:
- Bugfix Pull Request
##### Plugin Name:

consul_session
##### Summary:

So while I was looking at #1693, I ran pyflakes on the module and found a few warnings that I consider worth fixing, for the sake of code clarity (ie, mostly removal of unused variable and this kind of things)

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @mscherer. @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@sgargan This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by sgargan** [comment]
looks good :shipit:

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @sgargan for reviewing. Marking for inclusion.

**Pull request merged**
