### PR TITLE
kubernetes_templating

### PR DESCRIPTION
**Pull request by astropuffin**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

kubernetes
##### ANSIBLE VERSION

Tested a slightly tweaked implementation using the below version, but updated to be compatible with devel.

```
ansible 2.0.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Features:
- template files (with variables)
- relative paths (so it can reference ansible directories rather than abs paths)
- token authentication
- removes code that explicitly doesn't work (code clean up)

Almost all of the templating code was copied from the template action plugin. However, that plugin has substantially more code that handles file writing to a remote host, which this plugin doesn't need at all. As a result, I've probably imported more things than I need to. In the future a more generic "grab from file template" action plugin should be written, as this module/plugin doesn't need any special logic beyond what is already offered.

running the examples:

```
> ansible-p  ansible-playbook kubernetes.yml -vvv
No config file found; using defaults
 [WARNING]: provided hosts list is empty, only localhost is available

1 plays in kubernetes.yml

PLAY [Kube ns test] ************************************************************

TASK [testing : Create a kubernetes namespace from file] ***********************
task path: /Users/j2/work/src/github.com/dronedeploy/kube_deploy/roles/testing/tasks/main.yml:3
ok: [localhost] => {"changed": false, "invocation": {"module_args": {"api_endpoint": "redacted", "state": "present", "template": "ns.yml", "token": "redacted"}, "module_name": "kubernetes"}}

TASK [testing : Create a kubernetes namespace from template] *******************
task path: /Users/j2/work/src/github.com/dronedeploy/kube_deploy/roles/testing/tasks/main.yml:10
ok: [localhost] => (item=ansible-test) => {"changed": false, "invocation": {"module_args": {"api_endpoint": "kube-master.ddops.cool", "state": "present", "template": "ns.yml.j2", "token": "redacted"}, "module_name": "kubernetes"}, "item": "ansible-test"}

TASK [testing : Create a kubernetes namespace from inline] *********************
task path: /Users/j2/work/src/github.com/dronedeploy/kube_deploy/roles/testing/tasks/main.yml:19
ok: [localhost] => {"changed": false, "invocation": {"module_args": {"api_endpoint": "redacted", "inline": {"apiVersion": "v1", "kind": "Namespace", "metadata": {"annotations": {"a1": "value1", "a2": "value2"}, "labels": {"label_env": "test", "label_ver": "latest"}, "name": "ansible-test"}}, "state": "present", "token": "redacted"}, "module_name": "kubernetes"}}

TASK [testing : Create a kubernetes namespace from inline with variable] *******
task path: /Users/j2/work/src/github.com/dronedeploy/kube_deploy/roles/testing/tasks/main.yml:36
ok: [localhost] => (item=ansible-test) => {"changed": false, "invocation": {"module_args": {"api_endpoint": "redacted", "inline": {"apiVersion": "v1", "kind": "Namespace", "metadata": {"annotations": {"a1": "value1", "a2": "value2"}, "labels": {"label_env": "test", "label_ver": "latest"}, "name": "ansible-test"}}, "state": "present", "token": "redacted"}, "module_name": "kubernetes"}, "item": "ansible-test"}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

```

Note: I couldn't figure out where to put the action plugin code. I don't think this is the right spot for it. Please let me know where it goes and I'll update the PR.

### CODE REVIEW

**Comment by astropuffin** [comment]
no idea why the compile is failing. I'm using the same syntax as: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py#L91

It compiles fine locally:

```
> python -m py_compile action_plugins/kubernetes.py
> echo $?
0
```

**Comment by astropuffin** [comment]
ok, so reason it's not compiling is because tests are running python2.4...

**Comment by astropuffin** [comment]
ok so it's still having issues with python 2.4, currently `from __future__ import (absolute_import, division, print_function)`. It's an action plugin, so it should only have to comply with pythn 2.6+
https://docs.ansible.com/ansible/developing_modules_python3.html

can someone direct me as to how I can designate that properly?

**Comment by gregdek** [comment]
Thanks @astropuffin for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by astropuffin** [comment]
ready_for_review I believe this will work once the action plugin piece is moved to the correct location. Currently failing on python2.4 syntax checking, but the part that is failing was copied from an already passing action plugin. https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py#L17

**Comment by astropuffin** [comment]
Passing 2.4 compile check. Now failing the "in the wrong spot" checks.

**Pull request closed without merging**
