### PR TITLE
Sensu subscription bugfixes

### PR DESCRIPTION
**Pull request by andsens**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

sensu_subscription
##### ANSIBLE VERSION

```
2.2
```
##### SUMMARY

Fixes problem introduced in #205 as noted by @SamYaple ([comment](https://github.com/ansible/ansible-modules-extras/pull/205/files/5953864136e3a6da9ba2725baa7cf7c466fd42d0#r65942858))

Also fixes a [small thing about an error message](https://github.com/ansible/ansible-modules-extras/pull/205/files/5953864136e3a6da9ba2725baa7cf7c466fd42d0#r65904753) mentioned by @bcoca

### CODE REVIEW

**Comment by ghost** [comment]
Youll need to add this module to the 2.4 exclude list if it doesnt work with python 2.4:
https://github.com/ansible/ansible-modules-extras/blob/devel/.travis.yml#L121

Otherwise note the second form of syntax [here](http://docs.ansible.com/ansible/developing_modules_python3.html#exceptions)

@sivel provided that link earlier in the IRC channel

**Comment by andsens** [comment]
Argh, 2.4 is a PITA! :-)

Better now?

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by bcoca** [comment]
FYI, your exceptions were 2.4 compatible, but not 3.x compatible ( E as e vs E, e)

**Pull request merged**
