### PR TITLE
Portage module improvements

### PR DESCRIPTION
**Pull request by wltjr**
##### ISSUE TYPE
 - Module Pull Request

##### COMPONENT NAME
portage

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY
Added support for additional parameters. More to come.

Added portage parameter --keep-going
Added portage parameter --load-avg [FLOAT]
Added portage parameter --jobs[=INT]
Added myself to Authors

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @wltjr. To the current maintainers, @sayap please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wltjr** [comment]
Sure thing, and if @sayap is no longer interested in being or remaining the maintainer. I would be willing to take over said module and be the maintainer. Either way will continue to submit improvements just doing some things I need now. Eventually will add all portage options that make sense.

**Comment by sayap** [comment]
@wltjr I haven't got the opportunity to use the portage module much in the last couple of years. You may take over as the maintainer :)

**Comment by wltjr** [comment]
Thanks for allowing me to take over @sayap. I am using this module to maintain a few servers. I have been around Gentoo for over a decade, former Gentoo dev, etc. @gregdek please advise if there is anything further I need do, or if you want to pull in others for module review, etc. Thanks!

**Comment by gregdek** [comment]
Done and done. @wltjr you have the ball. :) Be sure to read over the requirements for module maintainers: https://github.com/ansible/ansible-modules-extras/blob/devel/GUIDELINES.md

**Comment by wltjr** [comment]
Ok I will read over the maintainers information. Thanks for the link!

**Comment by gregdek** [comment]
Thanks again to @wltjr. This module is going into community review.

We notice that you are one of the maintainers (@wltjr) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wltjr** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @wltjr. Since you are one of the maintainers (@wltjr) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
