### PR TITLE
Updated datacenter, cpu and memory options

### PR DESCRIPTION
**Pull request by mcltn**
##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request
- Bugfix Pull Request
- Docs Pull Request
##### ANSIBLE VERSION

```

```
##### SUMMARY

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @mcltn. This module is going into community review.

We notice that you are one of the maintainers (@mcltn) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mcltn** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @mcltn. Since you are one of the maintainers (@mcltn) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
Thanks. closes #3264

**Pull request merged**
