### PR TITLE
Amazon Redshift Module - Split Changes Out

### PR DESCRIPTION
**Pull request by trinitronx**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME
- `cloud/amazon/redshift.py`
##### SUMMARY

I realized we have some modules our team has developed but never got contributed back.  So this PR sets out to rectify that.  If it's not that useful, then no big deal, we'll just continue to use our local version, but we won't have to say we didn't try to push it back upstream.
- `cloud/amazon/redshift.py` - Rebased & used `git filter-branch --tree-filter` to split out our current working module code for RedShift from the original PR #2560

This includes an alternate version of an Amazon RedShift module that has been well tested.  It tries to be very simply idempotent by not attempting to modify an existing cluster with the same `cluster_identifier` if found.  It supports `check_mode`

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @trinitronx for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
Can i suggest a quick read of https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/GUIDELINES.md?

Particularly the use of helper functions such as camel_dict_to_snake_dict (it will remove the need to worry about the datetimes) and also error handling. needs_review

**Comment by gregdek** [comment]
Thanks @trinitronx for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@trinitronx A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@trinitronx Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@trinitronx A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@trinitronx Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
