### PR TITLE
Adding ldap_attr module

### PR DESCRIPTION
**Pull request by jtyr**
##### ISSUE TYPE

New Module Pull Request
##### COMPONENT NAME

`ldap_attr`
##### ANSIBLE VERSION

For Ansible 2.3
##### SUMMARY

This PR is adding a new module that allows to add/change/remove LDAP attributes. The module is based on the code from Peter Sagerson who gave me the [permission](https://bitbucket.org/psagers/ansible-ldap/pull-requests/2/adding-params-option-and-other-minor/diff#comment-16809629) to publish it.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @jtyr for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by spoage** [comment]
shipit

**Comment by jangrewe** [comment]
shipit

Works great for me (compared to the original one, which doesn't)

**Comment by drybjed** [comment]
@jtyr I'm checking the new modules on Ansible stable-2.2, unfrotunately it seems that the `ldap_attr` module doesn't want to work correctly with this playbook:

``` yaml
---

- name: Test ldap_attr
  hosts: all
  become: True

  vars:
    ldap_security_tls:
      - 'simple_bind=128'
      - 'update_ssf=128'
      - 'ssf=128'
      - 'tls=128'

  tasks:

    - name: Configure LDAP connection securit
      ldap_attr:
        dn: 'olcDatabase={1}mdb,cn=config'
        name: 'olcSecurity'
        values: '{{ ldap_security_tls }}'
        state: 'present'
```

The error message from Ansible is:

```
fatal: [ldap]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to ldap.deb8.gumed.edu.pl closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7GbTy1/ansible_module_ldap_attr.py\", line 352, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7GbTy1/ansible_module_ldap_attr.py\", line 329, in main\r\n    modlist = ldap.add()\r\n  File \"/tmp/ansible_7GbTy1/ansible_module_ldap_attr.py\", line 219, in add\r\n    values_to_add = filter(not self._is_value_present, self.values)\r\nTypeError: 'bool' object is not callable\r\n", "msg": "MODULE FAILURE"}
```

I'm not sure if this is due to a misconfigured `slapd` or a module issue. The test was done on Debian Jessie with the `slapd` installed from the Stable repository.

Can you check if that works on your end, or tell me how to better debug this?

**Comment by jtyr** [comment]
Thanks for testing the module, @drybjed. It definitely was a problem in the module. I think I have fixed it so please give it a try now.

**Comment by drybjed** [comment]
@jtyr Works now, thanks. I have only tested the `ldap_attr` module properly so far, but it looks like it works as expected.

shipit

**Comment by jtyr** [comment]
Thanks, @drybjed. I would appreciate if you could also test the `ldap_entry` module from teh PR #2952. Those two modules goes hand in had and should be merged together.

**Comment by drybjed** [comment]
@jtyr I have tested both modules some more, they seem to work as expected, good job! I'm going to include them in DebOps if you don't mind, the current versions used by the playbook don't work very well with latest Ansible releases.

Thanks again for taking care of these modules, and I'm looking forward for them being in Ansible proper. :-)

shipit

**Pull request closed without merging**
