### PR TITLE
Hpilo modules rev.2 

### PR DESCRIPTION
**Pull request by haad**
##### ISSUE TYPE

New Module Pull Request
##### COMPONENT NAME

module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

These modules allow user to manage hpilo based servers. It's possible to reboot, set boot device or boot_once device to reinstall destination server.

This module is based on original module from [repo](https://github.com/ansible-c/ansible-provisioning). I have change documenation and updated modules little bit.

### CODE REVIEW

**Comment by haad** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @haad for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by haad** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @haad for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
