### PR TITLE
zabbix_host: 2.4 only accepts array of host IDs for delete

### PR DESCRIPTION
**Pull request by jjahns**
During tests and API reference, the host.delete option does not accept a dict.  It only accepts an array of host IDs.  A change made to the module shows that placing the host_id value in an array as a parameter to the host.delete function works properly.

### CODE REVIEW

**Comment by jjahns** [comment]
Looks like there was a problem that was fixed in devel.

**Comment by gregdek** [comment]
@jjahns you closed then reopened -- is this an active PR or no?

**Comment by jjahns** [comment]
?It's active.

I apologize - the Travis CI was broken.

**Comment by jjahns** [comment]
Just wondering if there is anything else required to merge this item?

**Comment by gregdek** [comment]
@cove Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by jjahns** [comment]
shipit

This does not change the function of the module.  But it does address issue with zabbix-api

**Comment by gregdek** [comment]
Sorry @jjahns -- but "shipit" is only something the current module maintainer gets to say. :)  We'll wait on an opinion from @cove, and if we don't get it in a reasonable timeframe, we'll move on to the maintainer question.  I know it's a simple looking change, but trying to nail down the process.

**Comment by resmo** [comment]
PR is messed up with new modules added not related to `zabbix_host`.

@jjahns please make a different PR for the new modules, 

Hint. Make a separate branch for your work, do not commit into devel. In your current situation, I would do:

```
# make a branch for vmware stuff
git checkout devel
git checkout -b feature/vmware_stuff

# make a branch for zabbix stuff remove all later commits related to vmware
git checkout -b feature/zabbix_host
git reset --hard 7dfc952de5711f1d034ee298894988bcf8fcd0cf


# reset devel branch to an upstream commit
git checkout devel
git reset --hard b211bacb40bac9424398858ff70a1e218c612a3b

# rebase the vmware branch only containing vmware stuff
git checkout feature/vmware_stuff
git rebase -i 654df036551f1cd3ad13063d934d92248c429539
# delete all commits (lines) not related to VMware modules
```

**Comment by robynbergeron** [comment]
Hi @jjahns -- it looks like @resmo and @chrrrles are both recommending that you start a new PR for this , with some help above on how to get started. 

When you do that, let us know the PR # here and I'll close this out. Thanks!

**Comment by chrrrles** [comment]
Hello @jjahns, 

May you split this PR into three?   If it is holding you back from doing so, please disregard my earlier comments about refactoring to re-use functions from module_utils, and introducing a dependency on vconnector dependency.  Those can be addressed once these modules are in extras.

Thanks,
Charles

**Comment by jjahns** [comment]
I'm going to close the request, because of some internal issues here that have prevented me from working on this.

**Pull request closed without merging**
