### PR TITLE
Added OpenStack Quantum port module.

### PR DESCRIPTION
**Pull request by rosmo**

### CODE REVIEW

**Comment by jimi-c** [comment]
cc @emonty, as this may conflict with some of the work he's doing around the OpenStack modules.

**Comment by johnpbatty** [comment]
I also just submitted an OpenStack quantum_port module (#107), before I came across this one!
Looking at this implementation it does support more features/parameters than mine, so I recommend you take this in preference to mine.

**Comment by gregdek** [comment]
Adding "owner_pr" since @rosmo is an Extras module owner

**Comment by gregdek** [comment]
OK, so, according to new policy, since @rosmo is already a module owner, we need one more reviewer for this one to bring it in. Boilerplate follows:

---

Thanks for submitting your module to Ansible Extras. Our policy is that each new module needs to be reviewed and approved by at least two official module reviewers, the list of whom can be found here: https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Because you’re already an approved reviewer, we assume that you’ve reviewed your own module; you just need to find one other person to review, and you’re all set.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by emonty** [comment]
I'd really prefer to not merge this, as it's in the format of the modules we're deprecating. We have a set of neutron modules going in to ansible-modules-core right now, and I believe @dguerri has a port module coming. Also - please see https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/README.md for more background about what's going on in more detail

**Comment by gregdek** [comment]
Good enough for me. I'll close it. Thanks for the PR, @rosmo, and apologies.

**Pull request closed without merging**
