### PR TITLE
Use push_type and send link with push_link.

### PR DESCRIPTION
**Pull request by kovacsbalu**

### CODE REVIEW

**Comment by gregdek** [comment]
@willybarro Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by willybarro** [comment]
Thanks @kovacsbalu everything looks fine! :shipit:

**Comment by robynbergeron** [comment]
@willybarro thanks for the review! And thanks @kovacsbalu for the PR.

Marking for inclusion -- cc @ansible/core team.

**Comment by kovacsbalu** [comment]
Great! Thanks for all of you.

**Pull request merged**
