### PR TITLE
Composer - Removed No Progress

### LINKED ISSUE #323: composer: command=dump-autoload fails because it doesn't recognize the --no-progress option
## repro

If the following two tasks are executed after each other

```
 - composer: command=update working_dir={{ your_php_app_dir }} 
# assuming {{ your_php_app_dir }} has a valid composer.json
 - composer: command=dump-autoloads working_dir={{ your_php_app_dir }}
```

The second one fails with the following error:

```
failed: [localhost] => {"failed": true}
msg: [RuntimeException] The "--no-progress" option does not exist. dump-autoload [-o|--optimize] [--no-dev]
```
## guess at the root cause

always appended default options. As per http://docs.ansible.com/composer_module.html

> Default options that are always appended in each execution are –no-ansi, –no-progress, and –no-interaction
## Versions, environment
- Composer version 1.0-dev (829199c0530ea131262c804924f921447c71d4e8) 2015-03-16 13:11:02
- ansible 1.8.4
- ubuntu/trusty64

### PR DESCRIPTION
**Pull request by TomKita**
Removed no progress as default resolves #323

### CODE REVIEW

**Comment by bcoca** [comment]
i'm ok with removing it from defaults, but won't this create an issue with commands that DO support it? it will probably tie up stdout and mess with the feedback

**Comment by TomKita** [comment]
That is a good point could be changed to default only for install/update?

**Comment by bcoca** [comment]
that would be great

**Comment by resmo** [comment]
don't forget to correct the `notes:` in the doc.

**Comment by resmo** [comment]
@TomKita May I help you with the revision?

**Comment by TomKita** [comment]
@resmo Of course go for it I'm a bit tied up with other projects at the moment. Unfortunately this is on the lower end of my list.

**Comment by resmo** [comment]
@TomKita ok, I'll take it over.

**Comment by gregdek** [comment]
@resmo want to just open a new pr? If so, feel free to close this one and create a new one.

**Comment by robynbergeron** [comment]
Closing this one, since it looks like @resmo is now handling this in ansible/ansible-modules-extras/#965. Thanks @resmo, and thanks to @TomKita for the initial work :)

**Comment by robynbergeron** [comment]
And someday I'll learn the ropes of proper github referencing. Yay me!

**Pull request closed without merging**
