### PR TITLE
Implement template storage selection

### PR DESCRIPTION
**Pull request by alxsey**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

cloud/misc/proxmox.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 81d7e132f9) last updated 2016/08/16 19:17:45 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 45c1ae0ac1) last updated 2016/08/16 16:39:10 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD a6b34973a8) last updated 2016/08/16 16:39:10 (GMT -400)
```
##### SUMMARY

Added selection of the template store, deriving it from "ostemplate" parameter.

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alxsey. To the current maintainers, @UnderGreen please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by UnderGreen** [comment]
:shipit:

**Comment by UnderGreen** [comment]
Thank you, @alxsey.

**Comment by gregdek** [comment]
Thanks again to @alxsey for this PR, and thanks @UnderGreen for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by roongr2k7** [comment]
@alxsey @UnderGreen 
I use Proxmox 4.2 and also have this problem too.

This problem have at least 3 solution.
- add new parameter `template_storage`
- derive `template_storage` from `ostemplate` (as @alxsey did)
- specific disk storage in `disk` and use `storage` as `template_storage` and update document

```
disk: "local-lvm:10"
```
- remove parameter `storage` and derive disk storage from `disk`, template storage from `ostemplate`

**Pull request merged**
