### PR TITLE
Fix 2725

### PR DESCRIPTION
**Pull request by h0nIg**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

mongodb_user
##### ANSIBLE VERSION

2.1.2.0-0.3.rc3
2.1.1
##### SUMMARY

fix for https://github.com/ansible/ansible-modules-extras/issues/2725
created by maintainer @Lujeni, but since he is unavailable the fix should be merged asap into 2.1.2 + devel

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @h0nIg. To the current maintainers, @lujeni please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by h0nIg** [comment]
@gregdek the maintainer @lujeni created this on his repository, but he is unavailable right now. could you please include this fix?

**Comment by resmo** [comment]
based on code review LGTM

**Comment by gregdek** [comment]
Thanks again to @h0nIg for this PR, and thanks @lujeni for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
@h0nIg @resmo thanks for the review and the PR.

Sorry to be late.

**Comment by h0nIg** [comment]
@gregdek @resmo will there be a backport of the fix into 2.1? see #2923

**Comment by gregdek** [comment]
@h0nig Not generally our policy to backport fixes in Extras -- and besides, 2.2 is about to go into freeze, so this fix should be available soon enough.

**Pull request merged**
