### PR TITLE
New EC2 VPC facts module

### PR DESCRIPTION
**Pull request by szibis**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ec2_vpc_facts
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 4d42f1992b) last updated 2016/03/24 15:31:37 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 7efc09ef08) last updated 2016/03/24 16:00:43 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7f9cdc0350) last updated 2016/03/24 16:00:57 (GMT +200)
  config file = /path/to/my/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

For full automate creation process after new VPC or later (we don't need to store any static vars about VPC) we can get vpc-id used in instance create process or any other ec2 module that need vpc-id. We can check state of VPC or get CIDR block and then other facts modules to get more data. 
After new VPC create with proper tags it is able to take vpc-id later for example by tag name.
This module returns all available options from boto for VPC - http://boto.cloudhackers.com/en/latest/ref/vpc.html#boto.vpc.vpc.VPC
###### Example Output:

```
{"changed": false, "results": [{"cidr_block": "10.10.0.0/16", "classic_link_enabled": null, "dhcp_options_id": "dopt-c0000000", "id": "vpc-a0000001", "instance_tenancy": "default", "is_default": false, "state": "available"}, {"cidr_block": "10.50.0.0/16", "classic_link_enabled": null, "dhcp_options_id": "dopt-c2000000", "id": "vpc-10000009", "instance_tenancy": "default", "is_default": false, "state": "available"}]}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @szibis for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by gregdek** [comment]
Thanks @szibis for this PR. A maintainer of this module has asked for revisions to this PR. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by szibis** [comment]
ready_for_review

**Comment by resmo** [comment]
Thanks @szibis for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by szibis** [comment]
Look like almost same module exist with name ec2_vpc_net_facts. I miss that sorry.

**Pull request closed without merging**
