### PR TITLE
tempfile module

### PR DESCRIPTION
**Pull request by krzysztof-magosa**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

tempfile
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1975a545bd) last updated 2016/09/20 18:03:31 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 70d4ff8e38) last updated 2016/09/20 18:03:38 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD db7a3f48e1) last updated 2016/09/20 18:03:43 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

`mktemp` implementation differs between systems. It makes creating temporary files unnecessarily complicated in inter-OS playbooks. This module resolves that problem using python tempfile which is portable between systems.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @krzysztof-magosa for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by krzysztof-magosa** [comment]
To be honest I have no idea why these tests failed.
I did not change any existing files, and my code isn't covered by tests.

ready_for_review

**Comment by mattclay** [comment]
@krzysztof-magosa Tests failed because you're using exception handling syntax which doesn't work on python 2.4. Here's the relevant portion of the test output:

```
2016-09-21 08:16:39 + python2.4 -m compileall -fq -x '(/cloud/|/clustering/consul.*.py|/clustering/znode.py|/database/influxdb/|/database/mssql/|/monitoring/zabbix.*.py|/network/f5/|/notification/pushbullet.py|/packaging/language/maven_artifact.py|/packaging/os/dnf.py|/packaging/os/layman.py|/remote_management/ipmi/|/univention/|/web_infrastructure/letsencrypt.py)' .
2016-09-21 08:16:40 Compiling ./files/tempfile.py ...
2016-09-21 08:16:40   File "./files/tempfile.py", line 89
2016-09-21 08:16:40     except Exception as e:
2016-09-21 08:16:40                       ^
2016-09-21 08:16:40 SyntaxError: invalid syntax
```

You need to use `get_exception()` to get exception details. Here's an example:

https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L289

**Comment by krzysztof-magosa** [comment]
Thank you for explanation @mattclay. I will rework that.

**Comment by mattclay** [comment]
@krzysztof-magosa Your fix for the exception handling passes tests. The failure now is documentation related. From the test output:

```
2016-10-11 23:23:28 + ansible-validate-modules --exclude '/utilities/|/shippable(/|$)' .
2016-10-11 23:23:37 ============================================================================
2016-10-11 23:23:37 ./files/tempfile.py
2016-10-11 23:23:37 ============================================================================
2016-10-11 23:23:37 ERROR: version_added should be 2.3. Currently 0.0
2016-10-11 23:23:37 ERROR: No EXAMPLES provided
```

Here's an example of version added for a module:

https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L25

Be sure to set it to `2.3` since that's the next release version.

The other documentation error is about lack of examples. See here for an example of that:

https://github.com/ansible/ansible-modules-core/blob/devel/system/user.py#L201

For other general advice on developing modules, consult the documentation here:

http://docs.ansible.com/ansible/developing_modules.html

**Comment by krzysztof-magosa** [comment]
Should be fixed now.

**Comment by gregdek** [comment]
Thanks @krzysztof-magosa for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by willthames** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @krzysztof-magosa for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible/core could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
I  have some concerns about the naming of `mode`. 

Mode for file modules is used for `chmod`. I would suggest to change `mode` to `state` in this module to streamline it with other file modules.

@willthames any thoughts?

**Comment by krzysztof-magosa** [comment]
Hi @resmo,
You are right.
With `state` it would be consistent with e.g. `file` module and it would allow us to add `mode` in the future here.

Waiting for your decision guys.
Regards.

**Comment by willthames** [comment]
@resmo, good point, I hadn't thought of that parameter in line with other modules.

**Comment by willthames** [comment]
@krzysztof-magosa if you can make that change that would be appreciated.

**Comment by krzysztof-magosa** [comment]
@resmo, @willthames 
Change done and rechecked on local machine - works good.

**Comment by resmo** [comment]
LGTM. Thanks!

**Pull request merged**
