### PR TITLE
Fix for #2166

### LINKED ISSUE #2166: Cloud Module - cloudtrail - Error on existing trail without S3 prefix
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

AWS - Cloudtrail
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Describing (view) existing trails throws a module failure due to a missing key in the returned dictionary.
##### STEPS TO REPRODUCE
- Create a cloudtrail using existing module without a S3 prefix
- Re-run using existing cloudtrail configuration -- again, without s3 prefix
##### EXPECTED RESULTS

Nothing (unless there are changes)
##### ACTUAL RESULTS

Module error occurs due to KeyError as S3KeyPrefix is NOT part of the results when a describe-trail is performed.

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/<username>/.ansible/tmp/ansible-tmp-1462399000.22-104944138960760/cloudtrail", line 2435, in <module>
    main()
  File "/home/<username>/.ansible/tmp/ansible-tmp-1462399000.22-104944138960760/cloudtrail", line 194, in main
    results['view']['S3KeyPrefix']                != s3_key_prefix  or \
KeyError: 'S3KeyPrefix'
```

You can see the key does not exist if you perform `aws cloudtrail describe-trails`:

```
        {
            "IncludeGlobalServiceEvents": true, 
            "Name": "<trail-name>", 
            "TrailARN": "arn:aws:cloudtrail:ap-southeast-2:account_id:trail/<trail-name>", 
            "LogFileValidationEnabled": true, 
            "IsMultiRegionTrail": true, 
            "S3BucketName": "<s3-bucket-name>", 
            "HomeRegion": "ap-southeast-2"
        }
```

even though the code is expecting it as seen here on line 193 of `ansible-modules-extras/cloud/amazon/cloudtrail.py`:

```
              results['view']['S3KeyPrefix']                != s3_key_prefix  or \
```

### PR DESCRIPTION
**Pull request by mazay**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

CloudTrail module - cloudtrail.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

```
Fixes #2166

s3_key_prefix default value is set to None
If key prefix is set to empty string - change it to None
Use dict.get() with default=None to fetch key prefix from the response
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mazay for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mazay** [comment]
@gregdek According to travis logs there is some issue with "redshift.py" and "redshift_subnet_group.py", however I've made changes in different module.

**Comment by resmo** [comment]
hi @mazay could you please rebase this PR on top of devel?

```
git checkout devel
git pull https://github.com/ansible/ansible-modules-extras.git devel
git checkout mazay:patch-1
git rebase devel
git push -f origin mazay:patch-1
```

**Comment by mazay** [comment]
hi @resmo it's done.

**Comment by mazay** [comment]
done

**Comment by resmo** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @mazay for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @ansible could look over it.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
