### PR TITLE
Bugfix: maven_artifact urlparse was failing 

### PR DESCRIPTION
**Pull request by raben2**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

packaging/language/maven_artifact.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dev/scripts/ansible-modules/*']
```
##### SUMMARY

The Module was using urlparse.urlparse() which was failing on Python 2.7 
i properly imported urlparse and added some error handling

```
FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_f9s7gG/ansible_module_maven_artifact.py\", line 388, in <module>\r\n    main()\r\n  File \"/tmp/ansible_f9s7gG/ansible_module_maven_artifact.py\", line 337, in main\r\n    parsed_url = urlparse.urlparse(module.params[\"repository_url\"])\r\nAttributeError: 'function' object has no attribute 'urlparse'\r\n", "msg": "MODULE FAILURE", "parsed": false}"
```

### CODE REVIEW

**Comment by raben2** [comment]
@resmo @jimi-c could you have a look on this, please?

**Comment by gregdek** [comment]
Thanks @raben2. To the current maintainers, @chrisisbeef please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by chrisisbeef** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @raben2 for this PR, and thanks @chrisisbeef for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
