### PR TITLE
Add support for reiserfs

### PR DESCRIPTION
**Pull request by rkiyanchuk**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

`system/filesystem.py`
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Create commands mapping for Reiserfs tools so `filesystem.py` module can be used to create `reiserfs` filesystem on partitions.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @zoresvit. To the current maintainers, @abulimov please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
@zoresvit could you add some docs that says reiserfs was added in 2.2?

**Comment by rkiyanchuk** [comment]
@resmo Sure, will do. Where this info is expected to be added: the `DOCUMENTATION` string in the module file, or elsewhere in [ansible](https://github.com/ansible/ansible) repo?

**Comment by resmo** [comment]
@zoresvit probably a new line below https://github.com/zoresvit/ansible-modules-extras/blob/63505cc233739dcb147d137eb9f2a5bddd795443/system/filesystem.py#L32 

```
- reiserfs support was added in 2.2.
```

**Comment by resmo** [comment]
LGTM

**Comment by gregdek** [comment]
Thanks again to @zoresvit for this PR, and thanks @abulimov for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
shipping it.

**Pull request merged**
