### PR TITLE
add for vmware_guest the windows sysprep

### PR DESCRIPTION
**Pull request by stravassac**
##### ISSUE TYPE

 - Feature Pull Request
 
##### COMPONENT NAME

/cloud/vmware/vmware_guest.py
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### SUMMARY

Add the possibility to sysprep and join AD domain Windows template vmware with this options:
windows_sysprep:
fullName: "windows specific full name"
orgName: "steph"
computerName: "test_vm"
#productId: "12134" # not necessary
timeZone: 0
password: "win_pwd" #change local computer password
autoLogon: False
autoLogonCount: 0
joinDomain : "mydomain.net"
domainAdmin: "adroot"
domainAdminPassword: "win_password"
passwordPlainText: True

customize flag must be set to True

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @stravassac for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by troxil** [comment]
@stravassac - any chance to also include [guiRunOnce](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.customization.GuiRunOnce.html) to be able to run custom one off command list? 

The goal I have is, to move join to domain as well as shift to the correct OU within AD. I have added custom edits to my own (2.2.x vsphere_guest) that cover "netdom /join" command that do the join and supply the "/ou:<<OU>>" field. This isn't the most ideal.

Any suggestions welcome. I can see your implementing the SDK vmware provide, but it doesn't have this. 

Failing the inclusion of that - are you aware of a way to run the "Move-ADObject" PowerShell cmdlet on the domain controller it joined..

**Comment by stravassac** [comment]
@trolix
Actualy, I can't work on guiRunOnce, but why not after. You can replace that by configuring your Windows template with WinRM and use Ansible to run PowerShell on it.
For moving computer account in an other OU, we dont use it and I have no idea of the best method, perhaps running "Move-ADObject" later in Ansible Playbook.

**Comment by stravassac** [comment]
@trolix:
https://github.com/ansible/ansible/pull/19866

**Pull request closed without merging**
