### PR TITLE
satellite control module

### PR DESCRIPTION
**Pull request by t-v**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

satellite
##### SUMMARY

This is a module created to control a Red Hat Satellite or katello itself through its API.
It will allow you to get info out of it or publish content views, do promotions of environments and actually clean up older versions in contentviews.

### CODE REVIEW

**Comment by t-v** [comment]
No clue how to fix the TravisCI error:
ERROR: requests import found, should use ansible.module_utils.urls instead

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by t-v** [comment]
Finally I was able to rewrite the requests to use ansible.module_utils.urls

**Comment by gregdek** [comment]
@TimothyVandenbrande A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by t-v** [comment]
@gregdek sorry, I forgot to add the tag, so hereby:
ready_for_review

**Comment by gregdek** [comment]
Thanks @TimothyVandenbrande for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
