### PR TITLE
Optimize haproxy enable and disable actions

### PR DESCRIPTION
**Pull request by gyurco**
##### Issue Type:

Please pick one and delete the rest:
- Bugfix Pull Request
##### Plugin Name:

haproxy
##### Ansible Version:

```
2.0.1.0
```
##### Summary:

Enabling a haproxy host with the wait option can be very slow, because it 
first enables a service, then check if it is up, then enables a service again, checks it, and so on.

So optimize this loop with first enabling/disabling all services, then check them. This makes a transition from O(n) to O(1), where n is the number of proxies on a host.
##### Example output:

The same as before, just faster.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @gyurco. @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by ravibhure** [comment]
Thank you @gyurco, sounds good to me.

**shipit**

**Comment by gregdek** [comment]
Thanks again to @gyurco for this PR, and thanks @ravibhure for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by alikins** [comment]
Flipped back to community review for https://github.com/ansible/ansible-modules-extras/pull/1834/commits/750eea88cb893ebf6a5ef0f4ec5a76688a701b7a

ping @ravibhure

**Comment by gregdek** [comment]
Thanks @gyurco for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gyurco A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gyurco Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@gyurco A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
