### PR TITLE
added module random_string

### PR DESCRIPTION
**Pull request by ivica-k**
##### Issue Type:

Please pick one and delete the rest:
- New Module Pull Request
##### Plugin Name:

random_string
##### Ansible Version:

```
2.0.1.0
```
##### Summary:

Generates random strings to be used by `register` to create salts, passwords, tokens etc.
##### Example output:

```
{
    "changed": false, 
    "invocation": {
        "module_args": {
            "digits": true, 
            "length": 12, 
            "lower": "yes", 
            "lowercase": true, 
            "special": false, 
            "uppercase": true
        }
    }, 
    "rand_string": "GzyvA1cCl6lG"
}
```

### CODE REVIEW

**Comment by sivel** [comment]
I think I'd rather see this as a lookup plugin as opposed to a module.

**Comment by bcoca** [comment]
agreed, this makes more sense as a lookup.

**Comment by gregdek** [comment]
Thanks @ivica-k for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by ivica-kolenkas-devtech** [comment]
Thank you both for your comments. I'll try to figure out how to turn this into a lookup (or extend the existing `password` lookup), any links appreciated.

**Comment by ivica-k** [comment]
Thank you for your comments. I'll try to figure out how to turn this into a lookup (or extend the existing `password` lookup). Any links appreciated.

**Comment by sivel** [comment]
@ivica-k we have some minimal documentation around writing a lookup plugin, however you can find it at http://docs.ansible.com/ansible/developing_plugins.html#lookup-plugins

Feel free to stop by the ansible-devel mailing list if you have more questions.

**Pull request closed without merging**
