### PR TITLE
Ipa bugfixes

### PR DESCRIPTION
**Pull request by Nosmoht**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

FreeIPA modules

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 947e0f264e) last updated 2016/11/10 16:00:26 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 2584fca0ae) last updated 2016/11/10 16:01:10 (GMT +200)
  lib/ansible/modules/extras: (ipa_bugfixes 69f14436a7) last updated 2016/11/10 19:17:51 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

- Fix several bugs that when run in check mode and the object did not exist resulted in:
```
'list' object has no attribute 'get'
```
- Fix one bug in ipa_sudorule that resulted in:
```
invalid 'cn': Only one value is allowed
```
- Fix: ipa_hostgroup returns changed if host assigned hosts or hostgroups are not in lowercase

No official issue so far. Just feedback from a user that reported the issue after the modules where merged within https://github.com/ansible/ansible-modules-extras/pull/3247

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @Nosmoht. This module is going into community review.

We notice that you are one of the maintainers (@Nosmoht) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Nosmoht** [comment]
shipit

**Comment by Nosmoht** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @Nosmoht. Since you are one of the maintainers (@Nosmoht) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
