### PR TITLE
zypper: Add returncode to result

### PR DESCRIPTION
**Pull request by agx**
This will be used in integration tssts and makes the whole thing
more similar to the yum module.

### CODE REVIEW

**Comment by gregdek** [comment]
@dirtyharrycallahan Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by alxgu** [comment]
:+1: 
shipit

**Comment by agx** [comment]
Can this be merged?

**Comment by dirtyharrycallahan** [comment]
lgtm

**Pull request merged**
