### PR TITLE
add datadog_downtime module

### PR DESCRIPTION
**Pull request by stefanweller**
Added datadog_downtime module for immediate downtiming of monitors.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this module to Ansible Extras. Apologies that it’s taken a while to get your module reviewed.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by robynbergeron** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately. 

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
A friendly ping to @irabinovitch -- since you were excited about another datadog module addition, and perhaps you know folks who might be interested in reviewing this. All the info about reviewing is in the previous comment, or can also be read about here: https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

**Comment by gregdek** [comment]
Thanks @stefanweller for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by irabinovitch** [comment]
The test failure looks unrelated to the changes here. Whats the best way to re-trigger?

**Comment by stefanweller** [comment]
Just an info: I'll review, extend and then push again. Sorry for the delay.

**Comment by gregdek** [comment]
@stefanweller A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanweller** [comment]
ready_for_review
works_for_me
passes_guidelines

**Comment by gregdek** [comment]
Thanks @stefanweller for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by stefanweller** [comment]
@gregdek Hi Greg, can you help with the failing merge? Seems to be a Travis problem. THX!

**Comment by gregdek** [comment]
Hi @stefanweller.  Looks like the travis failure is because the branch is outdated (the zabbix failure is the clue) -- not surprising since the PR is 9 months old.  If you can rebase this PR, the travis failure should go away.

**Comment by stefanweller** [comment]
@gregdek Hi Greg, sorry but I'm still having problems in Travis.
https://travis-ci.org/ansible/ansible-modules-extras/builds/123945651
I merged devel into my fork and pushed. 
Do I have to rebase or should it work anyway?

**Comment by gregdek** [comment]
Looks like it's failing because your PR includes merge commits. To remove them:

http://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history

**Comment by gregdek** [comment]
Or you can use "git rebase -i" for an interactive rebase.

**Comment by stefanweller** [comment]
@gregdek Hi Greg, had to reset my fork. #2062 is the new pull request.

**Comment by gregdek** [comment]
Thanks @stefanweller. Will go check it out.

**Pull request closed without merging**
