### PR TITLE
Add nxos_save_config module

### PR DESCRIPTION
**Pull request by GGabriele**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

nxos_save_config
##### ANSIBLE VERSION

```
Ansible 2.1.0
```
##### SUMMARY

A module to save configuration for Nexus switches

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @GGabriele for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @GGabriele for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by GGabriele** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @GGabriele for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
