### PR TITLE
Improve mongodb_user error message

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

mongodb_user
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY
- Better error message using global exception.
## before

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_dmDDLM/ansible_module_mongodb_user.py\", line 352, in <module>\r\n    main()\r\n  File \"/tmp/ansible_dmDDLM/ansible_module_mongodb_user.py\", line 310, in main\r\n    client.admin.authenticate(login_user, login_password, source=login_database)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/database.py\", line 902, in authenticate\r\n    self.connection._cache_credentials(self.name, credentials)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 459, in _cache_credentials\r\n    auth.authenticate(credentials, sock_info, self.__simple_command)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/auth.py\", line 243, in authenticate\r\n    auth_func(credentials[1:], sock_info, cmd_func)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/auth.py\", line 222, in _authenticate_mongo_cr\r\n    cmd_func(sock_info, source, query)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py\", line 693, in __simple_command\r\n    helpers._check_command_response(response, None, msg)\r\n  File \"/usr/lib64/python2.7/site-packages/pymongo/helpers.py\", line 178, in _check_command_response\r\n    raise OperationFailure(msg % errmsg, code, response)\r\npymongo.errors.OperationFailure: command SON([('authenticate', 1), ('user', u'siteUserAdmin'), ('nonce', u'773e6e3a2eab4bea'), ('key', u'5938b412bd6b6691702496081b9a4ba0')]) failed: auth failed\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
## after

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database: command SON([('authenticate', 1), ('user', u'siteUserAdmin'), ('nonce', u'dd85fdbac4af07fb'), ('key', u'e2859863616e3434aed319090cbefbb0')]) failed: auth failed"}
```

### CODE REVIEW

**Comment by alikins** [comment]
(formatted error)

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):
  File "/tmp/ansible_dmDDLM/ansible_module_mongodb_user.py", line 352, in <module>
    main()
  File "/tmp/ansible_dmDDLM/ansible_module_mongodb_user.py", line 310, in main
    client.admin.authenticate(login_user, login_password, source=login_database)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 902, in authenticate
    self.connection._cache_credentials(self.name, credentials)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 459, in _cache_credentials
    auth.authenticate(credentials, sock_info, self.__simple_command)
  File "/usr/lib64/python2.7/site-packages/pymongo/auth.py", line 243, in authenticate
    auth_func(credentials[1:], sock_info, cmd_func)
  File "/usr/lib64/python2.7/site-packages/pymongo/auth.py", line 222, in _authenticate_mongo_cr
    cmd_func(sock_info, source, query)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 693, in __simple_command
    helpers._check_command_response(response, None, msg)
  File "/usr/lib64/python2.7/site-packages/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('authenticate', 1), ('user', u'siteUserAdmin'), ('nonce', u'773e6e3a2eab4bea'), ('key', u'5938b412bd6b6691702496081b9a4ba0')]) failed: auth failed
", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by alikins** [comment]
Is the version of pymongo installed on the remote node pymongo2.2 or older?

I would expect those exceptions to be handled with newer pymongo.

**Comment by gregdek** [comment]
Thanks again to @Lujeni. This module is going into community review.

We notice that you are one of the maintainers (@lujeni) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
@alikins 

> Is the version of pymongo installed on the remote node pymongo2.2 or older?
> I would expect those exceptions to be handled with newer pymongo.

``` python
In [2]: import pymongo

In [3]: pymongo.version
Out[3]: '3.2.2'
```

I am not sure to understand why the pymongo should handle this exception.
The code only catch specific exception. In our case the code must handle `Connection` + `Operation`, not only `Connection`.

imho, use a global exception is KISS and more resilient for this module.

Thanks

**Comment by alikins** [comment]
> I am not sure to understand why the pymongo should handle this exception.
> The code only catch specific exception. In our case the code must handle Connection + Operation, not only Connection.

Just curious if the conditional imports around https://github.com/ansible/ansible-modules-extras/blob/devel/database/misc/mongodb_user.py#L162 came into play. For old pymongo, ConnectionFailure and OperationFailure wouldn't be imported.

**Comment by Lujeni** [comment]
@alikins no it's just for the `MongoClient` import and the breaking change introduce on pymongo driver.

``` python
>>> import pymongo
>>> pymongo.version
'2.2'
>>> from pymongo.errors import ConnectionFailure
>>> from pymongo.errors import OperationFailure
>>> from pymongo import version as PyMongoVersion
>>> from pymongo import MongoClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name MongoClient
>>> 
```

However, i should remove the useless import now :)

**Pull request merged**
