### PR TITLE
Add win_chocolatey proxy support

### PR DESCRIPTION
**Pull request by ptemplier**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add win_chocolatey proxy support.
Add parameters to specify proxy url, user and password to be used when installing chocolatey and when installing package.
##### WORKAROUND

```
- name:  Check if chocolatey is installed
  win_stat: path='C:/ProgramData/chocolatey'
  register: choco_install

- name: Install Chocolatey using proxy
  raw: 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted ; $wc=new-object net.webclient ; $proxy = New-Object System.Net.WebProxy("{{http_proxy_host}}:{{http_proxy_port}}", $true)  ; $wc.proxy=$proxy ; iex($wc.downloadstring("https://chocolatey.org/install.ps1"))'
  when: choco_install.stat.exists == False

- name: Chocolatey set proxy
  raw: 'choco config set proxy http://{{http_proxy_host}}:{{http_proxy_port}}'

- name: install curl
  win_chocolatey:
    name: curl
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ptemplier. To the current maintainers, @smadam813 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ptemplier** [comment]
@nitzmahone any thoughts on this one ?

**Comment by dagwieers** [comment]
If this functionality is needed, please migrate it to https://github.com/ansible/ansible
We have tools for doing so: https://github.com/ansible/ansible-modules-extras/pull/3022#issuecomment-265457274

Anyone can do this BTW, so if someone other than the author wants to (help) getting this merged, please step forward :-)

**Comment by ptemplier** [comment]
This issue was moved to ansible/ansible#21886

**Pull request closed without merging**
