### PR TITLE
New ec2 asg facts module

### PR DESCRIPTION
**Pull request by stefanhorning**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ec2_asg_facts module at `cloud/amazon/ec2_asg_facts.py`
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### SUMMARY

New module to gather facts about AWS EC2 auto scaling groups (ASGs). Much like the other facts gathering modules we have already for EC2. This lets you get a list of ASGs in one go, to process them further. Uses the same return values as the [ec2_asg](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_asg.py) module to be used interchangably.

I haven't written many Ansible modules yet, so this might still need refactoring. Let me know what you think.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @stefanhorning for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
A PR for this type of module already exists https://github.com/ansible/ansible-modules-extras/pull/1710

This module is also written in boto rather than boto3 so doesn't meet guidelines.  I think it's best to proceed with the PR above.

close_me

**Comment by stefanhorning** [comment]
Ok, no problem. I just needed this quick so I wrote one myself.

**Comment by stefanhorning** [comment]
mentioned PR has moved to #2588

**Pull request closed without merging**
