### PR TITLE
vmware_guest: Add multiple nics management + Bug fixes

### PR DESCRIPTION
**Pull request by aperigault**
##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
- Fix var name:
function getfolder return folder_map instead of foldermap.

- Fix bug in deploy_template function:
If folder not start by /vm there is a "no folder matched the path" error

- Power on VM if state is set to poweredon

New feature : Move nic creation out of customizations + Add multiple nics management

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @aperigault. To the current maintainers, @jctanner, @jcpowermac, @mtnbikenc, @chrrrles please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dav1x** [comment]
@aperigault I'll review and test this tomorrow. Sorry been swamped today.

**Comment by dav1x** [comment]
```
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_o4WuNi/ansible_module_vmware_guest.py\", line 1346, in <module>\n    main()\n  File \"/tmp/ansible_o4WuNi/ansible_module_vmware_guest.py\", line 1324, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_o4WuNi/ansible_module_vmware_guest.py\", line 812, in deploy_template\n    network = get_obj(self.content, [vim.Network], device['network'])\nKeyError: 'network'\n", 
    "module_stdout": ""
```

@aperigault this doesnt work for me. 

```
        for device in self.params.get('nic'):
              network = get_obj(self.content, [vim.Network], device['network'])       
```

you'll need to iterate through the nic dict to get network value out. 

Like this:

```
         key = 0                     
         network = get_obj(self.content, [vim.Network], ip_settings[key]['network'])
```

Here is the play I was using:

```
---
- name: create vm                                                                                                                                                           
  hosts: localhost
  tasks:
    - vmware_guest:
        hostname: "10.x.1x.221"
        username: "administrator@vsphere.local"
        password: "P@ssw0rd"
        validate_certs: False
        name: "test03"
        datacenter: "Boston"
        cluster: "devel"
        validate_certs: False
        template: "ansible-template"
        annotation: "master"
        nic: 
            - type: vmxnet3
            - network: 'VM Network'
        nic: 
            - type: vmxnet3
            - network: 'dvVM_Network'
        #customize: True
        #domain: "e2e.bos.redhat.com"
        #dns_servers: ['10.x.x.5','10.x.x.2']
        #ips: "10.x.x.254"
        #networks:
          #'10.x.x.0/23':
            #network: 'dvVM_Network'
            #network: 'VM Network'
            #gateway: '10.x.x.254'
```

Also, you'll want to define the type of adapter to use:

```
              nic = vim.vm.device.VirtualDeviceSpec()
              nic.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
              nic.device = vim.vm.device.VirtualVmxnet3()
```

This hardsets to vmxnet3.

Lastly, if nic is not defined in the play and customize is, its going to fail. I think instead of removing the nic section from customize it may be better to make it its on section and use the options nic and customize as mutually exclusive perhaps?

Thoughts @jctanner?

**Comment by aperigault** [comment]
@dav1x could you try with a nic var like this:

```
nic:
    - type: vmxnet3
      network: 'Network1'
    - type: vmxnet3
      network: 'Network2'
```

I have not implemented nic type for now.

In vmware practises nics and customization are two separate thinks and it could be complicated to maintain network management if we have a copy of nic configuration in two different sections. I will prefer to add an error if you define ip customization without nic configuration?

I think it could be a good idea to add a nic label to link with customization parameters like this:

```
nic:
  - type: vmxnet3
    name: eth0
    network: VM Network
ips:
  - interface: eth0
    ip: 192.168.1.100
```

Indeed for me network var is useless, is not vmware_guest module job to check if you add an ip in the good network. But if you use this is not a real problem for me. We can eventually do network var not mandatory to set customization ip?

**Comment by dav1x** [comment]
@aperigault 

```
 [WARNING]: While constructing a mapping from /root/test_vmware_guest/main.yaml, line 7, column 9, found a duplicate dict key (validate_certs). Using last defined value
only.
```

Only the last NIC was created. 

```
nic:
  - type: vmxnet3
    name: eth0
    network: VM Network
```

I disagree with this layout. The hardware is agnostic to device labeling. This could be a Windows Template that's getting multiple vmxnets applied. I think when defining NICs all that really needs be applied is the type and VLAN (vSwitch portgroup or vDS portgroup).

**Comment by aperigault** [comment]
@dav1x 
1- Your error seems to not be related to my PR:

> duplicate dict key: validate_certs

I don't understand your problem. All nics are ok for me.
Have you define:

```
nic:
    - type: vmxnet3
      network: 'Network1'
    - type: vmxnet3
      network: 'Network2'
```

or 

```
nic:
    - type: vmxnet3
      network: 'Network1'
nic:
    - type: vmxnet3
      network: 'Network2'
```

?
I will test it again.

2- I understand.
Otherwise we can simplify just like this:

```
nic:
  - type: vmxnet3
    network: VM Network
ips:
  - ip: 192.168.1.100
    network: VM Network
```

But with this model we can't create two nics in the same vlan. Do we really need this ?

**Comment by zralt** [comment]
Hi,

This change breaks the disk adding / modifying when using a template to launch VMs. Somehow the separate NIC configuration overwrites the changes in the disk part. If I switch the order of disk / nic configuration, the disk get configured correctly.

**Comment by aperigault** [comment]
@zralt I added a new multidisk feature and fix this issue

**Comment by zralt** [comment]
@aperigault Thanks for the quick response, I can test it out on monday

**Comment by zralt** [comment]
Tried it out the modification, works perfect.

**Comment by gregdek** [comment]
Thanks @aperigault for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dav1x** [comment]
@aperigault the nic additions work fine. 

The one thing I see is that by default wait_for_ip is set but, poweredon isnt the default state. I think we should modify the logic to include a test for wait_for_ip otherwise clients will be waiting for an IP address forever unless they manually power on the VM. 

I need to add functionality to set multiple static IP addresses as well. If you include two nics in devices and only customize one, you get a NIC mismatch error in vcenter.

**Comment by karlism** [comment]
Hello!

Can you please add feature to create VM without any templates specified? We used this scenario with old vsphere_guest module previously, and by default new VMs booted from network and rest of the deployment was automated by kickstart.

Thanks!

**Comment by dav1x** [comment]
@karlism Can you submit a new issue for this request? I've added onto to your functionality @aperigault  Your PR LGTM

**Comment by aperigault** [comment]
@dav1x I don't understand the goal of wait_for_ip. Can I delete this var and always wait_for_ip when ips var is set and state is set to poweredon or restarted ?

**Comment by dav1x** [comment]
@aperigault Once your PR is merged ill submit a PR for multiple static IP addresses this is how I addressed it

            if wait_for_ip:
                 self.set_powerstate(vm, 'poweredon', force=False)
                 self.wait_for_vm_ip(vm)

**Comment by aperigault** [comment]
@dav1x I've fixed wait_for_ip problem with your trick.

**Comment by dav1x** [comment]
@jctanner Can you review this as well?

**Comment by aperigault** [comment]
@dav1x @jctanner I added a new feature to allow users to set vlan_id instead of vlan_name in nics configuration (https://github.com/ansible/ansible-modules-extras/pull/3481/commits/7f2e8fc8c5089efc8b9708e35d0bbfc9bede6c12)

**Pull request closed without merging**
