### PR TITLE
Allow s3 bucket lifecycle policies with multiple transitions

### PR DESCRIPTION
**Pull request by ryansydnor**
This addresses https://github.com/ansible/ansible-modules-extras/issues/986

This depends on https://github.com/boto/boto/pull/3431

### CODE REVIEW

**Comment by wimnat** [comment]
This discussion has been has before. A module handling one rule at a time more desirable as it's better  to have first class module parameters target than just 'rules' - it makes it easier for newcomers. 

It's easy to just use a with_items loop to insert multiple rules.

**Comment by ryansydnor** [comment]
@wimnat - I agree that first class module parameters are easier to understand for newcomers. However, given Ansible's principle of [idempotency](http://docs.ansible.com/ansible/glossary.html#idempotency), I'd much rather declare my desired state and converge to it than have to worry about my current state in order to manipulate it.

Is there a happy middle ground somewhere? Can I enhance the docs and delineate the parameters of "rules" rather than just via example?

**Comment by robynbergeron** [comment]
Thanks @ryansydnor. @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by wimnat** [comment]
I don't see the difference in your version and the existing version for idempotency or how the current version worries about existing state?

What's the difference between...

```
s3_lifecycle:
  some: x
  rule: 1
s3_lifecycle:
  some: x
  rule: 2

and 

s3_lifecycle:
  rules:
    - some: x
      rule: 1
    - some: x
      rule: 2
```

?

**Comment by bcoca** [comment]
The first allows for standard functions to validate what some/rule are, the second does not, it only asks us to validate that `rules` is a list and pushes further validation down to module author.

**Comment by copumpkin** [comment]
@wimnat in your first example, if `s3_lifecycle` were stating "what I want to be true" rather than "actions", you'd end up with the truth being

``` yaml
  some: x
  rule: 2
```

Since you first stated that you wanted the truth to be one thing, then stated it should be something else.

In the latter, the desired state is both rules.

I'm not saying one is inherently more Ansible-like than the other (I know of plenty of other modules that have `present` and `absent` rather than an overall desired state) but I do think they have pretty different semantics.

Having said that, I do think that as long as you have a user-chosen `id` field or something like it (which we do here, as far as I can tell), it's not ridiculous to go with a `present`/`absent`-style API on the individual rules, as @wimnat is proposing. I personally prefer @ryansydnor's current design, but more for aesthetic reasons and could swing either way.

@bcoca that's certainly true from an Ansible implementation standpoint, but it also seems worth talking about what we would want this to look like independent of implementation constraints, before constraining ourselves to today's implementation.

**Comment by ryansydnor** [comment]
@wimnat - I'd like to elaborate upon my "existing state" comment with some examples. 

**Example One**
1. Apply lifecycle policy by hand to entire bucket (no prefix).
2. Run s3_lifecycle module on subset (with prefix)
3. Error thrown about lifecycle rule overlap

**Example Two**
1. Apply lifecycle policy by hand to entire bucket
2. Run s3_lifecycle module with one rule
3. Bucket now has two rules on it (one of which was not specified in my playbook)

Both of these use cases are handled eloquently by the proposed changes to the module via convergence to a declared state, rather than a mutation of existing state.

**Comment by wimnat** [comment]
Example 1 assumes someone has been configuring rules outside of Ansible. Yes, you would get an error trying to bring about the state you want.  However, if the person was the type to do things manually on occasion, he may also be the type be a little upset if he ran Ansible and some or all of his manually created rules were nuked bringing about 'desired state'.

With example 2, it's the same thing.

It comes down to how people use Ansible. If you were always happy to say that Ansible wins and destroys existing config to bring about desired state then your way makes sense (which, btw, i am all for). Unfortunately, a lot of people don't use Ansible this way.  They may want to add a rule but leave other rules in place or vice versa. That's why modules like ec2_group wont just nuke all the rules without specifying a flag option first.

I prefer the flexibility of the current approach whereby I can use the module to leave existing rules in place rather than have to ensure that whatever policy i about about to commit is not going to destroy manual changes.

**Comment by gregdek** [comment]
This has been sitting a while. @wimnat have you come to any conclusion here?

**Comment by ryansydnor** [comment]
@wimnat - would a happy middle ground include a "purge_rules" option (similar to ec2_group) that defaults to false and only removes existing rules if included AND specified as true? If you think that works, I'm happy to add the functionality. If you don't think this is worthwhile, I can close the PR.

**Comment by wimnat** [comment]
@ryansydnor I still think this PR is too far a departure from how the module was originally written.  How it currently is is one philosophy, with this PR, it's a different philosophy.  Without core team weighing in with what they actually want then i don't really want to approve this. Sorry!

**Comment by ryansydnor** [comment]
@wimnat - good point. I agree that it makes sense to pull in the core team to take a look.

@robynbergeron @bcoca @gregdek - can you help coordinate that? Add the "core_review" label, perhaps?

**Comment by gregdek** [comment]
Happy to relabel as core_review as requested. Fair warning: this could take quite a while; there are lots of others in the queue. We're bringing more people into the core team, so hoping it won't be too long.

**Comment by ryansydnor** [comment]
@gregdek - that's quite alright. It's still waiting on https://github.com/boto/boto/pull/3431 to be merged.

At this point, I'm less interested in the specific functionality and more interested in the principles guiding the way we write modules. I think this is an opportunity for a good discussion to help clarify some of those principles.

**Comment by gregdek** [comment]
Agreed.

**Comment by gregdek** [comment]
Thanks @ryansydnor for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@ryansydnor A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
@gregdek can you mark this for core review please?

**Comment by gregdek** [comment]
@wimnat as you wish.

**Comment by gregdek** [comment]
Thanks @ryansydnor for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
@gregdek - bot clobbered core_review :(

**Comment by gregdek** [comment]
@wimnat because it no longer merges.

**Comment by gregdek** [comment]
@ryansydnor A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansydnor** [comment]
Currently on vacation with limited access to computers. Will address upon return.

**Comment by gregdek** [comment]
@ryansydnor Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ryansydnor** [comment]
I'm going to let this die. It's not aligned with the design the original author intended, the core team hasn't taken a look for quite some time (~3 months), and the module has drifted enough since the original PR I'm not willing to invest the time to rebase. Closing.

**Pull request closed without merging**
