### PR TITLE
route53_zone: support for delegation sets, update to boto3

### PR DESCRIPTION
**Pull request by manicminer**
- Add support for delegation sets
- Update to use boto3 (required to support delegation sets)
- Add support for creating public and private zones with the same name (previously the module would err if you tried to create a private zone with the same name as an existing public zone or vice versa)
- Add RETURN string to documentation

### CODE REVIEW

**Comment by manicminer** [comment]
Question: I just realised that I changed the output of this module (to be more in line with convention). The result dictionary is now called `result` where before it was called `set`. Also the previous return values for `vpc_id` and `vpc_region` are now returned in a list because private zones can be linked to more than one VPC. Is this OK, or should the previous return values be maintained verbatim?

**Comment by bcoca** [comment]
result or set really do not matter, it is not an 'official' convention, just seems to have grown 'organically'

As for returning new items in the results, that is fine, its removing/changing old ones that will break existing playbooks that is a problem.

**Comment by bcoca** [comment]
one problem though, this module WAS working with boto2, if you wan't to add boto3 for new functions, that is OK, but it should not break for people still stuck on boto2.

**Comment by manicminer** [comment]
OK, I'll add the use of boto2 back in for the existing capabilities, and just use boto3 for new options. Also will change the result variable to be called `set` as it is currently

@bcoca With regard to `vpc_id` and `vpc_region`, I wonder if the module should still return those, with the caveat that they would only indicate the first VPC in the result returned by route53?

**Comment by bcoca** [comment]
possibly adding the full list elsewhere and making a note in the docs that those are 'just the first'. No need to revert the 'set/result' change, my point is that "we don't care".

**Comment by manicminer** [comment]
wrt the vpc parameters, sounds good.

Are you sure about the set/result change? In the PR as it stands, I already renamed the return dictionary from `set` to `result` and this module was in the 2.0 release.

**Comment by manicminer** [comment]
I am reverting the change to the return dictionary, and re-working so that only the new `delegation_set` parameter uses boto3.

**Comment by gregdek** [comment]
Thanks @tombamford for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@manicminer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by thefotios** [comment]
Any update on this? Just got bit by not being able to create a zone with an existing name (eg, re-running the same playbook).

**Comment by gregdek** [comment]
@manicminer Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Closing due to contributor inactivity. @thefotios you may consider forking from the originating repo and re-submitting as a new PR to try to get it through the process.

**Pull request closed without merging**
