### PR TITLE
Add rootdir option to pkgng

### PR DESCRIPTION
**Pull request by mahadeva604**
Add support pkg -r 'rootdir' (pkg version 1.5.0) that will install in the given rootdir without chrooting.

### CODE REVIEW

**Comment by gregdek** [comment]
@bleader Please review; if you give +1, we will merge

**Comment by bleader** [comment]
It is worth noting that I haven't used pkgng or the ansible-module since I wrote the first version.

The patch seems pretty straightforward, and should work fine from my understanding. Only thing is we're adding a string propagated everywhere in the module, %s'ed into every command string, even as the default will be an empty string, that is not what I'd call pretty, but I don't have better solution to suggest.

**Comment by bleader** [comment]
That being said:
:+1:

**Comment by gregdek** [comment]
Hmm, looks like a merge conflict now... I'll take a look.

**Comment by gregdek** [comment]
@mahadeva604 Thanks for submitting this pull request. Unfortunately, it appears that the underlying code has changed since your submission, and this PR now needs to be rebased. 

If you believe that this PR still applies, please rebase and we will put it into our community review process as soon as possible.

**Comment by gregdek** [comment]
@mahadeva604 A friendly reminder: this pull request has been marked as needing your action, and it hasn't been updated in the last month. 

If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we'll keep it open pending your changes.

If we receive no indication from you within a week, we will close this pull request.

**Comment by mahadeva604** [comment]
Merge conflict resolved.

**Pull request merged**
