### PR TITLE
Added win_windows_update_agent module

### PR DESCRIPTION
**Pull request by adbertram**
##### ISSUE TYPE

- New Module Pull Request
##### COMPONENT NAME

win_windows_update_agent
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 23651b657e) last updated 2016/09/21 13:45:09 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 3486395970) last updated 2016/09/21 13:53:27 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 1f2319c3f3) last updated 2016/09/21 13:53:35 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/ansibleinventory/library']

```
##### SUMMARY

added a Windows win_windows_update_agent to control the WUA

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @adbertram for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @adbertram for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@adbertram A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
@adbertram Hi - this module looks like it could be very handy.  Are you able to rebase it - it looks like you have a lot of unrelated commits, probably as a result of doing a "git merge" instead of a " git pull --rebase " which ansible requires - see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

If you need help sorting out your git fork state I suggest asking on #ansible-devel irc channel or ansible-devel google group.

**Comment by adbertram** [comment]
@jhawkesworth Forgive my Git ignorance. I want to contribute but still getting the hang of Git. I'll try to rebase it and see what happens.

**Comment by jhawkesworth** [comment]
No worries. I did much the same with my first PR.  I still find git a bit fiddly but its worth getting used to.

**Comment by trondhindenes** [comment]
I did the same with my 5 first PRs - at least!

**Comment by gregdek** [comment]
@adbertram Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Sorry this is closed. If you need help rebasing your fork feel free to ask on ansible-devel irc channel.

**Pull request closed without merging**
