### PR TITLE
Support the ssl_cert_reqs directive

### PR DESCRIPTION
**Pull request by Lujeni**
Thanks

update:
`2016-05-04` - rebase

### CODE REVIEW

**Comment by ultrabug** [comment]
nice :+1:

**Comment by robynbergeron** [comment]
Hi @Lujeni -- thanks for this PR.

@elliotttf -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by btall** [comment]
+1

**Comment by gregdek** [comment]
@elliotttf This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by elliotttf** [comment]
Can I transfer maintainership of this to someone else? I haven't kept on
top of this as I'm no longer actively involved in server configuration and
deployment.

Elliott Foster
@elliotttf

**Comment by gregdek** [comment]
Thanks @elliotttf -- yes, thanks for letting us know. Is there anyone you can recommend?

**Comment by Lujeni** [comment]
@gregdek @elliotttf if u need i am interested to maintain this module. there is a process for this kind of request?

**Comment by Lujeni** [comment]
@gregdek Hi, any news?

**Comment by Lujeni** [comment]
@gregdek Bump. There is any process  ?

Thanks

**Comment by Lujeni** [comment]
@gregdek 
please `shipit`

**Comment by gregdek** [comment]
Thanks @lujeni, sorry it took a while to see this one :)

**Comment by gregdek** [comment]
Thanks @Lujeni for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by gregdek** [comment]
Thanks @Lujeni for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@Lujeni Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
Fix

**Comment by gregdek** [comment]
@Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
Hello,

> @Lujeni A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

@gregdek Why the labels `need_revision` and `pending_action` are still present ?

All seems good to me.

**Comment by resmo** [comment]
@Lujeni huch, this PR is a kind of a mess. I checked, you are marked as maintainer for this module. Marking it as shipit

**Comment by Lujeni** [comment]
@resmo you right !

`shipit`

**Pull request merged**
