### PR TITLE
Add lvol_cache module

### PR DESCRIPTION
**Pull request by p53**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

module
##### ANSIBLE VERSION

ansible 2.0.0.2
##### SUMMARY

This module focues on managing cache lvol's. Managing them is more complex than normal lvs, this module tries to hide that complexity

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @p53 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @p53 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@p53 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by raben2** [comment]
shipit

**Comment by p53** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @p53 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mmitucha** [comment]
shipit

**Pull request closed without merging**
