### PR TITLE
win_nssm: account get fix

### PR DESCRIPTION
**Pull request by h0nIg**
i introduced a new function with https://github.com/ansible/ansible-modules-extras/pull/1135 and https://github.com/ansible/ansible-modules-extras/pull/1143 that is not checking the @ on a user pricincipal correctly

### CODE REVIEW

**Comment by jhawkesworth** [comment]
Hi @h0nIg you seem to have conflicts - maybe a rebase is needed (I am not a git expert).
Mentioning @smadam813 for info

**Comment by h0nIg** [comment]
fixxed merge problems

**Comment by smadam813** [comment]
This trips me up all the time in powershell.  Easy mistake to make!  Looks good and thanks for the fix @h0nIg.

**Comment by h0nIg** [comment]
would be great if you comment on https://github.com/ansible/ansible/pull/12806 too, because the usersearch function is used on a lot of modules to get user with various formats and transform it to needed format. example: userprincipal:user@domain.net -> nt authority style:domain\user

**Comment by gregdek** [comment]
Thanks @h0nIg for the PR and @smadam813 for the review. Marking for inclusion.

**Pull request merged**
