### PR TITLE
New module for managing hosts file on windows

### PR DESCRIPTION
**Pull request by iagogarrido**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

win_hosts
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added a new module for windows hosts file management

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @iagogarrido for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sukpan** [comment]
Hi @iagogarrido, I see in the `windows/win_hosts.py` file that your examples reference `win_robocopy` and not `win_hosts`. 

Could you correct this please?

needs_revision

**Comment by gregdek** [comment]
Thanks @iagogarrido for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by iagogarrido** [comment]
In the last commit, I only changed the version_added in win_hosts.py. I can't read any info of the last commit build, so I guess the build failed due to a external error...

ready_for_review

**Pull request closed without merging**
