### PR TITLE
Use addresses and names reserved for documentation

### PR DESCRIPTION
**Pull request by ypid**
##### ISSUE TYPE
- Docs Pull Request
##### COMPONENT NAME

All matching once/all that I found.
##### ANSIBLE VERSION

devel
##### SUMMARY

Use addresses and names reserved for documentation while trying to preserve the meaning of the examples.

Related to: https://github.com/ansible/ansible/issues/17479

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ypid. To the current maintainers, @banyek, @alcamie101, @rosmo, @dagwieers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @xen0l, @resmo, @dazworrall, @2-B, @privateip, @wimnat, @erydo, @mhite, @caphrim007, @jcpowermac, @mtnbikenc, @stygstra, @smashwilson, @maxamillion, @chrrrles, @mgruener, @briceburg, @joshainglis, @karmab please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by xen0l** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @ypid for this PR, and thanks @banyek, @alcamie101, @rosmo, @dagwieers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @xen0l, @resmo, @dazworrall, @2-B, @privateip, @wimnat, @erydo, @mhite, @caphrim007, @jcpowermac, @mtnbikenc, @stygstra, @smashwilson, @maxamillion, @chrrrles, @mgruener, @briceburg, @joshainglis, @karmab for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by resmo** [comment]
LGTM

**Comment by keachi** [comment]
shipit

**Pull request merged**
