### PR TITLE
Bugfix for newer policycoreutils-python (eg. RHEL7)

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

sefcontext

##### ANSIBLE VERSION

v2.2

##### SUMMARY

The policycoreutils python API for RHEL6 and RHEL7 are sufficiently
different, requiring some additional definitions and specific conversion
that works on old and new implementations.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @dagwieers. This module is going into community review.

We notice that you are one of the maintainers (@dagwieers) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @dagwieers. Since you are one of the maintainers (@dagwieers) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dagwieers** [comment]
shipit

**Comment by nirik** [comment]
@dagwieers Any chance this could also land in the 2.2 stable branch? Thanks.

**Comment by dagwieers** [comment]
Sure, isn't that the case already ?

I don't think this is well-managed in Ansible right now. Someone should be overlooking which changes requires a backport to stable releases IMO. And the best time to evaluate that, is when it gets merged.

**Comment by bcoca** [comment]
The commiter that merges is supposed to make that evaluation.

@nirik that does not mean the author of the PR.

**Comment by dagwieers** [comment]
@bcoca OK, that is what I was expecting. That said I often do indicate my own judgement. I guess I forgot this time.

*PS That's why I thought tagging it as a "regression" was a good indication that it requires backporting.*

**Comment by bcoca** [comment]
'backport' label is there for that, 'regression' does not imply backport

**Comment by dagwieers** [comment]
Well, normal users cannot label issues/PRs.

A regression to me does indicate that you want to get it fixed ASAP in your stable branches. Because it was something that once worked and is now broken (impacting users).

**Comment by bcoca** [comment]
it can be broken in devel only

**Comment by dagwieers** [comment]
Things are often broken in devel, because devel usually includes new (untested) functionality.
Regressions for me imply stable releases (things that have worked in the field).

**Comment by bcoca** [comment]
and precisely to avoid the debate on 'what is a regression' is why we don't have them

**Comment by tjanez** [comment]
@bcoca, could you cherry-pick this to 2.2 stable branch?

**Comment by resmo** [comment]
it was cherry picked to 2.2. by e5a868136eef54cc22346f6eb3596e28bbff5934

**Comment by abadger** [comment]
We're going to make at least one more rc before 2.2.1 final so this will likely make it into 2.2.1

**Pull request merged**
