### PR TITLE
Properly label path argument with type='path'

### PR DESCRIPTION
**Pull request by mscherer**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

lxc_container

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mscherer for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @mscherer. To the current maintainers, @cloudnull please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by cloudnull** [comment]
thanks @mscherer for the changes. Looks good to me.

**Comment by cloudnull** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @mscherer for this PR, and thanks @cloudnull for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
