### PR TITLE
Module for appending windows environment Path variable User, System, Process level

### PR DESCRIPTION
**Pull request by Rajeshkumar90**
ISSUE TYPE

New Module Pull Request
COMPONENT NAME

Append value to Path Variable

ANSIBLE VERSION

ansible 2.1.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides

SUMMARY

Set an path environment variable for all level (User,Machine)

win_addpath:
pathvalue: 'C:\Program Files\Java\bin'
level: machine

Expexcted Result : In System env, Path variable should contain the above mentioned value

Expand an path environment variable for the current users

win_addpath:
pathvalue: '%JAVA_HOME%\bin'
level: user
Expexcted Result : In User env, Path variable should contain the above mentioned value in expanded format(C:\Program Files\Java\jdk1.8.0_112\bin)

Validation :

Checks path variable is present or not based on input for given level (User & machine)
Creates path variable with given value for given level(User & machine)
It will not add the value if it is already present in the path variable for given level(User & machine)
Validates User value with value available in "Path" Environment variable for given Level(User,Machine)and append the value to it if path value is not available.
Expands User value with value available in "Path" Environment variable for given Level(User,Machine)and append the value to it if path value is not available.
Creates new Path variable if it is not available for given Level(User,Machine) and append the value to it

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Rajeshkumar90 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by AbuAbbaad** [comment]
I think this would be really useful module to be shipped along with Ansible-Core, Adds more flexibility in deploying applications.

shipit

**Comment by jhawkesworth** [comment]
Hello,

Thanks for your contribution.  

First, there seem to be 2 modules in this branch.  Please can you provide a separate PR for each module so that each module can be reviewed and tested separately.

I don't think win_addpath is a good idea.  
It has a confusing name 'addpath' doesn't help you understand that it is for modifying environment variables.

Since 2.1, you can use facts to discover environment variables, so if you must set paths based on the existing path set on a machine, you can use win_environment and pass it a string based on the PATH from facts.   Personally I wouldn't do this as I want ansible to be in control of the exact PATH on all machines, to reduce the possiblity of wrong program being loaded.

While you can only do this for the user you are running ansible as at the moment, 'become' support is in progress for windows, which would let you get/set path for other users.

The win_shortcut module looks like a good start.  I would prefer it if it supported 'path' and 'src' as parameters for the source file (the one being linked to), and 'dest' for the link file.  If you need an example of how to do this, win_file.ps1 allows 'name', 'dest' or 'path' (although the way it does this could probably be improved).

for the reasons above 

needs_revision

**Comment by gregdek** [comment]
Thanks @Rajeshkumar90 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Rajeshkumar90** [comment]
Hello,

Thanks jhawkesworth for suggestion  
1. Shall we change the module name from win_addpath to win_appendpath 
2. Win_envirnoment is not working as expected as above module developed by us, Win_Environment module is just good if any new variable needs to be setup but doesn’t take required checks when updating PATH variable.

Tested win_envirnoment and found following inferences:

Example : To add C:\bin in path for Machine level 
 steps done by win_envirnoment module  
a) It adds C:\bin in system variable to PATH and removes the rest of the paths from the PATH variable

==============================================================
changed: [IP Addresss] => {"before_value": "C:\\bin", "changed": true, "invocation": {"module_name": "win_environment"}, "level": "user", "name": "path", "value": "C:\\bin\\test"}
==============================================================

b)Once the PATH variable gets wrongly updated, without actually checking and appending. WinRM and PowerShell modules just fail to work
===========================================================
<IPAddress> WINRM OPEN SHELL: 246DC733-6DC3-4DAB-B41A-26335A0F90B4
<IPAddress> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1480331319.31-196372307608147").FullName | Write-Host -Separator '';
<IPAddress> WINRM EXEC u'PowerShell' [u'-NoProfile', u'-NonInteractive', u'-ExecutionPolicy', u'Unrestricted', u'-EncodedCommand', u'UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA4ADAAMwAzADEAMwAxADkALgAzADEALQAxADkANgAzADcAMgAzADAANwA2ADAAOAAxADQANwAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=']
<IPAddress> WINRM RESULT u'<Response code 1, out "", err "\'PowerShell\' is not ">'
<IPAddress> WINRM STDOUT
<IPAddress> WINRM STDERR 'PowerShell' is not recognized as an internal or external command,
operable program or batch file.

<IPAddress> WINRM CLOSE SHELL: 246DC733-6DC3-4DAB-B41A-26335A0F90B4
fatal: [IPAddress]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA4ADAAMwAzADEAMwAxADkALgAzADEALQAxADkANgAzADcAMgAzADAANwA2ADAAOAAxADQANwAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA=, exited with result 1", "unreachable": true}

=============================================================

c) It doesn't expand the PATH variable declared for both system and machine

=========================================================
changed: [IPAddress] => {"before_value": null, "changed": true, "invocation": {"module_name": "win_environment"}, "level": "user", "name": "path", "value": "%JAVA_HOME%\\bin\\"}
==========================================================

Win_addpath module (Dedicated to Path variable for both system and User level)
1.It will append the value to Path variable if it is not already available 
2.It will not remove the rest of the variable available in Path variable
3.Expand path variable(From %JAVA_HOME%\bin\ to C:\Program Files\Java\bin)

**Comment by Rajeshkumar90** [comment]
'ready_for_review'

**Comment by gregdek** [comment]
Thanks @Rajeshkumar90 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
Care has to be taken with windows paths (this is true for all modules that specify paths for windows hosts) due to python interpreting \ as an escape sequence.

If you specify win_environment like this you can set the whole of the path.  I think this is preferable to partially specifying the path in your playbook and relying on the rest of it being correct on the windows host.

```
- name: ensure pstools is on the path for diagnostic purposes
  win_environment:
     state: present
     name: PATH
     value: 'C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\PSTools;'
     level: machine
```

**Review by daksha25 — APPROVED** [review]

**Review by daksha25 — APPROVED** [review]

**Comment by dagwieers** [comment]
I guess this PR can be closed now.

**Pull request closed without merging**
