### PR TITLE
Add Maintenance Mode support for VMware

### PR DESCRIPTION
**Pull request by jjahns**
##### Issue Type:

Please pick one and delete the rest:
- Feature Pull Request
##### Plugin Name:

vmware_maintenancemode
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

This change is to add support for placing ESXI hosts into maintenance mode.
##### Example output:

```
(Paste verbatim command output here if necessary)
```

### CODE REVIEW

**Comment by jjahns** [comment]
Looks like some problems with CI.  Investigating.

**Comment by jjahns** [comment]
This passed, so let me know if it requires changing.

**Comment by gregdek** [comment]
Thanks @jjahns for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by resmo** [comment]
well written and solid module. Does not yet support check mode but it could easily be implemented later. 
Maybe the vmware maintainers @chrrrles @privateip @jcpowermac @mtnbikenc could also have a look at it.

shipit

**Pull request merged**
