### PR TITLE
update monit output

### PR DESCRIPTION
**Pull request by mangas**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

monit
##### ANSIBLE VERSION

ansible 1.7.2
##### SUMMARY

This basically checks the monit version and parses the output differently. 

I couldn't find any unit tests for it so I only tested locally. 

Please let me know if you have any suggestions, I couldn't think of a different way to infer the version.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mangas for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mangas** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @mangas. To the current maintainers, @brian-brazil, @dstoflet please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mangas** [comment]
@gregdek can you ask anyone to review this PR? if there is anything I can do to help let me know

**Comment by mangas** [comment]
@brian-brazil @dstoflet can you guys help with this review?

**Comment by grisha87** [comment]
+1

**Comment by mangas** [comment]
@brian-brazil @dstoflet any chance you could look at this? A couple of months has passed in the meantime. would be nice to at least get a reply

**Comment by woodwo** [comment]
This one will be very helpful for monit users. I hope that well-respected maintainers @brian-brazil and @dstoflet will pay attention for that problem soon.

**Pull request closed without merging**
