### PR TITLE
added enabled vlan functionality for f5 vip

### PR DESCRIPTION
**Pull request by perbly**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

/network/f5/bigip_virtual_server.py
##### ANSIBLE VERSION

2.2.0

```

```
##### SUMMARY

Added function to to add enabled vlans for virtual server. 

Also changed a typo in the error message in the set_rules function.

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @perbly for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by perbly** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @perbly. To the current maintainers, @mhite, @caphrim007, @Etienne-Carriere please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
shipit

**Comment by gundalow** [comment]
As discussed in Networking Meeting 20160921 I'm happy to merge this in for 2.2.

@caphrim007 will add a test and if he finds issues he will treat the bug as a standard bugfix that needs to be applies between the 2.2 RCs

**Comment by perbly** [comment]
Thanks @gundalow @caphrim007  

I have started looking on how persistsence profile, profiles and rules are handled. We would like to re-run this modules with new/changed vars to bigip_virtual_server without getting the "already exists in partition" message.
We would also like the ability to update persistence profile to none if it was previous set to something. Did a commit that is working in my branch now but since i am a copy paste script kidde it probably needs some changes.
This is commited in https://github.com/perbly/ansible-modules-extras/commit/eefd79eda25a669af1aba81bdb999b5ac157423d
Feel free to comment.

**Comment by gundalow** [comment]
@perbly Could you please raise a PR against https://github.com/ansible/ansible-modules-extras/ then we can review it there. 

That's the standard process and it will avoid any discussion getting lost.

Thanks :)

**Pull request merged**
