### PR TITLE
Added os_host_aggregate and os_host_aggregate_member  modules

### PR DESCRIPTION
**Pull request by timl**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

os_host_aggregate and os_host_aggregate_member
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel ddd9f92255) last updated 2016/05/10 10:00:59 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 1f5cf669dd) last updated 2016/05/12 09:44:10 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 816673dd6f) last updated 2016/05/12 09:44:10 (GMT -500)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Adds support for management of OpenStack host aggregates.

`os_host_aggregate` handles creating, updating, and deleting aggregates.
`os_host_aggregate_member` handles host aggregate memberships.

These functions are split to match the existing OpenStack tools and APIs.  These modules depend on features available in the next release of shade (>1.8.0).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @timl. To the current maintainers, @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by haad** [comment]
I like this modules they look ok so 

shipit

**Comment by Shrews** [comment]
Could you please coordinate with the author of PR 2873 so that there is only one PR for these modules? Also, as @emonty pointed out in that PR, these modules should likely be renamed. They will also need to be retargeted for Ansible version 2.3.

**Comment by timl** [comment]
Closing this in favor of PR 2873

**Pull request closed without merging**
