### PR TITLE
Initial Commit for win_dns_reload_zone

### PR DESCRIPTION
**Pull request by teochenglim**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

New Module: win_dns_zone_reload
##### ANSIBLE VERSION

```
2.1.0
```
##### SUMMARY

```
Create a DNS record at local server
The zone must exists first, example "example.com"
To reload a windows DNS zone (After added/edited/deleted IP).
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @teochenglim. All backport requests must be reviewed by the core team, and this can take time. We appreciate your patience. 

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jhawkesworth** [comment]
@teochenglim Hi - I believe Ansible usually only accepts new modules into devel branch.  The stable-nnn branches are intended for bug fix releases only.  Depending on what you intended, you might want to close this and create a new PR based off devel branch, which would then go through ansible's usual community review process.

**Comment by teochenglim** [comment]
Create PR at #2584 and closing this one

**Comment by teochenglim** [comment]
Raised a new PR. Thanks.

Sent from my Samsung device

-------- Original message --------

**Pull request closed without merging**
