### PR TITLE
enables searching/finding rds snapshots

### PR DESCRIPTION
**Pull request by brockhaywood**
Related module which allows for copying snapshots between regions: https://github.com/ansible/ansible-modules-extras/pull/1280

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @brockhaywood --

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes, which can be contributed by anyone other than the author of the new module:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

More information about the review process can be seen here: 
https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
Pinging AWS friends for feedback: @jsmartin @scicoin-project @tombamford @garethr @jarv @jsdalton @silviud @adq @zbal @zeekin @willthames @lwade @carsongee @defionscode
@tastychutney @bpennypacker @loia

**Comment by robynbergeron** [comment]
Also note there is another related new module for RDS, #1280

**Comment by willthames** [comment]
I wonder if this should be called rds_snapshot_facts.

**Comment by willthames** [comment]
Most of my feedback on #1280 also applies here.

**Comment by brockhaywood** [comment]
Updated based on PR feedback. As it relates to the name of this module, I don't have strong feelings either way. I equated it to the ec2_ami_find hence the name.

**Comment by willthames** [comment]
passes_guidelines

I would name it rds_snapshot_facts, particularly as it works with no arguments. 

I would also suggest adding an example with no arguments.

**Comment by willthames** [comment]
Oh, and please squash commits.

**Comment by brockhaywood** [comment]
Renamed module and squashed commits

**Comment by willthames** [comment]
passes_guidelines

**Comment by manicminer** [comment]
Great module! I'm trying to use it in order to find the latest automated snapshot for an instance, in this regard it would be great if the results could be ordered and/or filtered for some attribute. I might have a go at adding this.

**Comment by manicminer** [comment]
I added some filtering/sorting options to this module. What would be the preferred way to submit these changes for comment?

@brockhaywood Would you like me to open a PR on your fork?

or should I open a new PR on ansible-modules-extras?

**Comment by willthames** [comment]
@tombamford, so what you're saying is 'works_for_me'

@robynbergeron, imo that's good enough to get this one merged.

@tombamford I would suggest creating a new PR, based on this one, on the assumption that this one should get merged shortly (now that you've tested it). If you can test #1280 too, that would be very handy.

**Comment by manicminer** [comment]
@willthames correct! sorry, should have tagged properly. works_for_me

I'll open a new PR shortly, and test #1280 as soon as I can.

**Comment by manicminer** [comment]
This change fell off my radar, but I have opened a new PR https://github.com/ansible/ansible-modules-extras/pull/1704 to replace this one.

**Pull request closed without merging**
