### PR TITLE
remove unicode prefix and correct text in table

### PR DESCRIPTION
**Pull request by bmillemathias**
Remove the unicode prefix displayed before the url pushover.net
Attempt to correct the text in the table which appear vertically.

### CODE REVIEW

**Comment by gregdek** [comment]
@weaselkeeper Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by gregdek** [comment]
@weaselkeeper This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@weaselkeeper still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by robynbergeron** [comment]
@weaselkeeper This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
@weaselkeeper still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by weaselkeeper** [comment]
ship it

as noted on 22 Dec.

**Comment by abadger** [comment]
Those aren't unicode markings.  They're markup to make urls into links.  They need to be uppercase "U" in order to be parsed correctly.  The pri argument description also needs to be a list element.

Since this has been here for a while, I'll make those changes and merge this.

**Comment by abadger** [comment]
Committed here: https://github.com/ansible/ansible-modules-extras/commit/0608318f90250d688fa0dce509c4ed356b525161  with the fixes I mentioned here: https://github.com/ansible/ansible-modules-extras/commit/d56ac42c8b234bf1a8892f2ab770fdc7f5e2edbc

@ bmillemathias Thanks for the patch to point out and fix these problems!  @weaselkeeper thanks for reviewing hte changes.

**Pull request closed without merging**
