### PR TITLE
Added consul module for windows

### PR DESCRIPTION
**Pull request by scullinan**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

win_consul
##### ANSIBLE VERSION

```
ansible 2.3.0.0
```
##### SUMMARY

This is a module for managing consul service registrations on windows. It is a port of the existing consul.py module so that it can work on windows. The only difference in usage is the module name i.e. "win" prefix otherwise this works in the same way.
Adidtional features that go beyond the consul.py impementation are:
- Implemented TCP checks which was missing from consul.py
- Implemented Status property to specify the initial state of the health check as supported by consul api.

```

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @scullinan for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by scullinan** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @scullinan for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by tomstaijen** [comment]
shipit

**Comment by anguswilliams** [comment]
shipit

**Comment by trondhindenes** [comment]
Great stuff @scullinan. Could you bump the version number so that it's inline with the current dev branch version and we'll get this merged (feel free to ping me when that's done)

**Comment by scullinan** [comment]
Thanks @trondhindenes, I have bumped the version in the py docs and in the PR description to 2.3.0.0, I'm assuming this is what you were asking?

**Comment by trondhindenes** [comment]
@nitzmahone would you take a look at this one? Potentially a super-important Ansible module so I'm afraid to merge it myself :-)

**Pull request closed without merging**
