### PR TITLE
adds module ec2_vpc_customer_gateway

### PR DESCRIPTION
**Pull request by klj613**

### CODE REVIEW

**Comment by klj613** [comment]
related to https://github.com/ansible/ansible-modules-extras/pull/1339 and https://github.com/ansible/ansible-modules-extras/pull/1338

**Comment by gregdek** [comment]
Thanks @klj613 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by sivel** [comment]
Here is some initial feedback based on automated scanning of this new module:

```
============================================================================
ec2_vpc_customer_gateway.py
============================================================================
ERROR: version_added should be 2.1. Currently 2.0
ERROR: sys.exit() call found
```

**Comment by klj613** [comment]
Thanks for the feedback. I will look into this in a day or two.

**Comment by klj613** [comment]
looked at existing modules and opted to use HAS_BOTO logic to remove the sys.exit

**Comment by MichaelBaydoun** [comment]
@klj613 in the new module review meeting today we discovered that this new module and another new module I wrote https://github.com/ansible/ansible-modules-extras/pull/1868 appear to cover the same functionality.  They would like us to put our heads together and come up with a plan.  In the next few days, can you review my module while I review yours?

**Comment by klj613** [comment]
Hello @MichaelBaydoun, Sorry for the late response. I'll check your module later tonight or tomorrow.

**Pull request closed without merging**
