### PR TITLE
Added "to_destination" option to forward port to remote host

### PR DESCRIPTION
**Pull request by rtm-ctrlz**
Example:
iptables -t nat -A port_forward -p tcp -m tcp --dport 2202 -j DNAT --to-destination 10.0.0.2:22

Use case:
On a host with a bunch of containers, ex. LXC.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @rtm-ctrlz. @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by sivel** [comment]
```
============================================================================
./system/iptables.py
============================================================================
ERROR: version_added for new option (to_destination) should be 2.1. Currently 0.0
```

**Comment by robynbergeron** [comment]
@rtm-ctrlz A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by LinusU** [comment]
@robynbergeron Seems like he fixed it a day ago, this looks good to me :+1: 

'shipit'

**Comment by gregdek** [comment]
Thanks again to @rtm-ctrlz for this PR, and thanks @LinusU for reviewing. Marking for inclusion.

**Comment by resmo** [comment]
Thanks @rtm-ctrlz for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by rtm-ctrlz** [comment]
'ready_for_review'

**Comment by LinusU** [comment]
'shipit'

Looking good :+1: I personally would prefer to squash to commits into one though...

**Comment by gregdek** [comment]
Thanks again to @rtm-ctrlz for this PR, and thanks @LinusU for reviewing. Marking for inclusion.

**Comment by LinusU** [comment]
132 commits? Something seems to have gone wrong with rebase/merge?

**Comment by jimi-c** [comment]
Yes, this needs to be cleaned up. This is common when a feature branch isn't used.

I'd create a new branch from origin/devel and cherry-pick the relevant commit(s) over to that, then revert/reset your working devel to match origin/devel. Unfortunately you'll most likely have to resubmit this PR as the source branch will have changed.

**Comment by jimi-c** [comment]
Another option would be to fork off a branch from your current devel, then fix devel by resetting/rebasing and cherry-pick the commit(s) back to devel. After that, `git push devel -f` to force push over your previous version on github should clean this up.

This way you should not have to resubmit the PR, but any further merges in your devel branch would mean you'd have to repeat this process (which is why it's always best to send PRs from feature branches).

**Comment by rtm-ctrlz** [comment]
Sorry for this mess with 130+ commits, fixed it.
Squashed changes to single commit.

As far as I can see this PR is 'ready_for_review'

**Comment by LinusU** [comment]
Looks good 'shipit'

**Comment by mscherer** [comment]
I am not sure the text to describe the option is correct. One can make dnat without specifying the port.

**Comment by gregdek** [comment]
Thanks @rtm-ctrlz. To the current maintainers, @LinusU please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by LinusU** [comment]
The code looks good but, as pointed out by @mscherer, the documentation probably needs another look at.

'needs_revision'

**Comment by gregdek** [comment]
Thanks @rtm-ctrlz for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @rtm-ctrlz for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rtm-ctrlz** [comment]
Same functionality was pulled with #1971
Thanks a lot

**Pull request closed without merging**
