### PR TITLE
univention udm_user: pep8

### PR DESCRIPTION
**Pull request by keachi**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

udm_user
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### SUMMARY

This is just a pylint / pep8 fix. There were too long lines in the module and some deprecated stuff, like <code>variable == None</code> instead of <code>variable is None</code>.

### CODE REVIEW

**Comment by resmo** [comment]
I just realized I overlooked this module also contains CamelCase. Would you mind also apply the change we discussed in https://github.com/ansible/ansible-modules-extras/pull/2439 for this module?

**Comment by keachi** [comment]
I'll changed camelCase to snake_case in this PR.

**Comment by gregdek** [comment]
maintainer unknown ping @gregdek @resmo @robynbergeron.

**Comment by resmo** [comment]
@2-B the bot does not yet know you are the maintainer, is this PR ready to merge?

**Comment by keachi** [comment]
This PR is ready to merge

**Pull request merged**
