### PR TITLE
New module - ec2_snapshot_facts

### PR DESCRIPTION
**Pull request by wimnat**
New module to get ec2 snapshot facts.

Useful for finding old snapshots to delete

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @wimnat -- Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
Also pinging our friends in the AWS crowd for their possible reviews :)

@jsmartin @scicoin-project @tombamford @garethr @lorin @jarv @jsdalton @silviud @adq @zbal @zeekin @willthames @lwade @carsongee @defionscode
@tastychutney @bpennypacker @loia

**Comment by bonovoxly** [comment]
This would be a very useful module to incorporate into Ansible.

**Comment by manicminer** [comment]
Tested and works_for_me. Also passes_guidelines

**Comment by manicminer** [comment]
Please shipit - thanks!

**Comment by wimnat** [comment]
@tombamford just fyi, i've updated this module to use boto3 instead.  It uses a new function i got merged in to module_utils/ec2.py.  I hope to get the other two helper functions in here merged in to utils too some time soon.

**Comment by wimnat** [comment]
@gregdek can i add shipit as a module author already?

**Comment by gregdek** [comment]
@wimnat yes you can! (The bot is still struggling with new modules, but we've got enough to put this one into shipit. Thanks!)

**Pull request merged**
