### PR TITLE
FreeIPA module polymorphic restructuring and small fixes

### PR DESCRIPTION
**Pull request by mkrupcale**
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
FreeIPA modules

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 2d2bb626d4) last updated 2016/11/16 17:08:46 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a4cddac368) last updated 2016/11/16 17:08:52 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 19c7d5b31b) last updated 2016/11/16 17:08:56 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
* Moved JSON-RPC client IPAClient class to ansible.module_utils.ipa, which is extended by all ipa modules
* ipa_user: incorporate displayname and userpassword attributes in module_user
* ipa_user: capitalized "I" in comment
* ipa_user: updated get_ssh_key_fingerprint to include possibility of the uploaded SSH key including user@hostname comment, which also appears in the queried fingerprint. This fixes a mismatch in the calculated and queried SSH key fingerprint in the user_diff calculation when the user already exists.
* ipa_hbacrule: ipaenabledflag must be 'TRUE' or 'FALSE', not 'NO'
* ipa_sudorule: ipaenabledflag must be 'TRUE' or 'FALSE', not 'NO'
* Add author to files missing it

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @mkrupcale. To the current maintainers, @Nosmoht please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Nosmoht** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @mkrupcale for this PR, and thanks @Nosmoht for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Nosmoht** [comment]
review_needed

Sorry, the code doesn't work anymore. I reviewed the code and it is looking fine. I really like the change done by @mkrupcale. Unfortunately the implementation of IPAClient in ansible.module_utils.ipa seems to be missing.

Current error

``` shell
Could not find imported module support code for ipa_user.  Looked for either IPAClient or ipa
```

Tested with:

``` shell
ansible 2.3.0 (devel 461286f914) last updated 2016/11/18 09:09:11 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a4cddac368) last updated 2016/11/18 09:10:52 (GMT +200)
  lib/ansible/modules/extras: (pr-ipa 8da2bcc7c3) last updated 2016/11/18 09:14:24 (GMT +200)
  config file = /home/tkrah/workspace/vagrant/ipa/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by resmo** [comment]
needs_info

IMHO ansible.module_utils.ipa is missing

**Comment by mkrupcale** [comment]
Yes, this is correct, ansible.module_utils.ipa is missing right now. I have the code in my fork of [mkrupcale/ansible:ipa-polymorphic](https://github.com/mkrupcale/ansible/tree/ipa-polymorphic) now, and have created a [pull request](https://github.com/ansible/ansible/pull/18542) to the corresponding upstream `ansible` repository. Sorry for the confusion, but I wasn't sure what the proper ordering was when getting these changes in which affected both `ansible` and `ansible-modules-extras` repositories.

**Comment by gregdek** [comment]
@mkrupcale, a community member requested some information about this PR; for that reason, we put this PR into the 'needs_info' state.

When you have answered the questions, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Nosmoht** [comment]
I've tested the changes together with https://github.com/ansible/ansible/pull/18542. If PR-18542 is merged, this one can be merged as well.

shipit

**Comment by gregdek** [comment]
Thanks again to @mkrupcale for this PR, and thanks @Nosmoht for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gundalow** [comment]
This code looks good though https://github.com/ansible/ansible/pull/18542 needs reviewing and merging first.

**Comment by gundalow** [comment]
Module_utils change has been merged, so I've now merged this.

**Pull request merged**
