### PR TITLE
Add facts module for NetApp E/EF-Series storage arrays.

### PR DESCRIPTION
**Pull request by hulquest**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

storage/netapp_e/na_eseries_facts.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 4cc4dc6793) last updated 2016/07/19 12:02:12 (GMT -600)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/19 12:02:18 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/19 12:02:21 (GMT -600)
  config file = /home/khulques/ansible.cfg
  configured module search path = ['/home/khulques/src/projects/ansible-modules-extras/storage/netapp_e', '/home/khulques/src/projects/ansible_eseries/ansible_modules']

```
##### SUMMARY

Adding facts module for the NetApp E/EF-Series storage array.

```
10.251.230.29 | SUCCESS => {
    "ansible_facts": {
        "netapp_disks": [
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C7FE5FC0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8AJBD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8096980000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8R8ZD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8096C80000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8R9BD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C80AB7C0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8SP3D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C80B14C0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8T23D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C80E26C0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8WAJD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C80E6A80000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8WM8D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C80E6F80000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8WMXD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C810FB00000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8ZAZD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8113D40000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8ZMJD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8118C80000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ8ZYSD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C812B280000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ915PD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C812B9C0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ916MD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8130C40000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ91K8D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8134340000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ91TBD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8134580000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ91TND", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C813F480000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ92J7D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8155F00000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ9410D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C8167B00000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ956ND", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C817ADC0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ96H7D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C819A5C0000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ98L8D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C819A740000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ98LGD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C81D0F80000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ9D70D", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }, 
            {
                "available": false, 
                "firmware_version": "MS09", 
                "id": "010000005000CCA03C81E9200000000000000000", 
                "media_type": "hdd", 
                "product_id": "HUC106060CSS601 ", 
                "serial_number": "PZJ9EUWD", 
                "status": "optimal", 
                "tray_ref": "0E00000000000000000000000000000000000000", 
                "usable_bytes": "594221686784"
            }
        ], 
        "netapp_enabled_features": [
            "autoCodeSync", 
            "autoLunTransfer", 
            "driveSlotLimit", 
            "flashReadCache", 
            "mixedDriveTypes", 
            "performanceTier", 
            "protectionInformation", 
            "raid6", 
            "ssdSupport", 
            "stagedDownload", 
            "storagePoolsType2", 
            "subLunsAllowed", 
            "totalNumberOfArvmMirrorsPerArray", 
            "totalNumberOfPitsPerArray", 
            "totalNumberOfThinVolumesPerArray"
        ], 
        "netapp_storage_pools": [
            {
                "available_capacity": "7700876361728", 
                "id": "0400000060080E5000299B640000058756D7447D", 
                "name": "Disk_Pool_1", 
                "total_capacity": "8220567404544", 
                "used_capacity": "519691042816"
            }, 
            {
                "available_capacity": "960810106880", 
                "id": "0400000060080E5000299C24000005AE56D74656", 
                "name": "1", 
                "total_capacity": "1188443373568", 
                "used_capacity": "227633266688"
            }
        ], 
        "netapp_volumes": [
            {
                "capacity": "42949672960", 
                "id": "0200000060080E5000299C24000005B456D9F393", 
                "is_thin_provisioned": false, 
                "name": "repos_0295", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "214748364800", 
                "id": "0200000060080E5000299B640000058456D74450", 
                "is_thin_provisioned": false, 
                "name": "Alpha", 
                "parent_storage_pool_id": "0400000060080E5000299C24000005AE56D74656"
            }, 
            {
                "capacity": "214748364800", 
                "id": "0200000060080E5000299C24000005AF56D746DF", 
                "is_thin_provisioned": false, 
                "name": "2", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "4294967296", 
                "id": "0200000060080E5000299B64000005EA57850F0B", 
                "is_thin_provisioned": false, 
                "name": "repos_0005", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "4294967296", 
                "id": "0200000060080E5000299C24000006275785122A", 
                "is_thin_provisioned": false, 
                "name": "repos_0006", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "214748364800", 
                "id": "0200000060080E5000299B64000005EE57850FB7", 
                "is_thin_provisioned": false, 
                "name": "ThickVolume", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "10737418240", 
                "id": "0200000060080E5000299C240000063F5790D592", 
                "is_thin_provisioned": false, 
                "name": "AlphaMT", 
                "parent_storage_pool_id": "0400000060080E5000299C24000005AE56D74656"
            }, 
            {
                "capacity": "2147483648", 
                "id": "0200000060080E5000299C240000064357910A48", 
                "is_thin_provisioned": false, 
                "name": "repos_0309", 
                "parent_storage_pool_id": "0400000060080E5000299C24000005AE56D74656"
            }, 
            {
                "capacity": "10737418240", 
                "id": "0200000060080E5000299B640000060957922746", 
                "is_thin_provisioned": false, 
                "name": "SSGroup_test", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "10737418240", 
                "id": "0200000060080E5000299C24000006CE57AC42F5", 
                "is_thin_provisioned": false, 
                "name": "NewThinVolumeByAnsible", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }, 
            {
                "capacity": "10737418240", 
                "id": "0200000060080E5000299B64000006A557AC401C", 
                "is_thin_provisioned": false, 
                "name": "NewVolumeByAnsible", 
                "parent_storage_pool_id": "0400000060080E5000299B640000058756D7447D"
            }
        ], 
        "snapshot_images": [
            {
                "active_cow": true, 
                "creation_method": "user", 
                "id": "3400000060080E5000299C24006305C15762AB4B", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "0", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063058F57616AAF", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063059057616AF1", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299C24006305BD57616DD0", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063059157616B44", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299C24006305BE576170BC", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299C24006305BF576170DB", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063059257616E39", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299C24006305C05761732B", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063059357629C80", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }, 
            {
                "active_cow": false, 
                "creation_method": "user", 
                "id": "3400000060080E5000299B640063059457629FF1", 
                "pit_capacity": "214748364800", 
                "reposity_cap_utilization": "2818048", 
                "rollback_source": false, 
                "status": "optimal"
            }
        ], 
        "ssid": "ansible1"
    }, 
    "changed": false, 
    "msg": "Gathered facts for ansible1."
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @hulquest for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hulquest** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @hulquest for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by dirtyharrycallahan** [comment]
As a NetApp customer I was just starting to look at this. Why did you @hulquest close the requests?

**Comment by hulquest** [comment]
It's a long story.  You can watch PR #2748 which is going through the PR process according to Ansible.  The plan is to review the first two modules and then add the rest in bulk.  There are about 20 in the pipeline for the E/EF platform.

**Pull request closed without merging**
