### PR TITLE
Ensure that port_path is split into at most 2 components.

### PR DESCRIPTION
**Pull request by welex91**
Without this fix, ec2_elb_facts will fail with:
ValueError: invalid literal for int() with base 10: '80/api/v1/health_check/'

if the Ping Target is HTTP:80/api/v1/health_check/

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @welex91. @mjschultz please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by mjschultz** [comment]
LGTM, :shipit:

**Comment by mjschultz** [comment]
Thanks @welex91, I didn't think about this since my checks are all top-level.

**Comment by welex91** [comment]
Thanks for the review, @mjschultz I guess this is ready to be shipit-ed ?

**Comment by mjschultz** [comment]
:shipit:

**Comment by gregdek** [comment]
Thanks again to @welex91 for this PR, and thanks @mjschultz for reviewing. Marking for inclusion.

**Comment by bcoca** [comment]
@welex91 can you flatten the commits?

**Comment by welex91** [comment]
I think I did the flatten correctly: git rebase -i HEAD~2 followed by git push origin devel --force.

:ready_for_review:

**Comment by gregdek** [comment]
Thanks @welex91. @rosmo please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by gregdek** [comment]
Thanks @welex91. @rosmo please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by rosmo** [comment]
needs_revision

**Comment by rosmo** [comment]
I don't think this PR should touch gluster_volume, is this an accident?

**Comment by welex91** [comment]
@rosmo: That's what happened when I merged and flattened the commits. Should I do something differently ?

**Comment by mjschultz** [comment]
@rosmo: I pushed up a clean version to https://github.com/ansible/ansible-modules-extras/pull/1565 if that's easier?

**Comment by welex91** [comment]
@mjschultz : good idea, certainly works for me ...

**Comment by rosmo** [comment]
@mjschultz, Looks good to me now. You can update PR's, you know :) (look up rebase and force push)

**Comment by mjschultz** [comment]
@rosmo that'd be a pretty big bug in github if I was able to force push to someone else's repo.

**Comment by rosmo** [comment]
@mjschultz, Obviously it would be. But with pull requests, you are proposing for a branch to be merged into another. You will be force pushing into your own fork only.

**Comment by mjschultz** [comment]
@rosmo, this isn't my proposed change its welex91's. I can't push to his repo therefore I can't update this PR which is why I opened a secondary.

**Comment by rosmo** [comment]
@mjschultz, Ah, I see, mixed you guys up, sorry about that!

**Comment by welex91** [comment]
Going with  #1565, thanks for all the reviews.

**Pull request closed without merging**
