### PR TITLE
Fix fail_json call in _mark_package_install

### PR DESCRIPTION
**Pull request by ToBeReplaced**
As per comments in #527

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @ToBeReplaced -- thanks for the PR. You're making my Fedora heart all shiny today. :)

@ignatenkobrain @DJMuggs -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also, @abadger -- I know you're busy :D But noticed you did the testing on #527 for DNF -- since this one is related, thought maybe you would be interested. Thanks :D

**Comment by igor-raits** [comment]
shipit

**Comment by robynbergeron** [comment]
@ignatenkobrain -- thanks for the quick review, and many thanks to @ToBeReplaced for the PR.

Marking for inclusion, cc: @ansible/core team.

**Pull request merged**
