### PR TITLE
Adding more options to yumrepo module

### PR DESCRIPTION
**Pull request by jtyr**
This PR adds some more options which might be useful for some users (should fix issue #1563). It also fixes one critical typo in the name of `Exception`.

### CODE REVIEW

**Comment by jtyr** [comment]
@ke3vin Please test if it works for you.

**Comment by gregdek** [comment]
Thanks @jtyr. Since you are a maintainer of this module, we are marking this PR for inclusion.

**Comment by PaddyDwyer** [comment]
@jtyr Hi, I had a need for a fix for #1563 too. I tested out your branch and it worked for me just fine.

**Comment by jtyr** [comment]
@PaddyDwyer Thanks for the confirmation. Hopefully the fix will be merged soon.

**Comment by jtyr** [comment]
Closing in favour of #1728.

**Comment by jtyr** [comment]
I'm reopening this PR in order to separate the shipment of the new parameters and the adding of the Managed Mode which is under discussion in the PR #1728 .

**Pull request closed without merging**
