### PR TITLE
New module - ec2_vol_facts

### PR DESCRIPTION
**Pull request by wimnat**
Module ec2_vol_facts.  Although ec2_vol module contains a "list" state, this state has been discouraged so if this module is merged then list state in ec2_vol could be deprecated.

This module goes beyond the list state by allowing vols returned to be filtered as per the amazon doc - http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVolumes.html

### CODE REVIEW

**Comment by robynbergeron** [comment]
Hi @wimnat --

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes, which can be contributed by anyone other than the author of the new module:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

More information about the review process can be seen here: 
https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

Thanks again for submitting your Ansible module!

**Comment by robynbergeron** [comment]
Pinging our lovely AWS crew for feedback -- @jsmartin @scicoin-project @tombamford @garethr @lorin @jarv @jsdalton @silviud @adq @zbal @zeekin @willthames @carsongee @defionscode
@tastychutney @bpennypacker @loia 

And, pinging @lwade in particular for feedback, as maintainer of the ec2_vol module in core.

@wimnat -- is it a "could" or "should" be deprecated wrt list state in ec2_vol -- and if this is merged, are you planning to do a PR for that? (Apologies if you already have and it's not ringing a bell in my wee little memory :D)

**Comment by robynbergeron** [comment]
I promise to all of you that I know the difference between windows and AWS. Except, apparently, when it comes to adding labels. Or when it's 4am. :person_with_pouting_face:

**Comment by wimnat** [comment]
I've been told in the past that facts modules are preferred over a list
state so I would guess this module could lead to deprecation of ec2_vol
list state but I will leave that to @bcoca and the rest of the core team to
answer.

**Comment by willthames** [comment]
@wimnat is that policy actually written down? 

I've tried to implement list state in modules before and been rejected, but it would be good if it were clarified somewhere. The filters selection is definitely a good feature, I just worry about a massive proliferation of modules and wonder if there isn't a better approach

**Comment by wimnat** [comment]
@willthames It's just been mentioned to me either here or in the ansible-devel google group.  It would probably be a good idea to add it to the module guidelines, if it is indeed gospel.  (Another thing i've been told here is that state should never have a default parameter but i don't think that's in the guidelines either)

I personally really favor separate modules for facts.  It particularly works for Amazon infrastructure with the filters dicts making it easy to grab particular info like a vpc id or snapshots tagged with a certain something.

I would also favor more modules that are more specific over fewer, more complex modules.

**Comment by tastychutney** [comment]
@wimnat That would be a change as well from what I've been told in the past. I had several facts modules rejected because "that's what inventory scripts are for". Never mind that they don't work for my use cases, which are AWS-based as well. :-)

**Comment by gregdek** [comment]
Going to defer to the core team here for policy ruling.

cc @ansible/core

**Comment by willthames** [comment]
@gregdek here is my opinion, for reference from an @ansible/aws point of view. 

I think @wimnat makes a bunch of good points - my main issue is that they should be written down with the guidelines. I'm happy enough to deprecate `state=list` on that basis, and replace it with this module (which has far better functionality due to the extra filtering that would complicate the ec2_vol module)

**Comment by bcoca** [comment]
already there:
" Sometimes you want to split the module, specially if you are adding a list/info state, you want a _facts version"

**Comment by willthames** [comment]
@bcoca - you're quite right, sorry. I think the statement could be stronger, but it is there. 

The only thing this is missing before passing guidelines is the RETURNS documentation structure.

**Comment by bcoca** [comment]
Return is not mandatory, yet. Feel free to submit PR that you think clarifies the guidelines more.

**Comment by willthames** [comment]
"Return: document the return structure of the module"

Feel free to update the documentation to clarify that that's not mandatory

**Comment by willthames** [comment]
Raised ansible/ansible#12957 to clarify guidelines

**Comment by wimnat** [comment]
@willthames, happy to ship this?

**Comment by willthames** [comment]
@wimnat in general I think I'd prefer to have the RETURN documentation but it's not a blocker if @bcoca thinks it's not mandatory. And it can always be added in a future PR.

:shipit:

**Comment by robynbergeron** [comment]
@wimnat @willthames -- as a friendly reminder, for new modules we need the +1 votes for guidelines and working (see https://github.com/ansible/ansible-modules-extras/pull/1109#issuecomment-149851917 above). Not because I <3 being picky, but just for consistency's sake :smile: 

If @willthames is willing to put up those votes I'm happy with shipping this, since as noted above the RETURN documentation isn't a blocker (though I would encourage filing a feature request against the module once it has shipped as a reminder for future things to do :D)

Let us know!

**Comment by willthames** [comment]
passes_guidelines

**Comment by willthames** [comment]
I don't have time right now to test if it works I'm afraid - I might be able to come back to it later.

**Comment by manicminer** [comment]
Tested most of the documented filters.

works_for_me

**Comment by wimnat** [comment]
@robynbergeron with the works_for_me and the passes_guidelines can this get shipped?

**Comment by gregdek** [comment]
@wimnat I think the answer is yes. Thanks for your perseverance. :) 

Marking as "shipit" at long last.

**Pull request merged**
