### PR TITLE
ec2_group_facts.py - new module for gathering EC2 security group facts (list associated instances, loadbalancers, ENIs)

### PR DESCRIPTION
**Pull request by Constantin07**
##### Issue Type:

New Module Pull Request
##### Summary:

This PR add a new module to query EC2 security group facts.
It includes details about associated resources to the security group like:
1. EC2 Instances
2. Elastic Load Balancers
3. Elastic Network Interfaces
4. RDS Instances

The 'lookup' option may take any combination of 'ec2', 'eni', 'elb', 'rds' to query a specific set of resources or just 'all' for all resources. By default it doesn't query any resource types.

Reason: From AWS console there is no easy way to identify to what resources a security group is associated.

Example:

```
  - name: Get security group details
    ec2_group_facts:
      region: "eu-west-1"
      filters:
        group-id: "sg-25c0a341"
      lookup:
        - ec2
        - eni
        - elb
        - rds
    register: group_facts

  - debug: var=group_facts
```

Here is a sample of output:

```
TASK: [debug var=group_facts] *************************************************
ok: [127.0.0.1] => {
    "var": {
        "group_facts": {
            "changed": false,
            "groups": [
                {
                    "resources": {
                        "ec2": [ "i-f9fc5440" ],
                        "elb": [ "test-dev-elb01" ],
                        "eni": [ "eni-5c0e5a7f" ],
                        "rds": [ "test-rds-mysql" ]
                    },
                    "description": "ELB security group",
                    "id": "sg-05250563",
                    "name": "default",
                    "rules": [
                        {
                            "from_port": null,
                            "grants": [
                                "sg-05250563"
                            ],
                            "ip_protocol": "-1",
                            "to_port": null
                        }
                    ],
                    "rules_egress": [
                        {
                            "from_port": null,
                            "grants": [
                                "0.0.0.0/0"
                            ],
                            "ip_protocol": "-1",
                            "to_port": null
                        }
                    ],
                    "vpc_id": "vpc-8a2ca6ee"
                }
            ],
            "invocation": {
                "module_args": "",
                "module_complex_args": {
                    "region": "us-east-1"
                },
                "module_name": "ec2_group_facts"
            }
        }
    }
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Constantin07 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by judev** [comment]
shipit

**Comment by phumpal** [comment]
@Constantin07 great work!  

I came across a permissions issue when a user or role doesn't have access to all resource types.

For example, I grant users access to EC2 security groups, ELB and ENI but not RDS.

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AccessDenied: User: arn:aws:sts::12345678910:assumed-role/foo/bar-RoleSession is not authorized to perform: rds:DescribeDBInstances"}
```

How do you recommend working around this or similar scenarios where a user shouldn't have read access to particular resources? 

Should I just iterate over the results returned by `ec2_group` instead?

**Comment by Constantin07** [comment]
@phumpal 
Probably to add an optional attribute which will allow to specify what resources you want to query with a combination of values like [ 'ec2' , 'eni', 'elb', 'rds' ] and default to just 'ec2' if not specified ...

Does it make sense?

**Comment by phumpal** [comment]
@Constantin07 makes sense - that definitely seems like a happy medium.

**Comment by wholroyd** [comment]
@Constantin07 @phumpal - I think it would be good if the parameter was something like `lookup` to provide that list to, default to `ec2` if you want, but also take an `all` option.

When it comes back, could the structure be more like this (see the `resources` key)?

`````` json
TASK: [debug var=group_facts] *************************************************
ok: [127.0.0.1] => {
    "var": {
        "group_facts": {
            "changed": false,
            "groups": [
                {
                    "resources": [
                      "ec2": [],
                      "elb": [ "test-dev-elb01" ],
                      "eni": [ "eni-5c0e5a7f" ],
                      "rds": [ "test-rds-mysql" ]
                    ],
                    "id": "sg-05250563",
                    "name": "default",
                    "rules": [
                        {
                            "from_port": null,
                            "grants": [
                                "sg-05250563"
                            ],
                            "ip_protocol": "-1",
                            "to_port": null
                        }
                    ],
                    "rules_egress": [
                        {
                            "from_port": null,
                            "grants": [
                                "0.0.0.0/0"
                            ],
                            "ip_protocol": "-1",
                            "to_port": null
                        }
                    ],
                    "vpc_id": "vpc-8a2ca6ee"
                }
            ],
            "invocation": {
                "module_args": "",
                "module_complex_args": {
                    "region": "us-east-1"
                },
                "module_name": "ec2_group_facts"
            }
        }
    }
}```
``````

**Comment by wholroyd** [comment]
On a side note, the module works wonderfully. Thanks @Constantin07 !

**Comment by MichaelBaydoun** [comment]
There are three new module pull requests, including this one, that seem to cover the same functionality
https://github.com/ansible/ansible-modules-extras/pull/1939
https://github.com/ansible/ansible-modules-extras/pull/1908
https://github.com/ansible/ansible-modules-extras/pull/1352

**Comment by wimnat** [comment]
I don't think this module is the right approach myself. I expect a SG facts module to just query the groups not go off and start querying other services. For that, I would use the respective facts module of the service. Boto3 always returns the associated sec groups when querying a resource. Just my 2 cents

**Comment by Constantin07** [comment]
@phumpal  @wholroyd Updated as per suggestions.

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by wimnat** [comment]
I still think this module does too much.  Smaller modules are better IMO.  Also, it needs to be switched over to boto3.

**Comment by Sodki** [comment]
I agree with @wimnat that this module seems to be overarching, instead of simply getting security group facts.

**Comment by ryansb** [comment]
An alternate implementation (with boto3 support) has been merged, closing this PR.

**Pull request closed without merging**
