### PR TITLE
Fix session-based kv acquire/release

### LINKED ISSUE #2155: consul_kv: Fix session-based kv acquire/release
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

consul_kv
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

```
pip freeze | grep consul
python-consul==0.6.0
```
##### SUMMARY

Following the documented procedure for adding a KV with an associated session fails in multiple ways:
- setting `state` to `acquire` or `release` results in an error that the only valid options are `present` or `absent`
- setting the `session` attribute does nothing; it is not actually used in the code
##### STEPS TO REPRODUCE

``` yaml
    - name: Register KV with session
      consul_kv:
        key: 'stg/metadata/sessionkv'
        value: testing
        session: "{{ sessionid }}"
        state: acquire
```

ansible-playbook -i 'localhost,' -c local consul-kv.yml
##### EXPECTED RESULTS
- successful playbook execution
- registration of a kv pair in consul with an associated session lock
##### ACTUAL RESULTS

```
fatal: [ec2.compute-1.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "value of state must be one of: present,absent, got: acquire"}
```

After fixing this error and the associated `lock()` method which appears to have never been wired, I noticed that the session wasn't even being passed into the params.

Fixes here: https://github.com/quantopian/ansible-modules-extras/commit/552ab6bb97d08353f66171149ca7fb305570a0bb

### PR DESCRIPTION
**Pull request by irlevesque**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

consul_kv
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Fixes https://github.com/ansible/ansible-modules-extras/issues/2155

Ensure that the `session` and `state` values are accepted as module parameters per the module documentation, that these parameters successfully invoke the `lock()` method, that the `lock()` method defines `consul_api`, and that the module only returns `changed` when a modification to the original values occurs.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @irlevesque. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
looks good, can you add the example from #2155 to the docs? If you're feeling diligent there are tests in the core project that you could update. After that I'm happy, shipit

**Comment by gregdek** [comment]
Thanks again to @irlevesque for this PR, and thanks @sgargan for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by sgargan** [comment]
@gregdek please wait for the docs updates before shipping. thanks

**Comment by irlevesque** [comment]
The usage example has been added to the module.

**Pull request merged**
