### PR TITLE
Add ec2_snapshot_facts module to find snapshots

### PR DESCRIPTION
**Pull request by 399a36c3b7**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_snapshot_facs
##### ANSIBLE VERSION

Should not have any version restrictions

```
ansible 1.9.5
  configured module search path = None
```
##### SUMMARY

Currently, there doesn't seem to be a module to be able to search snapshots by useful attributes such as owners, tags, or source volumeId.
Usage:

```
- ec2_snapshot_facts:
    owner: ["self", "2222222222"]
    volume_id: "vol-aaaaaaaaaa"
  register: reg
```

Output:

```
ok: [my-redacted-server] => {
    "var": {
        "reg": {
            "changed": false, 
            "invocation": {
                "module_args": "", 
                "module_complex_args": {
                    "owner": ["self", "2222222222"],
                    "volume_id": "vol-aaaaaaaaaa"
                }, 
                "module_name": "ec2_snapshot_facts"
            }, 
            "results": [
                {
                    "description": "Fancy Description", 
                    "encrypted": true, 
                    "id": "snap-111111111", 
                    "owner_id": "111111111111", 
                    "progress": "100%", 
                    "region": "RegionInfo:us-west-1", 
                    "start_time": "2016-03-00T00:00:00.000Z", 
                    "status": "completed", 
                    "tags": {
                       "MyGreatTag": "IsVeryGreat"
                    }, 
                    "volume_id": "vol-aaaaaaaaaa", 
                    "volume_size": 42
                }
            ]
        }
    }
}
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @alxnov for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @alxnov for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by willthames** [comment]
Worth comparing to #1088

**Comment by gregdek** [comment]
Good catch @willthames -- thanks.

@alxnov I'm going to close this PR as a duplicate. Would you please take a look at #1088? It seems to do mostly the same things, has been in the queue for quite some time, and already has one "shipit". If you can test it and validate that it does what's needed, we can then merge that PR.

**Pull request closed without merging**
