### PR TITLE
Require domain in rocketchat

### PR DESCRIPTION
**Pull request by Fale**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

rocketchat
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

Rocket Chat always need a domain specified (as per doc https://docs.ansible.com/ansible/rocketchat_module.html)

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Fale. To the current maintainers, @ramondelafuente please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ramondelafuente** [comment]
@gregdek It seems I suddenly own a module I had nothing to do with. Looks like a copy from the Slack module. I'm OK with leaving someone's name om the list of authors as a 'thank you', but if the maintainer could be changed that would be great ;-)

**Comment by Fale** [comment]
I can volounter to take the maintainership of this module

**Comment by resmo** [comment]
@Fale Thanks for your effort, IMHO the author in the module is wrong, it should be @Deepakkothandan . Let's ping @Deepakkothandan to review your changes.

**Comment by resmo** [comment]
@resmo marked this PR as pending_action for fix the maintainer

**Comment by Deepakkothandan** [comment]
@ramondelafuente As the slack module was not completely compatible with the Rocketchat web hooks, I had to fork the existing slack module, to make the necessary changes, so it can be used with Rocketchat. I  mentioned the contributors of slack module into the fork, as a thank you :smile: . Should I change the module owner ?

**Comment by Deepakkothandan** [comment]
@Fale Thank you for reporting / fixing the issue with the module and the Pull Request.
@resmo Thank you and the PR can be merged

**Comment by resmo** [comment]
@Deepakkothandan You left the copy right notice which is all it needs and should be kept as is, author is used for "you contributed this module in the first place" regardless of copyright owner. So it makes perfectly sense to add you as the author in the yaml doc.

**Pull request merged**
