### PR TITLE
This check needs to be name to name - not name to dict.

### PR DESCRIPTION
**Pull request by andybak**
list_mailboxes returns a list of dicts not a list of names.

### CODE REVIEW

**Comment by resmo** [comment]
this change looks unlogical, did you remove the correct line?

**Comment by robynbergeron** [comment]
@andybak -- thanks for the PR. Let us know the answer to @resmo's question and we'll proceed ahead! :)

@resmo -- as always, thanks for the quick eyeball :)

@quentinsf -- FYI that this is coming.

**Comment by andybak** [comment]
Sorry - careless mistake. Tried to take a shortcut and use the Github editor rather than use my local working module source.

Would you prefer me to close this and do another PR to get a cleaner commit history?

**Comment by resmo** [comment]
either rebase (change, git add, git commit --amend, git push -f) or close this pr and make a new one :). as you like

**Comment by quentinsf** [comment]
shipit

**Pull request closed without merging**
