### PR TITLE
add azure resource manager template deployment module

### PR DESCRIPTION
**Pull request by devigned**
With Azure Resource Manager, you can create a simple template (in JSON format) that defines deployment and configuration of your application. This template is known as a Resource Manager template and provides a declarative way to define deployment. (see: https://azure.microsoft.com/en-us/documentation/articles/resource-group-overview/#template-deployment).

This module provides support for Azure Resource Manager templates via the following:

``` yaml
# Create or update a template deployment based on a uri to the template and parameters specified inline.
# This deploys a VM with SSH support for a given public key, then stores the result in 'azure_vms'. The result is then used
# to create a new host group. This host group is then used to wait for each instance to respond to the public IP SSH.

---
- hosts: localhost
  tasks:
    - name: Destroy Azure Deploy
      azure_deployment:
        state: absent
        subscription_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        resource_group_name: dev-ops-cle

    - name: Create Azure Deploy
      azure_deployment:
        state: present
        subscription_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        resource_group_name: dev-ops-cle
        parameters:
          newStorageAccountName:
            value: devopsclestorage1
          adminUsername:
            value: devopscle
          dnsNameForPublicIP:
            value: devopscleazure
          location:
            value: West US
          vmSize:
            value: Standard_A2
          vmName:
            value: ansibleSshVm
          sshKeyData:
            value: YOUR_SSH_PUBLIC_KEY
        template_link: 'https://raw.githubusercontent.com/azure/azure-quickstart-templates/master/101-vm-sshkey/azuredeploy.json'
      register: azure
    - name: Add new instance to host group
      add_host: hostname={{ item['ips'][0].public_ip }} groupname=azure_vms
      with_items: azure.instances

- hosts: azure_vms
  user: devopscle
  tasks:
    - name: Wait for SSH to come up
      wait_for: port=22 timeout=2000 state=started
    - name: echo the hostname of the vm
      shell: hostname
```

This is my first PR to Ansible, so please be gentle. I believe I followed the contribution guidelines, but if I've omitted something, please let me know.

### CODE REVIEW

**Comment by nitzmahone** [comment]
Well, this is timely- I've been working on resource-specific Azure RM modules this week (Compute/Network/Storage). The generic template executor was going to be the last one I did, so you saved me the trouble! :) 

Once the stuff I'm working on is ready to merge, I'll check back with you about ensuring consistency of arg names, auth mechanisms, etc., then we can merge them all in at once (shooting for 2.1). We'll probably also want to share some of the auth code that's the same (token generation, etc), possibly in a new module_utils file.

Thanks for the submission!

**Comment by devigned** [comment]
Awesome! Looking forward to working with you.

**Comment by trondhindenes** [comment]
That's funny, I've been working on a couple of modules aswell:
https://github.com/trondhindenes/ansible-arm-deployment

From what I can see, my work differs from @devigned primarily in that my module works on a local template file which can be Jinja2-templated and then pushed to arm, while David's expects a template uri (which is resolvable by the azure arm api).

**Comment by devigned** [comment]
@trondhindenes it does take a local template or an inline template. Though, I really like what you have done with the Jinjia2 template. Perhaps I could add that approach as well.

I wanted to make sure users could use the published samples without needing to grok the full complexity of the template schema.

**Comment by devigned** [comment]
Closing in favor of #1839

**Pull request closed without merging**
