### PR TITLE
win_acl: windows 2008 fix + special account fix + strict fix

### PR DESCRIPTION
**Pull request by h0nIg**
there are problems related to windows 2008 and using special accounts like SYSTEM.
- SID is used instead of full computername\accountname or domain\accountname
- use account table instead of useraccount / group table, since it contains all accounts

### CODE REVIEW

**Comment by schwartzmx** [comment]
+1, nice work

**Comment by h0nIg** [comment]
added support for userprincipal and made parameter strict compliant

**Comment by h0nIg** [comment]
passes_guidelines

**Comment by robynbergeron** [comment]
Hi, @h0nIg -- thanks for this PR.

@schwartzmx & @trondhindenes -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
Also, @schwartzmx -- I know you already +1'd this, just want to make sure you are still okay with it since there were a few changes since your +1 (sorry for the delay :disappointed: and now). If yes -- please add the shipit comment... otherwise, let us know! :)

**Comment by h0nIg** [comment]
hey @schwartzmx, could you please add a comment?

**Comment by h0nIg** [comment]
it is possible to include the changes without @schwartzmx +1, because it seems he is not available since the last 4 weeks

**Comment by trondhindenes** [comment]
I can probably take a look at it tomorrow. However, I don't understand the following sentence from the .py help file:
"Specify whether to add C(present) or remove C(absent) the specified access rule" - what is "C"?

**Comment by h0nIg** [comment]
```
Module checklist
........
Made use of U() for urls, C() for files and options, I() for params, M() for modules?
```

http://docs.ansible.com/ansible/developing_modules.html

**Comment by sivel** [comment]
`C()` is used to make a string mono spaced such as for code blocks and such in the documentation.

See http://docs.ansible.com/ansible/developing_modules.html#documenting-your-module

**Comment by trondhindenes** [comment]
I few comments: 
"Type" is a required parameter, but ansible does not return an error when it is omitted
If the specified user already has an acl the script doesn't seem to work as it should. I tried setting a user to FullControl:Deny on a folder, and then use Ansible to set FullControl:Allow. Ansible returns no error and no change.

I'm not sure any of these are bugs from the original script or related to the PR. @h0nIg would you care to have a look, and let me know if they're not related to this pr?

**Comment by h0nIg** [comment]
@trondhindenes 

```
"Type" is a required parameter, but ansible does not return an error when it is omitted
```

you are right, corrected

```
If the specified user already has an acl the script doesn't seem to work as it should. I tried setting a user to FullControl:Deny on a folder, and then use Ansible to set FullControl:Allow. Ansible returns no error and no change.
```

allow andy deny can co-exist. its necessary for group access and the case to exclude a specific user from this group.
i think you used the user the directoy was created by and the directory already had this explicit permission? btw: its working on my machine (2008+2012)

```
TASK [win_file path=C:/test1234/ state=directory] ******************************
changed: [server1]

TASK [win_acl propagation=None state=present user=apache rights=FullControl path=C:/test1234/ type=allow inherit=ContainerInherit, ObjectInherit] ***
changed: [server1]

TASK [win_acl propagation=None state=present user=apache rights=FullControl path=C:/test1234/ type=deny inherit=ContainerInherit, ObjectInherit] ***
changed: [server1]

TASK [win_acl propagation=None state=present user=apache rights=FullControl path=C:/test1234/ type=allow inherit=ContainerInherit, ObjectInherit] ***
ok: [server1]

TASK [win_acl propagation=None state=present user=apache rights=FullControl path=C:/test1234/ type=deny inherit=ContainerInherit, ObjectInherit] ***
ok: [server1]
```

**Comment by h0nIg** [comment]
since @schwartzmx is not responding: it is possible that someone else can review the change?

ping: @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch @trondhindenes

**Comment by koloros** [comment]
i would appreciate the inclusion.

works_for_me

ping: @trondhindenes @petemounce @elventear @smadam813 @jhawkesworth @angstwad @sivel @chrishoffman @cchurch

**Comment by celticur** [comment]
personally i think, the guidelines are met. nice to have: move the user functions to a general place but it seems that this is indented by https://github.com/ansible/ansible/pull/12806 and https://github.com/ansible/ansible/pull/13812

passes_guidelines

**Comment by schwartzmx** [comment]
shipit

**Comment by gregdek** [comment]
Thanks again to @h0nIg for this PR, and thanks @schwartzmx @trondhindenes for reviewing. Marking for inclusion.

**Pull request merged**
