### PR TITLE
adding username/password support along with ssl/starttls to mail

### PR DESCRIPTION
**Pull request by bhcopeland**
Original pull request from here https://github.com/ansible/ansible/pull/7213

The mail module lacks the ability to have SMTP username and password. Also, due to sending credentials support has been added for SSL/TLS and STARTTLS.

Would be really good to get this merged.

### CODE REVIEW

**Comment by bhcopeland** [comment]
will this be merged?

**Comment by bcoca** [comment]
yes, but could you modify it so we still handle the exception if non ssl (line 177) connection fails? Your patch removed this in favor of handling ssl failure exception.

**Comment by danpilch** [comment]
Any update on this? I could really appreciate having this functionality!

**Comment by bhcopeland** [comment]
I can merge changes from #271. If needs be. Tested it and outputted okay.

**Comment by danpilch** [comment]
verified as working.

**Pull request merged**
