### PR TITLE
Add support for "state=latest" for both single package or whole packages upgrade

### PR DESCRIPTION
**Pull request by keltia**
Please review, I'm a Python rookie :)

As pkg-upgrade(8) and pkg-version(8) do not support single package handling I had to get the whole list and filter to implement single-package upgrade.  For whole system upgrade, use `name=ALL`.  Welcome any comment & corrections.

### CODE REVIEW

**Comment by nerzhul** [comment]
I approve, this can be useful for updating our freebsd distros

**Comment by keltia** [comment]
There are ways to do that already using `shell` module but it is not omnipotent as `shell`/`command` modules can not be.  The goal is to develop a playbook that upgrade the host and its jails after a `poudriere` run.

**Comment by gregdek** [comment]
@keltia looks like this needs to be rebased; when you do, please ping @bleader in the comments. If he gives a +1, we will merge.

**Comment by keltia** [comment]
Rebased with recent sources. @bleader please check.

**Comment by nerzhul** [comment]
@keltia i think you merge instead of rebase :(

**Comment by keltia** [comment]
@nerzhul did I got bitten by the sorry state of a UI by git?  Afraid so :(  Will look at how to fix that, thanks.

**Comment by nerzhul** [comment]
reset to your commit, then rebase and fix the commit and push force

**Comment by abadger** [comment]
Couple thoughts:
- instead of  "All"  use "*".  This is inline with the other package
  management modules and doesn't risk there being a package named "All" in
  the future.
- instead of using map and lambda you can probably use a list comprehension.

**Comment by bcoca** [comment]
I don't know which level of hell would the submitter or approver of a 'all' package to a distro should be condemned to ... but I'm thinking a pretty high number.

**Comment by abadger** [comment]
Probably one level down from the "root" package ;-)

**Comment by gregdek** [comment]
@keltia Unfortunately, I think this PR is probably broken beyond repair, so I'm going to make the call to close it.

I'm also going to make a recommendation: that you stash the changes you made to packaging/os/pkgng.py, start with a clean fork of the very latest ansible-modules-extras repo, and submit a new pull request.  At that point, we will be happy to get it back into our review process.

We really do appreciate your effort. Git can be a bear to sort out. :)

**Comment by keltia** [comment]
> @keltia Unfortunately, I think this PR is probably broken beyond repair, so I'm going to make the call to close it.

Agreed.

> I'm also going to make a recommendation: that you stash the changes you made to packaging/os/pkgng.py, start with a clean fork of the very latest ansible repo, and submit a new pull request.  At that point, we will be happy to get it into our review process.

That is also my plan.

Thanks!

## 

Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Comment by LeeBrown** [comment]
Can this be resurrected?  pkg-version and pkg-upgrade can take a package name at this time.
pkg-version -n mypackage
pkg-update mypackage

are the expected syntax.  I'd be happy to test.

**Pull request closed without merging**
