### PR TITLE
Fix mongodb user compatibility check (#2731)

### PR DESCRIPTION
**Pull request by Lujeni**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

mongodb_user
##### SUMMARY

https://github.com/ansible/ansible-modules-extras/issues/2731

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @Lujeni. This module is going into community review.

We notice that you are one of the maintainers (@lujeni) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Lujeni** [comment]
@gregdek should I backport this kind of fix in the stable branch ?

**Comment by gregdek** [comment]
@Lujeni generally not -- we don't backport Extras PRs unless they're security vulnerabilities.

**Comment by Lujeni** [comment]
`shipit`

**Comment by gregdek** [comment]
Thanks @Lujeni. Since you are one of the maintainers (@lujeni) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request merged**
