### PR TITLE
Add module to add and remove member volumes to an async mirror group.

### PR DESCRIPTION
**Pull request by hulquest**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

storage/netapp/netapp_e_amg_member.py
##### ANSIBLE VERSION

```
(khulques) [ansible-modules-extras]$ ansible --version
ansible 2.2.0 (devel cf4d436e07) last updated 2016/09/23 08:04:22 (GMT -600)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/19 12:02:18 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/19 12:02:21 (GMT -600)
  config file = /home/khulques/ansible.cfg
  configured module search path = ['/home/khulques/src/projects/ansible-modules-extras/storage/netapp', '/home/khulques/src/projects/ansible_eseries/ansible_modules']
```
##### SUMMARY

Add a module to add and remove mirror pair volumes to an asynchronous mirror group.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @hulquest. This module is going into community review.

We notice that you are one of the maintainers (@hulquest) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hulquest** [comment]
Always welcome comments from the core team.  If no comments, then shipit.

**Comment by gregdek** [comment]
Thanks @hulquest. Since you are one of the maintainers (@hulquest) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @hulquest for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by hulquest** [comment]
I think this is ready_for_review and shipit.  The shippable error doesn't appear to be related to the module (python2.4 not found).  I was a little sloppy with PR #3066 and this module is passing CI tests.

**Pull request closed without merging**
