### PR TITLE
Adds route advertisement state to the bigip_virtual_server module

### PR DESCRIPTION
**Pull request by caphrim007**
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

network/f5/bigip_virtual_server.py
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Adds the route advertisement state as an acceptable parameter to the bigip_virtual_server module

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks again to @caphrim007. This module is going into community review.

We notice that you are one of the maintainers (@mhite, @caphrim007, @Etienne-Carriere) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by caphrim007** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @caphrim007. Since you are one of the maintainers (@mhite, @caphrim007, @Etienne-Carriere) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
shipit

**Pull request merged**
