### PR TITLE
Added arbiter support to gluster_volume module

### PR DESCRIPTION
**Pull request by ColOfAbRiX**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

gluster_volume
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 89c826df9d) last updated 2016/09/16 15:12:47 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 48d932643b) last updated 2016/09/16 15:13:15 (GMT +000)
  lib/ansible/modules/extras: (feature/gluster_volume 95f4f52167) last updated 2016/09/19 16:44:19 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Added arbiter support to glusterfs_volume.
The module couldn't manage the configuration of an arbiter and I've added the relevant code following the official GlusterFS documentation https://gluster.readthedocs.io/en/latest/Administrator%20Guide/arbiter-volumes-and-quorum/

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @ColOfAbRiX. To the current maintainers, @rosmo please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nathanhruby** [comment]
(edited) I took a quick look at the code and it seems sane based on gluster docs.  Needs the arg added to DOCUMENTATION.

**Comment by ColOfAbRiX** [comment]
Thank you @nathanhruby, I've added the documentation.

**Comment by nathanhruby** [comment]
ping @rosmo for review, would love to get this in next release

**Comment by gregdek** [comment]
Thanks @ColOfAbRiX for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ColOfAbRiX** [comment]
ready_for_review

**Comment by ColOfAbRiX** [comment]
Moved to https://github.com/ansible/ansible/pull/19844

**Pull request closed without merging**
