### PR TITLE
New role to manage mongodb roles/privileges

### PR DESCRIPTION
**Pull request by Lujeni**
## Context

User administrators can create custom roles to ensure collection-level and command-level granularity and to adhere to the policy of least privilege. Administrators create and edit roles using this module.
### Env

python: 2.7.9
pymongo: 2.8 & 3.0.3
mongodb: 3.x
### Ansible

``` bash

# create the role + 1 privilege (insert+find)
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foobar privilege_actions='find,insert' state='present'"

# update the privilege to support only find
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foobar privilege_actions='find' state='present'"

# create a new privilege (foo) on the same role
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foo privilege_actions='find,insert' state='present'"

# drop the first privilege (foobar)
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foobar privilege_actions='find,insert' state='present' privilege_state='absent'"

# drop the second privilege (foo).
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foo privilege_actions='find,insert' state='present' privilege_state='absent'"

# add a new privilege when the role is empty.
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foobar privilege_actions='find,insert' state='present'"

# drop the role.
python ansible/hacking/test-module -m ./ansible-modules-extras/database/misc/mongodb_role.py -a "name=foo_find db=foo privilege_db=foo privilege_collection=foobar privilege_actions='find,insert' state='absent'"
```
### Mongodb

``` bash
> db.createUser({name: 'ansible', pwd: 'ansible', roles: ['foo_find']}
> use foo
> db.auth('ansible', 'ansible')
> db.foobar.insert({})
WriteResult({
    "writeError" : {
        "code" : 13,
        "errmsg" : "not authorized on foo to execute command { insert: \"foobar\", documents: ...."
    }
})
```

Thanks

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Lujeni -- this module currently fails Travis because of Python 2.4 checks. Ansible modules must run on 2.4. 

Please make sure Travis passes, and when you're done, please add a comment with the text "ready_for_review" and we will continue with the review process.  Thanks!

**Comment by Lujeni** [comment]
`ready_for_review` (Python 2.4 compliance done).

@gregdek There is a reason to support this very old version? and maybe add a note into the guide (http://docs.ansible.com/ansible/developing_modules.html) about the python versions must be support by the module.

Thanks !

**Comment by gregdek** [comment]
@Lujeni Thanks for making your revisions. One of the reasons that Ansible is popular is that it works on a very wide set of systems. That's the reason for maintaining Python 2.4 compatibility.

You are correct that we don't state this explicitly in the module checklist; I've made a note to update it.

This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes, which can be contributed by anyone other than the author of the new module:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

More information about the review process can be seen here: 
https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md

Thanks again for submitting your Ansible module!

**Comment by Lujeni** [comment]
Hello @gregdek 

There is a way to accelerate the integration of a new plugin ?
I will be happy to provided more tests on another platform.

Thanks

**Comment by Lujeni** [comment]
Hello @gregdek 

Can we `shipit` this module pls?

**Comment by gregdek** [comment]
@lujeni we're going to change the way we do new module inclusion right after the 2.2 release, so we should be able to include it then.

**Pull request closed without merging**
