### PR TITLE
Updated tags example to an actual datadog tag

### PR DESCRIPTION
**Pull request by agilekevin**

### CODE REVIEW

**Comment by gregdek** [comment]
@arturaz please review; if you +1, we will merge

**Comment by arturaz** [comment]
I guess. We don't really use datadog anymore, so I can't say anything on this module :)

**Comment by gregdek** [comment]
Merged, since it's only a documentation sample. 

@arturaz since you don't use this, can I presume you're not interested in owning this module?

**Comment by arturaz** [comment]
No, I'm not.

**Pull request merged**
