### PR TITLE
Add support for managing and configuring Infoblox via ansible

### PR DESCRIPTION
**Pull request by djgilcrease**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

infoblox
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Adding support to manage Infoblox from ansible.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @djgilcrease for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @djgilcrease for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by djgilcrease** [comment]
Updated to fix build break ready_for_review

**Comment by gregdek** [comment]
Thanks @djgilcrease for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregsidelinger** [comment]
I was playing around with this module on ansible 2.0.1.0 with python 2.6 (RHEL 6).  When using wapi 1.2.1 I had to specify a context type of application/json in order to not get 400 responses from infoblox.  

Also all of your .format calls fail because python 2.6 requires positional arguments when using "{ }".format('something').  Think it should be "{0}".format('something') to support python 2.6.

Finally create_cname_record blows up with a 400 error if the cname already exists.

**Comment by djgilcrease** [comment]
Thank you for the feedback @gregsidelinger 
I fixed the format called, and added the Content-Type header as well as checking if the cname already exists before attempting to create it

**Comment by pastephens** [comment]
I'm trying to use this module but keep getting an "infoblox is undefined" error. I've copied the module into ./library alongside my repo and set perms to 755. Here is the error:

`fatal: [vedgex]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'infoblox' is undefined\n\nThe error appears to have been in '/home/stephens1/ansible/roles/vedge-web/tasks/local.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Get Network\n  ^ here\n"}
`

**Comment by juliedavila** [comment]
hi @djgilcrease would mind rebasing this to fix the travis issue, I'd like to get this one in

**Comment by cidrblock** [comment]
+1 for adding this.

**Comment by Smuggla** [comment]
Any update?

**Pull request closed without merging**
