### PR TITLE
Include volume encryption status in 'ec2_vol_facts' module

### PR DESCRIPTION
**Pull request by rouge8**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

ec2_vol_facts
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Include whether or not a volume is encrypted in the results.

After:

```
        {
            "attachment_set": {
                "attach_time": "2016-04-18T02:41:35.000Z",
                "device": "/dev/sdi",
                "instance_id": "i-foo",
                "status": "attached"
            },
            "create_time": "2016-04-18T02:41:28.333Z",
            "encrypted": true,
            "id": "vol-foo",
            "iops": null,
            "region": "us-west-1",
            "size": 50,
            "snapshot_id": "",
            "status": "in-use",
            "tags": {},
            "type": "standard",
            "zone": "us-west-1b"
        }
```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @rouge8. To the current maintainers, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rouge8** [comment]
@gregdek how long do you wait for maintainer review?

**Comment by gregdek** [comment]
The bot usually pings the maintainer every two weeks if there's no answer.

@wimnat any chance you can look at this one? Looks to be a one-liner.

**Comment by rkonrath** [comment]
I got this error:
ansible_amodule_ec2_vol_facts.py\", line 80, in get_volume_info\r\n    'encrypted': volume.encrypted,\r\nAttributeError: 'Volume' object has no attribute 'encrypted'\r\n", "msg": "MODULE FAILURE"}

Encrypted and Not Encrypted EBS Volumes, same issue.

**Pull request closed without merging**
