### PR TITLE
Added iam_user_facts.py module - gathering facts about IAM user(s)

### PR DESCRIPTION
**Pull request by Constantin07**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ansible-modules-extras/cloud/amazon/iam_user_facts.py
##### ANSIBLE VERSION

```
2.2.0
```
##### SUMMARY

New module to gather facts about IAM user(s).

```
TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "iam_user_res": {
        "changed": false,
        "iam_users": [
            {
                "arn": "arn:aws:iam::156460693975:user/dev/test_user",
                "create_date": "2016-05-24T12:24:59+00:00",
                "password_last_used": "2016-05-25T13:39:11+00:00",
                "path": "/dev/",
                "user_id": "AIDAIOOCQKTUGI6QJLGH2",
                "user_name": "test_user"
            }
        ]
    }
}

```

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by Constantin07** [comment]
ready_for_review

Note: The build fails with the below error which is not related to this pull request.

```
Compiling ./database/mssql/mssql_db.py ...
  File "./database/mssql/mssql_db.py", line 182
    except Exception as e:
                      ^
SyntaxError: invalid syntax
```

**Comment by gundalow** [comment]
Hi,

Looks like this branch needs updating to fix the Travis issues, please see this guide on how to do that cleanly.

http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

**Comment by Constantin07** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @Constantin07 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
