### PR TITLE
pacman: Remove choice list for boolean values in arg spec

### PR DESCRIPTION
**Pull request by indrajitr**
This also makes argument_spec more consistent with core modules.
Apply this after preferable #767.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @indrajitr!

@elasticdog Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by indrajitr** [comment]
@gregdek, apparently there isn't an active maintainer for this module. See: https://github.com/ansible/ansible-modules-extras/pull/358#issuecomment-118546035.
Any recommendation you'd have to move this forward?

**Comment by gregdek** [comment]
@indrajitr apologies for the delay here; still working on process.

How would you feel about maintaining this module? Since it appears that you've now had other patches merged for this module, seems like you should be the one to take it over -- if you're willing. :)

**Comment by indrajitr** [comment]
Sure, I'd be happy to. How do you want me to take it from here?

**Comment by gregdek** [comment]
@indrajitr yes -- modify the author: field to include your name and Github ID. When you're done, please add a comment with the text "ready_for_review" and we will mark for inclusion.  At that point, you will be able to review other PRs for this module.  Thanks!

**Comment by indrajitr** [comment]
ready_for_review

**Comment by indrajitr** [comment]
@gregdek, Just checking out, anything else needed here?

**Comment by gregdek** [comment]
Nope, just hadn't gotten to it. 

Thanks for volunteering to take this on, @indrajitr -- marking for inclusion. cc: @ansible/core team.

**Comment by jimi-c** [comment]
Merged, thanks!

**Pull request merged**
