### PR TITLE
Minor change: added instance 'status' in the output of the module

### PR DESCRIPTION
**Pull request by Constantin07**
This is minor change to include in the output of the module the currently missing 'state' of EC2 instance.
This is useful for checking the status of EC2 instance before taking any further decision.

```
...
                    "sourceDestCheck": "true",
                    "spot_instance_request_id": null,
                    "state": "stopped",
                    "state_reason": {
                        "code": "Client.UserInitiatedShutdown",
                        "message": "Client.UserInitiatedShutdown: User initiated shutdown"
                    },
                    "subnet_id": "subnet-d14f65fa",
...
```

### CODE REVIEW

**Comment by wimnat** [comment]
Also here https://github.com/ansible/ansible-modules-extras/pull/1089

**Comment by robynbergeron** [comment]
@wimnat -- just double-checking to ensure I am deciphering correctly :) -- is this minor change already included in your (not yet merged) PR in #1089?

**Comment by robynbergeron** [comment]
@Constantin07 -- thanks for this PR.

@michaeljs1990 -- Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.
If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by robynbergeron** [comment]
@michaeljs1990 -- also worth noting that per @wimnat's comment -- this change (I believe) may already be encompassed in #1089 -- but I'll leave this one open pending an outcome on that PR.

**Comment by wimnat** [comment]
Correct! This minor change is part of the other PR. We'll wait to see the
outcome of @michaeljs1990 comments.

**Comment by wimnat** [comment]
@robynbergeron @Constantin07 this can be closed now as 1089 got merged :)

**Comment by Constantin07** [comment]
@wimnat  Thanks

**Comment by gregdek** [comment]
Thanks @Constantin07 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by Constantin07** [comment]
As @wimnat wimnat mentioned this functionality was already merged in 1089.

**Pull request closed without merging**
