### PR TITLE
Add new ec2_vpc_dhcp_options module

### PR DESCRIPTION
**Pull request by joelthompson**
This module manages EC2 DHCP options for a given VPC. It allows you to
specify all the options which AWS allows you to set in a DHCP option
set.

### CODE REVIEW

**Comment by joelthompson** [comment]
Note: This is ported from ansible/ansible-modules-core#2161 into -extras and incorporates @jsmartin suggestions on decoupling from Ansible host group semantics.

**Comment by gregdek** [comment]
Thanks @joelthompson for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by copumpkin** [comment]
:+1: (or is that supposed to be :shipit:?)

**Comment by ryansydnor** [comment]
LGTM! shipit

**Comment by joelthompson** [comment]
@gregdek -- any update on getting this merged?

Thanks!

**Comment by sivel** [comment]
Here is some initial feedback based on automated scanning of this new module:

```
============================================================================
test/ec2_vpc_dhcp_options.py
============================================================================
Traceback (most recent call last):
  File "ansible_testing/modules.py", line 383, in validate
    doc, examples, ret = get_docstring(self.path, verbose=True)
  File "/Users/matt/python_venvs/ansibledev/ansible/lib/ansible/utils/module_docs.py", line 74, in get_docstring
    doc = yaml.safe_load(child.value.s)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages/yaml/scanner.py", line 580, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "<string>", line 51, column 64:
     ... back to the old option set. NOTE: This setting
                                         ^

ERROR: Invalid or no DOCUMENTATION provided
ERROR: No RETURN provided
ERROR: version_added should be 2.1. Currently 2.0
```

**Comment by joelthompson** [comment]
Thanks for the feedback @sivel -- this should be addressed now.

This automated feedback tool looks awesome! Is this something you can share that I can use going forward, and is it documented somewhere (that I just missed)?

**Comment by gregdek** [comment]
With @sivel's issues fixed and multiple +1s, marking this for inclusion. Thanks @joelthompson for the PR.

**Comment by joelthompson** [comment]
Thanks @bcoca !

**Pull request merged**
