### PR TITLE
Added cloud/Amazon module for SSM

### PR DESCRIPTION
**Pull request by woznij**
##### ISSUE TYPE
- New Module Pull Request
##### COMPONENT NAME

ssm_send_command
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 29fda4be1e) last updated 2016/09/16 18:26:39 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 2e1e3562b9) last updated 2016/09/16 18:26:41 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 9b5c64e240) last updated 2016/09/16 18:26:42 (GMT +000)
  config file =
  configured module search path = Default w/o overrides

```
##### SUMMARY

This module allows you to interface with Amazon Simple Systems Manager (SSM) to manage the configuration of your Amazon EC2 instances.  Specifically this module allows you to use the Run Command functionality to run system commands against your hosts. E.g. you can run PowerShell commands against Windows hosts or bash commands against a Linux host. The specific advantage is that you do not need to log into those hosts as the SSM service takes care of the execution. For more information see http://docs.aws.amazon.com/ssm/latest/APIReference/Welcome.html

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @woznij for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by woznij** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @woznij for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by nastrofaction** [comment]
shipit

**Pull request closed without merging**
