### PR TITLE
Digital ocean domain record

### PR DESCRIPTION
**Pull request by ghost**
##### ISSUE TYPE

```
New Module Pull Request
```
##### COMPONENT NAME

digital_ocean_dns_record
##### ANSIBLE VERSION

2.x
##### SUMMARY

This creates a digital_ocean_domain_record module which allows developers to manage DNS records on digital ocean.

### CODE REVIEW

**Comment by sivel** [comment]
```
============================================================================
./cloud/digital_ocean/digital_ocean_domain_record.py
============================================================================
ERROR: No RETURN documentation provided
ERROR: sys.exit() call found. Should be exit_json/fail_json
```

**Comment by pogotech** [comment]
Working on the documentation error and some other inconsistencies with this module. I am updating syntax to match what is present in the core DO modules and DO API calls.

**Comment by pogotech** [comment]
It looks like the checks have passed. I have tested this module and results are good. I think it is ready for merge whenever available.

**Comment by thomasmassmann** [comment]
From what I can see it is only possible to [add](https://github.com/ansible/ansible-modules-extras/pull/1745/files#diff-8cc2a423d5be293d9c1e60ab77d970e6R275) or [remove](https://github.com/ansible/ansible-modules-extras/pull/1745/files#diff-8cc2a423d5be293d9c1e60ab77d970e6R279) a record, but not to update. Is this correct? Would it be possible to add this as well?

Edit:
What I want to achieve is that the record is changed when a droplet has to be recreated (for whatever reason).

**Comment by pogotech** [comment]
I can add the update feature. I was planning on adding it at a later time.
I was not sure that anyone would want or need that.

On Mon, Jul 11, 2016 at 6:31 AM Thomas Massmann <notifications@github.com>
wrote:

> From what I can see it is only possible to add
> <https://github.com/ansible/ansible-modules-extras/pull/1745/files#diff-8cc2a423d5be293d9c1e60ab77d970e6R275>
> or remove
> <https://github.com/ansible/ansible-modules-extras/pull/1745/files#diff-8cc2a423d5be293d9c1e60ab77d970e6R279>
> a record, but not to update. Is this correct? Would it be possible to add
> this as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/ansible-modules-extras/pull/1745#issuecomment-231698933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKE_8OpE58pIj_REWbhjHyE3Ya5BPFIDks5qUhuZgaJpZM4Hj1ZV>
> .
>
-- 

Jim Gaspari
240-593-1463

**Comment by pogotech** [comment]
I see what you are trying to accomplish. It will take a little time, but I'll get that feature added as soon as possible.

**Comment by pogotech** [comment]
@tmassman I was unable to get this to fully function. When I try to do an update, I get an error. I need to look at the dopy module to make sure that this is not something that I am doing.

Also, shippable says that my build failed and I am not sure why.

**Comment by cbenhagen** [comment]
@pogotech What is the status of this?

**Comment by pogotech** [comment]
I gave up on this and deleted my fork once they closed this issue and changed how they are doing the ansible extras. I can go back and redo this if you would like, but I was not sure that anyone was really interested besides me.

**Comment by cbenhagen** [comment]
Yes, please give it another try. Let me know if you'd like me to help.

**Comment by pogotech** [comment]
I will give it a try I need to figure out how to cherry pick the commits from this repo into a new ansible fork that I have. I would like to keep the commit history to give the original author.

**Comment by woohgit** [comment]
I have a working version withouth any dependency.  It's written to use pure `REST` and do not depend on external python libraries.

Please stay tuned, need to make sure that the things below works properly:

- [X] Create record
- [X] Delete record
- [X] Handle multiple pages for record list
- [X] Ensure data ends with `.` if `type` in `[CNAME, MX]`
- [X] Transform all data to lowercase
- [X] Proper error handling
- [X] Transform `data` to `@` if `domain` == `data`
- [x] Proper and consistent return values
- [ ] Refactor to comply with the ansible `CODING GUIDLINES`

**Pull request closed without merging**
