### PR TITLE
Additional upgrade mode fixes for pacman module with check_mode safety

### PR DESCRIPTION
**Pull request by indrajitr**
- ensure upgrade option honors and actually supports `check_mode`
- enabling just `upgrade` and `update_cache` should perform upgrade
- example added for the equivalent for `pacman -Syu`

NB: This is a followup of #762

### CODE REVIEW

**Comment by indrajitr** [comment]
Apologies, I accidentally pushed my devel branch to origin which in turn lead to commit for #807 showing up here. You can simply close #807 once this is applied.

While at this, anything else that I should do or take care of to have this accepted?

**Comment by gregdek** [comment]
@elasticdog Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

**Comment by indrajitr** [comment]
@gregdek, https://github.com/ansible/ansible-modules-extras/pull/807#issuecomment-135832135

**Comment by indrajitr** [comment]
Closing in favor of a different PR (#1018)

**Pull request closed without merging**
