### PR TITLE
Added proxied option to cloudflare_dns

### PR DESCRIPTION
**Pull request by rwky**
##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

cloudflare_dns
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 982db58aff) last updated 2016/09/08 11:50:49 (GMT +100)
  lib/ansible/modules/core: (detached HEAD db38f0c876) last updated 2016/09/08 13:03:40 (GMT +100)
  lib/ansible/modules/extras: (cloudflare-dns-proxied cba2db0c87) last updated 2016/09/19 14:48:21 (GMT +100)
  config file = /home/rowan/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This adds support for the cloudflare proxied parameter to A, AAAA and CNAME records.

### CODE REVIEW

**Comment by resmo** [comment]
The docs for the new argument are missing.

**Comment by rwky** [comment]
Whoops sorry! I've added the docs.

**Comment by gregdek** [comment]
Thanks @rwky for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by rwky** [comment]
ready_for_review

**Comment by rwky** [comment]
Not sure if ansible bot picked up the last comment, ready_for_review

**Comment by gregdek** [comment]
Thanks @rwky. To the current maintainers, @mgruener please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mgruener** [comment]
Thanks for implementing this @rwky . Looks good to me.

shipit

**Comment by gregdek** [comment]
Thanks again to @rwky for this PR, and thanks @mgruener for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by EpiqSty** [comment]
Hi,

We are trying to use proxied option in the ansible 2.3.0.0, and seems it's not working:

```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "account_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "account_email": "technik@pin.xx",
            "port": null,
            "priority": 1,
            "proto": null,
            "proxied": true, <-------- we are trying to set proxied:true
            "record": "login",
            "service": null,
            "solo": null,
            "state": "present",
            "timeout": 30,
            "ttl": 1,
            "type": "A",
            "value": "21.0.9.6",
            "weight": 1,
            "zone": "bXXXX24.de"
        }
    },
    "result": {
        "record": {
            "content": "21.0.9.6",
            "created_on": "2018-01-22T15:09:38.728833Z",
            "id": "XXX",
            "locked": false,
            "meta": {
                "auto_added": false,
                "managed_by_apps": false
            },
            "modified_on": "2018-01-22T15:09:38.728833Z",
            "name": "login.bXXXX24.de",
            "proxiable": true,
            "proxied": false, <-------- but result is false
            "ttl": 1,
            "type": "A",
            "zone_id": "YYY",
            "zone_name": "bXXXX24.de"
        }
    }
}
```

Meanwhile, the direct curl PUT request to CloudFlare API works fine.
How could we troubleshoot it? Should it works in ansible version 2.3.0.0 or we have to update?

Thanks in advance!

**Comment by Akasurde** [comment]
@EpiqSty This repository is closed. Please open a new issue [here](https://github.com/ansible/ansible/issues/new).

**Pull request merged**
