### PR TITLE
Added module for git-flow, V.1.0

### PR DESCRIPTION
**Pull request by jdinunzio**
Adds hooks for executing git-flow commands. Git-flow is a collection of Git extensions to provide high-level repository operations for Vincent Driessen's [branching model](http://nvie.com/posts/a-successful-git-branching-model/). 

You can install git-flow using your favorite package manager, or from its [github repository](https://github.com/nvie/gitflow). You can also read [Getting Starting -- Git-flow](http://yakiloo.com/getting-started-git-flow/).

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks for submitting this module to Ansible Extras. Apologies that it’s taken a while to get your module reviewed.

To help facilitate reviews, we’ve broadened the number of people who can approve modules for inclusion into the Extras repository. The list of official reviewers can be found here:

https://github.com/ansible/ansible-modules-extras/blob/devel/REVIEWERS.md 

Our new policy is that if a new module is reviewed and approved by at least two official module reviewers, the module will be approved for inclusion.  We will be asking the community of reviewers to take a look at these modules on a regular basis.

To ensure that your module has the best chance of being approved, please double-check that you adhere to the Ansible module guidelines: http://docs.ansible.com/developing_modules.html#module-checklist

**Comment by gregdek** [comment]
Adding new process. We will be evaluating all new module PRs according to this process, effective immediately.

# 

Thanks for submitting this new module to Ansible Extras! This module is now in community review, a process that is open to all Ansible users. In order for this module to be approved, it must gain the following votes:

“works_for_me”: If you have tested the module thoroughly, including testing of all of the module’s options, and if the module works for you, please add “works_for_me” in the comments.

“passes_guidelines”: If you have gone through the module guidelines and the module meets all of the requirements, please add “passes_guidelines” in the comments. Guidelines are available here: http://docs.ansible.com/developing_modules.html#module-checklist

“needs_revision”: If the module fails to work for you, or if it doesn’t meet guidelines, please add “needs_revision” in the comments with details about what needs to be fixed.

When a module has both “works_for_me” and “passes_guidelines” tags, we will promote the module for inclusion in Ansible Extras.  At this point, you will be expected to maintain the module by fixing bugs and evaluating pull requests in a timely manner. 

Thanks again for submitting your Ansible module!

**Comment by cirulls** [comment]
I tried out this module and it "works_for_me". I successfully run the following commands (as described in the documentation):

```
gitflow: path={{ path }} command=init
gitflow: path={{ path }} command=feature action=start name=foo
gitflow: path={{ path }} command=feature action=finish name=foo
gitflow: path={{ path }} command=release action=start name=1.5
gitflow: path={{ path }} command=release action=finish name=1.5
gitflow: command=version
```

I have not tried commands with the optional parameters `remote` and `base`.  

The only command that caused me some trouble was `command=release action=finish`. This was because my git configuration requires me to provide a commit message when doing a release. As a result, the ansible task was hanging forever because it was expecting a commit message from my text editor. I got around this problem via [this pull request](https://github.com/jdinuncio/ansible-modules-extras/pull/1) submitted to @jdinuncio.

**Comment by gregdek** [comment]
Thanks @jdinuncio for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jdinunzio** [comment]
ready_for_review 'version_added' updated to '2.2' as travis required. @gregdek thanks for your help!

**Pull request closed without merging**
