### PR TITLE
Changed status() to be case-sensitive of process

### PR DESCRIPTION
**Pull request by wimnat**
Code change as per solution proposed in https://github.com/ansible/ansible-modules-extras/issues/146.

### CODE REVIEW

**Comment by bcoca** [comment]
a better fix would be to just make parts[0].lower(), this will be resilient to upstream case changes

**Comment by wimnat** [comment]
Do you mean to add parts[0].lower() in addition to the current change?  lower() has to be removed from the parts = statement so that the actual process name is unchanged.

**Comment by bcoca** [comment]
this patch:

```
-            parts = line.lower().split()
-            if len(parts) > 2 and parts[0] == 'process' and parts[1] == "'%s'" % name:
+            parts = line.split()
+            if len(parts) > 2 and parts[0].lower() == 'process' and parts[1] == "'%s'" % name:
```

**Comment by wimnat** [comment]
Yep, agreed.  PR updated.

**Pull request merged**
