### PR TITLE
Use boto3 in sts assume role module

### PR DESCRIPTION
**Pull request by AKoetsier**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

sts_assume_role
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### SUMMARY

This is a small update to the original sts_assume_role module to use boto3. With the current module you cannot assume a role when starting from a saml-login or another assumed role while using aws profiles. It is a bug within boto which was fixed in boto3.

This module is a drop-in replacement for the current one. It accepts the exact same arguments and returns a dict with the same fields as the current one.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @AKoetsier. To the current maintainers, @bekelchik please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by bekelchik** [comment]
shipit

**Review by bekelchik — APPROVED** [review]

**Comment by gregdek** [comment]
Thanks again to @AKoetsier for this PR, and thanks @bekelchik for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
Thanks @AKoetsier for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by AKoetsier** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @AKoetsier. To the current maintainers, @bekelchik please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Review by bekelchik — APPROVED** [review]

**Comment by bekelchik** [comment]
shipit

**Comment by sgzijl** [comment]
LGTM - shipit

**Comment by gregdek** [comment]
Thanks again to @AKoetsier for this PR, and thanks @bekelchik for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Pull request closed without merging**
