### PR TITLE
Ovirt merge with firstyear

### PR DESCRIPTION
**Pull request by vincentvdk**
Made some small cosmetic changes and fixed a small bug on a jason_fail message. Other than that everyting looks ok to be merged.

### CODE REVIEW

**Comment by Firstyear** [comment]
Looks good to me.

**Comment by gregdek** [comment]
Marking for inclusion as owner_pr

**Comment by gregdek** [comment]
Well, wait... this is actually a giant merge...30 commits? @vincentvdk?

**Comment by vincentvdk** [comment]
@gregdek  I think they should've been squashed, most of them are small changes. Except from the cloud-init stuff, I did some testing (except cloud-init) and looks good.

**Comment by Firstyear** [comment]
They can be squashed without issue I expect. They weren't squashed because git doesn't like squashing commits that have already been pushed, and I didn't do any branch fiddling to make it work. Are you able to squash this @vincentvdk ?

**Comment by gregdek** [comment]
OK, I'll give it the thumbs-up then. cc: @ansible/core for inclusion.

**Comment by bcoca** [comment]
can you clean up the commit history?

**Comment by vincentvdk** [comment]
I'll try to squash the commits. There's also an issue #978 regarding the cloud-init functionality. We have a RHEV setup here at work where I could test on, but if @Firstyear also could have a look at the issue, that would be great.

**Comment by Firstyear** [comment]
squash them all into a branch, I'll look at the cloud-init issue when i'm not being overloaded at work.

**Comment by gregdek** [comment]
Whoops, removing the shipit tag here as we're still waiting for a squash.

**Comment by robynbergeron** [comment]
@vincentvdk @Firstyear I know you lovely people are super busy... just checking in to make sure this hasn't been forgotten :)

**Comment by vincentvdk** [comment]
Hi @robynbergeron . No, still on my radar.

**Comment by robynbergeron** [comment]
@vincentvdk -- thanks for the update. Just let us know when you're ready :)

**Comment by vincentvdk** [comment]
Squashed the commits i could find in the history.

**Comment by gregdek** [comment]
Thanks @vincentvdk for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

**Comment by robynbergeron** [comment]
@vincentvdk A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes.

**Comment by gregdek** [comment]
@vincentvdk Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If we don't hear from you within another 14 days, we will close this pull request.

**Comment by gregdek** [comment]
Superseded by #1543.

**Pull request closed without merging**
