### PR TITLE
Adding Site_ID param

### PR DESCRIPTION
**Pull request by blakfeld**
The company I work for was setting the Site ID to a custom thing using some dumb powershell script, and this seems like a far better place for it.

### CODE REVIEW

**Comment by gregdek** [comment]
@whenrik Please review this PR to make sure it adheres to the following guidelines:

http://docs.ansible.com/developing_modules.html#module-checklist

If it passes these guidelines, and if you believe it’s a good PR otherwise, please add a comment with "shipit" in the text, and we will flag it for inclusion.

If it fails these guidelines, please add a comment with "needs_revision" in the text, along with the needed changes, and we will flag it for revision.

Also, @whenrik please submit a PR adding your Github ID into the author field of the documentation, so we can more easily assign PRs and issues for this module to you. Thanks!

**Comment by gregdek** [comment]
@whenrik This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by robynbergeron** [comment]
@whenrik still waiting on your review.  Please comment with text 'shipit' or 'needs_revision' as appropriate. If we don't hear from you within 14 days, we will start to look for additional maintainers for this module.

**Comment by robynbergeron** [comment]
@whenrik This change is still pending your review; do you have time to take a look and comment? Please comment with text 'shipit' or 'needs_revision' as appropriate.

**Comment by blakfeld** [comment]
Anyone opposed to merging this?

**Comment by blakfeld** [comment]
Anyone opposed to merging this?

**Comment by nitzmahone** [comment]
@blakfeld - change looks good, just need to add the new site_id arg to the .py doc file with a version_added of 2.1. Ping me once that's in and I'll merge!

**Comment by blakfeld** [comment]
Thanks @nitzmahone ! Added.

**Comment by blakfeld** [comment]
Er, @nitzmahone It looks like this PR is causing builds to fail? A Co-worker is trying to push a bigfix and this module fails saying version_added is wrong? Did I manage to break Ansible? Because if so I think I want to go buy myself a trophy.

**Comment by nitzmahone** [comment]
Nah, just the module doc validator doing its job (and me not, apparently)- you updated version_added on the module to 2.1, when it should've just been added to the new site_id arg (so people using 2.0 know it's not there). I'll fix it.

**Comment by blakfeld** [comment]
Ack! Sorry about that!

**Comment by nitzmahone** [comment]
No worries!

**Pull request merged**
