### PR TITLE
Fix itertools.imap TypeError in haproxy module

### PR DESCRIPTION
**Pull request by fbnfgc**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
haproxy module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
Bugfix proposal for issue https://github.com/ansible/ansible-modules-extras/issues/3377.

Relates to https://github.com/ansible/ansible-modules-extras/issues/3377

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @fbnfgc. To the current maintainers, @ravibhure please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ravibhure** [comment]
Thanks @fbnfgc,
Fixed #3350

**Comment by gregdek** [comment]
Thanks @fbnfgc for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

**Comment by fbnfgc** [comment]
#3350 has been merged and this PR has the same purpose. It should be closed. Thanks for your time.

**Pull request closed without merging**
