### PR TITLE
Add logicmonitor and logicmonitor_facts modules

### PR DESCRIPTION
**Pull request by woz5999**
Add modules to integrate with LogicMonitor. 

LogicMonitor is a hosted, full-stack, infrastructure monitoring platform.

This module manages hosts, host groups, and collectors within a LogicMonitor account.

http://www.logicmonitor.com/

### CODE REVIEW

**Comment by robynbergeron** [comment]
Thanks @woz5999 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

**Comment by woz5999** [comment]
The community might have trouble testing this module without an actual LogicMonitor account. Is there some process to help facilitate members that might want to test and verify?

**Comment by gregdek** [comment]
Thanks @woz5999 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by woz5999** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @woz5999 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by jolexa** [comment]
shipit

**Comment by gregdek** [comment]
Thanks @woz5999 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by gregdek** [comment]
@woz5999 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by woz5999** [comment]
ready_for_review

**Comment by gregdek** [comment]
Thanks @woz5999 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by ghost** [comment]
shipit

**Comment by gregdek** [comment]
Two shipits since last modification, putting into shipit for final review

**Comment by sivel** [comment]
A few notes:
1. do not use `popen`, use `module.run_command`
2. there are a number of `platform` and service related things that could be removed and re-used from `ansible.module_utils.facts`
3. Do not wrap all imports in `try/except`, only external 3rd party modules
4. Do not use urllib2 directly, utilize `ansible.module_utils.urls`
5. `version_added` on arguments is not needed for new modules, as new arguments are added later, `version_added` is required on individual arguments
6. Unnecessary dependency on py26+, there are no external dependencies driving py2.6.  py2.4 support could be achieved by not using `.format` and such.
7. This module should be updated to pass py2.4 through py2.6 syntax checks implemented in newer travis checks.
8. `json` should be imported in `try/except` with `simplejson`.  See `ansible.module_utils.basic` for examples.
9. Instead of using `logger`, look into using `module.debug` and `module.log`

needs_revision

**Comment by woz5999** [comment]
I took a look at their feedback. Shouldn't be anything major. I'm hoping I
can get it all finished by the end of next week.

**Comment by gregdek** [comment]
Thanks @woz5999 for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by woz5999** [comment]
@sivel Is there any documentation available for ansible.module_utils.facts? I haven't been able to find any online and it's a bit onerous to have to read through module source code to attempt to find methods that might be applicable to what we're doing.

**Comment by sivel** [comment]
@woz5999 there aren't really any other modules doing this, but since we have really robust fact gathering to determine init system, it felt like we should be using that rather than this module trying to handle it.  The `Facts` class has a `get_service_mgr_facts`, method.  However, that is only part of it.  

The other side that I see here, is that these modules attempt to perform a number of service related operations, based off of this information.  We already have a service module (and in some cases these are being split into independent modules), and I kind of feel that this module breaks the mold, by trying to do it, itself, instead of using the service modules.

That raises another point, in that maybe some of this could just be galaxy roles, by removing all of the service interactions from the modules, and leave restarting services up to the user or role to utilize the service modules.

In general I feel like the `Service` class in these modules tries to duplicate a lot of what ansible already has built in, but in a less robust way.

**Comment by woz5999** [comment]
@sivel Thanks for the quick feedback. Everything you've said is 100% right, so I'll go ahead and take that route.

**Pull request closed without merging**
