### PR TITLE
Update bigip_pool.py

### PR DESCRIPTION
**Pull request by xoanmi**
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

ansible-modules-extras/network/f5/bigip_pool.py
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
```
##### SUMMARY

Solve issue with port check in module.

### CODE REVIEW

**Comment by gregdek** [comment]
Thanks @xoanmi. To the current maintainers, @mhite please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

**Comment by mhite** [comment]
Is this attempting to address something different than the patch that was merged in #1927?

**Comment by mhite** [comment]
I think I see what you were trying to fix -- issue #1992 with a verbose description of the problem and PR #1994 to fix.

**Comment by mhite** [comment]
@gregdek - we can close this as #1992 / #1994 document and fix the issue, respectively.

**Comment by gregdek** [comment]
Closing per @mhite -- thanks for looking into it.

A sincere thanks to @xoanmi for the PR.

**Pull request closed without merging**
